In [1]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
from matplotlib.pyplot import rcParams
import seaborn as sbs
import scipy as sp
from scipy import stats
import statistics as st  
import datetime 
from datetime import datetime      
from datetime import timedelta
#date_parser=lambda x:datetime.strptime(x,'%y/%m/%d')

## Import pipeline export Data

In [2]:

data1=pd.read_csv("C:/Users/georgea1/OneDrive - Trinity College Dublin/Angel George/Chap 2. Treatment/Data/ITIS Data/RIV/April 2026/Redcap_clinical_data_harmonized_version0.0.3 (9).csv")
data1

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\2491348118.py:1: DtypeWarning: Columns (93,94,95,105,112,113,117,120,122,231,235,271,273,290,297,302,317,318,327,329,335,350,351,366,377,399,400,448,458,507,508,509) have mixed types. Specify dtype option on import or set low_memory=False.
  data1=pd.read_csv("C:/Users/georgea1/OneDrive - Trinity College Dublin/Angel George/Chap 2. Treatment/Data/ITIS Data/RIV/April 2026/Redcap_clinical_data_harmonized_version0.0.3 (9).csv")

,RKD.ID,Date.Of.Visit,ANCA_Levels,anca_status,ancaswitch,Repeat.Instrument,Repeat.Instance.x,Data.Access.Group.x,Patient.ID,COVID.19.related.entry.,...,Date.of.transplant.,Date.of.graft.failure,Date.of.graft.failure.or.last.followup,Repeat.Instance.y.y,kidney_function_status,affectedOrgan_ENT,affectedOrgan_Chest,affectedOrgan_Nervous_system,inductiontreatmentType_Cyclophosphamide,death
0,1,2012-08-31,134.0,ANCA Positive,Switch Status Unknown,Encounters,1,TUH - Tallaght,1,No,...,NaN,NaN,NaN,NaN,Functioning native kidneys,Unchecked,Unchecked,Unchecked,Checked,NaN
1,1,2012-09-07,NaN,ANCA Positive,Pos-Pos Switch,Encounters,36,TUH - Tallaght,1,No,...,NaN,NaN,NaN,NaN,Functioning native kidneys,Unchecked,Unchecked,Unchecked,Checked,NaN
2,1,2012-09-17,110.0,ANCA Positive,Pos-Pos Switch,Encounters,37,TUH - Tallaght,1,No,...,NaN,NaN,NaN,NaN,Functioning native kidneys,Unchecked,Unchecked,Unchecked,Checked,NaN
3,1,2012-09-21,92.0,ANCA Positive,Pos-Pos Switch,Encounters,2,TUH - Tallaght,1,No,...,NaN,NaN,NaN,NaN,Functioning native kidneys,Unchecked,Unchecked,Unchecked,Checked,NaN
4,1,2012-09-28,NaN,ANCA Positive,Pos-Pos Switch,Encounters,28,TUH - Tallaght,1,No,...,NaN,NaN,NaN,NaN,Functioning native kidneys,Unchecked,Unchecked,Unchecked,Checked,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8022,28793,2026-01-21,147.0,ANCA Positive,Switch Status Unknown,Encounters,1,CUH - Cork University Hospital,28793,No,...,NaN,NaN,NaN,NaN,CKD5,Unchecked,Unchecked,Unchecked,Checked,NaN
8023,28796,2025-07-28,NaN,ANCA Status Unknown,Switch Status Unknown,Encounters,2,NaN,28796,No,...,NaN,NaN,NaN,NaN,Functioning native kidneys,Checked,Checked,Unchecked,Unchecked,NaN
8024,28796,2026-01-30,NaN,ANCA Negative,Switch Status Unknown,Encounters,1,NaN,28796,No,...,NaN,NaN,NaN,NaN,Functioning native kidneys,Checked,Checked,Unchecked,Unchecked,NaN
8025,28797,2026-02-02,134.0,ANCA Positive,Switch Status Unknown,Encounters,1,CUH - Cork University Hospital,28797,NaN,...,NaN,NaN,NaN,NaN,CKD5,Unchecked,Unchecked,Unchecked,Unchecked,NaN
8026,28797,2026-03-26,134.0,ANCA Positive,Pos-Pos Switch,Encounters,2,CUH - Cork University Hospital,28797,NaN,...,NaN,NaN,NaN,NaN,CKD5,Unchecked,Unchecked,Unchecked,Unchecked,NaN

In [3]:
data1.rename(columns = {'Date.Of.Visit':'Date_Of_Visit'}, inplace = True)

In [4]:
## Remove duplicates:
duplicateRows = data1[data1.duplicated(['RKD.ID','Date_Of_Visit'])]
duplicateRows

Empty DataFrame
Columns: [RKD.ID, Date_Of_Visit, ANCA_Levels, anca_status, ancaswitch, Repeat.Instrument, Repeat.Instance.x, Data.Access.Group.x, Patient.ID, COVID.19.related.entry., Interval.from.diagnosis..months., Hospital.Site, Other.Hospital, Type.of.Visit, Employment.status, Disease.activity.since.last.return, Urinalysis.Done, urinalysis_protein, urinalysis_blood, Dialysis.dependent, Date.of.dialysis.start, Date.of.dialysis.stop, Sofa.score, Weight..KG., BMI, Is.this.the.patient.s.first.assessment., General.features, General.features...yes..choice.Myalgia., General.features...yes..choice.Arthralgia...arthritis., General.features...yes..choice.Fever....38.C., General.features...yes..choice.Weight.loss.....2.kg., Cutaneous, Cutaneous...yes..choice.Infarct., Cutaneous...yes..choice.Purpura., Cutaneous...yes..choice.Ulcer., Cutaneous...yes..choice.Gangrene., Cutaneous...yes..choice.Other.skin.vasculitis., Mucous.membranes...eyes, Mucous.membranes...eyes...yes..choice.Mouth.ulcers., Mucous.membranes...eyes...yes..choice.Genital.ulcers., Mucous.membranes...eyes...yes..choice.Adnexal.inflammation., Mucous.membranes...eyes...yes..choice.Significant.proptosis., Mucous.membranes...eyes...yes..choice.Scleritis...Episcleritis., Mucous.membranes...eyes...yes..choice.Conjunctivitis...Blepharitis...Keratitis., Mucous.membranes...eyes...yes..choice.Blurred.vision., Mucous.membranes...eyes...yes..choice.Sudden.visual.loss., Mucous.membranes...eyes...yes..choice.Uveitis., Mucous.membranes...eyes...yes..choice.Retinal.changes..vasculitis..thrombosis...exudate...haemorrhage.., ENT, ENT...yes..choice.Bloody.nasal.discharge...crusts...ulcers...granulomata., ENT...yes..choice.Paranasal.sinus.involvement., ENT...yes..choice.Subglottic.stenosis., ENT...yes..choice.Conductive.hearing.loss., ENT...yes..choice.Sensorineural.hearing.loss., Chest, Chest...yes..choice.Wheeze., Chest...yes..choice.Nodules.or.cavities., Chest...yes..choice.Pleural.effusion...pleurisy., Chest...yes..choice.Infiltrate., Chest...yes..choice.Endobronchial.involvement., Chest...yes..choice.Massive.haemoptysis...alveolar.haemorrhage., Chest...yes..choice.Respiratory.failure., Cardiovascular, Cardiovascular...yes..choice.Loss.of.pulses., Cardiovascular...yes..choice.Valvular.heart.disease., Cardiovascular...yes..choice.Pericarditis., Cardiovascular...yes..choice.Ischaemic.cardiac.pain., Cardiovascular...yes..choice.Cardiomyopathy., Cardiovascular...yes..choice.Congestive.cardiac.failure., Abdominal, Abdominal...yes..choice.Bloody.diarrhoea., Abdominal...yes..choice.Peritonitis., Abdominal...yes..choice.Ischaemic.abdominal.pain., Renal, Renal...yes..choice.Hypertension., Renal...yes..choice.Proteinuria..1.., Renal...yes..choice.Haematuria....10.RBCs.hpf., Renal...yes..choice.Serum.creatinine.125.249....uM.L., Renal...yes..choice.Serum.creatinine.250.499.....uM.L., Renal...yes..choice.Serum.creatinine....500.uM.L., Renal...yes..choice.Rise.in.serum.creatinine..30..or.fall.in.creatinine.clearance..25.., Nervous.system, Nervous.system...yes..choice.Headache., Nervous.system...yes..choice.Meningitis., Nervous.system...yes..choice.Organic.confusion., Nervous.system...yes..choice.Seizures..not.hypertensive.., Nervous.system...yes..choice.Cerebrovascular.accident., Nervous.system...yes..choice.Spinal.cord.lesion., Nervous.system...yes..choice.Cranial.nerve.palsy., Nervous.system...yes..choice.Sensory.peripheral.neuropathy., Nervous.system...yes..choice.Mononeuritis.multiplex., Other.1, Other.1...yes, Other.2...yes, Other.3...yes, Other.4...yes, PERSISTENT.DISEASE.ONLY...Tick.here.if.all.the.abnormalities.are.due.to.persistent.disease., BVAS.score, bvasScoreCalculator, numberOfMajorBVASItems, ...]
Index: []

[0 rows x 517 columns]

In [5]:
data1['Age_Encounters'].describe()

count    8017.000000
mean       62.499688
std        14.433654
min        10.000000
25%        54.000000
50%        64.000000
75%        73.000000
max        98.000000
Name: Age_Encounters, dtype: float64


## Import IV therapy data

In [6]:
IV=pd.read_csv("C:/Users/georgea1/OneDrive - Trinity College Dublin/Angel George/Chap 2. Treatment/Data/ITIS Data/RIV/April 2026/Redcap_IVTherapy_data_merged_version0.0.3 (8).csv")
IV

,RKD.ID,Repeat.Instrument,Repeat.Instance,Data.Access.Group,IV.therapy,IV.therapy...other..ATC,Vaccine,Vaccine...Other..ATC,Date.of.IV.therapy,Dose.of.IV.therapy,Unit.of.dose,Unit.of.dose...other,Complete..7,Date.of.diagnosis,IVTherapy_interval_from_diagnosis
0,1,Treatment - Intermittent pulse administrations,1,TUH - Tallaght,Cyclophosphamide Injectable Solution - UATC/ L...,NaN,NaN,NaN,2012-09-03,920.0,mg,NaN,Complete,31/08/2012,3.0
1,1,Treatment - Intermittent pulse administrations,2,TUH - Tallaght,Cyclophosphamide Injectable Solution - UATC/ L...,NaN,NaN,NaN,2012-09-17,920.0,mg,NaN,Complete,31/08/2012,17.0
2,1,Treatment - Intermittent pulse administrations,3,TUH - Tallaght,Methylprednisolone - UATC/D07AA01,NaN,NaN,NaN,2012-09-17,500.0,mg,NaN,Complete,31/08/2012,17.0
3,1,Treatment - Intermittent pulse administrations,4,TUH - Tallaght,Methylprednisolone - UATC/D07AA01,NaN,NaN,NaN,2012-09-19,500.0,mg,NaN,Complete,31/08/2012,19.0
4,1,Treatment - Intermittent pulse administrations,5,TUH - Tallaght,Cyclophosphamide Injectable Solution - UATC/ L...,NaN,NaN,NaN,2012-10-01,920.0,mg,NaN,Complete,31/08/2012,31.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6379,28797,Treatment - Intermittent pulse administrations,2,CUH - Cork University Hospital,Rituximab - UATC/L01XC02 -- Truxima,NaN,NaN,NaN,2026-03-02,1000.0,mg,NaN,Complete,10/02/2026,20.0
6380,28800,Treatment - Intermittent pulse administrations,1,CUH - Cork University Hospital,Methylprednisolone - UATC/D07AA01,NaN,NaN,NaN,2026-02-13,1.0,g,NaN,Complete,NaN,NaN
6381,28800,Treatment - Intermittent pulse administrations,2,CUH - Cork University Hospital,Methylprednisolone - UATC/D07AA01,NaN,NaN,NaN,2026-02-14,1.0,g,NaN,Complete,NaN,NaN
6382,28800,Treatment - Intermittent pulse administrations,3,CUH - Cork University Hospital,Methylprednisolone - UATC/D07AA01,NaN,NaN,NaN,2026-02-15,1.0,g,NaN,Complete,NaN,NaN
6383,28800,Treatment - Intermittent pulse administrations,4,CUH - Cork University Hospital,Cyclophosphamide Injectable Solution - UATC/ L...,NaN,NaN,NaN,2026-02-19,1.2,g,NaN,Complete,NaN,NaN

In [7]:
IV.rename(columns = {'Date of IV therapy':'Date.of.IV.therapy'}, inplace = True)
IV.rename(columns = {'RKD ID':'RKD.ID'}, inplace = True)
IV.rename(columns = {'IV therapy':'IV.therapy'}, inplace = True)
IV.rename(columns = {'Dose of IV therapy':'Dose.of.IV.therapy'}, inplace = True)

In [8]:
IV['Date.of.IV.therapy'] = pd.to_datetime(IV['Date.of.IV.therapy'], format='%Y-%m-%d')

In [9]:
IV= IV.sort_values(by=['RKD.ID', 'Date.of.IV.therapy'])

In [10]:
duplicateRows = IV[IV.duplicated(['RKD.ID','Date.of.IV.therapy','IV.therapy'])]
duplicateRows

,RKD.ID,Repeat.Instrument,Repeat.Instance,Data.Access.Group,IV.therapy,IV.therapy...other..ATC,Vaccine,Vaccine...Other..ATC,Date.of.IV.therapy,Dose.of.IV.therapy,Unit.of.dose,Unit.of.dose...other,Complete..7,Date.of.diagnosis,IVTherapy_interval_from_diagnosis
80,7,Treatment - Intermittent pulse administrations,21,TUH - Tallaght,Vaccine,NaN,Influenza vaccines - UATC/J07BB -- Quadrivalen...,NaN,2025-10-23,NaN,NaN,NaN,Complete,01/10/2011,5136.0
363,59,Treatment - Intermittent pulse administrations,9,TUH - Tallaght,"IvIg - UATC/J06BA02 (immunoglobulins, normal h...",NaN,NaN,NaN,2013-03-17,45.0,g,NaN,Complete,27/02/2013,18.0
452,77,Treatment - Intermittent pulse administrations,10,TUH - Tallaght,Cyclophosphamide Injectable Solution - UATC/ L...,NaN,NaN,NaN,2017-12-18,700.0,mg,NaN,Complete,26/06/2014,1271.0
455,77,Treatment - Intermittent pulse administrations,13,TUH - Tallaght,Cyclophosphamide Injectable Solution - UATC/ L...,NaN,NaN,NaN,2018-01-11,700.0,mg,NaN,Complete,26/06/2014,1295.0
502,85,Treatment - Intermittent pulse administrations,5,TUH - Tallaght,Cyclophosphamide Injectable Solution - UATC/ L...,NaN,NaN,NaN,2014-11-24,1100.0,mg,NaN,Complete,14/08/2014,102.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6233,28733,Treatment - Intermittent pulse administrations,2,NaN,Vaccine,NaN,Influenza vaccines - UATC/J07BB -- Quadrivalen...,NaN,2024-10-01,NaN,NaN,NaN,Complete,NaN,NaN
6240,28736,Treatment - Intermittent pulse administrations,2,NaN,Vaccine,NaN,Influenza vaccines - UATC/J07BB -- Quadrivalen...,NaN,2024-10-01,NaN,NaN,NaN,Complete,NaN,NaN
6335,28772,Treatment - Intermittent pulse administrations,4,CUH - Cork University Hospital,Methylprednisolone - UATC/D07AA01,NaN,NaN,NaN,NaT,1.0,g,NaN,Incomplete,11/11/2025,NaN
6336,28772,Treatment - Intermittent pulse administrations,5,CUH - Cork University Hospital,Methylprednisolone - UATC/D07AA01,NaN,NaN,NaN,NaT,1.0,g,NaN,Incomplete,11/11/2025,NaN
6361,28783,Treatment - Intermittent pulse administrations,2,NaN,Rituximab - UATC/L01XC02 -- Ruxience,NaN,NaN,NaN,NaT,NaN,NaN,NaN,Incomplete,24/01/2025,NaN

In [11]:
duplicateRows.shape

(68, 15)

In [12]:
IV=IV.drop_duplicates(subset=['RKD.ID','Date.of.IV.therapy','IV.therapy'], keep='first')

In [13]:
# List of columns to keep
columns_to_keep = [
    "RKD.ID",
    "IV.therapy",
    "Date.of.IV.therapy",
    "Dose.of.IV.therapy",
    "Unit.of.dose",
    'Unit.of.dose...other'
]

# Keep only the selected columns
IV= IV[columns_to_keep]
IV

,RKD.ID,IV.therapy,Date.of.IV.therapy,Dose.of.IV.therapy,Unit.of.dose,Unit.of.dose...other
0,1,Cyclophosphamide Injectable Solution - UATC/ L...,2012-09-03,920.0,mg,NaN
1,1,Cyclophosphamide Injectable Solution - UATC/ L...,2012-09-17,920.0,mg,NaN
2,1,Methylprednisolone - UATC/D07AA01,2012-09-17,500.0,mg,NaN
3,1,Methylprednisolone - UATC/D07AA01,2012-09-19,500.0,mg,NaN
4,1,Cyclophosphamide Injectable Solution - UATC/ L...,2012-10-01,920.0,mg,NaN
...,...,...,...,...,...,...
6379,28797,Rituximab - UATC/L01XC02 -- Truxima,2026-03-02,1000.0,mg,NaN
6380,28800,Methylprednisolone - UATC/D07AA01,2026-02-13,1.0,g,NaN
6381,28800,Methylprednisolone - UATC/D07AA01,2026-02-14,1.0,g,NaN
6382,28800,Methylprednisolone - UATC/D07AA01,2026-02-15,1.0,g,NaN
6383,28800,Cyclophosphamide Injectable Solution - UATC/ L...,2026-02-19,1.2,g,NaN

## Subset Methylprednisolone

In [14]:
mtp=IV.loc[(IV['IV.therapy']=='Methylprednisolone - UATC/D07AA01')]
mtp

,RKD.ID,IV.therapy,Date.of.IV.therapy,Dose.of.IV.therapy,Unit.of.dose,Unit.of.dose...other
2,1,Methylprednisolone - UATC/D07AA01,2012-09-17,500.0,mg,NaN
3,1,Methylprednisolone - UATC/D07AA01,2012-09-19,500.0,mg,NaN
25,2,Methylprednisolone - UATC/D07AA01,2012-03-26,500.0,mg,NaN
26,2,Methylprednisolone - UATC/D07AA01,2012-03-27,500.0,mg,NaN
27,2,Methylprednisolone - UATC/D07AA01,2012-03-28,500.0,mg,NaN
...,...,...,...,...,...,...
6371,28793,Methylprednisolone - UATC/D07AA01,2026-01-23,500.0,mg,NaN
6372,28793,Methylprednisolone - UATC/D07AA01,2026-01-24,500.0,mg,NaN
6380,28800,Methylprednisolone - UATC/D07AA01,2026-02-13,1.0,g,NaN
6381,28800,Methylprednisolone - UATC/D07AA01,2026-02-14,1.0,g,NaN
6382,28800,Methylprednisolone - UATC/D07AA01,2026-02-15,1.0,g,NaN

In [15]:
mtp= mtp.dropna(axis=1, how='all')
mtp

,RKD.ID,IV.therapy,Date.of.IV.therapy,Dose.of.IV.therapy,Unit.of.dose
2,1,Methylprednisolone - UATC/D07AA01,2012-09-17,500.0,mg
3,1,Methylprednisolone - UATC/D07AA01,2012-09-19,500.0,mg
25,2,Methylprednisolone - UATC/D07AA01,2012-03-26,500.0,mg
26,2,Methylprednisolone - UATC/D07AA01,2012-03-27,500.0,mg
27,2,Methylprednisolone - UATC/D07AA01,2012-03-28,500.0,mg
...,...,...,...,...,...
6371,28793,Methylprednisolone - UATC/D07AA01,2026-01-23,500.0,mg
6372,28793,Methylprednisolone - UATC/D07AA01,2026-01-24,500.0,mg
6380,28800,Methylprednisolone - UATC/D07AA01,2026-02-13,1.0,g
6381,28800,Methylprednisolone - UATC/D07AA01,2026-02-14,1.0,g
6382,28800,Methylprednisolone - UATC/D07AA01,2026-02-15,1.0,g

In [16]:
mtp['Dose.of.IV.therapy'].isnull().sum()

9

In [17]:
mtp['Dose.of.IV.therapy'].describe()

count    1379.000000
mean      589.262509
std       274.581319
min         1.000000
25%       500.000000
50%       500.000000
75%      1000.000000
max      2000.000000
Name: Dose.of.IV.therapy, dtype: float64

In [18]:
mtp['Dose.of.IV.therapy'].value_counts(dropna=False)

Dose.of.IV.therapy
500.0     773
1000.0    366
250.0     141
100.0      24
125.0      23
1.0        13
NaN         9
800.0       6
300.0       6
150.0       5
625.0       4
550.0       3
750.0       3
350.0       3
410.0       3
375.0       3
340.0       1
2000.0      1
60.0        1
Name: count, dtype: int64

In [19]:
mtp['Unit.of.dose'].value_counts(dropna=False)

Unit.of.dose
mg    1378
g       10
Name: count, dtype: int64

In [20]:
mask = mtp['Unit.of.dose'] == 'g'
mtp.loc[mask, 'Dose.of.IV.therapy'] *= 1000
mtp.loc[mask, 'Unit.of.dose'] = 'mg'

## Round the doses to the interval [250,3000]

In [21]:
mtp.loc[mtp['Dose.of.IV.therapy'] < 250, 'Dose.of.IV.therapy'] = 250

In [22]:
mtp['Dose.of.IV.therapy'].describe()

count    1379.00000
mean      602.24438
std       263.04614
min       250.00000
25%       500.00000
50%       500.00000
75%      1000.00000
max      2000.00000
Name: Dose.of.IV.therapy, dtype: float64

## Fill missing dose with median, which is 500mg

In [23]:
mtp['Dose.of.IV.therapy'] = mtp['Dose.of.IV.therapy'].fillna(500)
mtp['Dose.of.IV.therapy'].isnull().sum()

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\1294994764.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mtp['Dose.of.IV.therapy'] = mtp['Dose.of.IV.therapy'].fillna(500)

0

## Create separate columns for each dose

In [24]:
# Step 1 — Sort by ID and dose date
mtp_sorted = mtp.sort_values(["RKD.ID", "Date.of.IV.therapy"]).copy()

# Step 2 — Assign dose number for each patient
mtp_sorted["dose_number"] = mtp_sorted.groupby("RKD.ID").cumcount() + 1

# Step 3 — Rename columns for pivoting
mtp_wide = mtp_sorted.pivot_table(
    index="RKD.ID",
    columns="dose_number",
    values=["Date.of.IV.therapy", "Dose.of.IV.therapy"],
    aggfunc="first"
)

# Step 4 — Flatten multi-index column names
mtp_wide.columns = [
    f"mtp_{col[1]}_dose_{col[0].replace('Date.of.IV.therapy','date').replace('Dose.of.IV.therapy','value')}"
    for col in mtp_wide.columns
]

mtp_wide = mtp_wide.reset_index()
mtp_wide

,RKD.ID,mtp_1_dose_date,mtp_2_dose_date,mtp_3_dose_date,mtp_4_dose_date,mtp_5_dose_date,mtp_6_dose_date,mtp_7_dose_date,mtp_8_dose_date,mtp_9_dose_date,...,mtp_5_dose_value,mtp_6_dose_value,mtp_7_dose_value,mtp_8_dose_value,mtp_9_dose_value,mtp_10_dose_value,mtp_11_dose_value,mtp_12_dose_value,mtp_13_dose_value,mtp_14_dose_value
0,1,2012-09-17,2012-09-19,NaT,NaT,NaT,NaT,NaT,NaT,NaT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,2012-03-26,2012-03-27,2012-03-28,NaT,NaT,NaT,NaT,NaT,NaT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,2012-05-24,2017-04-06,NaT,NaT,NaT,NaT,NaT,NaT,NaT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,7,2012-06-14,2012-06-15,2012-06-16,NaT,NaT,NaT,NaT,NaT,NaT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,9,2012-12-07,2012-12-08,2012-12-09,NaT,NaT,NaT,NaT,NaT,NaT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
465,28779,2025-11-18,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
466,28780,2024-05-17,2024-05-18,2024-05-19,NaT,NaT,NaT,NaT,NaT,NaT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
467,28790,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
468,28793,2026-01-22,2026-01-23,2026-01-24,NaT,NaT,NaT,NaT,NaT,NaT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
469,28800,2026-02-13,2026-02-14,2026-02-15,NaT,NaT,NaT,NaT,NaT,NaT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [25]:
mtp_wide.columns

Index(['RKD.ID', 'mtp_1_dose_date', 'mtp_2_dose_date', 'mtp_3_dose_date',
       'mtp_4_dose_date', 'mtp_5_dose_date', 'mtp_6_dose_date',
       'mtp_7_dose_date', 'mtp_8_dose_date', 'mtp_9_dose_date',
       'mtp_10_dose_date', 'mtp_11_dose_date', 'mtp_12_dose_date',
       'mtp_13_dose_date', 'mtp_14_dose_date', 'mtp_1_dose_value',
       'mtp_2_dose_value', 'mtp_3_dose_value', 'mtp_4_dose_value',
       'mtp_5_dose_value', 'mtp_6_dose_value', 'mtp_7_dose_value',
       'mtp_8_dose_value', 'mtp_9_dose_value', 'mtp_10_dose_value',
       'mtp_11_dose_value', 'mtp_12_dose_value', 'mtp_13_dose_value',
       'mtp_14_dose_value'],
      dtype='object')

In [26]:
mtp_wide['mtp_1_dose_value'].value_counts(dropna=False)

mtp_1_dose_value
500.0     268
1000.0    135
250.0      58
800.0       2
550.0       1
2000.0      1
350.0       1
410.0       1
300.0       1
625.0       1
375.0       1
Name: count, dtype: int64

## Merge with encounter frame

In [27]:
import numpy as np
import pandas as pd

def merge_visits_with_mtp(visits, mtp_wide):

    df = visits.copy()
    mtp = mtp_wide.copy()

    # Ensure Date_Of_Visit is datetime
    df["Date_Of_Visit"] = pd.to_datetime(df["Date_Of_Visit"], errors="coerce")

    # Merge wide IV data onto visits
    df = df.merge(mtp, on="RKD.ID", how="left")

    # Identify dose blocks
    dose_numbers = sorted(
        int(col.split("_")[1])
        for col in mtp.columns
        if col.startswith("mtp_") and col.endswith("_dose_date")
    )

    for n in dose_numbers:

        dose_date_col = f"mtp_{n}_dose_date"
        value_col     = f"mtp_{n}_dose_value"

        # Convert IV dates to datetime
        df[dose_date_col] = pd.to_datetime(df[dose_date_col], errors="coerce")

        # Condition:
        # Keep the dose if the visit occurs AFTER the dose date
        # Blank it otherwise
        mask = (
            df[dose_date_col].notna() &
            (df[dose_date_col] < df["Date_Of_Visit"])
        )

        # Blank outside window
        df.loc[~mask, [dose_date_col, value_col]] = [np.nan, np.nan]

    return df

In [28]:
mtp_merged_data = merge_visits_with_mtp(data1, mtp_wide)
mtp_merged_data

,RKD.ID,Date_Of_Visit,ANCA_Levels,anca_status,ancaswitch,Repeat.Instrument,Repeat.Instance.x,Data.Access.Group.x,Patient.ID,COVID.19.related.entry.,...,mtp_5_dose_value,mtp_6_dose_value,mtp_7_dose_value,mtp_8_dose_value,mtp_9_dose_value,mtp_10_dose_value,mtp_11_dose_value,mtp_12_dose_value,mtp_13_dose_value,mtp_14_dose_value
0,1,2012-08-31,134.0,ANCA Positive,Switch Status Unknown,Encounters,1,TUH - Tallaght,1,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,2012-09-07,NaN,ANCA Positive,Pos-Pos Switch,Encounters,36,TUH - Tallaght,1,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,2012-09-17,110.0,ANCA Positive,Pos-Pos Switch,Encounters,37,TUH - Tallaght,1,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1,2012-09-21,92.0,ANCA Positive,Pos-Pos Switch,Encounters,2,TUH - Tallaght,1,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1,2012-09-28,NaN,ANCA Positive,Pos-Pos Switch,Encounters,28,TUH - Tallaght,1,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8022,28793,2026-01-21,147.0,ANCA Positive,Switch Status Unknown,Encounters,1,CUH - Cork University Hospital,28793,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8023,28796,2025-07-28,NaN,ANCA Status Unknown,Switch Status Unknown,Encounters,2,NaN,28796,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8024,28796,2026-01-30,NaN,ANCA Negative,Switch Status Unknown,Encounters,1,NaN,28796,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8025,28797,2026-02-02,134.0,ANCA Positive,Switch Status Unknown,Encounters,1,CUH - Cork University Hospital,28797,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8026,28797,2026-03-26,134.0,ANCA Positive,Pos-Pos Switch,Encounters,2,CUH - Cork University Hospital,28797,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Reorder columns

In [29]:
def reorder_mtp_columns(df):

    cols = list(df.columns)

    # Identify dose numbers based ONLY on dose_date
    dose_numbers = sorted(
        int(c.split("_")[1])
        for c in cols
        if c.startswith("mtp_") and c.endswith("_dose_date")
    )

    # 1) Core columns (non-mtp)
    core_cols = [c for c in cols if not c.startswith("mtp_")]

    # 2) Dose blocks (ordered)
    dose_blocks = []
    for n in dose_numbers:
        block = [
            f"mtp_{n}_dose_date",
            f"mtp_{n}_dose_value",
            f"mtp_{n}_dose_unit",
            f"mtp_{n}_vanish_days",
            f"mtp_{n}_vanish_date",
        ]
        dose_blocks.extend([c for c in block if c in cols])

    # 3) Everything else starting with mtp_ (course columns, intervals, etc.)
    other_mtp_cols = [
        c for c in cols
        if c.startswith("mtp_") and c not in dose_blocks
    ]

    # Build final ordering
    ordered_cols = core_cols + dose_blocks + other_mtp_cols

    return df[ordered_cols]

In [30]:
mtp_merged_data = reorder_mtp_columns(mtp_merged_data)
mtp_merged_data

,RKD.ID,Date_Of_Visit,ANCA_Levels,anca_status,ancaswitch,Repeat.Instrument,Repeat.Instance.x,Data.Access.Group.x,Patient.ID,COVID.19.related.entry.,...,mtp_10_dose_date,mtp_10_dose_value,mtp_11_dose_date,mtp_11_dose_value,mtp_12_dose_date,mtp_12_dose_value,mtp_13_dose_date,mtp_13_dose_value,mtp_14_dose_date,mtp_14_dose_value
0,1,2012-08-31,134.0,ANCA Positive,Switch Status Unknown,Encounters,1,TUH - Tallaght,1,No,...,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN
1,1,2012-09-07,NaN,ANCA Positive,Pos-Pos Switch,Encounters,36,TUH - Tallaght,1,No,...,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN
2,1,2012-09-17,110.0,ANCA Positive,Pos-Pos Switch,Encounters,37,TUH - Tallaght,1,No,...,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN
3,1,2012-09-21,92.0,ANCA Positive,Pos-Pos Switch,Encounters,2,TUH - Tallaght,1,No,...,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN
4,1,2012-09-28,NaN,ANCA Positive,Pos-Pos Switch,Encounters,28,TUH - Tallaght,1,No,...,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8022,28793,2026-01-21,147.0,ANCA Positive,Switch Status Unknown,Encounters,1,CUH - Cork University Hospital,28793,No,...,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN
8023,28796,2025-07-28,NaN,ANCA Status Unknown,Switch Status Unknown,Encounters,2,NaN,28796,No,...,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN
8024,28796,2026-01-30,NaN,ANCA Negative,Switch Status Unknown,Encounters,1,NaN,28796,No,...,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN
8025,28797,2026-02-02,134.0,ANCA Positive,Switch Status Unknown,Encounters,1,CUH - Cork University Hospital,28797,NaN,...,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN
8026,28797,2026-03-26,134.0,ANCA Positive,Pos-Pos Switch,Encounters,2,CUH - Cork University Hospital,28797,NaN,...,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN

In [31]:
#mtp_merged_data.to_csv('C:/Users/georgea1/OneDrive - Trinity College Dublin/Desktop/mtp_itis_final_riv2.csv',index=True)

In [32]:
## Apply age encouters and calculate relative dose

In [33]:
import pandas as pd
import numpy as np

# Ensure Age_Encounters is numeric
mtp_merged_data["Age_Encounters"] = pd.to_numeric(
    mtp_merged_data["Age_Encounters"], errors="coerce"
)

age = mtp_merged_data["Age_Encounters"]

for n in range(1, 15):
    dose_col = f"mtp_{n}_dose_value"

    if dose_col in mtp_merged_data.columns:
        # Ensure dose column is numeric
        mtp_merged_data[dose_col] = pd.to_numeric(
            mtp_merged_data[dose_col], errors="coerce"
        )

        dose = mtp_merged_data[dose_col]

        mtp_merged_data[dose_col] = np.select(
            [
                age.between(65, 73, inclusive="both") & dose.notna(),
                age.between(74, 82, inclusive="both") & dose.notna(),
                age.gt(82) & dose.notna(),
            ],
            [
                dose * 1.5,
                dose * 2.0,
                dose * 2.5
            ],
            default=dose
        )

## Define course

### Calculate interval between doses

## Remove blank columns

In [34]:
mtp_merged_data  = mtp_merged_data.dropna(axis=1, how='all')
mtp_merged_data

,RKD.ID,Date_Of_Visit,ANCA_Levels,anca_status,ancaswitch,Repeat.Instrument,Repeat.Instance.x,Data.Access.Group.x,Patient.ID,COVID.19.related.entry.,...,mtp_10_dose_date,mtp_10_dose_value,mtp_11_dose_date,mtp_11_dose_value,mtp_12_dose_date,mtp_12_dose_value,mtp_13_dose_date,mtp_13_dose_value,mtp_14_dose_date,mtp_14_dose_value
0,1,2012-08-31,134.0,ANCA Positive,Switch Status Unknown,Encounters,1,TUH - Tallaght,1,No,...,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN
1,1,2012-09-07,NaN,ANCA Positive,Pos-Pos Switch,Encounters,36,TUH - Tallaght,1,No,...,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN
2,1,2012-09-17,110.0,ANCA Positive,Pos-Pos Switch,Encounters,37,TUH - Tallaght,1,No,...,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN
3,1,2012-09-21,92.0,ANCA Positive,Pos-Pos Switch,Encounters,2,TUH - Tallaght,1,No,...,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN
4,1,2012-09-28,NaN,ANCA Positive,Pos-Pos Switch,Encounters,28,TUH - Tallaght,1,No,...,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8022,28793,2026-01-21,147.0,ANCA Positive,Switch Status Unknown,Encounters,1,CUH - Cork University Hospital,28793,No,...,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN
8023,28796,2025-07-28,NaN,ANCA Status Unknown,Switch Status Unknown,Encounters,2,NaN,28796,No,...,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN
8024,28796,2026-01-30,NaN,ANCA Negative,Switch Status Unknown,Encounters,1,NaN,28796,No,...,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN
8025,28797,2026-02-02,134.0,ANCA Positive,Switch Status Unknown,Encounters,1,CUH - Cork University Hospital,28797,NaN,...,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN
8026,28797,2026-03-26,134.0,ANCA Positive,Pos-Pos Switch,Encounters,2,CUH - Cork University Hospital,28797,NaN,...,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN

In [35]:
import numpy as np
import pandas as pd

def min_interval_table(df, max_dose=14):
    x = df.copy()

    # Parse dose dates
    for n in range(1, max_dose + 1):
        col = f"mtp_{n}_dose_date"
        if col in x.columns:
            x[col] = pd.to_datetime(x[col], errors="coerce", dayfirst=True)

    # Use earliest dose dates per patient (avoids repeated visit rows)
    per_patient = (
        x.groupby("RKD.ID")[[c for c in x.columns if c.startswith("mtp_") and c.endswith("_dose_date")]]
         .min()
         .reset_index()
    )

    # Build min interval per dose (global min across dataset)
    rows = []
    d1 = "mtp_1_dose_date"

    for n in range(2, max_dose + 1):
        dn = f"mtp_{n}_dose_date"
        if dn not in per_patient.columns:
            continue

        interval_series = (per_patient[dn] - per_patient[d1]).dt.days

        rows.append({
            "interval_name": f"interval_{n}_minus_1_days",
            "min_days": interval_series.min(skipna=True)
        })

    return pd.DataFrame(rows)

# Example:
min_intervals_table = min_interval_table(mtp_merged_data, max_dose=14)
min_intervals_table

               interval_name  min_days
0    interval_2_minus_1_days       1.0
1    interval_3_minus_1_days       2.0
2    interval_4_minus_1_days       3.0
3    interval_5_minus_1_days       4.0
4    interval_6_minus_1_days       5.0
5    interval_7_minus_1_days       9.0
6    interval_8_minus_1_days      13.0
7    interval_9_minus_1_days      17.0
8   interval_10_minus_1_days    3154.0
9   interval_11_minus_1_days    3182.0
10  interval_12_minus_1_days    3183.0
11  interval_13_minus_1_days    3185.0
12  interval_14_minus_1_days    3186.0

In [36]:
def update_mtp_doses(df, base_dose, target_dose, max_days=30):
    result = df.copy()

    base_date   = f"mtp_{base_dose}_dose_date"
    target_date = f"mtp_{target_dose}_dose_date"
    base_value  = f"mtp_{base_dose}_dose_value"
    target_value= f"mtp_{target_dose}_dose_value"

    # Parse dates
    result[base_date]   = pd.to_datetime(result[base_date], errors="coerce", dayfirst=True)
    result[target_date] = pd.to_datetime(result[target_date], errors="coerce", dayfirst=True)

    # Parse numeric values
    result[base_value]   = pd.to_numeric(result[base_value], errors="coerce")
    result[target_value] = pd.to_numeric(result[target_value], errors="coerce")

    def _per_patient(g):
        g = g.copy()

        d_base   = g[base_date].dropna()
        d_target = g[target_date].dropna()

        # Need both doses
        if d_base.empty or d_target.empty:
            return g

        base_date_val   = d_base.iloc[0]
        target_date_val = d_target.iloc[0]

        # Check interval
        interval_days = (target_date_val - base_date_val).days
        if pd.isna(interval_days) or interval_days > max_days:
            return g

        # Get dose values
        v_base   = g.loc[g[base_date].notna(), base_value].dropna()
        v_target = g.loc[g[target_date].notna(), target_value].dropna()

        base_val   = v_base.iloc[0]   if not v_base.empty   else np.nan
        target_val = v_target.iloc[0] if not v_target.empty else np.nan

        cumulative = base_val + target_val

        # Replace ALL non-missing base-dose rows
        mask = g[base_date].notna()
        g.loc[mask, base_date]  = target_date_val
        g.loc[mask, base_value] = cumulative

        # Blank target-dose after merge
        g[target_date]  = pd.NaT
        g[target_value] = np.nan

        return g

    return result.groupby("RKD.ID", group_keys=False).apply(_per_patient)

In [37]:
mtp_merged_data = update_mtp_doses(mtp_merged_data, base_dose=1, target_dose=2)

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\684288360.py:55: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  return result.groupby("RKD.ID", group_keys=False).apply(_per_patient)

In [38]:
mtp_merged_data = update_mtp_doses(mtp_merged_data, base_dose=1, target_dose=3)

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\684288360.py:55: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  return result.groupby("RKD.ID", group_keys=False).apply(_per_patient)

In [39]:
mtp_merged_data = update_mtp_doses(mtp_merged_data, base_dose=1, target_dose=4)

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\684288360.py:55: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  return result.groupby("RKD.ID", group_keys=False).apply(_per_patient)

In [40]:
mtp_merged_data = update_mtp_doses(mtp_merged_data, base_dose=1, target_dose=5)

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\684288360.py:55: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  return result.groupby("RKD.ID", group_keys=False).apply(_per_patient)

In [41]:
mtp_merged_data = update_mtp_doses(mtp_merged_data, base_dose=1, target_dose=6)

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\684288360.py:55: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  return result.groupby("RKD.ID", group_keys=False).apply(_per_patient)

In [42]:
mtp_merged_data = update_mtp_doses(mtp_merged_data, base_dose=1, target_dose=7)

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\684288360.py:55: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  return result.groupby("RKD.ID", group_keys=False).apply(_per_patient)

In [43]:
mtp_merged_data = update_mtp_doses(mtp_merged_data, base_dose=1, target_dose=8)

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\684288360.py:55: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  return result.groupby("RKD.ID", group_keys=False).apply(_per_patient)

In [44]:
mtp_merged_data = update_mtp_doses(mtp_merged_data, base_dose=1, target_dose=9)

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\684288360.py:55: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  return result.groupby("RKD.ID", group_keys=False).apply(_per_patient)

In [45]:
import numpy as np
import pandas as pd

def min_interval_table(df, max_dose=14):
    x = df.copy()

    # Parse dose dates
    for n in range(1, max_dose + 1):
        col = f"mtp_{n}_dose_date"
        if col in x.columns:
            x[col] = pd.to_datetime(x[col], errors="coerce", dayfirst=True)

    # Use earliest dose dates per patient (avoids repeated visit rows)
    per_patient = (
        x.groupby("RKD.ID")[[c for c in x.columns if c.startswith("mtp_") and c.endswith("_dose_date")]]
         .min()
         .reset_index()
    )

    # Build min interval per dose (global min across dataset)
    rows = []
    d1 = "mtp_2_dose_date"

    for n in range(2, max_dose + 1):
        dn = f"mtp_{n}_dose_date"
        if dn not in per_patient.columns:
            continue

        interval_series = (per_patient[dn] - per_patient[d1]).dt.days

        rows.append({
            "interval_name": f"interval_{n}_minus_2_days",
            "min_days": interval_series.min(skipna=True)
        })

    return pd.DataFrame(rows)

# Example:
min_intervals_table = min_interval_table(mtp_merged_data, max_dose=14)
min_intervals_table

               interval_name  min_days
0    interval_2_minus_2_days       0.0
1    interval_3_minus_2_days       1.0
2    interval_4_minus_2_days       7.0
3    interval_5_minus_2_days       NaN
4    interval_6_minus_2_days       NaN
5    interval_7_minus_2_days       NaN
6    interval_8_minus_2_days       NaN
7    interval_9_minus_2_days       NaN
8   interval_10_minus_2_days       NaN
9   interval_11_minus_2_days       NaN
10  interval_12_minus_2_days       NaN
11  interval_13_minus_2_days       NaN
12  interval_14_minus_2_days       NaN

In [46]:
mtp_merged_data = update_mtp_doses(mtp_merged_data, base_dose=2, target_dose=3)

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\684288360.py:55: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  return result.groupby("RKD.ID", group_keys=False).apply(_per_patient)

In [47]:
mtp_merged_data = update_mtp_doses(mtp_merged_data, base_dose=2, target_dose=4)

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\684288360.py:55: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  return result.groupby("RKD.ID", group_keys=False).apply(_per_patient)

In [48]:
import numpy as np
import pandas as pd

def min_interval_table(df, max_dose=14):
    x = df.copy()

    # Parse dose dates
    for n in range(1, max_dose + 1):
        col = f"mtp_{n}_dose_date"
        if col in x.columns:
            x[col] = pd.to_datetime(x[col], errors="coerce", dayfirst=True)

    # Use earliest dose dates per patient (avoids repeated visit rows)
    per_patient = (
        x.groupby("RKD.ID")[[c for c in x.columns if c.startswith("mtp_") and c.endswith("_dose_date")]]
         .min()
         .reset_index()
    )

    # Build min interval per dose (global min across dataset)
    rows = []
    d1 = "mtp_3_dose_date"

    for n in range(2, max_dose + 1):
        dn = f"mtp_{n}_dose_date"
        if dn not in per_patient.columns:
            continue

        interval_series = (per_patient[dn] - per_patient[d1]).dt.days

        rows.append({
            "interval_name": f"interval_{n}_minus_3_days",
            "min_days": interval_series.min(skipna=True)
        })

    return pd.DataFrame(rows)

# Example:
min_intervals_table = min_interval_table(mtp_merged_data, max_dose=14)
min_intervals_table

               interval_name  min_days
0    interval_2_minus_3_days    -364.0
1    interval_3_minus_3_days       0.0
2    interval_4_minus_3_days       1.0
3    interval_5_minus_3_days       2.0
4    interval_6_minus_3_days       NaN
5    interval_7_minus_3_days       NaN
6    interval_8_minus_3_days       NaN
7    interval_9_minus_3_days       NaN
8   interval_10_minus_3_days       NaN
9   interval_11_minus_3_days       NaN
10  interval_12_minus_3_days       NaN
11  interval_13_minus_3_days       NaN
12  interval_14_minus_3_days       NaN

In [49]:
mtp_merged_data = update_mtp_doses(mtp_merged_data, base_dose=3, target_dose=4)

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\684288360.py:55: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  return result.groupby("RKD.ID", group_keys=False).apply(_per_patient)

In [50]:
mtp_merged_data = update_mtp_doses(mtp_merged_data, base_dose=3, target_dose=5)

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\684288360.py:55: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  return result.groupby("RKD.ID", group_keys=False).apply(_per_patient)

In [51]:
import numpy as np
import pandas as pd

def min_interval_table(df, max_dose=14):
    x = df.copy()

    # Parse dose dates
    for n in range(1, max_dose + 1):
        col = f"mtp_{n}_dose_date"
        if col in x.columns:
            x[col] = pd.to_datetime(x[col], errors="coerce", dayfirst=True)

    # Use earliest dose dates per patient (avoids repeated visit rows)
    per_patient = (
        x.groupby("RKD.ID")[[c for c in x.columns if c.startswith("mtp_") and c.endswith("_dose_date")]]
         .min()
         .reset_index()
    )

    # Build min interval per dose (global min across dataset)
    rows = []
    d1 = "mtp_4_dose_date"

    for n in range(2, max_dose + 1):
        dn = f"mtp_{n}_dose_date"
        if dn not in per_patient.columns:
            continue

        interval_series = (per_patient[dn] - per_patient[d1]).dt.days

        rows.append({
            "interval_name": f"interval_{n}_minus_4_days",
            "min_days": interval_series.min(skipna=True)
        })

    return pd.DataFrame(rows)

# Example:
min_intervals_table = min_interval_table(mtp_merged_data, max_dose=14)
min_intervals_table

               interval_name  min_days
0    interval_2_minus_4_days    -553.0
1    interval_3_minus_4_days    -189.0
2    interval_4_minus_4_days       0.0
3    interval_5_minus_4_days       1.0
4    interval_6_minus_4_days       2.0
5    interval_7_minus_4_days      24.0
6    interval_8_minus_4_days       NaN
7    interval_9_minus_4_days       NaN
8   interval_10_minus_4_days       NaN
9   interval_11_minus_4_days       NaN
10  interval_12_minus_4_days       NaN
11  interval_13_minus_4_days       NaN
12  interval_14_minus_4_days       NaN

In [52]:
mtp_merged_data = update_mtp_doses(mtp_merged_data, base_dose=4, target_dose=5)

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\684288360.py:55: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  return result.groupby("RKD.ID", group_keys=False).apply(_per_patient)

In [53]:
mtp_merged_data = update_mtp_doses(mtp_merged_data, base_dose=4, target_dose=6)

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\684288360.py:55: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  return result.groupby("RKD.ID", group_keys=False).apply(_per_patient)

In [54]:
mtp_merged_data = update_mtp_doses(mtp_merged_data, base_dose=4, target_dose=7)

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\684288360.py:55: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  return result.groupby("RKD.ID", group_keys=False).apply(_per_patient)

In [55]:
import numpy as np
import pandas as pd

def min_interval_table(df, max_dose=14):
    x = df.copy()

    # Parse dose dates
    for n in range(1, max_dose + 1):
        col = f"mtp_{n}_dose_date"
        if col in x.columns:
            x[col] = pd.to_datetime(x[col], errors="coerce", dayfirst=True)

    # Use earliest dose dates per patient (avoids repeated visit rows)
    per_patient = (
        x.groupby("RKD.ID")[[c for c in x.columns if c.startswith("mtp_") and c.endswith("_dose_date")]]
         .min()
         .reset_index()
    )

    # Build min interval per dose (global min across dataset)
    rows = []
    d1 = "mtp_5_dose_date"

    for n in range(2, max_dose + 1):
        dn = f"mtp_{n}_dose_date"
        if dn not in per_patient.columns:
            continue

        interval_series = (per_patient[dn] - per_patient[d1]).dt.days

        rows.append({
            "interval_name": f"interval_{n}_minus_5_days",
            "min_days": interval_series.min(skipna=True)
        })

    return pd.DataFrame(rows)

# Example:
min_intervals_table = min_interval_table(mtp_merged_data, max_dose=14)
min_intervals_table

               interval_name  min_days
0    interval_2_minus_5_days       NaN
1    interval_3_minus_5_days       NaN
2    interval_4_minus_5_days    -220.0
3    interval_5_minus_5_days       0.0
4    interval_6_minus_5_days       NaN
5    interval_7_minus_5_days       NaN
6    interval_8_minus_5_days       NaN
7    interval_9_minus_5_days       NaN
8   interval_10_minus_5_days       NaN
9   interval_11_minus_5_days       NaN
10  interval_12_minus_5_days       NaN
11  interval_13_minus_5_days       NaN
12  interval_14_minus_5_days       NaN

In [56]:
import numpy as np
import pandas as pd

def min_interval_table(df, max_dose=14):
    x = df.copy()

    # Parse dose dates
    for n in range(1, max_dose + 1):
        col = f"mtp_{n}_dose_date"
        if col in x.columns:
            x[col] = pd.to_datetime(x[col], errors="coerce", dayfirst=True)

    # Use earliest dose dates per patient (avoids repeated visit rows)
    per_patient = (
        x.groupby("RKD.ID")[[c for c in x.columns if c.startswith("mtp_") and c.endswith("_dose_date")]]
         .min()
         .reset_index()
    )

    # Build min interval per dose (global min across dataset)
    rows = []
    d1 = "mtp_6_dose_date"

    for n in range(2, max_dose + 1):
        dn = f"mtp_{n}_dose_date"
        if dn not in per_patient.columns:
            continue

        interval_series = (per_patient[dn] - per_patient[d1]).dt.days

        rows.append({
            "interval_name": f"interval_{n}_minus_6_days",
            "min_days": interval_series.min(skipna=True)
        })

    return pd.DataFrame(rows)

# Example:
min_intervals_table = min_interval_table(mtp_merged_data, max_dose=14)
min_intervals_table

               interval_name  min_days
0    interval_2_minus_6_days       NaN
1    interval_3_minus_6_days       NaN
2    interval_4_minus_6_days       NaN
3    interval_5_minus_6_days       NaN
4    interval_6_minus_6_days       NaN
5    interval_7_minus_6_days       NaN
6    interval_8_minus_6_days       NaN
7    interval_9_minus_6_days       NaN
8   interval_10_minus_6_days       NaN
9   interval_11_minus_6_days       NaN
10  interval_12_minus_6_days       NaN
11  interval_13_minus_6_days       NaN
12  interval_14_minus_6_days       NaN

In [57]:
import numpy as np
import pandas as pd

def min_interval_table(df, max_dose=14):
    x = df.copy()

    # Parse dose dates
    for n in range(1, max_dose + 1):
        col = f"mtp_{n}_dose_date"
        if col in x.columns:
            x[col] = pd.to_datetime(x[col], errors="coerce", dayfirst=True)

    # Use earliest dose dates per patient (avoids repeated visit rows)
    per_patient = (
        x.groupby("RKD.ID")[[c for c in x.columns if c.startswith("mtp_") and c.endswith("_dose_date")]]
         .min()
         .reset_index()
    )

    # Build min interval per dose (global min across dataset)
    rows = []
    d1 = "mtp_7_dose_date"

    for n in range(2, max_dose + 1):
        dn = f"mtp_{n}_dose_date"
        if dn not in per_patient.columns:
            continue

        interval_series = (per_patient[dn] - per_patient[d1]).dt.days

        rows.append({
            "interval_name": f"interval_{n}_minus_7_days",
            "min_days": interval_series.min(skipna=True)
        })

    return pd.DataFrame(rows)

# Example:
min_intervals_table = min_interval_table(mtp_merged_data, max_dose=14)
min_intervals_table

               interval_name  min_days
0    interval_2_minus_7_days       NaN
1    interval_3_minus_7_days       NaN
2    interval_4_minus_7_days       NaN
3    interval_5_minus_7_days       NaN
4    interval_6_minus_7_days       NaN
5    interval_7_minus_7_days       NaN
6    interval_8_minus_7_days       NaN
7    interval_9_minus_7_days       NaN
8   interval_10_minus_7_days       NaN
9   interval_11_minus_7_days       NaN
10  interval_12_minus_7_days       NaN
11  interval_13_minus_7_days       NaN
12  interval_14_minus_7_days       NaN

In [58]:
import numpy as np
import pandas as pd

def min_interval_table(df, max_dose=14):
    x = df.copy()

    # Parse dose dates
    for n in range(1, max_dose + 1):
        col = f"mtp_{n}_dose_date"
        if col in x.columns:
            x[col] = pd.to_datetime(x[col], errors="coerce", dayfirst=True)

    # Use earliest dose dates per patient (avoids repeated visit rows)
    per_patient = (
        x.groupby("RKD.ID")[[c for c in x.columns if c.startswith("mtp_") and c.endswith("_dose_date")]]
         .min()
         .reset_index()
    )

    # Build min interval per dose (global min across dataset)
    rows = []
    d1 = "mtp_8_dose_date"

    for n in range(2, max_dose + 1):
        dn = f"mtp_{n}_dose_date"
        if dn not in per_patient.columns:
            continue

        interval_series = (per_patient[dn] - per_patient[d1]).dt.days

        rows.append({
            "interval_name": f"interval_{n}_minus_8_days",
            "min_days": interval_series.min(skipna=True)
        })

    return pd.DataFrame(rows)

# Example:
min_intervals_table = min_interval_table(mtp_merged_data, max_dose=14)
min_intervals_table

               interval_name  min_days
0    interval_2_minus_8_days       NaN
1    interval_3_minus_8_days       NaN
2    interval_4_minus_8_days       NaN
3    interval_5_minus_8_days       NaN
4    interval_6_minus_8_days       NaN
5    interval_7_minus_8_days       NaN
6    interval_8_minus_8_days       NaN
7    interval_9_minus_8_days       NaN
8   interval_10_minus_8_days       NaN
9   interval_11_minus_8_days       NaN
10  interval_12_minus_8_days       NaN
11  interval_13_minus_8_days       NaN
12  interval_14_minus_8_days       NaN

In [61]:
import numpy as np
import pandas as pd

def min_interval_table(df, max_dose=14):
    x = df.copy()

    # Parse dose dates
    for n in range(1, max_dose + 1):
        col = f"mtp_{n}_dose_date"
        if col in x.columns:
            x[col] = pd.to_datetime(x[col], errors="coerce", dayfirst=True)

    # Use earliest dose dates per patient (avoids repeated visit rows)
    per_patient = (
        x.groupby("RKD.ID")[[c for c in x.columns if c.startswith("mtp_") and c.endswith("_dose_date")]]
         .min()
         .reset_index()
    )

    # Build min interval per dose (global min across dataset)
    rows = []
    d1 = "mtp_9_dose_date"

    for n in range(2, max_dose + 1):
        dn = f"mtp_{n}_dose_date"
        if dn not in per_patient.columns:
            continue

        interval_series = (per_patient[dn] - per_patient[d1]).dt.days

        rows.append({
            "interval_name": f"interval_{n}_minus_9_days",
            "min_days": interval_series.min(skipna=True)
        })

    return pd.DataFrame(rows)

# Example:
min_intervals_table = min_interval_table(mtp_merged_data, max_dose=14)
min_intervals_table

               interval_name  min_days
0    interval_2_minus_9_days       NaN
1    interval_3_minus_9_days       NaN
2    interval_4_minus_9_days       NaN
3    interval_5_minus_9_days       NaN
4    interval_6_minus_9_days       NaN
5    interval_7_minus_9_days       NaN
6    interval_8_minus_9_days       NaN
7    interval_9_minus_9_days       NaN
8   interval_10_minus_9_days       NaN
9   interval_11_minus_9_days       NaN
10  interval_12_minus_9_days       NaN
11  interval_13_minus_9_days       NaN
12  interval_14_minus_9_days       NaN

In [59]:
import numpy as np
import pandas as pd

def min_interval_table(df, max_dose=14):
    x = df.copy()

    # Parse dose dates
    for n in range(1, max_dose + 1):
        col = f"mtp_{n}_dose_date"
        if col in x.columns:
            x[col] = pd.to_datetime(x[col], errors="coerce", dayfirst=True)

    # Use earliest dose dates per patient (avoids repeated visit rows)
    per_patient = (
        x.groupby("RKD.ID")[[c for c in x.columns if c.startswith("mtp_") and c.endswith("_dose_date")]]
         .min()
         .reset_index()
    )

    # Build min interval per dose (global min across dataset)
    rows = []
    d1 = "mtp_10_dose_date"

    for n in range(2, max_dose + 1):
        dn = f"mtp_{n}_dose_date"
        if dn not in per_patient.columns:
            continue

        interval_series = (per_patient[dn] - per_patient[d1]).dt.days

        rows.append({
            "interval_name": f"interval_{n}_minus_10_days",
            "min_days": interval_series.min(skipna=True)
        })

    return pd.DataFrame(rows)

# Example:
min_intervals_table = min_interval_table(mtp_merged_data, max_dose=14)
min_intervals_table

                interval_name  min_days
0    interval_2_minus_10_days       NaN
1    interval_3_minus_10_days       NaN
2    interval_4_minus_10_days       NaN
3    interval_5_minus_10_days       NaN
4    interval_6_minus_10_days       NaN
5    interval_7_minus_10_days       NaN
6    interval_8_minus_10_days       NaN
7    interval_9_minus_10_days       NaN
8   interval_10_minus_10_days       0.0
9   interval_11_minus_10_days      28.0
10  interval_12_minus_10_days      29.0
11  interval_13_minus_10_days      31.0
12  interval_14_minus_10_days      32.0

In [60]:
mtp_merged_data = update_mtp_doses(mtp_merged_data, base_dose=10, target_dose=11)

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\684288360.py:55: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  return result.groupby("RKD.ID", group_keys=False).apply(_per_patient)

In [61]:
mtp_merged_data = update_mtp_doses(mtp_merged_data, base_dose=10, target_dose=12)

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\684288360.py:55: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  return result.groupby("RKD.ID", group_keys=False).apply(_per_patient)

In [62]:
import numpy as np
import pandas as pd

def min_interval_table(df, max_dose=14):
    x = df.copy()

    # Parse dose dates
    for n in range(1, max_dose + 1):
        col = f"mtp_{n}_dose_date"
        if col in x.columns:
            x[col] = pd.to_datetime(x[col], errors="coerce", dayfirst=True)

    # Use earliest dose dates per patient (avoids repeated visit rows)
    per_patient = (
        x.groupby("RKD.ID")[[c for c in x.columns if c.startswith("mtp_") and c.endswith("_dose_date")]]
         .min()
         .reset_index()
    )

    # Build min interval per dose (global min across dataset)
    rows = []
    d1 = "mtp_13_dose_date"

    for n in range(2, max_dose + 1):
        dn = f"mtp_{n}_dose_date"
        if dn not in per_patient.columns:
            continue

        interval_series = (per_patient[dn] - per_patient[d1]).dt.days

        rows.append({
            "interval_name": f"interval_{n}_minus_13_days",
            "min_days": interval_series.min(skipna=True)
        })

    return pd.DataFrame(rows)

# Example:
min_intervals_table = min_interval_table(mtp_merged_data, max_dose=14)
min_intervals_table

                interval_name  min_days
0    interval_2_minus_13_days       NaN
1    interval_3_minus_13_days       NaN
2    interval_4_minus_13_days       NaN
3    interval_5_minus_13_days       NaN
4    interval_6_minus_13_days       NaN
5    interval_7_minus_13_days       NaN
6    interval_8_minus_13_days       NaN
7    interval_9_minus_13_days       NaN
8   interval_10_minus_13_days      -2.0
9   interval_11_minus_13_days       NaN
10  interval_12_minus_13_days       NaN
11  interval_13_minus_13_days       0.0
12  interval_14_minus_13_days       1.0

In [63]:
mtp_merged_data = update_mtp_doses(mtp_merged_data, base_dose=13, target_dose=14)

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\684288360.py:55: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  return result.groupby("RKD.ID", group_keys=False).apply(_per_patient)

In [64]:
mtp_merged_data.shape

(8027, 531)

In [65]:
mtp_merged_data  = mtp_merged_data.dropna(axis=1, how='all')
mtp_merged_data.shape

(8027, 517)

In [66]:
mtp_merged_data.columns

Index(['RKD.ID', 'Date_Of_Visit', 'ANCA_Levels', 'anca_status', 'ancaswitch',
       'Repeat.Instrument', 'Repeat.Instance.x', 'Data.Access.Group.x',
       'Patient.ID', 'COVID.19.related.entry.',
       ...
       'mtp_3_dose_date', 'mtp_3_dose_value', 'mtp_4_dose_date',
       'mtp_4_dose_value', 'mtp_5_dose_date', 'mtp_5_dose_value',
       'mtp_10_dose_date', 'mtp_10_dose_value', 'mtp_13_dose_date',
       'mtp_13_dose_value'],
      dtype='object', length=517)

In [67]:
## Rename columns

In [68]:
mtp_merged_data.rename(
    columns={
        "mtp_10_dose_date": "mtp_6_dose_date",
        "mtp_10_dose_value": "mtp_6_dose_value"
    },
    inplace=True
)
mtp_merged_data.rename(
    columns={
        "mtp_13_dose_date": "mtp_7_dose_date",
        "mtp_13_dose_value": "mtp_7_dose_value"
    },
    inplace=True
)

In [69]:
## recheck intervals again

In [70]:
import numpy as np
import pandas as pd

def min_interval_table(df, max_dose=7):
    x = df.copy()

    # Parse dose dates
    for n in range(1, max_dose + 1):
        col = f"mtp_{n}_dose_date"
        if col in x.columns:
            x[col] = pd.to_datetime(x[col], errors="coerce", dayfirst=True)

    # Use earliest dose dates per patient (avoids repeated visit rows)
    per_patient = (
        x.groupby("RKD.ID")[[c for c in x.columns if c.startswith("mtp_") and c.endswith("_dose_date")]]
         .min()
         .reset_index()
    )

    # Build min interval per dose (global min across dataset)
    rows = []
    d1 = "mtp_6_dose_date"

    for n in range(2, max_dose + 1):
        dn = f"mtp_{n}_dose_date"
        if dn not in per_patient.columns:
            continue

        interval_series = (per_patient[dn] - per_patient[d1]).dt.days

        rows.append({
            "interval_name": f"interval_{n}_minus_6_days",
            "min_days": interval_series.min(skipna=True)
        })

    return pd.DataFrame(rows)

# Example:
min_intervals_table = min_interval_table(mtp_merged_data, max_dose=7)
min_intervals_table

             interval_name  min_days
0  interval_2_minus_6_days       NaN
1  interval_3_minus_6_days       NaN
2  interval_4_minus_6_days       NaN
3  interval_5_minus_6_days       NaN
4  interval_6_minus_6_days       0.0
5  interval_7_minus_6_days       3.0

In [71]:
mtp_merged_data = update_mtp_doses(mtp_merged_data, base_dose=6, target_dose=7)

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\684288360.py:55: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  return result.groupby("RKD.ID", group_keys=False).apply(_per_patient)

In [72]:
mtp_merged_data  = mtp_merged_data.dropna(axis=1, how='all')
mtp_merged_data.shape

(8027, 515)

## Calculate interval between days

In [73]:
for n in range(1, 7):
    dose_col = f"mtp_{n}_dose_date"
    new_col  = f"days_visit_minus_mtp{n}"

    if dose_col in mtp_merged_data.columns:
        mtp_merged_data[new_col] = (
            pd.to_datetime(mtp_merged_data["Date_Of_Visit"], errors="coerce", dayfirst=True)
            - pd.to_datetime(mtp_merged_data[dose_col], errors="coerce", dayfirst=True)
        ).dt.days

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\2189848082.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  mtp_merged_data[new_col] = (
C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\2189848082.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  mtp_merged_data[new_col] = (
C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\2189848082.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  mtp_merged_data[new_col] = (
C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\2189848082.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  mtp_merged_data[new_col] = (
C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\2189848082.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  mtp_merged_data[new_col] = (
C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\2189848082.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  mtp_merged_data[new_col] = (

In [74]:
## Replace negative values with 0

In [75]:
for n in range(1, 7):
    day_col = f"days_visit_minus_mtp{n}"

    if day_col in mtp_merged_data.columns:
        mtp_merged_data[day_col] = mtp_merged_data[day_col].clip(lower=0)

In [76]:
for n in range(1, 7):
    dose_col = f"mtp_{n}_dose_value"

    if dose_col in mtp_merged_data.columns:
        mtp_merged_data[dose_col] = (
            pd.to_numeric(mtp_merged_data[dose_col], errors="coerce")
            .clip(lower=250, upper=3000)
        )

In [77]:
## Apply itis

In [78]:
import numpy as np
import pandas as pd

# ---------------------------------------------
# 1. Sigmoid function (UNCHANGED)
# ---------------------------------------------
def sigmoid_curve(x, A, n, d):
    return A / (1 + np.exp(n * (x - d)))

# ---------------------------------------------
# 2. Interpolation functions for A(dose), d(dose), n(dose) (UNCHANGED)
# ---------------------------------------------
A1 = 0.40
A2 = 0.80
dose1 = 250
dose2 = 3000

m_A = (A2 - A1) / (dose2 - dose1)
b_A = A1 - m_A * dose1
def calculate_A(dose):
    return m_A * dose + b_A

d1 = 15
d2 = 21
m_d = (d2 - d1) / (dose2 - dose1)
b_d = d1 - m_d * dose1
def calculate_d(dose):
    return m_d * dose + b_d

# vanish logic (UNCHANGED)
def calculate_n_from_vanish(A, d, vanish_day):
    return np.log(99) / (vanish_day - d)

vanish1 = 21
vanish2 = 30
n1 = calculate_n_from_vanish(A1, d1, vanish1)
n2 = calculate_n_from_vanish(A2, d2, vanish2)

m_n = (n2 - n1) / (dose2 - dose1)
b_n = n1 - m_n * dose1
def calculate_n(dose):
    return m_n * dose + b_n

# ---------------------------------------------
# 3. ITIS computation for ALL doses 1–11 (equations unchanged)
# ---------------------------------------------
def compute_ITIS_generic(row, dose_num):
    dose_col = f"mtp_{dose_num}_dose_value"
    time_col = f"days_visit_minus_mtp{dose_num}"

    dose = row[dose_col]
    time = row[time_col]

    # Skip invalid values
    if pd.isna(dose) or pd.isna(time):
        return np.nan

    A = calculate_A(dose)
    d = calculate_d(dose)
    n = calculate_n(dose)

    return sigmoid_curve(time, A, n, d)

# Create ITIS columns for doses 1–11
for n in range(1, 7):
    dose_col = f"mtp_{n}_dose_value"
    time_col = f"days_visit_minus_mtp{n}"
    out_col  = f"mtp_dose{n}_ITIS"

    if dose_col in mtp_merged_data.columns and time_col in mtp_merged_data.columns:
        mtp_merged_data[out_col] = mtp_merged_data.apply(
            lambda row: compute_ITIS_generic(row, n),
            axis=1
        )

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\1114932393.py:8: RuntimeWarning: overflow encountered in exp
  return A / (1 + np.exp(n * (x - d)))
C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\1114932393.py:71: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  mtp_merged_data[out_col] = mtp_merged_data.apply(
C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\1114932393.py:8: RuntimeWarning: overflow encountered in exp
  return A / (1 + np.exp(n * (x - d)))
C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\1114932393.py:71: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  mtp_merged_data[out_col] = mtp_merged_data.apply(
C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\1114932393.py:8: RuntimeWarning: overflow encountered in exp
  return A / (1 + np.exp(n * (x - d)))
C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\1114932393.py:71: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  mtp_merged_data[out_col] = mtp_merged_data.apply(
C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\1114932393.py:8: RuntimeWarning: overflow encountered in exp
  return A / (1 + np.exp(n * (x - d)))
C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\1114932393.py:71: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  mtp_merged_data[out_col] = mtp_merged_data.apply(
C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\1114932393.py:8: RuntimeWarning: overflow encountered in exp
  return A / (1 + np.exp(n * (x - d)))
C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\1114932393.py:71: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  mtp_merged_data[out_col] = mtp_merged_data.apply(
C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\1114932393.py:8: RuntimeWarning: overflow encountered in exp
  return A / (1 + np.exp(n * (x - d)))
C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\1114932393.py:71: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  mtp_merged_data[out_col] = mtp_merged_data.apply(

In [79]:
itis_cols = [
    "mtp_dose1_ITIS",
    "mtp_dose2_ITIS",
    "mtp_dose3_ITIS",
    "mtp_dose4_ITIS",
    "mtp_dose5_ITIS",
    "mtp_dose6_ITIS",

]

for col in itis_cols:
    if col in mtp_merged_data.columns:
        mtp_merged_data[col] = mtp_merged_data[col].round(2)

In [80]:
## Calculate cumulative ITIS

In [81]:
import numpy as np

# List of ITIS component columns
itis_cols = [
    "mtp_dose1_ITIS",
    "mtp_dose2_ITIS",
    "mtp_dose3_ITIS",
    "mtp_dose4_ITIS",
    "mtp_dose5_ITIS",
    "mtp_dose6_ITIS",

]

def compute_cumulative_ITIS(row):
    values = row[itis_cols].dropna().values

    # If all ITIS_i are missing → cumulative result is NaN
    if len(values) == 0:
        return np.nan

    # Apply formula: 1 - Π(1 - ITIS_i)
    product = np.prod(1 - values)
    return 1 - product

# Create new column
mtp_merged_data["MTP_IV_ITIS"] = mtp_merged_data.apply(compute_cumulative_ITIS, axis=1)

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\374300237.py:26: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  mtp_merged_data["MTP_IV_ITIS"] = mtp_merged_data.apply(compute_cumulative_ITIS, axis=1)

In [82]:
mtp_merged_data['MTP_IV_ITIS'].fillna(0, inplace=True)

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\4013821450.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  mtp_merged_data['MTP_IV_ITIS'].fillna(0, inplace=True)

In [83]:
mask = (
    (
        (mtp_merged_data['IV.therapy'] == 'Methylprednisolone - UATC/D07AA01') &
        (
            mtp_merged_data['MTP_IV_ITIS'].isna() |
            (mtp_merged_data['MTP_IV_ITIS'] == 0)
        )
    )
    |
    (
        mtp_merged_data['treatment_type'].str.contains('Methylprednisolone - UATC/D07AA01', na=False) &
        (mtp_merged_data['MTP_IV_ITIS'] == 0)
    )
)

mtp_merged_data.loc[mask, 'MTP_IV_ITIS'] = 0.60

In [84]:
#mtp_merged_data.to_csv('C:/Users/georgea1/OneDrive - Trinity College Dublin/Desktop/mtp_itis_final_riv.csv',index=True)

## CYC IV

In [85]:
#mtp_with_intervals=pd.read_csv("C:/Users/georgea1/OneDrive - Trinity College Dublin/Angel George/Chap 2. Treatment/Data/ITIS Data/RIV/December 2025/Redcap_clinical_data_harmonized_version0.0.3 (3).csv")
#mtp_with_intervals

In [86]:
mtp_with_intervals=mtp_merged_data.copy()
mtp_with_intervals

,RKD.ID,Date_Of_Visit,ANCA_Levels,anca_status,ancaswitch,Repeat.Instrument,Repeat.Instance.x,Data.Access.Group.x,Patient.ID,COVID.19.related.entry.,...,days_visit_minus_mtp4,days_visit_minus_mtp5,days_visit_minus_mtp6,mtp_dose1_ITIS,mtp_dose2_ITIS,mtp_dose3_ITIS,mtp_dose4_ITIS,mtp_dose5_ITIS,mtp_dose6_ITIS,MTP_IV_ITIS
0,1,2012-08-31,134.0,ANCA Positive,Switch Status Unknown,Encounters,1,TUH - Tallaght,1,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00
1,1,2012-09-07,NaN,ANCA Positive,Pos-Pos Switch,Encounters,36,TUH - Tallaght,1,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00
2,1,2012-09-17,110.0,ANCA Positive,Pos-Pos Switch,Encounters,37,TUH - Tallaght,1,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00
3,1,2012-09-21,92.0,ANCA Positive,Pos-Pos Switch,Encounters,2,TUH - Tallaght,1,No,...,NaN,NaN,NaN,0.51,NaN,NaN,NaN,NaN,NaN,0.51
4,1,2012-09-28,NaN,ANCA Positive,Pos-Pos Switch,Encounters,28,TUH - Tallaght,1,No,...,NaN,NaN,NaN,0.51,NaN,NaN,NaN,NaN,NaN,0.51
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8022,28793,2026-01-21,147.0,ANCA Positive,Switch Status Unknown,Encounters,1,CUH - Cork University Hospital,28793,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00
8023,28796,2025-07-28,NaN,ANCA Status Unknown,Switch Status Unknown,Encounters,2,NaN,28796,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00
8024,28796,2026-01-30,NaN,ANCA Negative,Switch Status Unknown,Encounters,1,NaN,28796,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00
8025,28797,2026-02-02,134.0,ANCA Positive,Switch Status Unknown,Encounters,1,CUH - Cork University Hospital,28797,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00
8026,28797,2026-03-26,134.0,ANCA Positive,Pos-Pos Switch,Encounters,2,CUH - Cork University Hospital,28797,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00

In [87]:
mtp_with_intervals.rename(columns = {'Date.Of.Visit':'Date_Of_Visit'}, inplace = True)

In [88]:
cyc=IV.loc[(IV['IV.therapy']=='Cyclophosphamide Injectable Solution - UATC/ L01AA01')]
cyc

,RKD.ID,IV.therapy,Date.of.IV.therapy,Dose.of.IV.therapy,Unit.of.dose,Unit.of.dose...other
0,1,Cyclophosphamide Injectable Solution - UATC/ L...,2012-09-03,920.0,mg,NaN
1,1,Cyclophosphamide Injectable Solution - UATC/ L...,2012-09-17,920.0,mg,NaN
4,1,Cyclophosphamide Injectable Solution - UATC/ L...,2012-10-01,920.0,mg,NaN
5,1,Cyclophosphamide Injectable Solution - UATC/ L...,2012-10-22,920.0,mg,NaN
6,1,Cyclophosphamide Injectable Solution - UATC/ L...,2012-11-12,920.0,mg,NaN
...,...,...,...,...,...,...
6366,28786,Cyclophosphamide Injectable Solution - UATC/ L...,2025-12-30,800.0,mg,NaN
6373,28793,Cyclophosphamide Injectable Solution - UATC/ L...,2026-01-23,NaN,mg,NaN
6374,28793,Cyclophosphamide Injectable Solution - UATC/ L...,2026-02-09,NaN,mg,NaN
6375,28793,Cyclophosphamide Injectable Solution - UATC/ L...,2026-02-27,NaN,mg,NaN
6383,28800,Cyclophosphamide Injectable Solution - UATC/ L...,2026-02-19,1.2,g,NaN

In [89]:
cyc= cyc.dropna(axis=1, how='all')
cyc

,RKD.ID,IV.therapy,Date.of.IV.therapy,Dose.of.IV.therapy,Unit.of.dose,Unit.of.dose...other
0,1,Cyclophosphamide Injectable Solution - UATC/ L...,2012-09-03,920.0,mg,NaN
1,1,Cyclophosphamide Injectable Solution - UATC/ L...,2012-09-17,920.0,mg,NaN
4,1,Cyclophosphamide Injectable Solution - UATC/ L...,2012-10-01,920.0,mg,NaN
5,1,Cyclophosphamide Injectable Solution - UATC/ L...,2012-10-22,920.0,mg,NaN
6,1,Cyclophosphamide Injectable Solution - UATC/ L...,2012-11-12,920.0,mg,NaN
...,...,...,...,...,...,...
6366,28786,Cyclophosphamide Injectable Solution - UATC/ L...,2025-12-30,800.0,mg,NaN
6373,28793,Cyclophosphamide Injectable Solution - UATC/ L...,2026-01-23,NaN,mg,NaN
6374,28793,Cyclophosphamide Injectable Solution - UATC/ L...,2026-02-09,NaN,mg,NaN
6375,28793,Cyclophosphamide Injectable Solution - UATC/ L...,2026-02-27,NaN,mg,NaN
6383,28800,Cyclophosphamide Injectable Solution - UATC/ L...,2026-02-19,1.2,g,NaN

## Make sure all dose units are 'mg'. if it is gram change to'mg'

In [90]:
cyc['Unit.of.dose'].value_counts(dropna=False)

Unit.of.dose
mg       1495
g           7
Other       6
NaN         1
Name: count, dtype: int64

In [91]:
mask = cyc['Unit.of.dose'] == 'g'
cyc.loc[mask, 'Dose.of.IV.therapy'] *= 1000
cyc.loc[mask, 'Unit.of.dose'] = 'mg'

In [92]:
cyc['Unit.of.dose'].value_counts(dropna=False)

Unit.of.dose
mg       1502
Other       6
NaN         1
Name: count, dtype: int64

In [93]:
cyc['Dose.of.IV.therapy'].isnull().sum()

15

In [94]:
cyc['Dose.of.IV.therapy'].describe()

count    1494.000000
mean      868.223561
std       275.678902
min         0.000000
25%       660.000000
50%       900.000000
75%      1000.000000
max      2000.000000
Name: Dose.of.IV.therapy, dtype: float64

In [95]:
cyc.loc[cyc['Dose.of.IV.therapy'] < 150, 'Dose.of.IV.therapy'] = 150

In [96]:
cyc['Dose.of.IV.therapy'].value_counts(dropna=False)

Dose.of.IV.therapy
1000.0    294
1200.0    239
500.0     131
900.0      84
750.0      68
         ...
850.0       1
1170.0      1
240.0       1
357.0       1
870.0       1
Name: count, Length: 90, dtype: int64

## Fill missing dose with median

In [97]:
cyc['Dose.of.IV.therapy'] = cyc['Dose.of.IV.therapy'].fillna(1000)
cyc['Dose.of.IV.therapy'].isnull().sum()

0

## Create separate columns for doses in the IV dataset

In [98]:
# Step 1 — Sort by ID and dose date
cyc_sorted = cyc.sort_values(["RKD.ID", "Date.of.IV.therapy"]).copy()

# Step 2 — Assign dose number for each patient
cyc_sorted["dose_number"] = cyc_sorted.groupby("RKD.ID").cumcount() + 1

# Step 3 — Rename columns for pivoting
cyc_wide = cyc_sorted.pivot_table(
    index="RKD.ID",
    columns="dose_number",
    values=["Date.of.IV.therapy", "Dose.of.IV.therapy"],
    aggfunc="first"
)

# Step 4 — Flatten multi-index column names
cyc_wide.columns = [
    f"cyc_{col[1]}_dose_{col[0].replace('Date.of.IV.therapy','date').replace('Dose.of.IV.therapy','value')}"
    for col in cyc_wide.columns
]

cyc_wide = cyc_wide.reset_index()
cyc_wide

,RKD.ID,cyc_1_dose_date,cyc_2_dose_date,cyc_3_dose_date,cyc_4_dose_date,cyc_5_dose_date,cyc_6_dose_date,cyc_7_dose_date,cyc_8_dose_date,cyc_9_dose_date,...,cyc_10_dose_value,cyc_11_dose_value,cyc_12_dose_value,cyc_13_dose_value,cyc_14_dose_value,cyc_15_dose_value,cyc_16_dose_value,cyc_17_dose_value,cyc_18_dose_value,cyc_19_dose_value
0,1,2012-09-03,2012-09-17,2012-10-01,2012-10-22,2012-11-12,2012-12-03,2012-12-26,2013-01-13,2013-02-11,...,1100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,2012-06-01,2012-06-18,2012-07-18,NaT,NaT,NaT,NaT,NaT,NaT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,4,2012-08-28,2012-09-10,2012-09-24,2012-10-08,2012-10-29,2012-11-19,2012-12-21,2013-01-11,2013-02-01,...,400.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,5,2012-10-04,2012-10-18,2012-11-01,NaT,NaT,NaT,NaT,NaT,NaT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,7,2012-01-25,2012-02-09,2012-02-22,2012-03-15,2012-04-11,2012-05-03,2012-05-25,2012-06-14,NaT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
322,28772,2025-11-19,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
323,28783,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
324,28786,2025-12-18,2025-12-30,NaT,NaT,NaT,NaT,NaT,NaT,NaT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
325,28793,2026-01-23,2026-02-09,2026-02-27,NaT,NaT,NaT,NaT,NaT,NaT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
326,28800,2026-02-19,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Merge with encounterframe

In [99]:
import numpy as np
import pandas as pd

def merge_visits_with_cyc(visits, cyc_wide):

    df = visits.copy()
    cyc = cyc_wide.copy()

    # Ensure Date_Of_Visit is datetime
    df["Date_Of_Visit"] = pd.to_datetime(df["Date_Of_Visit"], errors="coerce")

    # Merge wide IV data onto visits
    df = df.merge(cyc, on="RKD.ID", how="left")

    # Identify dose blocks
    dose_numbers = sorted(
        int(col.split("_")[1])
        for col in cyc.columns
        if col.startswith("cyc_") and col.endswith("_dose_date")
    )

    for n in dose_numbers:

        dose_date_col = f"cyc_{n}_dose_date"
        value_col     = f"cyc_{n}_dose_value"
     

        # Convert IV dates to datetime
        df[dose_date_col] = pd.to_datetime(df[dose_date_col], errors="coerce")

        # Condition:
        # Keep the dose if the visit occurs AFTER the dose date
        # Blank it otherwise
        mask = (
            df[dose_date_col].notna() &
            (df[dose_date_col] < df["Date_Of_Visit"])
        )

        # Blank outside window
        df.loc[~mask, [dose_date_col, value_col]] = [np.nan, np.nan]

    return df

In [102]:
cyc_merged_data = merge_visits_with_cyc(mtp_with_intervals, cyc_wide)
cyc_merged_data

,RKD.ID,Date_Of_Visit,ANCA_Levels,anca_status,ancaswitch,Repeat.Instrument,Repeat.Instance.x,Data.Access.Group.x,Patient.ID,COVID.19.related.entry.,...,cyc_10_dose_value,cyc_11_dose_value,cyc_12_dose_value,cyc_13_dose_value,cyc_14_dose_value,cyc_15_dose_value,cyc_16_dose_value,cyc_17_dose_value,cyc_18_dose_value,cyc_19_dose_value
0,1,2012-08-31,134.0,ANCA Positive,Switch Status Unknown,Encounters,1,TUH - Tallaght,1,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,2012-09-07,NaN,ANCA Positive,Pos-Pos Switch,Encounters,36,TUH - Tallaght,1,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,2012-09-17,110.0,ANCA Positive,Pos-Pos Switch,Encounters,37,TUH - Tallaght,1,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1,2012-09-21,92.0,ANCA Positive,Pos-Pos Switch,Encounters,2,TUH - Tallaght,1,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1,2012-09-28,NaN,ANCA Positive,Pos-Pos Switch,Encounters,28,TUH - Tallaght,1,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8022,28793,2026-01-21,147.0,ANCA Positive,Switch Status Unknown,Encounters,1,CUH - Cork University Hospital,28793,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8023,28796,2025-07-28,NaN,ANCA Status Unknown,Switch Status Unknown,Encounters,2,NaN,28796,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8024,28796,2026-01-30,NaN,ANCA Negative,Switch Status Unknown,Encounters,1,NaN,28796,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8025,28797,2026-02-02,134.0,ANCA Positive,Switch Status Unknown,Encounters,1,CUH - Cork University Hospital,28797,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8026,28797,2026-03-26,134.0,ANCA Positive,Pos-Pos Switch,Encounters,2,CUH - Cork University Hospital,28797,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Remove completely blank columns

In [103]:
cyc_merged_data  = cyc_merged_data.dropna(axis=1, how='all')
cyc_merged_data

,RKD.ID,Date_Of_Visit,ANCA_Levels,anca_status,ancaswitch,Repeat.Instrument,Repeat.Instance.x,Data.Access.Group.x,Patient.ID,COVID.19.related.entry.,...,cyc_8_dose_value,cyc_9_dose_value,cyc_10_dose_value,cyc_11_dose_value,cyc_12_dose_value,cyc_13_dose_value,cyc_14_dose_value,cyc_15_dose_value,cyc_16_dose_value,cyc_17_dose_value
0,1,2012-08-31,134.0,ANCA Positive,Switch Status Unknown,Encounters,1,TUH - Tallaght,1,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,2012-09-07,NaN,ANCA Positive,Pos-Pos Switch,Encounters,36,TUH - Tallaght,1,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,2012-09-17,110.0,ANCA Positive,Pos-Pos Switch,Encounters,37,TUH - Tallaght,1,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1,2012-09-21,92.0,ANCA Positive,Pos-Pos Switch,Encounters,2,TUH - Tallaght,1,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1,2012-09-28,NaN,ANCA Positive,Pos-Pos Switch,Encounters,28,TUH - Tallaght,1,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8022,28793,2026-01-21,147.0,ANCA Positive,Switch Status Unknown,Encounters,1,CUH - Cork University Hospital,28793,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8023,28796,2025-07-28,NaN,ANCA Status Unknown,Switch Status Unknown,Encounters,2,NaN,28796,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8024,28796,2026-01-30,NaN,ANCA Negative,Switch Status Unknown,Encounters,1,NaN,28796,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8025,28797,2026-02-02,134.0,ANCA Positive,Switch Status Unknown,Encounters,1,CUH - Cork University Hospital,28797,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8026,28797,2026-03-26,134.0,ANCA Positive,Pos-Pos Switch,Encounters,2,CUH - Cork University Hospital,28797,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Reorder columns

In [104]:
def reorder_cyc_columns(df):

    cols = list(df.columns)

    # Identify dose numbers based ONLY on dose_date
    dose_numbers = sorted(
        int(c.split("_")[1])
        for c in cols
        if c.startswith("cyc_") and c.endswith("_dose_date")
    )

    # 1) Core columns (non-cyc)
    core_cols = [c for c in cols if not c.startswith("cyc_")]

    # 2) Dose blocks (ordered)
    dose_blocks = []
    for n in dose_numbers:
        block = [
            f"cyc_{n}_dose_date",
            f"cyc_{n}_dose_value",
            f"cyc_{n}_vanish_days",
            f"cyc_{n}_vanish_date",
        ]
        dose_blocks.extend([c for c in block if c in cols])

    # 3) Everything else starting with cyc_ (course columns, intervals, etc.)
    other_cyc_cols = [
        c for c in cols
        if c.startswith("cyc_") and c not in dose_blocks
    ]

    # Build final ordering
    ordered_cols = core_cols + dose_blocks + other_cyc_cols

    return df[ordered_cols]

In [105]:
cyc_merged_data = reorder_cyc_columns(cyc_merged_data)
cyc_merged_data

,RKD.ID,Date_Of_Visit,ANCA_Levels,anca_status,ancaswitch,Repeat.Instrument,Repeat.Instance.x,Data.Access.Group.x,Patient.ID,COVID.19.related.entry.,...,cyc_13_dose_date,cyc_13_dose_value,cyc_14_dose_date,cyc_14_dose_value,cyc_15_dose_date,cyc_15_dose_value,cyc_16_dose_date,cyc_16_dose_value,cyc_17_dose_date,cyc_17_dose_value
0,1,2012-08-31,134.0,ANCA Positive,Switch Status Unknown,Encounters,1,TUH - Tallaght,1,No,...,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN
1,1,2012-09-07,NaN,ANCA Positive,Pos-Pos Switch,Encounters,36,TUH - Tallaght,1,No,...,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN
2,1,2012-09-17,110.0,ANCA Positive,Pos-Pos Switch,Encounters,37,TUH - Tallaght,1,No,...,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN
3,1,2012-09-21,92.0,ANCA Positive,Pos-Pos Switch,Encounters,2,TUH - Tallaght,1,No,...,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN
4,1,2012-09-28,NaN,ANCA Positive,Pos-Pos Switch,Encounters,28,TUH - Tallaght,1,No,...,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8022,28793,2026-01-21,147.0,ANCA Positive,Switch Status Unknown,Encounters,1,CUH - Cork University Hospital,28793,No,...,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN
8023,28796,2025-07-28,NaN,ANCA Status Unknown,Switch Status Unknown,Encounters,2,NaN,28796,No,...,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN
8024,28796,2026-01-30,NaN,ANCA Negative,Switch Status Unknown,Encounters,1,NaN,28796,No,...,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN
8025,28797,2026-02-02,134.0,ANCA Positive,Switch Status Unknown,Encounters,1,CUH - Cork University Hospital,28797,NaN,...,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN
8026,28797,2026-03-26,134.0,ANCA Positive,Pos-Pos Switch,Encounters,2,CUH - Cork University Hospital,28797,NaN,...,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN

In [106]:
#cyc_merged_data .to_csv('C:/Users/georgea1/OneDrive - Trinity College Dublin/Desktop/cycfinal3.csv',index=True)

In [107]:
## Calculate relative dose based on age_encounter

In [108]:
import pandas as pd
import numpy as np

# Ensure Age_Encounters is numeric
cyc_merged_data["Age_Encounters"] = pd.to_numeric(
    cyc_merged_data["Age_Encounters"], errors="coerce"
)

age = cyc_merged_data["Age_Encounters"]

for n in range(1, 18):
    dose_col = f"cyc_{n}_dose_value"

    if dose_col in cyc_merged_data.columns:
        # Ensure dose column is numeric
        cyc_merged_data[dose_col] = pd.to_numeric(
            cyc_merged_data[dose_col], errors="coerce"
        )

        dose = cyc_merged_data[dose_col]

        cyc_merged_data[dose_col] = np.select(
            [
                age.between(65, 73, inclusive="both") & dose.notna(),
                age.between(74, 82, inclusive="both") & dose.notna(),
                age.gt(82) & dose.notna(),
            ],
            [
                dose * 1.5,
                dose * 2.0,
                dose * 2.5
            ],
            default=dose
        )

In [109]:
## Calculate relative dose based on lymphocyte counts

In [110]:
import pandas as pd
import numpy as np

# Ensure required columns are correct type
cyc_merged_data["lymphocyte_count"] = pd.to_numeric(
    cyc_merged_data["lymphocyte_count"], errors="coerce"
)

cyc_merged_data["Date_Of_Visit"] = pd.to_datetime(
    cyc_merged_data["Date_Of_Visit"], errors="coerce"
)

# ---------------------------------------------
# Dose-specific vanish day interpolation
# dose 150  -> vanish 60
# dose 8000 -> vanish 110
# ---------------------------------------------
dose_min = 150
dose_max = 8000
vanish_min = 60
vanish_max = 110

m_vanish = (vanish_max - vanish_min) / (dose_max - dose_min)
b_vanish = vanish_min - m_vanish * dose_min

def calculate_vanish_day(dose):
    return m_vanish * dose + b_vanish

for n in range(1, 18):
    dose_date_col = f"cyc_{n}_dose_date"
    dose_col = f"cyc_{n}_dose_value"

    if dose_date_col in cyc_merged_data.columns and dose_col in cyc_merged_data.columns:
        cyc_merged_data[dose_date_col] = pd.to_datetime(
            cyc_merged_data[dose_date_col], errors="coerce"
        )
        cyc_merged_data[dose_col] = pd.to_numeric(
            cyc_merged_data[dose_col], errors="coerce"
        )

        interval = (
            cyc_merged_data["Date_Of_Visit"] - cyc_merged_data[dose_date_col]
        ).dt.days

        lymph = cyc_merged_data["lymphocyte_count"]
        dose = cyc_merged_data[dose_col]

        # Calculate dose-specific vanish day
        vanish_day = calculate_vanish_day(dose)

        # Optional: clip to keep within intended range
        vanish_day = vanish_day.clip(lower=vanish_min, upper=vanish_max)

        # Apply only when interval is within that dose's vanish window
        apply_mask = interval.ge(0) & interval.le(vanish_day)

        adjusted = np.select(
            [
                lymph.gt(0.3) & lymph.le(0.7),
                lymph.le(0.3),
            ],
            [
                dose * 1.5,
                dose * 2.0,
            ],
            default=dose
        )

        cyc_merged_data.loc[apply_mask, dose_col] = adjusted[apply_mask]

## Define courses:
### check interval between doses

In [111]:
import numpy as np
import pandas as pd

def min_interval_table(df, max_dose=17):
    x = df.copy()

    # Parse dose dates
    for n in range(1, max_dose + 1):
        col = f"cyc_{n}_dose_date"
        if col in x.columns:
            x[col] = pd.to_datetime(x[col], errors="coerce", dayfirst=True)

    # Use earliest dose dates per patient (avoids repeated visit rows)
    per_patient = (
        x.groupby("RKD.ID")[[c for c in x.columns if c.startswith("cyc_") and c.endswith("_dose_date")]]
         .min()
         .reset_index()
    )

    # Build min interval per dose (global min across dataset)
    rows = []
    d1 = "cyc_1_dose_date"

    for n in range(2, max_dose + 1):
        dn = f"cyc_{n}_dose_date"
        if dn not in per_patient.columns:
            continue

        interval_series = (per_patient[dn] - per_patient[d1]).dt.days

        rows.append({
            "interval_name": f"interval_{n}_minus_1_days",
            "min_days": interval_series.min(skipna=True)
        })

    return pd.DataFrame(rows)

# Example:
min_intervals_table = min_interval_table(cyc_merged_data, max_dose=17)
min_intervals_table

               interval_name  min_days
0    interval_2_minus_1_days       1.0
1    interval_3_minus_1_days      14.0
2    interval_4_minus_1_days      22.0
3    interval_5_minus_1_days      35.0
4    interval_6_minus_1_days      42.0
5    interval_7_minus_1_days      49.0
6    interval_8_minus_1_days     109.0
7    interval_9_minus_1_days     129.0
8   interval_10_minus_1_days     130.0
9   interval_11_minus_1_days     151.0
10  interval_12_minus_1_days     165.0
11  interval_13_minus_1_days     186.0
12  interval_14_minus_1_days     635.0
13  interval_15_minus_1_days     653.0
14  interval_16_minus_1_days    4312.0
15  interval_17_minus_1_days    4334.0

In [112]:
def update_cyc_doses(df, base_dose, target_dose, max_days=180):
    result = df.copy()

    base_date   = f"cyc_{base_dose}_dose_date"
    target_date = f"cyc_{target_dose}_dose_date"
    base_value  = f"cyc_{base_dose}_dose_value"
    target_value= f"cyc_{target_dose}_dose_value"

    # Parse dates
    result[base_date]   = pd.to_datetime(result[base_date], errors="coerce", dayfirst=True)
    result[target_date] = pd.to_datetime(result[target_date], errors="coerce", dayfirst=True)

    # Parse numeric values
    result[base_value]   = pd.to_numeric(result[base_value], errors="coerce")
    result[target_value] = pd.to_numeric(result[target_value], errors="coerce")

    def _per_patient(g):
        g = g.copy()

        d_base   = g[base_date].dropna()
        d_target = g[target_date].dropna()

        # Need both doses
        if d_base.empty or d_target.empty:
            return g

        base_date_val   = d_base.iloc[0]
        target_date_val = d_target.iloc[0]

        # Check interval
        interval_days = (target_date_val - base_date_val).days
        if pd.isna(interval_days) or interval_days > max_days:
            return g

        # Get dose values
        v_base   = g.loc[g[base_date].notna(), base_value].dropna()
        v_target = g.loc[g[target_date].notna(), target_value].dropna()

        base_val   = v_base.iloc[0]   if not v_base.empty   else np.nan
        target_val = v_target.iloc[0] if not v_target.empty else np.nan

        cumulative = base_val + target_val

        # Replace ALL non-missing base-dose rows
        mask = g[base_date].notna()
        g.loc[mask, base_date]  = target_date_val
        g.loc[mask, base_value] = cumulative

        # Blank target-dose after merge
        g[target_date]  = pd.NaT
        g[target_value] = np.nan

        return g

    return result.groupby("RKD.ID", group_keys=False).apply(_per_patient)

In [113]:
cyc_merged_data = update_cyc_doses(cyc_merged_data, base_dose=1, target_dose=2)

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\1179665449.py:55: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  return result.groupby("RKD.ID", group_keys=False).apply(_per_patient)

In [114]:
cyc_merged_data = update_cyc_doses(cyc_merged_data, base_dose=1, target_dose=3)

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\1179665449.py:55: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  return result.groupby("RKD.ID", group_keys=False).apply(_per_patient)

In [115]:
cyc_merged_data = update_cyc_doses(cyc_merged_data, base_dose=1, target_dose=4)

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\1179665449.py:55: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  return result.groupby("RKD.ID", group_keys=False).apply(_per_patient)

In [116]:
cyc_merged_data = update_cyc_doses(cyc_merged_data, base_dose=1, target_dose=5)

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\1179665449.py:55: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  return result.groupby("RKD.ID", group_keys=False).apply(_per_patient)

In [117]:
cyc_merged_data = update_cyc_doses(cyc_merged_data, base_dose=1, target_dose=6)

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\1179665449.py:55: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  return result.groupby("RKD.ID", group_keys=False).apply(_per_patient)

In [118]:
cyc_merged_data = update_cyc_doses(cyc_merged_data, base_dose=1, target_dose=7)

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\1179665449.py:55: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  return result.groupby("RKD.ID", group_keys=False).apply(_per_patient)

In [119]:
cyc_merged_data = update_cyc_doses(cyc_merged_data, base_dose=1, target_dose=8)

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\1179665449.py:55: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  return result.groupby("RKD.ID", group_keys=False).apply(_per_patient)

In [120]:
cyc_merged_data = update_cyc_doses(cyc_merged_data, base_dose=1, target_dose=9)

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\1179665449.py:55: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  return result.groupby("RKD.ID", group_keys=False).apply(_per_patient)

In [121]:
cyc_merged_data = update_cyc_doses(cyc_merged_data, base_dose=1, target_dose=10)

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\1179665449.py:55: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  return result.groupby("RKD.ID", group_keys=False).apply(_per_patient)

In [122]:
cyc_merged_data = update_cyc_doses(cyc_merged_data, base_dose=1, target_dose=11)

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\1179665449.py:55: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  return result.groupby("RKD.ID", group_keys=False).apply(_per_patient)

In [123]:
cyc_merged_data = update_cyc_doses(cyc_merged_data, base_dose=1, target_dose=12)

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\1179665449.py:55: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  return result.groupby("RKD.ID", group_keys=False).apply(_per_patient)

In [124]:
cyc_merged_data = update_cyc_doses(cyc_merged_data, base_dose=1, target_dose=13)

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\1179665449.py:55: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  return result.groupby("RKD.ID", group_keys=False).apply(_per_patient)

In [125]:
cyc_merged_data

,RKD.ID,Date_Of_Visit,ANCA_Levels,anca_status,ancaswitch,Repeat.Instrument,Repeat.Instance.x,Data.Access.Group.x,Patient.ID,COVID.19.related.entry.,...,cyc_13_dose_date,cyc_13_dose_value,cyc_14_dose_date,cyc_14_dose_value,cyc_15_dose_date,cyc_15_dose_value,cyc_16_dose_date,cyc_16_dose_value,cyc_17_dose_date,cyc_17_dose_value
0,1,2012-08-31,134.0,ANCA Positive,Switch Status Unknown,Encounters,1,TUH - Tallaght,1,No,...,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN
1,1,2012-09-07,NaN,ANCA Positive,Pos-Pos Switch,Encounters,36,TUH - Tallaght,1,No,...,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN
2,1,2012-09-17,110.0,ANCA Positive,Pos-Pos Switch,Encounters,37,TUH - Tallaght,1,No,...,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN
3,1,2012-09-21,92.0,ANCA Positive,Pos-Pos Switch,Encounters,2,TUH - Tallaght,1,No,...,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN
4,1,2012-09-28,NaN,ANCA Positive,Pos-Pos Switch,Encounters,28,TUH - Tallaght,1,No,...,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8022,28793,2026-01-21,147.0,ANCA Positive,Switch Status Unknown,Encounters,1,CUH - Cork University Hospital,28793,No,...,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN
8023,28796,2025-07-28,NaN,ANCA Status Unknown,Switch Status Unknown,Encounters,2,NaN,28796,No,...,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN
8024,28796,2026-01-30,NaN,ANCA Negative,Switch Status Unknown,Encounters,1,NaN,28796,No,...,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN
8025,28797,2026-02-02,134.0,ANCA Positive,Switch Status Unknown,Encounters,1,CUH - Cork University Hospital,28797,NaN,...,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN
8026,28797,2026-03-26,134.0,ANCA Positive,Pos-Pos Switch,Encounters,2,CUH - Cork University Hospital,28797,NaN,...,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN

In [129]:
#cyc_merged_data .to_csv('C:/Users/georgea1/OneDrive - Trinity College Dublin/Desktop/cycfinal4.csv',index=True)

In [126]:
df = cyc_merged_data.copy()

df["cyc_1_dose_date"] = pd.to_datetime(df["cyc_1_dose_date"], errors="coerce", dayfirst=True)
df["cyc_13_dose_date"] = pd.to_datetime(df["cyc_13_dose_date"], errors="coerce", dayfirst=True)

df["interval_13_minus_1_days"] = (
    df["cyc_13_dose_date"] - df["cyc_1_dose_date"]
).dt.days



df["interval_13_minus_1_days"].min()

511.0

## Remove completely blank columns

In [127]:
cyc_merged_data  = cyc_merged_data.dropna(axis=1, how='all')
cyc_merged_data.shape

(8027, 562)

## Second Dose

In [128]:
import numpy as np
import pandas as pd

def min_interval_table(df, max_dose=17):
    x = df.copy()

    # Parse dose dates
    for n in range(1, max_dose + 1):
        col = f"cyc_{n}_dose_date"
        if col in x.columns:
            x[col] = pd.to_datetime(x[col], errors="coerce", dayfirst=True)

    # Use earliest dose dates per patient (avoids repeated visit rows)
    per_patient = (
        x.groupby("RKD.ID")[[c for c in x.columns if c.startswith("cyc_") and c.endswith("_dose_date")]]
         .min()
         .reset_index()
    )

    # Build min interval per dose (global min across dataset)
    rows = []
    d1 = "cyc_2_dose_date"

    for n in range(2, max_dose + 1):
        dn = f"cyc_{n}_dose_date"
        if dn not in per_patient.columns:
            continue

        interval_series = (per_patient[dn] - per_patient[d1]).dt.days

        rows.append({
            "interval_name": f"interval_{n}_minus_2_days",
            "min_days": interval_series.min(skipna=True)
        })

    return pd.DataFrame(rows)

# Example:
min_intervals_table = min_interval_table(cyc_merged_data, max_dose=17)
min_intervals_table

               interval_name  min_days
0    interval_2_minus_2_days       0.0
1    interval_3_minus_2_days      14.0
2    interval_4_minus_2_days      47.0
3    interval_5_minus_2_days       NaN
4    interval_6_minus_2_days       NaN
5    interval_7_minus_2_days       NaN
6    interval_8_minus_2_days       NaN
7    interval_9_minus_2_days       NaN
8   interval_10_minus_2_days       NaN
9   interval_11_minus_2_days       NaN
10  interval_12_minus_2_days       NaN
11  interval_13_minus_2_days       NaN
12  interval_14_minus_2_days       NaN
13  interval_15_minus_2_days       NaN
14  interval_16_minus_2_days       NaN
15  interval_17_minus_2_days       NaN

## Dose 3- Dose 2

In [129]:
cyc_merged_data = update_cyc_doses(cyc_merged_data, base_dose=2, target_dose=3)

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\1179665449.py:55: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  return result.groupby("RKD.ID", group_keys=False).apply(_per_patient)

## Dose 4-Dose2

In [130]:
cyc_merged_data = update_cyc_doses(cyc_merged_data, base_dose=2, target_dose=4)

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\1179665449.py:55: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  return result.groupby("RKD.ID", group_keys=False).apply(_per_patient)

## Third Dose

In [131]:
import numpy as np
import pandas as pd

def min_interval_table(df, max_dose=17):
    x = df.copy()

    # Parse dose dates
    for n in range(1, max_dose + 1):
        col = f"cyc_{n}_dose_date"
        if col in x.columns:
            x[col] = pd.to_datetime(x[col], errors="coerce", dayfirst=True)

    # Use earliest dose dates per patient (avoids repeated visit rows)
    per_patient = (
        x.groupby("RKD.ID")[[c for c in x.columns if c.startswith("cyc_") and c.endswith("_dose_date")]]
         .min()
         .reset_index()
    )

    # Build min interval per dose (global min across dataset)
    rows = []
    d1 = "cyc_3_dose_date"

    for n in range(2, max_dose + 1):
        dn = f"cyc_{n}_dose_date"
        if dn not in per_patient.columns:
            continue

        interval_series = (per_patient[dn] - per_patient[d1]).dt.days

        rows.append({
            "interval_name": f"interval_{n}_minus_3_days",
            "min_days": interval_series.min(skipna=True)
        })

    return pd.DataFrame(rows)

# Example:
min_intervals_table = min_interval_table(cyc_merged_data, max_dose=17)
min_intervals_table

               interval_name  min_days
0    interval_2_minus_3_days       NaN
1    interval_3_minus_3_days       0.0
2    interval_4_minus_3_days      33.0
3    interval_5_minus_3_days       NaN
4    interval_6_minus_3_days       NaN
5    interval_7_minus_3_days       NaN
6    interval_8_minus_3_days       NaN
7    interval_9_minus_3_days       NaN
8   interval_10_minus_3_days       NaN
9   interval_11_minus_3_days       NaN
10  interval_12_minus_3_days       NaN
11  interval_13_minus_3_days       NaN
12  interval_14_minus_3_days       NaN
13  interval_15_minus_3_days       NaN
14  interval_16_minus_3_days       NaN
15  interval_17_minus_3_days       NaN

## Dose 4-Dose 3

In [132]:
cyc_merged_data = update_cyc_doses(cyc_merged_data, base_dose=3, target_dose=4)

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\1179665449.py:55: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  return result.groupby("RKD.ID", group_keys=False).apply(_per_patient)

## Fourth Dose

In [133]:
import numpy as np
import pandas as pd

def min_interval_table(df, max_dose=17):
    x = df.copy()

    # Parse dose dates
    for n in range(1, max_dose + 1):
        col = f"cyc_{n}_dose_date"
        if col in x.columns:
            x[col] = pd.to_datetime(x[col], errors="coerce", dayfirst=True)

    # Use earliest dose dates per patient (avoids repeated visit rows)
    per_patient = (
        x.groupby("RKD.ID")[[c for c in x.columns if c.startswith("cyc_") and c.endswith("_dose_date")]]
         .min()
         .reset_index()
    )

    # Build min interval per dose (global min across dataset)
    rows = []
    d1 = "cyc_4_dose_date"

    for n in range(2, max_dose + 1):
        dn = f"cyc_{n}_dose_date"
        if dn not in per_patient.columns:
            continue

        interval_series = (per_patient[dn] - per_patient[d1]).dt.days

        rows.append({
            "interval_name": f"interval_{n}_minus_4_days",
            "min_days": interval_series.min(skipna=True)
        })

    return pd.DataFrame(rows)

# Example:
min_intervals_table = min_interval_table(cyc_merged_data, max_dose=17)
min_intervals_table

               interval_name  min_days
0    interval_2_minus_4_days       NaN
1    interval_3_minus_4_days       NaN
2    interval_4_minus_4_days       0.0
3    interval_5_minus_4_days      14.0
4    interval_6_minus_4_days      35.0
5    interval_7_minus_4_days      56.0
6    interval_8_minus_4_days      77.0
7    interval_9_minus_4_days       NaN
8   interval_10_minus_4_days       NaN
9   interval_11_minus_4_days       NaN
10  interval_12_minus_4_days       NaN
11  interval_13_minus_4_days       NaN
12  interval_14_minus_4_days       NaN
13  interval_15_minus_4_days       NaN
14  interval_16_minus_4_days       NaN
15  interval_17_minus_4_days       NaN

## Dose 5-dose4

In [134]:
cyc_merged_data = update_cyc_doses(cyc_merged_data, base_dose=4, target_dose=5)

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\1179665449.py:55: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  return result.groupby("RKD.ID", group_keys=False).apply(_per_patient)

## Dose 6- Dose 4

In [135]:
cyc_merged_data = update_cyc_doses(cyc_merged_data, base_dose=4, target_dose=6)

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\1179665449.py:55: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  return result.groupby("RKD.ID", group_keys=False).apply(_per_patient)

## Dose 7- Dose 4

In [136]:
cyc_merged_data = update_cyc_doses(cyc_merged_data, base_dose=4, target_dose=7)

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\1179665449.py:55: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  return result.groupby("RKD.ID", group_keys=False).apply(_per_patient)

## Dose 8- Dose 4

In [137]:
cyc_merged_data = update_cyc_doses(cyc_merged_data, base_dose=4, target_dose=8)

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\1179665449.py:55: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  return result.groupby("RKD.ID", group_keys=False).apply(_per_patient)

## Fifth Dose

In [138]:
import numpy as np
import pandas as pd

def min_interval_table(df, max_dose=17):
    x = df.copy()

    # Parse dose dates
    for n in range(1, max_dose + 1):
        col = f"cyc_{n}_dose_date"
        if col in x.columns:
            x[col] = pd.to_datetime(x[col], errors="coerce", dayfirst=True)

    # Use earliest dose dates per patient (avoids repeated visit rows)
    per_patient = (
        x.groupby("RKD.ID")[[c for c in x.columns if c.startswith("cyc_") and c.endswith("_dose_date")]]
         .min()
         .reset_index()
    )

    # Build min interval per dose (global min across dataset)
    rows = []
    d1 = "cyc_5_dose_date"

    for n in range(2, max_dose + 1):
        dn = f"cyc_{n}_dose_date"
        if dn not in per_patient.columns:
            continue

        interval_series = (per_patient[dn] - per_patient[d1]).dt.days

        rows.append({
            "interval_name": f"interval_{n}_minus_5_days",
            "min_days": interval_series.min(skipna=True)
        })

    return pd.DataFrame(rows)

# Example:
min_intervals_table = min_interval_table(cyc_merged_data, max_dose=17)
min_intervals_table

               interval_name  min_days
0    interval_2_minus_5_days       NaN
1    interval_3_minus_5_days       NaN
2    interval_4_minus_5_days       NaN
3    interval_5_minus_5_days       NaN
4    interval_6_minus_5_days       NaN
5    interval_7_minus_5_days       NaN
6    interval_8_minus_5_days       NaN
7    interval_9_minus_5_days       NaN
8   interval_10_minus_5_days       NaN
9   interval_11_minus_5_days       NaN
10  interval_12_minus_5_days       NaN
11  interval_13_minus_5_days       NaN
12  interval_14_minus_5_days       NaN
13  interval_15_minus_5_days       NaN
14  interval_16_minus_5_days       NaN
15  interval_17_minus_5_days       NaN

## Sixth dose

In [139]:
import numpy as np
import pandas as pd

def min_interval_table(df, max_dose=17):
    x = df.copy()

    # Parse dose dates
    for n in range(1, max_dose + 1):
        col = f"cyc_{n}_dose_date"
        if col in x.columns:
            x[col] = pd.to_datetime(x[col], errors="coerce", dayfirst=True)

    # Use earliest dose dates per patient (avoids repeated visit rows)
    per_patient = (
        x.groupby("RKD.ID")[[c for c in x.columns if c.startswith("cyc_") and c.endswith("_dose_date")]]
         .min()
         .reset_index()
    )

    # Build min interval per dose (global min across dataset)
    rows = []
    d1 = "cyc_6_dose_date"

    for n in range(2, max_dose + 1):
        dn = f"cyc_{n}_dose_date"
        if dn not in per_patient.columns:
            continue

        interval_series = (per_patient[dn] - per_patient[d1]).dt.days

        rows.append({
            "interval_name": f"interval_{n}_minus_6_days",
            "min_days": interval_series.min(skipna=True)
        })

    return pd.DataFrame(rows)

# Example:
min_intervals_table = min_interval_table(cyc_merged_data, max_dose=17)
min_intervals_table

               interval_name  min_days
0    interval_2_minus_6_days       NaN
1    interval_3_minus_6_days       NaN
2    interval_4_minus_6_days       NaN
3    interval_5_minus_6_days       NaN
4    interval_6_minus_6_days       0.0
5    interval_7_minus_6_days       9.0
6    interval_8_minus_6_days      20.0
7    interval_9_minus_6_days      27.0
8   interval_10_minus_6_days      33.0
9   interval_11_minus_6_days      52.0
10  interval_12_minus_6_days      55.0
11  interval_13_minus_6_days      72.0
12  interval_14_minus_6_days      76.0
13  interval_15_minus_6_days      94.0
14  interval_16_minus_6_days       NaN
15  interval_17_minus_6_days       NaN

## Dose 7- Dose 6

In [140]:
cyc_merged_data = update_cyc_doses(cyc_merged_data, base_dose=6, target_dose=7)

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\1179665449.py:55: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  return result.groupby("RKD.ID", group_keys=False).apply(_per_patient)

## Dose 8- Dose 6

In [141]:
cyc_merged_data = update_cyc_doses(cyc_merged_data, base_dose=6, target_dose=8)

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\1179665449.py:55: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  return result.groupby("RKD.ID", group_keys=False).apply(_per_patient)

## Dose 9 - Dose 6

In [142]:
cyc_merged_data = update_cyc_doses(cyc_merged_data, base_dose=6, target_dose=9)

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\1179665449.py:55: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  return result.groupby("RKD.ID", group_keys=False).apply(_per_patient)

## Dose 10 - Dose 6

In [143]:
cyc_merged_data = update_cyc_doses(cyc_merged_data, base_dose=6, target_dose=10)

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\1179665449.py:55: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  return result.groupby("RKD.ID", group_keys=False).apply(_per_patient)

## Dose 11- Dose 6

In [144]:
cyc_merged_data = update_cyc_doses(cyc_merged_data, base_dose=6, target_dose=11)

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\1179665449.py:55: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  return result.groupby("RKD.ID", group_keys=False).apply(_per_patient)

## Dose 12- Dose 6

In [145]:
cyc_merged_data = update_cyc_doses(cyc_merged_data, base_dose=6, target_dose=12)

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\1179665449.py:55: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  return result.groupby("RKD.ID", group_keys=False).apply(_per_patient)

In [146]:
## dose 13-dose 6

In [147]:
cyc_merged_data = update_cyc_doses(cyc_merged_data, base_dose=6, target_dose=13)

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\1179665449.py:55: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  return result.groupby("RKD.ID", group_keys=False).apply(_per_patient)

In [148]:
##Dose 14- Dose 6

In [149]:
cyc_merged_data = update_cyc_doses(cyc_merged_data, base_dose=6, target_dose=14)

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\1179665449.py:55: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  return result.groupby("RKD.ID", group_keys=False).apply(_per_patient)

In [150]:
## Dose 15- Dose 6

In [151]:
cyc_merged_data = update_cyc_doses(cyc_merged_data, base_dose=6, target_dose=15)
cyc_merged_data

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\1179665449.py:55: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  return result.groupby("RKD.ID", group_keys=False).apply(_per_patient)

,RKD.ID,Date_Of_Visit,ANCA_Levels,anca_status,ancaswitch,Repeat.Instrument,Repeat.Instance.x,Data.Access.Group.x,Patient.ID,COVID.19.related.entry.,...,cyc_13_dose_date,cyc_13_dose_value,cyc_14_dose_date,cyc_14_dose_value,cyc_15_dose_date,cyc_15_dose_value,cyc_16_dose_date,cyc_16_dose_value,cyc_17_dose_date,cyc_17_dose_value
0,1,2012-08-31,134.0,ANCA Positive,Switch Status Unknown,Encounters,1,TUH - Tallaght,1,No,...,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN
1,1,2012-09-07,NaN,ANCA Positive,Pos-Pos Switch,Encounters,36,TUH - Tallaght,1,No,...,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN
2,1,2012-09-17,110.0,ANCA Positive,Pos-Pos Switch,Encounters,37,TUH - Tallaght,1,No,...,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN
3,1,2012-09-21,92.0,ANCA Positive,Pos-Pos Switch,Encounters,2,TUH - Tallaght,1,No,...,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN
4,1,2012-09-28,NaN,ANCA Positive,Pos-Pos Switch,Encounters,28,TUH - Tallaght,1,No,...,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8022,28793,2026-01-21,147.0,ANCA Positive,Switch Status Unknown,Encounters,1,CUH - Cork University Hospital,28793,No,...,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN
8023,28796,2025-07-28,NaN,ANCA Status Unknown,Switch Status Unknown,Encounters,2,NaN,28796,No,...,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN
8024,28796,2026-01-30,NaN,ANCA Negative,Switch Status Unknown,Encounters,1,NaN,28796,No,...,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN
8025,28797,2026-02-02,134.0,ANCA Positive,Switch Status Unknown,Encounters,1,CUH - Cork University Hospital,28797,NaN,...,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN
8026,28797,2026-03-26,134.0,ANCA Positive,Pos-Pos Switch,Encounters,2,CUH - Cork University Hospital,28797,NaN,...,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN

In [152]:
## Remove blank columns

In [153]:
cyc_merged_data  = cyc_merged_data.dropna(axis=1, how='all')
cyc_merged_data.shape

(8027, 558)

In [154]:
import numpy as np
import pandas as pd

def min_interval_table(df, max_dose=17):
    x = df.copy()

    # Parse dose dates
    for n in range(1, max_dose + 1):
        col = f"cyc_{n}_dose_date"
        if col in x.columns:
            x[col] = pd.to_datetime(x[col], errors="coerce", dayfirst=True)

    # Use earliest dose dates per patient (avoids repeated visit rows)
    per_patient = (
        x.groupby("RKD.ID")[[c for c in x.columns if c.startswith("cyc_") and c.endswith("_dose_date")]]
         .min()
         .reset_index()
    )

    # Build min interval per dose (global min across dataset)
    rows = []
    d1 = "cyc_7_dose_date"

    for n in range(2, max_dose + 1):
        dn = f"cyc_{n}_dose_date"
        if dn not in per_patient.columns:
            continue

        interval_series = (per_patient[dn] - per_patient[d1]).dt.days

        rows.append({
            "interval_name": f"interval_{n}_minus_7_days",
            "min_days": interval_series.min(skipna=True)
        })

    return pd.DataFrame(rows)

# Example:
min_intervals_table = min_interval_table(cyc_merged_data, max_dose=17)
min_intervals_table

               interval_name  min_days
0    interval_2_minus_7_days       NaN
1    interval_3_minus_7_days       NaN
2    interval_4_minus_7_days       NaN
3    interval_6_minus_7_days       NaN
4    interval_7_minus_7_days       0.0
5    interval_8_minus_7_days      27.0
6   interval_10_minus_7_days       NaN
7   interval_11_minus_7_days       NaN
8   interval_12_minus_7_days       NaN
9   interval_13_minus_7_days       NaN
10  interval_14_minus_7_days       NaN
11  interval_15_minus_7_days       NaN
12  interval_16_minus_7_days       NaN
13  interval_17_minus_7_days       NaN

In [155]:
## dose 8- dose 7

In [156]:
cyc_merged_data = update_cyc_doses(cyc_merged_data, base_dose=7, target_dose=8)

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\1179665449.py:55: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  return result.groupby("RKD.ID", group_keys=False).apply(_per_patient)

In [157]:
#cyc_merged_data = update_cyc_doses(cyc_merged_data, base_dose=7, target_dose=9)

In [158]:
#cyc_merged_data = update_cyc_doses(cyc_merged_data, base_dose=7, target_dose=10)

In [159]:
#cyc_merged_data = update_cyc_doses(cyc_merged_data, base_dose=7, target_dose=11)

In [160]:
import numpy as np
import pandas as pd

def min_interval_table(df, max_dose=17):
    x = df.copy()

    # Parse dose dates
    for n in range(1, max_dose + 1):
        col = f"cyc_{n}_dose_date"
        if col in x.columns:
            x[col] = pd.to_datetime(x[col], errors="coerce", dayfirst=True)

    # Use earliest dose dates per patient (avoids repeated visit rows)
    per_patient = (
        x.groupby("RKD.ID")[[c for c in x.columns if c.startswith("cyc_") and c.endswith("_dose_date")]]
         .min()
         .reset_index()
    )

    # Build min interval per dose (global min across dataset)
    rows = []
    d1 = "cyc_8_dose_date"

    for n in range(2, max_dose + 1):
        dn = f"cyc_{n}_dose_date"
        if dn not in per_patient.columns:
            continue

        interval_series = (per_patient[dn] - per_patient[d1]).dt.days

        rows.append({
            "interval_name": f"interval_{n}_minus_8_days",
            "min_days": interval_series.min(skipna=True)
        })

    return pd.DataFrame(rows)

# Example:
min_intervals_table = min_interval_table(cyc_merged_data, max_dose=17)
min_intervals_table

               interval_name  min_days
0    interval_2_minus_8_days       NaN
1    interval_3_minus_8_days       NaN
2    interval_4_minus_8_days       NaN
3    interval_6_minus_8_days   -1155.0
4    interval_7_minus_8_days       NaN
5    interval_8_minus_8_days       0.0
6   interval_10_minus_8_days       NaN
7   interval_11_minus_8_days       NaN
8   interval_12_minus_8_days       NaN
9   interval_13_minus_8_days       NaN
10  interval_14_minus_8_days       NaN
11  interval_15_minus_8_days       NaN
12  interval_16_minus_8_days       NaN
13  interval_17_minus_8_days       NaN

In [161]:
import numpy as np
import pandas as pd

def min_interval_table(df, max_dose=17):
    x = df.copy()

    # Parse dose dates
    for n in range(1, max_dose + 1):
        col = f"cyc_{n}_dose_date"
        if col in x.columns:
            x[col] = pd.to_datetime(x[col], errors="coerce", dayfirst=True)

    # Use earliest dose dates per patient (avoids repeated visit rows)
    per_patient = (
        x.groupby("RKD.ID")[[c for c in x.columns if c.startswith("cyc_") and c.endswith("_dose_date")]]
         .min()
         .reset_index()
    )

    # Build min interval per dose (global min across dataset)
    rows = []
    d1 = "cyc_11_dose_date"

    for n in range(2, max_dose + 1):
        dn = f"cyc_{n}_dose_date"
        if dn not in per_patient.columns:
            continue

        interval_series = (per_patient[dn] - per_patient[d1]).dt.days

        rows.append({
            "interval_name": f"interval_{n}_minus_11_days",
            "min_days": interval_series.min(skipna=True)
        })

    return pd.DataFrame(rows)

# Example:
min_intervals_table = min_interval_table(cyc_merged_data, max_dose=17)
min_intervals_table

                interval_name  min_days
0    interval_2_minus_11_days       NaN
1    interval_3_minus_11_days       NaN
2    interval_4_minus_11_days       NaN
3    interval_6_minus_11_days       NaN
4    interval_7_minus_11_days       NaN
5    interval_8_minus_11_days       NaN
6   interval_10_minus_11_days       NaN
7   interval_11_minus_11_days       0.0
8   interval_12_minus_11_days      13.0
9   interval_13_minus_11_days       NaN
10  interval_14_minus_11_days       NaN
11  interval_15_minus_11_days       NaN
12  interval_16_minus_11_days       NaN
13  interval_17_minus_11_days       NaN

In [162]:
## Dose 12- Dose 11

In [163]:
cyc_merged_data = update_cyc_doses(cyc_merged_data, base_dose=11, target_dose=12)

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\1179665449.py:55: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  return result.groupby("RKD.ID", group_keys=False).apply(_per_patient)

In [164]:
import numpy as np
import pandas as pd

def min_interval_table(df, max_dose=17):
    x = df.copy()

    # Parse dose dates
    for n in range(1, max_dose + 1):
        col = f"cyc_{n}_dose_date"
        if col in x.columns:
            x[col] = pd.to_datetime(x[col], errors="coerce", dayfirst=True)

    # Use earliest dose dates per patient (avoids repeated visit rows)
    per_patient = (
        x.groupby("RKD.ID")[[c for c in x.columns if c.startswith("cyc_") and c.endswith("_dose_date")]]
         .min()
         .reset_index()
    )

    # Build min interval per dose (global min across dataset)
    rows = []
    d1 = "cyc_12_dose_date"

    for n in range(2, max_dose + 1):
        dn = f"cyc_{n}_dose_date"
        if dn not in per_patient.columns:
            continue

        interval_series = (per_patient[dn] - per_patient[d1]).dt.days

        rows.append({
            "interval_name": f"interval_{n}_minus_12_days",
            "min_days": interval_series.min(skipna=True)
        })

    return pd.DataFrame(rows)

# Example:
min_intervals_table = min_interval_table(cyc_merged_data, max_dose=17)
min_intervals_table

                interval_name  min_days
0    interval_2_minus_12_days       NaN
1    interval_3_minus_12_days       NaN
2    interval_4_minus_12_days       NaN
3    interval_6_minus_12_days       NaN
4    interval_7_minus_12_days       NaN
5    interval_8_minus_12_days       NaN
6   interval_10_minus_12_days       NaN
7   interval_11_minus_12_days       NaN
8   interval_12_minus_12_days       0.0
9   interval_13_minus_12_days      14.0
10  interval_14_minus_12_days      28.0
11  interval_15_minus_12_days      46.0
12  interval_16_minus_12_days      62.0
13  interval_17_minus_12_days      84.0

In [165]:
## Dose 13- Dose 12

In [166]:
cyc_merged_data = update_cyc_doses(cyc_merged_data, base_dose=12, target_dose=13)

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\1179665449.py:55: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  return result.groupby("RKD.ID", group_keys=False).apply(_per_patient)

In [167]:
cyc_merged_data = update_cyc_doses(cyc_merged_data, base_dose=12, target_dose=14)

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\1179665449.py:55: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  return result.groupby("RKD.ID", group_keys=False).apply(_per_patient)

In [168]:
cyc_merged_data = update_cyc_doses(cyc_merged_data, base_dose=12, target_dose=15)

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\1179665449.py:55: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  return result.groupby("RKD.ID", group_keys=False).apply(_per_patient)

In [169]:
cyc_merged_data = update_cyc_doses(cyc_merged_data, base_dose=12, target_dose=16)

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\1179665449.py:55: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  return result.groupby("RKD.ID", group_keys=False).apply(_per_patient)

In [170]:
cyc_merged_data = update_cyc_doses(cyc_merged_data, base_dose=12, target_dose=17)

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\1179665449.py:55: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  return result.groupby("RKD.ID", group_keys=False).apply(_per_patient)

In [171]:
cyc_merged_data  = cyc_merged_data.dropna(axis=1, how='all')
cyc_merged_data.shape

(8027, 548)

## Rename columns

In [172]:
cyc_merged_data.rename(
    columns={
        "cyc_6_dose_date": "cyc_5_dose_date",
        "cyc_6_dose_value": "cyc_5_dose_value"
    },
    inplace=True
)
cyc_merged_data.rename(
    columns={
        "cyc_7_dose_date": "cyc_6_dose_date",
        "cyc_7_dose_value": "cyc_6_dose_value"
    },
    inplace=True
)
cyc_merged_data.rename(
    columns={
        "cyc_8_dose_date": "cyc_7_dose_date",
        "cyc_8_dose_value": "cyc_7_dose_value"
    },
    inplace=True
)

In [173]:
cyc_merged_data.rename(
    columns={
        "cyc_9_dose_date": "cyc_8_dose_date",
        "cyc_9_dose_value": "cyc_8_dose_value"
    },
    inplace=True
)
cyc_merged_data.rename(
    columns={
        "cyc_10_dose_date": "cyc_9_dose_date",
        "cyc_10_dose_value": "cyc_9_dose_value"
    },
    inplace=True
)
cyc_merged_data.rename(
    columns={
        "cyc_11_dose_date": "cyc_10_dose_date",
        "cyc_11_dose_value": "cyc_10_dose_value"
    },
    inplace=True
)
cyc_merged_data.rename(
    columns={
        "cyc_12_dose_date": "cyc_11_dose_date",
        "cyc_12_dose_value": "cyc_11_dose_value"
    },
    inplace=True
)

## Calculate interval between date of iv and date of visit

In [174]:
for n in range(1, 12):
    dose_col = f"cyc_{n}_dose_date"
    new_col  = f"days_visit_minus_cyc{n}"

    if dose_col in cyc_merged_data.columns:
        cyc_merged_data[new_col] = (
            pd.to_datetime(cyc_merged_data["Date_Of_Visit"], errors="coerce", dayfirst=True)
            - pd.to_datetime(cyc_merged_data[dose_col], errors="coerce", dayfirst=True)
        ).dt.days

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\583457403.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  cyc_merged_data[new_col] = (
C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\583457403.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  cyc_merged_data[new_col] = (
C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\583457403.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  cyc_merged_data[new_col] = (
C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\583457403.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  cyc_merged_data[new_col] = (
C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\583457403.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  cyc_merged_data[new_col] = (
C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\583457403.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  cyc_merged_data[new_col] = (
C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\583457403.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  cyc_merged_data[new_col] = (
C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\583457403.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  cyc_merged_data[new_col] = (
C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\583457403.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  cyc_merged_data[new_col] = (
C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\583457403.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  cyc_merged_data[new_col] = (

##  Replace minus days difference with 0

In [175]:
for n in range(1, 12):
    day_col = f"days_visit_minus_cyc{n}"

    if day_col in cyc_merged_data.columns:
        cyc_merged_data[day_col] = cyc_merged_data[day_col].clip(lower=0)

## Apply ITIS equation to all doses

In [176]:
for n in range(1, 12):
    dose_col = f"cyc_{n}_dose_value"

    if dose_col in cyc_merged_data.columns:
        cyc_merged_data[dose_col] = (
            pd.to_numeric(cyc_merged_data[dose_col], errors="coerce")
            .clip(lower=150, upper=8000)
        )

In [177]:
import numpy as np
import pandas as pd

# ---------------------------------------------
# 1. Sigmoid function (UNCHANGED)
# ---------------------------------------------
def sigmoid_curve(x, A, n, d):
    return A / (1 + np.exp(n * (x - d)))

# ---------------------------------------------
# 2. Interpolation functions for A(dose), d(dose), n(dose) (UNCHANGED)
# ---------------------------------------------
A1 = 0.60
A2 = 0.90
dose1 = 150
dose2 = 8000

m_A = (A2 - A1) / (dose2 - dose1)
b_A = A1 - m_A * dose1
def calculate_A(dose):
    return m_A * dose + b_A

d1 = 40
d2 = 80
m_d = (d2 - d1) / (dose2 - dose1)
b_d = d1 - m_d * dose1
def calculate_d(dose):
    return m_d * dose + b_d

# vanish logic (UNCHANGED)
def calculate_n_from_vanish(A, d, vanish_day):
    return np.log(99) / (vanish_day - d)

vanish1 = 60
vanish2 = 110
n1 = calculate_n_from_vanish(A1, d1, vanish1)
n2 = calculate_n_from_vanish(A2, d2, vanish2)

m_n = (n2 - n1) / (dose2 - dose1)
b_n = n1 - m_n * dose1
def calculate_n(dose):
    return m_n * dose + b_n

# ---------------------------------------------
# 3. ITIS computation for ALL doses 1–11 (equations unchanged)
# ---------------------------------------------
def compute_ITIS_generic(row, dose_num):
    dose_col = f"cyc_{dose_num}_dose_value"
    time_col = f"days_visit_minus_cyc{dose_num}"

    dose = row[dose_col]
    time = row[time_col]

    # Skip invalid values
    if pd.isna(dose) or pd.isna(time):
        return np.nan

    A = calculate_A(dose)
    d = calculate_d(dose)
    n = calculate_n(dose)

    return sigmoid_curve(time, A, n, d)

# Create ITIS columns for doses 1–11
for n in range(1, 12):
    dose_col = f"cyc_{n}_dose_value"
    time_col = f"days_visit_minus_cyc{n}"
    out_col  = f"cyc_dose{n}_ITIS"

    if dose_col in cyc_merged_data.columns and time_col in cyc_merged_data.columns:
        cyc_merged_data[out_col] = cyc_merged_data.apply(
            lambda row: compute_ITIS_generic(row, n),
            axis=1
        )

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\4183939967.py:8: RuntimeWarning: overflow encountered in exp
  return A / (1 + np.exp(n * (x - d)))
C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\4183939967.py:71: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  cyc_merged_data[out_col] = cyc_merged_data.apply(
C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\4183939967.py:8: RuntimeWarning: overflow encountered in exp
  return A / (1 + np.exp(n * (x - d)))
C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\4183939967.py:71: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  cyc_merged_data[out_col] = cyc_merged_data.apply(
C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\4183939967.py:71: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  cyc_merged_data[out_col] = cyc_merged_data.apply(
C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\4183939967.py:71: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  cyc_merged_data[out_col] = cyc_merged_data.apply(
C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\4183939967.py:8: RuntimeWarning: overflow encountered in exp
  return A / (1 + np.exp(n * (x - d)))
C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\4183939967.py:71: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  cyc_merged_data[out_col] = cyc_merged_data.apply(
C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\4183939967.py:71: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  cyc_merged_data[out_col] = cyc_merged_data.apply(
C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\4183939967.py:8: RuntimeWarning: overflow encountered in exp
  return A / (1 + np.exp(n * (x - d)))
C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\4183939967.py:71: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  cyc_merged_data[out_col] = cyc_merged_data.apply(
C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\4183939967.py:71: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  cyc_merged_data[out_col] = cyc_merged_data.apply(
C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\4183939967.py:71: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  cyc_merged_data[out_col] = cyc_merged_data.apply(
C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\4183939967.py:71: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  cyc_merged_data[out_col] = cyc_merged_data.apply(

In [178]:
itis_cols = [
    "cyc_dose1_ITIS",
    "cyc_dose2_ITIS",
    "cyc_dose3_ITIS",
    "cyc_dose4_ITIS",
    "cyc_dose5_ITIS",
    "cyc_dose6_ITIS",
    "cyc_dose7_ITIS",
    "cyc_dose9_ITIS",
    "cyc_dose10_ITIS",
    "cyc_dose11_ITIS",
]

for col in itis_cols:
    if col in cyc_merged_data.columns:
        cyc_merged_data[col] = cyc_merged_data[col].round(2)

## Cumulative CYC_IV ITIS

In [179]:
import numpy as np

# List of ITIS component columns
itis_cols = [
    "cyc_dose1_ITIS",
    "cyc_dose2_ITIS",
    "cyc_dose3_ITIS",
    "cyc_dose4_ITIS",
    "cyc_dose5_ITIS",
    "cyc_dose6_ITIS",
    "cyc_dose7_ITIS",
    "cyc_dose9_ITIS",
    "cyc_dose10_ITIS",
    "cyc_dose11_ITIS",
]

def compute_cumulative_ITIS(row):
    values = row[itis_cols].dropna().values

    # If all ITIS_i are missing → cumulative result is NaN
    if len(values) == 0:
        return np.nan

    # Apply formula: 1 - Π(1 - ITIS_i)
    product = np.prod(1 - values)
    return 1 - product

# Create new column
cyc_merged_data["CYC_IV_ITIS"] = cyc_merged_data.apply(compute_cumulative_ITIS, axis=1)

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\2660845610.py:29: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  cyc_merged_data["CYC_IV_ITIS"] = cyc_merged_data.apply(compute_cumulative_ITIS, axis=1)

In [180]:
cyc_merged_data["CYC_IV_ITIS"].fillna(0, inplace=True)
cyc_merged_data["CYC_IV_ITIS"]

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\1582224104.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  cyc_merged_data["CYC_IV_ITIS"].fillna(0, inplace=True)

0       0.0
1       0.9
2       0.9
3       0.9
4       0.9
       ...
8022    0.0
8023    0.0
8024    0.0
8025    0.0
8026    0.0
Name: CYC_IV_ITIS, Length: 8027, dtype: float64

In [181]:
mask = (
    (
        (cyc_merged_data['IV.therapy.y'] == 'Cyclophosphamide Injectable Solution - UATC/ L01AA01') &
        (
            cyc_merged_data['CYC_IV_ITIS'].isna() |
            (cyc_merged_data['CYC_IV_ITIS'] == 0)
        )
    )
    |
    (
        cyc_merged_data['treatment_type'].str.contains(
            'IV Cyclophosphamide - UATC/L01AA01|Cyclophosphamide Injectable Solution - UATC/ L01AA01|Cyclophosphamide - UATC/L01AA01',
            na=False
        ) &
        (cyc_merged_data['CYC_IV_ITIS'] == 0)
    )
)

cyc_merged_data.loc[mask, 'CYC_IV_ITIS'] = 0.75

In [182]:
cyc_merged_data["CYC_IV_ITIS"].describe()

count    8027.000000
mean        0.132453
std         0.294417
min         0.000000
25%         0.000000
50%         0.000000
75%         0.000000
max         0.900000
Name: CYC_IV_ITIS, dtype: float64

In [183]:
mtp_with_intervals=cyc_merged_data.copy()
mtp_with_intervals

,RKD.ID,Date_Of_Visit,ANCA_Levels,anca_status,ancaswitch,Repeat.Instrument,Repeat.Instance.x,Data.Access.Group.x,Patient.ID,COVID.19.related.entry.,...,cyc_dose2_ITIS,cyc_dose3_ITIS,cyc_dose4_ITIS,cyc_dose5_ITIS,cyc_dose6_ITIS,cyc_dose7_ITIS,cyc_dose9_ITIS,cyc_dose10_ITIS,cyc_dose11_ITIS,CYC_IV_ITIS
0,1,2012-08-31,134.0,ANCA Positive,Switch Status Unknown,Encounters,1,TUH - Tallaght,1,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
1,1,2012-09-07,NaN,ANCA Positive,Pos-Pos Switch,Encounters,36,TUH - Tallaght,1,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.9
2,1,2012-09-17,110.0,ANCA Positive,Pos-Pos Switch,Encounters,37,TUH - Tallaght,1,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.9
3,1,2012-09-21,92.0,ANCA Positive,Pos-Pos Switch,Encounters,2,TUH - Tallaght,1,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.9
4,1,2012-09-28,NaN,ANCA Positive,Pos-Pos Switch,Encounters,28,TUH - Tallaght,1,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8022,28793,2026-01-21,147.0,ANCA Positive,Switch Status Unknown,Encounters,1,CUH - Cork University Hospital,28793,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
8023,28796,2025-07-28,NaN,ANCA Status Unknown,Switch Status Unknown,Encounters,2,NaN,28796,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
8024,28796,2026-01-30,NaN,ANCA Negative,Switch Status Unknown,Encounters,1,NaN,28796,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
8025,28797,2026-02-02,134.0,ANCA Positive,Switch Status Unknown,Encounters,1,CUH - Cork University Hospital,28797,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
8026,28797,2026-03-26,134.0,ANCA Positive,Pos-Pos Switch,Encounters,2,CUH - Cork University Hospital,28797,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0

In [184]:
#cyc_merged_data .to_csv('C:/Users/georgea1/OneDrive - Trinity College Dublin/Desktop/cycfinal.csv',index=True)

## Rituximab

In [185]:
#mtp_with_intervals=pd.read_csv("C:/Users/georgea1/OneDrive - Trinity College Dublin/Angel George/Chap 2. Treatment/Data/ITIS Data/RIV/December 2025/Redcap_clinical_data_harmonized_version0.0.3 (3).csv")
#mtp_with_intervals

In [186]:
#mtp_with_intervals.rename(columns = {'Date.Of.Visit':'Date_Of_Visit'}, inplace = True)

In [187]:
rtx=IV.loc[(IV['IV.therapy']=='Rituximab - UATC/L01XC02 -- Mabthera')|(IV['IV.therapy']=='Rituximab - UATC/L01XC02 -- Ruxience')|(IV['IV.therapy']=='Rituximab - UATC/L01XC02 -- Truxima')]
rtx

,RKD.ID,IV.therapy,Date.of.IV.therapy,Dose.of.IV.therapy,Unit.of.dose,Unit.of.dose...other
14,1,Rituximab - UATC/L01XC02 -- Mabthera,2021-05-26,800.0,mg,NaN
16,1,Rituximab - UATC/L01XC02 -- Mabthera,2022-03-04,800.0,mg,NaN
18,1,Rituximab - UATC/L01XC02 -- Mabthera,2022-09-01,800.0,mg,NaN
20,1,Rituximab - UATC/L01XC02 -- Ruxience,2023-03-06,710.0,mg,NaN
22,1,Rituximab - UATC/L01XC02 -- Ruxience,2024-03-11,710.0,mg,NaN
...,...,...,...,...,...,...
6368,28789,Rituximab - UATC/L01XC02 -- Ruxience,2025-01-02,NaN,NaN,NaN
6376,28796,Rituximab - UATC/L01XC02 -- Ruxience,2025-10-13,1000.0,mg,NaN
6377,28796,Rituximab - UATC/L01XC02 -- Ruxience,2025-10-27,1000.0,mg,NaN
6378,28797,Rituximab - UATC/L01XC02 -- Truxima,2026-02-13,1000.0,mg,NaN
6379,28797,Rituximab - UATC/L01XC02 -- Truxima,2026-03-02,1000.0,mg,NaN

In [188]:
## Drop duplicates

In [189]:
rtx = rtx.drop_duplicates(
    subset=[
        "RKD.ID",
        "IV.therapy",
        "Date.of.IV.therapy",
        "Dose.of.IV.therapy"
    ]
)
rtx.shape

(2196, 6)

In [190]:
rtx['Unit.of.dose'].value_counts(dropna=False)

Unit.of.dose
mg     2149
g        31
NaN      16
Name: count, dtype: int64

In [191]:
mask = rtx['Unit.of.dose'] == 'g'
rtx.loc[mask, 'Dose.of.IV.therapy'] *= 1000
rtx.loc[mask, 'Unit.of.dose'] = 'mg'

In [192]:
rtx['Unit.of.dose'].value_counts(dropna=False)

Unit.of.dose
mg     2180
NaN      16
Name: count, dtype: int64

In [193]:
rtx['Dose.of.IV.therapy'].isnull().sum()

31

In [194]:
rtx['Dose.of.IV.therapy'].describe()

count    2165.000000
mean      803.281755
std       208.367990
min         1.000000
25%       600.000000
50%       800.000000
75%      1000.000000
max      1800.000000
Name: Dose.of.IV.therapy, dtype: float64

In [195]:
rtx['Dose.of.IV.therapy'].value_counts(dropna=False)

Dose.of.IV.therapy
1000.0    949
500.0     463
800.0     170
700.0      89
750.0      65
         ...
645.0       1
562.0       1
638.0       1
754.0       1
460.0       1
Name: count, Length: 63, dtype: int64

In [196]:
rtx.loc[rtx['Dose.of.IV.therapy'] < 500, 'Dose.of.IV.therapy'] = 500

In [197]:
rtx['Dose.of.IV.therapy'].describe()

count    2165.000000
mean      804.474365
std       205.460359
min       500.000000
25%       600.000000
50%       800.000000
75%      1000.000000
max      1800.000000
Name: Dose.of.IV.therapy, dtype: float64

In [198]:
rtx['Dose.of.IV.therapy'] = rtx['Dose.of.IV.therapy'].fillna(1000)
rtx['Dose.of.IV.therapy'].isnull().sum()

0

In [199]:
# Step 1 — Sort by ID and dose date
rtx_sorted = rtx.sort_values(["RKD.ID", "Date.of.IV.therapy"]).copy()

# Step 2 — Assign dose number for each patient
rtx_sorted["dose_number"] = rtx_sorted.groupby("RKD.ID").cumcount() + 1

# Step 3 — Rename columns for pivoting
rtx_wide = rtx_sorted.pivot_table(
    index="RKD.ID",
    columns="dose_number",
    values=["Date.of.IV.therapy", "Dose.of.IV.therapy"],
    aggfunc="first"
)

# Step 4 — Flatten multi-index column names
rtx_wide.columns = [
    f"rtx_{col[1]}_dose_{col[0].replace('Date.of.IV.therapy','date').replace('Dose.of.IV.therapy','value')}"
    for col in rtx_wide.columns
]

rtx_wide = rtx_wide.reset_index()
rtx_wide

,RKD.ID,rtx_1_dose_date,rtx_2_dose_date,rtx_3_dose_date,rtx_4_dose_date,rtx_5_dose_date,rtx_6_dose_date,rtx_7_dose_date,rtx_8_dose_date,rtx_9_dose_date,...,rtx_25_dose_value,rtx_26_dose_value,rtx_27_dose_value,rtx_28_dose_value,rtx_29_dose_value,rtx_30_dose_value,rtx_31_dose_value,rtx_32_dose_value,rtx_33_dose_value,rtx_34_dose_value
0,1,2021-05-26,2022-03-04,2022-09-01,2023-03-06,2024-03-11,2025-09-15,NaT,NaT,NaT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,3,2017-04-06,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,7,2012-07-02,2012-07-16,2014-01-08,NaT,NaT,NaT,NaT,NaT,NaT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,10,2013-09-01,2013-09-17,2015-08-28,2016-08-13,NaT,NaT,NaT,NaT,NaT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,11,2017-09-21,2018-02-26,2018-08-07,2018-12-06,2021-07-05,2022-10-12,2023-07-19,2023-11-30,2024-05-23,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
537,28785,2025-12-02,2025-12-16,NaT,NaT,NaT,NaT,NaT,NaT,NaT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
538,28786,2026-01-14,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
539,28789,2025-01-02,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
540,28796,2025-10-13,2025-10-27,NaT,NaT,NaT,NaT,NaT,NaT,NaT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
541,28797,2026-02-13,2026-03-02,NaT,NaT,NaT,NaT,NaT,NaT,NaT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [200]:
import numpy as np
import pandas as pd

def merge_visits_with_rtx(visits, mtp_wide):

    df = visits.copy()
    rtx = rtx_wide.copy()

    # Ensure Date_Of_Visit is datetime
    df["Date_Of_Visit"] = pd.to_datetime(df["Date_Of_Visit"], errors="coerce")

    # Merge wide IV data onto visits
    df = df.merge(rtx, on="RKD.ID", how="left")

    # Identify dose blocks
    dose_numbers = sorted(
        int(col.split("_")[1])
        for col in rtx.columns
        if col.startswith("rtx_") and col.endswith("_dose_date")
    )

    for n in dose_numbers:

        dose_date_col = f"rtx_{n}_dose_date"
        value_col     = f"rtx_{n}_dose_value"


        # Convert IV dates to datetime
        df[dose_date_col] = pd.to_datetime(df[dose_date_col], errors="coerce")

        # Condition:
        # Keep the dose if the visit occurs AFTER the dose date
        # Blank it otherwise
        mask = (
            df[dose_date_col].notna() &
            (df[dose_date_col] < df["Date_Of_Visit"])
        )

        # Blank outside window
        df.loc[~mask, [dose_date_col, value_col]] = [np.nan, np.nan]

    return df

In [201]:
rtx_merged_data = merge_visits_with_rtx(mtp_with_intervals, rtx_wide)
rtx_merged_data

,RKD.ID,Date_Of_Visit,ANCA_Levels,anca_status,ancaswitch,Repeat.Instrument,Repeat.Instance.x,Data.Access.Group.x,Patient.ID,COVID.19.related.entry.,...,rtx_25_dose_value,rtx_26_dose_value,rtx_27_dose_value,rtx_28_dose_value,rtx_29_dose_value,rtx_30_dose_value,rtx_31_dose_value,rtx_32_dose_value,rtx_33_dose_value,rtx_34_dose_value
0,1,2012-08-31,134.0,ANCA Positive,Switch Status Unknown,Encounters,1,TUH - Tallaght,1,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,2012-09-07,NaN,ANCA Positive,Pos-Pos Switch,Encounters,36,TUH - Tallaght,1,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,2012-09-17,110.0,ANCA Positive,Pos-Pos Switch,Encounters,37,TUH - Tallaght,1,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1,2012-09-21,92.0,ANCA Positive,Pos-Pos Switch,Encounters,2,TUH - Tallaght,1,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1,2012-09-28,NaN,ANCA Positive,Pos-Pos Switch,Encounters,28,TUH - Tallaght,1,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8022,28793,2026-01-21,147.0,ANCA Positive,Switch Status Unknown,Encounters,1,CUH - Cork University Hospital,28793,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8023,28796,2025-07-28,NaN,ANCA Status Unknown,Switch Status Unknown,Encounters,2,NaN,28796,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8024,28796,2026-01-30,NaN,ANCA Negative,Switch Status Unknown,Encounters,1,NaN,28796,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8025,28797,2026-02-02,134.0,ANCA Positive,Switch Status Unknown,Encounters,1,CUH - Cork University Hospital,28797,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8026,28797,2026-03-26,134.0,ANCA Positive,Pos-Pos Switch,Encounters,2,CUH - Cork University Hospital,28797,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [202]:
## drop blank columns
rtx_merged_data =rtx_merged_data.dropna(axis=1, how='all')
rtx_merged_data.shape

(8027, 637)

In [203]:
#rtx_merged_data.to_csv('C:/Users/georgea1/OneDrive - Trinity College Dublin/Desktop/RTX_1.csv',index=True)

In [204]:
## RTX ITIS vs age encounter

In [205]:
import pandas as pd
import numpy as np

# Ensure Age_Encounters is numeric
rtx_merged_data["Age_Encounters"] = pd.to_numeric(
    rtx_merged_data["Age_Encounters"], errors="coerce"
)

age = rtx_merged_data["Age_Encounters"]

for n in range(1, 34):
    dose_col = f"rtx_{n}_dose_value"

    if dose_col in rtx_merged_data.columns:
        # Ensure dose column is numeric
        rtx_merged_data[dose_col] = pd.to_numeric(
            rtx_merged_data[dose_col], errors="coerce"
        )

        dose = rtx_merged_data[dose_col]

        rtx_merged_data[dose_col] = np.select(
            [
                age.between(65, 73, inclusive="both") & dose.notna(),
                age.between(74, 82, inclusive="both") & dose.notna(),
                age.gt(82) & dose.notna(),
            ],
            [
                dose * 1.5,
                dose * 2.0,
                dose * 2.5
            ],
            default=dose
        )

## Define course
### calculate the difference between the dose date

## first dose

In [206]:
import numpy as np
import pandas as pd

def min_interval_table(df, max_dose=34):
    x = df.copy()

    # Parse dose dates
    for n in range(1, max_dose + 1):
        col = f"rtx_{n}_dose_date"
        if col in x.columns:
            x[col] = pd.to_datetime(x[col], errors="coerce", dayfirst=True)

    # Use earliest dose dates per patient (avoids repeated visit rows)
    per_patient = (
        x.groupby("RKD.ID")[[c for c in x.columns if c.startswith("rtx_") and c.endswith("_dose_date")]]
         .min()
         .reset_index()
    )

    # Build min interval per dose (global min across dataset)
    rows = []
    d1 = "rtx_1_dose_date"

    for n in range(2, max_dose + 1):
        dn = f"rtx_{n}_dose_date"
        if dn not in per_patient.columns:
            continue

        interval_series = (per_patient[dn] - per_patient[d1]).dt.days

        rows.append({
            "interval_name": f"interval_{n}_minus_1_days",
            "min_days": interval_series.min(skipna=True)
        })

    return pd.DataFrame(rows)


min_intervals_table = min_interval_table(rtx_merged_data, max_dose=34)
min_intervals_table

               interval_name  min_days
0    interval_2_minus_1_days       3.0
1    interval_3_minus_1_days      13.0
2    interval_4_minus_1_days      20.0
3    interval_5_minus_1_days      28.0
4    interval_6_minus_1_days     176.0
5    interval_7_minus_1_days     382.0
6    interval_8_minus_1_days     396.0
7    interval_9_minus_1_days     536.0
8   interval_10_minus_1_days     550.0
9   interval_11_minus_1_days     682.0
10  interval_12_minus_1_days     689.0
11  interval_13_minus_1_days     696.0
12  interval_14_minus_1_days     703.0
13  interval_15_minus_1_days     850.0
14  interval_16_minus_1_days     871.0
15  interval_17_minus_1_days    1214.0
16  interval_18_minus_1_days    1403.0
17  interval_19_minus_1_days    1526.0
18  interval_20_minus_1_days    1653.0
19  interval_21_minus_1_days    1900.0
20  interval_22_minus_1_days    2530.0
21  interval_23_minus_1_days    2544.0
22  interval_24_minus_1_days    2719.0
23  interval_25_minus_1_days    2733.0
24  interval_26_minus_1_days    2922.0
25  interval_27_minus_1_days    3286.0
26  interval_28_minus_1_days    3300.0
27  interval_29_minus_1_days    3468.0
28  interval_30_minus_1_days    3482.0
29  interval_31_minus_1_days    3738.0
30  interval_32_minus_1_days    3752.0
31  interval_33_minus_1_days    3921.0
32  interval_34_minus_1_days    3937.0

In [207]:
def update_rtx_doses(df, base_dose, target_dose, max_days=60):
    result = df.copy()

    base_date   = f"rtx_{base_dose}_dose_date"
    target_date = f"rtx_{target_dose}_dose_date"
    base_value  = f"rtx_{base_dose}_dose_value"
    target_value= f"rtx_{target_dose}_dose_value"

    # Parse dates
    result[base_date]   = pd.to_datetime(result[base_date], errors="coerce", dayfirst=True)
    result[target_date] = pd.to_datetime(result[target_date], errors="coerce", dayfirst=True)

    # Parse numeric values
    result[base_value]   = pd.to_numeric(result[base_value], errors="coerce")
    result[target_value] = pd.to_numeric(result[target_value], errors="coerce")

    def _per_patient(g):
        g = g.copy()

        d_base   = g[base_date].dropna()
        d_target = g[target_date].dropna()

        # Need both doses
        if d_base.empty or d_target.empty:
            return g

        base_date_val   = d_base.iloc[0]
        target_date_val = d_target.iloc[0]

        # Check interval
        interval_days = (target_date_val - base_date_val).days
        if pd.isna(interval_days) or interval_days > max_days:
            return g

        # Get dose values
        v_base   = g.loc[g[base_date].notna(), base_value].dropna()
        v_target = g.loc[g[target_date].notna(), target_value].dropna()

        base_val   = v_base.iloc[0]   if not v_base.empty   else np.nan
        target_val = v_target.iloc[0] if not v_target.empty else np.nan

        cumulative = base_val + target_val

        # Replace ALL non-missing base-dose rows
        mask = g[base_date].notna()
        g.loc[mask, base_date]  = target_date_val
        g.loc[mask, base_value] = cumulative

        # Blank target-dose after merge
        g[target_date]  = pd.NaT
        g[target_value] = np.nan

        return g

    return result.groupby("RKD.ID", group_keys=False).apply(_per_patient)

In [208]:
rtx_merged_data = update_rtx_doses(rtx_merged_data, base_dose=1, target_dose=2)

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\656049958.py:55: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  return result.groupby("RKD.ID", group_keys=False).apply(_per_patient)

In [209]:
rtx_merged_data = update_rtx_doses(rtx_merged_data, base_dose=1, target_dose=3)

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\656049958.py:55: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  return result.groupby("RKD.ID", group_keys=False).apply(_per_patient)

In [210]:
rtx_merged_data = update_rtx_doses(rtx_merged_data, base_dose=1, target_dose=4)

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\656049958.py:55: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  return result.groupby("RKD.ID", group_keys=False).apply(_per_patient)

In [211]:
rtx_merged_data = update_rtx_doses(rtx_merged_data, base_dose=1, target_dose=5)

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\656049958.py:55: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  return result.groupby("RKD.ID", group_keys=False).apply(_per_patient)

In [212]:
## Second dose

In [213]:
import numpy as np
import pandas as pd

def min_interval_table(df, max_dose=34):
    x = df.copy()

    # Parse dose dates
    for n in range(1, max_dose + 1):
        col = f"rtx_{n}_dose_date"
        if col in x.columns:
            x[col] = pd.to_datetime(x[col], errors="coerce", dayfirst=True)

    # Use earliest dose dates per patient (avoids repeated visit rows)
    per_patient = (
        x.groupby("RKD.ID")[[c for c in x.columns if c.startswith("rtx_") and c.endswith("_dose_date")]]
         .min()
         .reset_index()
    )

    # Build min interval per dose (global min across dataset)
    rows = []
    d1 = "rtx_2_dose_date"

    for n in range(2, max_dose + 1):
        dn = f"rtx_{n}_dose_date"
        if dn not in per_patient.columns:
            continue

        interval_series = (per_patient[dn] - per_patient[d1]).dt.days

        rows.append({
            "interval_name": f"interval_{n}_minus_2_days",
            "min_days": interval_series.min(skipna=True)
        })

    return pd.DataFrame(rows)


min_intervals_table = min_interval_table(rtx_merged_data, max_dose=34)
min_intervals_table

               interval_name  min_days
0    interval_2_minus_2_days       0.0
1    interval_3_minus_2_days       3.0
2    interval_4_minus_2_days       8.0
3    interval_5_minus_2_days      14.0
4    interval_6_minus_2_days     420.0
5    interval_7_minus_2_days     539.0
6    interval_8_minus_2_days     854.0
7    interval_9_minus_2_days     937.0
8   interval_10_minus_2_days    1275.0
9   interval_11_minus_2_days    1464.0
10  interval_12_minus_2_days    1660.0
11  interval_13_minus_2_days    1919.0
12  interval_14_minus_2_days    2199.0
13  interval_15_minus_2_days    2500.0
14  interval_16_minus_2_days    4080.0
15  interval_17_minus_2_days    4263.0
16  interval_18_minus_2_days       NaN
17  interval_19_minus_2_days       NaN
18  interval_20_minus_2_days       NaN
19  interval_21_minus_2_days       NaN
20  interval_22_minus_2_days       NaN
21  interval_23_minus_2_days       NaN
22  interval_24_minus_2_days       NaN
23  interval_25_minus_2_days       NaN
24  interval_26_minus_2_days       NaN
25  interval_27_minus_2_days       NaN
26  interval_28_minus_2_days       NaN
27  interval_29_minus_2_days       NaN
28  interval_30_minus_2_days       NaN
29  interval_31_minus_2_days       NaN
30  interval_32_minus_2_days       NaN
31  interval_33_minus_2_days       NaN
32  interval_34_minus_2_days       NaN

In [214]:
rtx_merged_data = update_rtx_doses(rtx_merged_data, base_dose=2, target_dose=3)

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\656049958.py:55: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  return result.groupby("RKD.ID", group_keys=False).apply(_per_patient)

In [215]:
rtx_merged_data = update_rtx_doses(rtx_merged_data, base_dose=2, target_dose=4)

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\656049958.py:55: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  return result.groupby("RKD.ID", group_keys=False).apply(_per_patient)

In [216]:
rtx_merged_data = update_rtx_doses(rtx_merged_data, base_dose=2, target_dose=5)

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\656049958.py:55: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  return result.groupby("RKD.ID", group_keys=False).apply(_per_patient)

## Third Dose

In [217]:
import numpy as np
import pandas as pd

def min_interval_table(df, max_dose=34):
    x = df.copy()

    # Parse dose dates
    for n in range(1, max_dose + 1):
        col = f"rtx_{n}_dose_date"
        if col in x.columns:
            x[col] = pd.to_datetime(x[col], errors="coerce", dayfirst=True)

    # Use earliest dose dates per patient (avoids repeated visit rows)
    per_patient = (
        x.groupby("RKD.ID")[[c for c in x.columns if c.startswith("rtx_") and c.endswith("_dose_date")]]
         .min()
         .reset_index()
    )

    # Build min interval per dose (global min across dataset)
    rows = []
    d1 = "rtx_3_dose_date"

    for n in range(2, max_dose + 1):
        dn = f"rtx_{n}_dose_date"
        if dn not in per_patient.columns:
            continue

        interval_series = (per_patient[dn] - per_patient[d1]).dt.days

        rows.append({
            "interval_name": f"interval_{n}_minus_3_days",
            "min_days": interval_series.min(skipna=True)
        })

    return pd.DataFrame(rows)


min_intervals_table = min_interval_table(rtx_merged_data, max_dose=34)
min_intervals_table

               interval_name  min_days
0    interval_2_minus_3_days   -2849.0
1    interval_3_minus_3_days       0.0
2    interval_4_minus_3_days       7.0
3    interval_5_minus_3_days      14.0
4    interval_6_minus_3_days      24.0
5    interval_7_minus_3_days     198.0
6    interval_8_minus_3_days     386.0
7    interval_9_minus_3_days     678.0
8   interval_10_minus_3_days     787.0
9   interval_11_minus_3_days    1267.0
10  interval_12_minus_3_days    1442.0
11  interval_13_minus_3_days    1645.0
12  interval_14_minus_3_days    1820.0
13  interval_15_minus_3_days    1998.0
14  interval_16_minus_3_days    2785.0
15  interval_17_minus_3_days    2968.0
16  interval_18_minus_3_days    3144.0
17  interval_19_minus_3_days    3311.0
18  interval_20_minus_3_days    3654.0
19  interval_21_minus_3_days    3982.0
20  interval_22_minus_3_days       NaN
21  interval_23_minus_3_days       NaN
22  interval_24_minus_3_days       NaN
23  interval_25_minus_3_days       NaN
24  interval_26_minus_3_days       NaN
25  interval_27_minus_3_days       NaN
26  interval_28_minus_3_days       NaN
27  interval_29_minus_3_days       NaN
28  interval_30_minus_3_days       NaN
29  interval_31_minus_3_days       NaN
30  interval_32_minus_3_days       NaN
31  interval_33_minus_3_days       NaN
32  interval_34_minus_3_days       NaN

In [218]:
rtx_merged_data = update_rtx_doses(rtx_merged_data, base_dose=3, target_dose=4)

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\656049958.py:55: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  return result.groupby("RKD.ID", group_keys=False).apply(_per_patient)

In [219]:
rtx_merged_data = update_rtx_doses(rtx_merged_data, base_dose=3, target_dose=5)

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\656049958.py:55: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  return result.groupby("RKD.ID", group_keys=False).apply(_per_patient)

In [220]:
rtx_merged_data = update_rtx_doses(rtx_merged_data, base_dose=3, target_dose=6)

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\656049958.py:55: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  return result.groupby("RKD.ID", group_keys=False).apply(_per_patient)

## Fourth Dose

In [221]:
import numpy as np
import pandas as pd

def min_interval_table(df, max_dose=34):
    x = df.copy()

    # Parse dose dates
    for n in range(1, max_dose + 1):
        col = f"rtx_{n}_dose_date"
        if col in x.columns:
            x[col] = pd.to_datetime(x[col], errors="coerce", dayfirst=True)

    # Use earliest dose dates per patient (avoids repeated visit rows)
    per_patient = (
        x.groupby("RKD.ID")[[c for c in x.columns if c.startswith("rtx_") and c.endswith("_dose_date")]]
         .min()
         .reset_index()
    )

    # Build min interval per dose (global min across dataset)
    rows = []
    d1 = "rtx_4_dose_date"

    for n in range(2, max_dose + 1):
        dn = f"rtx_{n}_dose_date"
        if dn not in per_patient.columns:
            continue

        interval_series = (per_patient[dn] - per_patient[d1]).dt.days

        rows.append({
            "interval_name": f"interval_{n}_minus_4_days",
            "min_days": interval_series.min(skipna=True)
        })

    return pd.DataFrame(rows)


min_intervals_table = min_interval_table(rtx_merged_data, max_dose=34)
min_intervals_table

               interval_name  min_days
0    interval_2_minus_4_days   -2586.0
1    interval_3_minus_4_days   -2377.0
2    interval_4_minus_4_days       0.0
3    interval_5_minus_4_days       7.0
4    interval_6_minus_4_days      88.0
5    interval_7_minus_4_days     159.0
6    interval_8_minus_4_days     342.0
7    interval_9_minus_4_days     566.0
8   interval_10_minus_4_days     591.0
9   interval_11_minus_4_days    1114.0
10  interval_12_minus_4_days    1289.0
11  interval_13_minus_4_days    1548.0
12  interval_14_minus_4_days    1828.0
13  interval_15_minus_4_days    2129.0
14  interval_16_minus_4_days    3891.0
15  interval_17_minus_4_days    4074.0
16  interval_18_minus_4_days       NaN
17  interval_19_minus_4_days       NaN
18  interval_20_minus_4_days       NaN
19  interval_21_minus_4_days       NaN
20  interval_22_minus_4_days       NaN
21  interval_23_minus_4_days       NaN
22  interval_24_minus_4_days       NaN
23  interval_25_minus_4_days       NaN
24  interval_26_minus_4_days       NaN
25  interval_27_minus_4_days       NaN
26  interval_28_minus_4_days       NaN
27  interval_29_minus_4_days       NaN
28  interval_30_minus_4_days       NaN
29  interval_31_minus_4_days       NaN
30  interval_32_minus_4_days       NaN
31  interval_33_minus_4_days       NaN
32  interval_34_minus_4_days       NaN

In [222]:
rtx_merged_data = update_rtx_doses(rtx_merged_data, base_dose=4, target_dose=5)

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\656049958.py:55: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  return result.groupby("RKD.ID", group_keys=False).apply(_per_patient)

In [223]:
## Fifth Dose

In [224]:
import numpy as np
import pandas as pd

def min_interval_table(df, max_dose=34):
    x = df.copy()

    # Parse dose dates
    for n in range(1, max_dose + 1):
        col = f"rtx_{n}_dose_date"
        if col in x.columns:
            x[col] = pd.to_datetime(x[col], errors="coerce", dayfirst=True)

    # Use earliest dose dates per patient (avoids repeated visit rows)
    per_patient = (
        x.groupby("RKD.ID")[[c for c in x.columns if c.startswith("rtx_") and c.endswith("_dose_date")]]
         .min()
         .reset_index()
    )

    # Build min interval per dose (global min across dataset)
    rows = []
    d1 = "rtx_5_dose_date"

    for n in range(2, max_dose + 1):
        dn = f"rtx_{n}_dose_date"
        if dn not in per_patient.columns:
            continue

        interval_series = (per_patient[dn] - per_patient[d1]).dt.days

        rows.append({
            "interval_name": f"interval_{n}_minus_5_days",
            "min_days": interval_series.min(skipna=True)
        })

    return pd.DataFrame(rows)


min_intervals_table = min_interval_table(rtx_merged_data, max_dose=34)
min_intervals_table

               interval_name  min_days
0    interval_2_minus_5_days   -2090.0
1    interval_3_minus_5_days   -3275.0
2    interval_4_minus_5_days   -1625.0
3    interval_5_minus_5_days       0.0
4    interval_6_minus_5_days       8.0
5    interval_7_minus_5_days      15.0
6    interval_8_minus_5_days      23.0
7    interval_9_minus_5_days     314.0
8   interval_10_minus_5_days     345.0
9   interval_11_minus_5_days     477.0
10  interval_12_minus_5_days     484.0
11  interval_13_minus_5_days     491.0
12  interval_14_minus_5_days     498.0
13  interval_15_minus_5_days     645.0
14  interval_16_minus_5_days     666.0
15  interval_17_minus_5_days    1009.0
16  interval_18_minus_5_days    1198.0
17  interval_19_minus_5_days    1321.0
18  interval_20_minus_5_days    1448.0
19  interval_21_minus_5_days    1695.0
20  interval_22_minus_5_days    2325.0
21  interval_23_minus_5_days    2339.0
22  interval_24_minus_5_days    2514.0
23  interval_25_minus_5_days    2528.0
24  interval_26_minus_5_days    2717.0
25  interval_27_minus_5_days    3081.0
26  interval_28_minus_5_days    3095.0
27  interval_29_minus_5_days    3263.0
28  interval_30_minus_5_days    3277.0
29  interval_31_minus_5_days    3533.0
30  interval_32_minus_5_days    3547.0
31  interval_33_minus_5_days    3716.0
32  interval_34_minus_5_days    3732.0

In [225]:
rtx_merged_data = update_rtx_doses(rtx_merged_data, base_dose=5, target_dose=6)

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\656049958.py:55: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  return result.groupby("RKD.ID", group_keys=False).apply(_per_patient)

In [226]:
rtx_merged_data = update_rtx_doses(rtx_merged_data, base_dose=5, target_dose=7)

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\656049958.py:55: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  return result.groupby("RKD.ID", group_keys=False).apply(_per_patient)

In [227]:
rtx_merged_data = update_rtx_doses(rtx_merged_data, base_dose=5, target_dose=8)

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\656049958.py:55: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  return result.groupby("RKD.ID", group_keys=False).apply(_per_patient)

In [228]:
## Sixth dose

In [229]:
import numpy as np
import pandas as pd

def min_interval_table(df, max_dose=34):
    x = df.copy()

    # Parse dose dates
    for n in range(1, max_dose + 1):
        col = f"rtx_{n}_dose_date"
        if col in x.columns:
            x[col] = pd.to_datetime(x[col], errors="coerce", dayfirst=True)

    # Use earliest dose dates per patient (avoids repeated visit rows)
    per_patient = (
        x.groupby("RKD.ID")[[c for c in x.columns if c.startswith("rtx_") and c.endswith("_dose_date")]]
         .min()
         .reset_index()
    )

    # Build min interval per dose (global min across dataset)
    rows = []
    d1 = "rtx_7_dose_date"

    for n in range(2, max_dose + 1):
        dn = f"rtx_{n}_dose_date"
        if dn not in per_patient.columns:
            continue

        interval_series = (per_patient[dn] - per_patient[d1]).dt.days

        rows.append({
            "interval_name": f"interval_{n}_minus_7_days",
            "min_days": interval_series.min(skipna=True)
        })

    return pd.DataFrame(rows)


min_intervals_table = min_interval_table(rtx_merged_data, max_dose=34)
min_intervals_table

               interval_name  min_days
0    interval_2_minus_7_days   -4442.0
1    interval_3_minus_7_days   -3865.0
2    interval_4_minus_7_days   -4029.0
3    interval_5_minus_7_days   -3674.0
4    interval_6_minus_7_days   -1700.0
5    interval_7_minus_7_days       0.0
6    interval_8_minus_7_days       7.0
7    interval_9_minus_7_days      13.0
8   interval_10_minus_7_days      20.0
9   interval_11_minus_7_days     217.0
10  interval_12_minus_7_days     307.0
11  interval_13_minus_7_days     314.0
12  interval_14_minus_7_days     321.0
13  interval_15_minus_7_days     468.0
14  interval_16_minus_7_days     489.0
15  interval_17_minus_7_days     832.0
16  interval_18_minus_7_days    1021.0
17  interval_19_minus_7_days    1144.0
18  interval_20_minus_7_days    1271.0
19  interval_21_minus_7_days    1518.0
20  interval_22_minus_7_days    2148.0
21  interval_23_minus_7_days    2162.0
22  interval_24_minus_7_days    2337.0
23  interval_25_minus_7_days    2351.0
24  interval_26_minus_7_days    2540.0
25  interval_27_minus_7_days    2904.0
26  interval_28_minus_7_days    2918.0
27  interval_29_minus_7_days    3086.0
28  interval_30_minus_7_days    3100.0
29  interval_31_minus_7_days    3356.0
30  interval_32_minus_7_days    3370.0
31  interval_33_minus_7_days    3539.0
32  interval_34_minus_7_days    3555.0

In [230]:
rtx_merged_data = update_rtx_doses(rtx_merged_data, base_dose=7, target_dose=8)

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\656049958.py:55: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  return result.groupby("RKD.ID", group_keys=False).apply(_per_patient)

In [233]:
rtx_merged_data = update_rtx_doses(rtx_merged_data, base_dose=7, target_dose=9)

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\656049958.py:55: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  return result.groupby("RKD.ID", group_keys=False).apply(_per_patient)

In [234]:
rtx_merged_data = update_rtx_doses(rtx_merged_data, base_dose=7, target_dose=10)

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\656049958.py:55: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  return result.groupby("RKD.ID", group_keys=False).apply(_per_patient)

In [235]:
import numpy as np
import pandas as pd

def min_interval_table(df, max_dose=34):
    x = df.copy()

    # Parse dose dates
    for n in range(1, max_dose + 1):
        col = f"rtx_{n}_dose_date"
        if col in x.columns:
            x[col] = pd.to_datetime(x[col], errors="coerce", dayfirst=True)

    # Use earliest dose dates per patient (avoids repeated visit rows)
    per_patient = (
        x.groupby("RKD.ID")[[c for c in x.columns if c.startswith("rtx_") and c.endswith("_dose_date")]]
         .min()
         .reset_index()
    )

    # Build min interval per dose (global min across dataset)
    rows = []
    d1 = "rtx_8_dose_date"

    for n in range(2, max_dose + 1):
        dn = f"rtx_{n}_dose_date"
        if dn not in per_patient.columns:
            continue

        interval_series = (per_patient[dn] - per_patient[d1]).dt.days

        rows.append({
            "interval_name": f"interval_{n}_minus_8_days",
            "min_days": interval_series.min(skipna=True)
        })

    return pd.DataFrame(rows)


min_intervals_table = min_interval_table(rtx_merged_data, max_dose=34)
min_intervals_table

               interval_name  min_days
0    interval_2_minus_8_days   -3253.0
1    interval_3_minus_8_days   -3002.0
2    interval_4_minus_8_days   -2675.0
3    interval_5_minus_8_days   -2500.0
4    interval_6_minus_8_days   -2305.0
5    interval_7_minus_8_days   -1445.0
6    interval_8_minus_8_days       0.0
7    interval_9_minus_8_days      14.0
8   interval_10_minus_8_days     154.0
9   interval_11_minus_8_days     200.0
10  interval_12_minus_8_days     224.0
11  interval_13_minus_8_days    1002.0
12  interval_14_minus_8_days    1282.0
13  interval_15_minus_8_days    1345.0
14  interval_16_minus_8_days    1352.0
15  interval_17_minus_8_days    1535.0
16  interval_18_minus_8_days    1711.0
17  interval_19_minus_8_days    1878.0
18  interval_20_minus_8_days    2221.0
19  interval_21_minus_8_days    2549.0
20  interval_22_minus_8_days       NaN
21  interval_23_minus_8_days       NaN
22  interval_24_minus_8_days       NaN
23  interval_25_minus_8_days       NaN
24  interval_26_minus_8_days       NaN
25  interval_27_minus_8_days       NaN
26  interval_28_minus_8_days       NaN
27  interval_29_minus_8_days       NaN
28  interval_30_minus_8_days       NaN
29  interval_31_minus_8_days       NaN
30  interval_32_minus_8_days       NaN
31  interval_33_minus_8_days       NaN
32  interval_34_minus_8_days       NaN

In [236]:
rtx_merged_data = update_rtx_doses(rtx_merged_data, base_dose=8, target_dose=9)

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\656049958.py:55: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  return result.groupby("RKD.ID", group_keys=False).apply(_per_patient)

In [237]:
import numpy as np
import pandas as pd

def min_interval_table(df, max_dose=34):
    x = df.copy()

    # Parse dose dates
    for n in range(1, max_dose + 1):
        col = f"rtx_{n}_dose_date"
        if col in x.columns:
            x[col] = pd.to_datetime(x[col], errors="coerce", dayfirst=True)

    # Use earliest dose dates per patient (avoids repeated visit rows)
    per_patient = (
        x.groupby("RKD.ID")[[c for c in x.columns if c.startswith("rtx_") and c.endswith("_dose_date")]]
         .min()
         .reset_index()
    )

    # Build min interval per dose (global min across dataset)
    rows = []
    d1 = "rtx_9_dose_date"

    for n in range(2, max_dose + 1):
        dn = f"rtx_{n}_dose_date"
        if dn not in per_patient.columns:
            continue

        interval_series = (per_patient[dn] - per_patient[d1]).dt.days

        rows.append({
            "interval_name": f"interval_{n}_minus_9_days",
            "min_days": interval_series.min(skipna=True)
        })

    return pd.DataFrame(rows)


min_intervals_table = min_interval_table(rtx_merged_data, max_dose=34)
min_intervals_table

               interval_name  min_days
0    interval_2_minus_9_days   -3734.0
1    interval_3_minus_9_days   -2760.0
2    interval_4_minus_9_days   -2654.0
3    interval_5_minus_9_days   -2367.0
4    interval_6_minus_9_days   -2193.0
5    interval_7_minus_9_days   -1774.0
6    interval_8_minus_9_days   -1592.0
7    interval_9_minus_9_days       0.0
8   interval_10_minus_9_days       7.0
9   interval_11_minus_9_days      14.0
10  interval_12_minus_9_days      21.0
11  interval_13_minus_9_days     160.0
12  interval_14_minus_9_days     167.0
13  interval_15_minus_9_days     314.0
14  interval_16_minus_9_days     335.0
15  interval_17_minus_9_days     678.0
16  interval_18_minus_9_days     867.0
17  interval_19_minus_9_days     990.0
18  interval_20_minus_9_days    1117.0
19  interval_21_minus_9_days    1364.0
20  interval_22_minus_9_days    1994.0
21  interval_23_minus_9_days    2008.0
22  interval_24_minus_9_days    2183.0
23  interval_25_minus_9_days    2197.0
24  interval_26_minus_9_days    2386.0
25  interval_27_minus_9_days    2750.0
26  interval_28_minus_9_days    2764.0
27  interval_29_minus_9_days    2932.0
28  interval_30_minus_9_days    2946.0
29  interval_31_minus_9_days    3202.0
30  interval_32_minus_9_days    3216.0
31  interval_33_minus_9_days    3385.0
32  interval_34_minus_9_days    3401.0

In [238]:
rtx_merged_data = update_rtx_doses(rtx_merged_data, base_dose=9, target_dose=10)

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\656049958.py:55: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  return result.groupby("RKD.ID", group_keys=False).apply(_per_patient)

In [239]:
rtx_merged_data = update_rtx_doses(rtx_merged_data, base_dose=9, target_dose=11)

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\656049958.py:55: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  return result.groupby("RKD.ID", group_keys=False).apply(_per_patient)

In [240]:
rtx_merged_data = update_rtx_doses(rtx_merged_data, base_dose=9, target_dose=12)

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\656049958.py:55: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  return result.groupby("RKD.ID", group_keys=False).apply(_per_patient)

In [241]:
import numpy as np
import pandas as pd

def min_interval_table(df, max_dose=34):
    x = df.copy()

    # Parse dose dates
    for n in range(1, max_dose + 1):
        col = f"rtx_{n}_dose_date"
        if col in x.columns:
            x[col] = pd.to_datetime(x[col], errors="coerce", dayfirst=True)

    # Use earliest dose dates per patient (avoids repeated visit rows)
    per_patient = (
        x.groupby("RKD.ID")[[c for c in x.columns if c.startswith("rtx_") and c.endswith("_dose_date")]]
         .min()
         .reset_index()
    )

    # Build min interval per dose (global min across dataset)
    rows = []
    d1 = "rtx_10_dose_date"

    for n in range(2, max_dose + 1):
        dn = f"rtx_{n}_dose_date"
        if dn not in per_patient.columns:
            continue

        interval_series = (per_patient[dn] - per_patient[d1]).dt.days

        rows.append({
            "interval_name": f"interval_{n}_minus_10_days",
            "min_days": interval_series.min(skipna=True)
        })

    return pd.DataFrame(rows)


min_intervals_table = min_interval_table(rtx_merged_data, max_dose=34)
min_intervals_table

                interval_name  min_days
0    interval_2_minus_10_days   -3896.0
1    interval_3_minus_10_days   -2774.0
2    interval_4_minus_10_days   -2816.0
3    interval_5_minus_10_days   -2211.0
4    interval_6_minus_10_days   -2009.0
5    interval_7_minus_10_days   -1813.0
6    interval_8_minus_10_days   -1095.0
7    interval_9_minus_10_days    -508.0
8   interval_10_minus_10_days       0.0
9   interval_11_minus_10_days       7.0
10  interval_12_minus_10_days      14.0
11  interval_13_minus_10_days      21.0
12  interval_14_minus_10_days     182.0
13  interval_15_minus_10_days     396.0
14  interval_16_minus_10_days     897.0
15  interval_17_minus_10_days    1080.0
16  interval_18_minus_10_days    1256.0
17  interval_19_minus_10_days    1423.0
18  interval_20_minus_10_days    1766.0
19  interval_21_minus_10_days    2094.0
20  interval_22_minus_10_days       NaN
21  interval_23_minus_10_days       NaN
22  interval_24_minus_10_days       NaN
23  interval_25_minus_10_days       NaN
24  interval_26_minus_10_days       NaN
25  interval_27_minus_10_days       NaN
26  interval_28_minus_10_days       NaN
27  interval_29_minus_10_days       NaN
28  interval_30_minus_10_days       NaN
29  interval_31_minus_10_days       NaN
30  interval_32_minus_10_days       NaN
31  interval_33_minus_10_days       NaN
32  interval_34_minus_10_days       NaN

In [242]:
rtx_merged_data = update_rtx_doses(rtx_merged_data, base_dose=10, target_dose=11)

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\656049958.py:55: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  return result.groupby("RKD.ID", group_keys=False).apply(_per_patient)

In [243]:
rtx_merged_data = update_rtx_doses(rtx_merged_data, base_dose=10, target_dose=12)

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\656049958.py:55: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  return result.groupby("RKD.ID", group_keys=False).apply(_per_patient)

In [244]:
rtx_merged_data = update_rtx_doses(rtx_merged_data, base_dose=10, target_dose=13)

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\656049958.py:55: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  return result.groupby("RKD.ID", group_keys=False).apply(_per_patient)

In [245]:
import numpy as np
import pandas as pd

def min_interval_table(df, max_dose=34):
    x = df.copy()

    # Parse dose dates
    for n in range(1, max_dose + 1):
        col = f"rtx_{n}_dose_date"
        if col in x.columns:
            x[col] = pd.to_datetime(x[col], errors="coerce", dayfirst=True)

    # Use earliest dose dates per patient (avoids repeated visit rows)
    per_patient = (
        x.groupby("RKD.ID")[[c for c in x.columns if c.startswith("rtx_") and c.endswith("_dose_date")]]
         .min()
         .reset_index()
    )

    # Build min interval per dose (global min across dataset)
    rows = []
    d1 = "rtx_11_dose_date"

    for n in range(2, max_dose + 1):
        dn = f"rtx_{n}_dose_date"
        if dn not in per_patient.columns:
            continue

        interval_series = (per_patient[dn] - per_patient[d1]).dt.days

        rows.append({
            "interval_name": f"interval_{n}_minus_11_days",
            "min_days": interval_series.min(skipna=True)
        })

    return pd.DataFrame(rows)


min_intervals_table = min_interval_table(rtx_merged_data, max_dose=34)
min_intervals_table

                interval_name  min_days
0    interval_2_minus_11_days   -4465.0
1    interval_3_minus_11_days   -2977.0
2    interval_4_minus_11_days   -3385.0
3    interval_5_minus_11_days   -2415.0
4    interval_6_minus_11_days   -2549.0
5    interval_7_minus_11_days   -2200.0
6    interval_8_minus_11_days   -1638.0
7    interval_9_minus_11_days   -1456.0
8   interval_10_minus_11_days   -1337.0
9   interval_11_minus_11_days       0.0
10  interval_12_minus_11_days       7.0
11  interval_13_minus_11_days      14.0
12  interval_14_minus_11_days      21.0
13  interval_15_minus_11_days     168.0
14  interval_16_minus_11_days     189.0
15  interval_17_minus_11_days     532.0
16  interval_18_minus_11_days     721.0
17  interval_19_minus_11_days     844.0
18  interval_20_minus_11_days     971.0
19  interval_21_minus_11_days    1218.0
20  interval_22_minus_11_days    1848.0
21  interval_23_minus_11_days    1862.0
22  interval_24_minus_11_days    2037.0
23  interval_25_minus_11_days    2051.0
24  interval_26_minus_11_days    2240.0
25  interval_27_minus_11_days    2604.0
26  interval_28_minus_11_days    2618.0
27  interval_29_minus_11_days    2786.0
28  interval_30_minus_11_days    2800.0
29  interval_31_minus_11_days    3056.0
30  interval_32_minus_11_days    3070.0
31  interval_33_minus_11_days    3239.0
32  interval_34_minus_11_days    3255.0

In [246]:
rtx_merged_data = update_rtx_doses(rtx_merged_data, base_dose=11, target_dose=12)

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\656049958.py:55: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  return result.groupby("RKD.ID", group_keys=False).apply(_per_patient)

In [247]:
rtx_merged_data = update_rtx_doses(rtx_merged_data, base_dose=11, target_dose=13)

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\656049958.py:55: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  return result.groupby("RKD.ID", group_keys=False).apply(_per_patient)

In [248]:
rtx_merged_data = update_rtx_doses(rtx_merged_data, base_dose=11, target_dose=14)

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\656049958.py:55: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  return result.groupby("RKD.ID", group_keys=False).apply(_per_patient)

In [249]:
import numpy as np
import pandas as pd

def min_interval_table(df, max_dose=34):
    x = df.copy()

    # Parse dose dates
    for n in range(1, max_dose + 1):
        col = f"rtx_{n}_dose_date"
        if col in x.columns:
            x[col] = pd.to_datetime(x[col], errors="coerce", dayfirst=True)

    # Use earliest dose dates per patient (avoids repeated visit rows)
    per_patient = (
        x.groupby("RKD.ID")[[c for c in x.columns if c.startswith("rtx_") and c.endswith("_dose_date")]]
         .min()
         .reset_index()
    )

    # Build min interval per dose (global min across dataset)
    rows = []
    d1 = "rtx_12_dose_date"

    for n in range(2, max_dose + 1):
        dn = f"rtx_{n}_dose_date"
        if dn not in per_patient.columns:
            continue

        interval_series = (per_patient[dn] - per_patient[d1]).dt.days

        rows.append({
            "interval_name": f"interval_{n}_minus_12_days",
            "min_days": interval_series.min(skipna=True)
        })

    return pd.DataFrame(rows)


min_intervals_table = min_interval_table(rtx_merged_data, max_dose=34)
min_intervals_table

                interval_name  min_days
0    interval_2_minus_12_days   -3683.0
1    interval_3_minus_12_days   -3467.0
2    interval_4_minus_12_days   -2764.0
3    interval_5_minus_12_days   -2904.0
4    interval_6_minus_12_days   -2542.0
5    interval_7_minus_12_days   -2414.0
6    interval_8_minus_12_days   -1938.0
7    interval_9_minus_12_days   -1756.0
8   interval_10_minus_12_days   -1637.0
9   interval_11_minus_12_days    -916.0
10  interval_12_minus_12_days       0.0
11  interval_13_minus_12_days      18.0
12  interval_14_minus_12_days     203.0
13  interval_15_minus_12_days     439.0
14  interval_16_minus_12_days     446.0
15  interval_17_minus_12_days     629.0
16  interval_18_minus_12_days     805.0
17  interval_19_minus_12_days     972.0
18  interval_20_minus_12_days    1315.0
19  interval_21_minus_12_days    1643.0
20  interval_22_minus_12_days       NaN
21  interval_23_minus_12_days       NaN
22  interval_24_minus_12_days       NaN
23  interval_25_minus_12_days       NaN
24  interval_26_minus_12_days       NaN
25  interval_27_minus_12_days       NaN
26  interval_28_minus_12_days       NaN
27  interval_29_minus_12_days       NaN
28  interval_30_minus_12_days       NaN
29  interval_31_minus_12_days       NaN
30  interval_32_minus_12_days       NaN
31  interval_33_minus_12_days       NaN
32  interval_34_minus_12_days       NaN

In [250]:
rtx_merged_data = update_rtx_doses(rtx_merged_data, base_dose=12, target_dose=13)

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\656049958.py:55: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  return result.groupby("RKD.ID", group_keys=False).apply(_per_patient)

In [251]:
import numpy as np
import pandas as pd

def min_interval_table(df, max_dose=34):
    x = df.copy()

    # Parse dose dates
    for n in range(1, max_dose + 1):
        col = f"rtx_{n}_dose_date"
        if col in x.columns:
            x[col] = pd.to_datetime(x[col], errors="coerce", dayfirst=True)

    # Use earliest dose dates per patient (avoids repeated visit rows)
    per_patient = (
        x.groupby("RKD.ID")[[c for c in x.columns if c.startswith("rtx_") and c.endswith("_dose_date")]]
         .min()
         .reset_index()
    )

    # Build min interval per dose (global min across dataset)
    rows = []
    d1 = "rtx_13_dose_date"

    for n in range(2, max_dose + 1):
        dn = f"rtx_{n}_dose_date"
        if dn not in per_patient.columns:
            continue

        interval_series = (per_patient[dn] - per_patient[d1]).dt.days

        rows.append({
            "interval_name": f"interval_{n}_minus_13_days",
            "min_days": interval_series.min(skipna=True)
        })

    return pd.DataFrame(rows)


min_intervals_table = min_interval_table(rtx_merged_data, max_dose=34)
min_intervals_table

                interval_name  min_days
0    interval_2_minus_13_days   -4645.0
1    interval_3_minus_13_days   -3817.0
2    interval_4_minus_13_days   -3565.0
3    interval_5_minus_13_days   -3254.0
4    interval_6_minus_13_days   -2892.0
5    interval_7_minus_13_days   -2604.0
6    interval_8_minus_13_days   -2121.0
7    interval_9_minus_13_days   -1939.0
8   interval_10_minus_13_days   -1820.0
9   interval_11_minus_13_days    -995.0
10  interval_12_minus_13_days    -813.0
11  interval_13_minus_13_days       0.0
12  interval_14_minus_13_days       8.0
13  interval_15_minus_13_days      15.0
14  interval_16_minus_13_days      22.0
15  interval_17_minus_13_days     205.0
16  interval_18_minus_13_days     381.0
17  interval_19_minus_13_days     548.0
18  interval_20_minus_13_days     891.0
19  interval_21_minus_13_days    1219.0
20  interval_22_minus_13_days       NaN
21  interval_23_minus_13_days       NaN
22  interval_24_minus_13_days       NaN
23  interval_25_minus_13_days       NaN
24  interval_26_minus_13_days       NaN
25  interval_27_minus_13_days       NaN
26  interval_28_minus_13_days       NaN
27  interval_29_minus_13_days       NaN
28  interval_30_minus_13_days       NaN
29  interval_31_minus_13_days       NaN
30  interval_32_minus_13_days       NaN
31  interval_33_minus_13_days       NaN
32  interval_34_minus_13_days       NaN

In [252]:
rtx_merged_data = update_rtx_doses(rtx_merged_data, base_dose=13, target_dose=14)

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\656049958.py:55: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  return result.groupby("RKD.ID", group_keys=False).apply(_per_patient)

In [253]:
rtx_merged_data = update_rtx_doses(rtx_merged_data, base_dose=13, target_dose=15)

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\656049958.py:55: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  return result.groupby("RKD.ID", group_keys=False).apply(_per_patient)

In [254]:
rtx_merged_data = update_rtx_doses(rtx_merged_data, base_dose=13, target_dose=16)

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\656049958.py:55: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  return result.groupby("RKD.ID", group_keys=False).apply(_per_patient)

In [255]:
import numpy as np
import pandas as pd

def min_interval_table(df, max_dose=34):
    x = df.copy()

    # Parse dose dates
    for n in range(1, max_dose + 1):
        col = f"rtx_{n}_dose_date"
        if col in x.columns:
            x[col] = pd.to_datetime(x[col], errors="coerce", dayfirst=True)

    # Use earliest dose dates per patient (avoids repeated visit rows)
    per_patient = (
        x.groupby("RKD.ID")[[c for c in x.columns if c.startswith("rtx_") and c.endswith("_dose_date")]]
         .min()
         .reset_index()
    )

    # Build min interval per dose (global min across dataset)
    rows = []
    d1 = "rtx_15_dose_date"

    for n in range(2, max_dose + 1):
        dn = f"rtx_{n}_dose_date"
        if dn not in per_patient.columns:
            continue

        interval_series = (per_patient[dn] - per_patient[d1]).dt.days

        rows.append({
            "interval_name": f"interval_{n}_minus_15_days",
            "min_days": interval_series.min(skipna=True)
        })

    return pd.DataFrame(rows)


min_intervals_table = min_interval_table(rtx_merged_data, max_dose=34)
min_intervals_table

                interval_name  min_days
0    interval_2_minus_15_days   -4395.0
1    interval_3_minus_15_days   -4195.0
2    interval_4_minus_15_days   -3878.0
3    interval_5_minus_15_days   -3773.0
4    interval_6_minus_15_days   -3647.0
5    interval_7_minus_15_days   -3528.0
6    interval_8_minus_15_days   -3052.0
7    interval_9_minus_15_days   -2870.0
8   interval_10_minus_15_days   -2751.0
9   interval_11_minus_15_days   -1414.0
10  interval_12_minus_15_days   -1114.0
11  interval_13_minus_15_days    -931.0
12  interval_14_minus_15_days    -749.0
13  interval_15_minus_15_days       0.0
14  interval_16_minus_15_days      13.0
15  interval_17_minus_15_days     196.0
16  interval_18_minus_15_days     553.0
17  interval_19_minus_15_days     676.0
18  interval_20_minus_15_days     803.0
19  interval_21_minus_15_days    1050.0
20  interval_22_minus_15_days    1680.0
21  interval_23_minus_15_days    1694.0
22  interval_24_minus_15_days    1869.0
23  interval_25_minus_15_days    1883.0
24  interval_26_minus_15_days    2072.0
25  interval_27_minus_15_days    2436.0
26  interval_28_minus_15_days    2450.0
27  interval_29_minus_15_days    2618.0
28  interval_30_minus_15_days    2632.0
29  interval_31_minus_15_days    2888.0
30  interval_32_minus_15_days    2902.0
31  interval_33_minus_15_days    3071.0
32  interval_34_minus_15_days    3087.0

In [256]:
rtx_merged_data = update_rtx_doses(rtx_merged_data, base_dose=15, target_dose=16)

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\656049958.py:55: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  return result.groupby("RKD.ID", group_keys=False).apply(_per_patient)

In [257]:
import numpy as np
import pandas as pd

def min_interval_table(df, max_dose=34):
    x = df.copy()

    # Parse dose dates
    for n in range(1, max_dose + 1):
        col = f"rtx_{n}_dose_date"
        if col in x.columns:
            x[col] = pd.to_datetime(x[col], errors="coerce", dayfirst=True)

    # Use earliest dose dates per patient (avoids repeated visit rows)
    per_patient = (
        x.groupby("RKD.ID")[[c for c in x.columns if c.startswith("rtx_") and c.endswith("_dose_date")]]
         .min()
         .reset_index()
    )

    # Build min interval per dose (global min across dataset)
    rows = []
    d1 = "rtx_16_dose_date"

    for n in range(2, max_dose + 1):
        dn = f"rtx_{n}_dose_date"
        if dn not in per_patient.columns:
            continue

        interval_series = (per_patient[dn] - per_patient[d1]).dt.days

        rows.append({
            "interval_name": f"interval_{n}_minus_16_days",
            "min_days": interval_series.min(skipna=True)
        })

    return pd.DataFrame(rows)


min_intervals_table = min_interval_table(rtx_merged_data, max_dose=34)
min_intervals_table

                interval_name  min_days
0    interval_2_minus_16_days       NaN
1    interval_3_minus_16_days   -4370.0
2    interval_4_minus_16_days       NaN
3    interval_5_minus_16_days   -3807.0
4    interval_6_minus_16_days   -3445.0
5    interval_7_minus_16_days   -3415.0
6    interval_8_minus_16_days   -2316.0
7    interval_9_minus_16_days       NaN
8   interval_10_minus_16_days   -2017.0
9   interval_11_minus_16_days   -1800.0
10  interval_12_minus_16_days   -1503.0
11  interval_13_minus_16_days   -1317.0
12  interval_14_minus_16_days   -1253.0
13  interval_15_minus_16_days    -812.0
14  interval_16_minus_16_days       0.0
15  interval_17_minus_16_days       NaN
16  interval_18_minus_16_days       NaN
17  interval_19_minus_16_days       NaN
18  interval_20_minus_16_days       NaN
19  interval_21_minus_16_days       NaN
20  interval_22_minus_16_days       NaN
21  interval_23_minus_16_days       NaN
22  interval_24_minus_16_days       NaN
23  interval_25_minus_16_days       NaN
24  interval_26_minus_16_days       NaN
25  interval_27_minus_16_days       NaN
26  interval_28_minus_16_days       NaN
27  interval_29_minus_16_days       NaN
28  interval_30_minus_16_days       NaN
29  interval_31_minus_16_days       NaN
30  interval_32_minus_16_days       NaN
31  interval_33_minus_16_days       NaN
32  interval_34_minus_16_days       NaN

In [258]:
import numpy as np
import pandas as pd

def min_interval_table(df, max_dose=34):
    x = df.copy()

    # Parse dose dates
    for n in range(1, max_dose + 1):
        col = f"rtx_{n}_dose_date"
        if col in x.columns:
            x[col] = pd.to_datetime(x[col], errors="coerce", dayfirst=True)

    # Use earliest dose dates per patient (avoids repeated visit rows)
    per_patient = (
        x.groupby("RKD.ID")[[c for c in x.columns if c.startswith("rtx_") and c.endswith("_dose_date")]]
         .min()
         .reset_index()
    )

    # Build min interval per dose (global min across dataset)
    rows = []
    d1 = "rtx_17_dose_date"

    for n in range(2, max_dose + 1):
        dn = f"rtx_{n}_dose_date"
        if dn not in per_patient.columns:
            continue

        interval_series = (per_patient[dn] - per_patient[d1]).dt.days

        rows.append({
            "interval_name": f"interval_{n}_minus_17_days",
            "min_days": interval_series.min(skipna=True)
        })

    return pd.DataFrame(rows)


min_intervals_table = min_interval_table(rtx_merged_data, max_dose=34)
min_intervals_table

                interval_name  min_days
0    interval_2_minus_17_days   -4263.0
1    interval_3_minus_17_days   -4200.0
2    interval_4_minus_17_days   -4074.0
3    interval_5_minus_17_days   -3969.0
4    interval_6_minus_17_days   -3843.0
5    interval_7_minus_17_days   -3724.0
6    interval_8_minus_17_days   -3248.0
7    interval_9_minus_17_days   -3066.0
8   interval_10_minus_17_days   -2947.0
9   interval_11_minus_17_days   -1610.0
10  interval_12_minus_17_days   -1310.0
11  interval_13_minus_17_days   -1127.0
12  interval_14_minus_17_days    -945.0
13  interval_15_minus_17_days    -343.0
14  interval_16_minus_17_days       NaN
15  interval_17_minus_17_days       0.0
16  interval_18_minus_17_days     176.0
17  interval_19_minus_17_days     312.0
18  interval_20_minus_17_days     439.0
19  interval_21_minus_17_days     686.0
20  interval_22_minus_17_days    1316.0
21  interval_23_minus_17_days    1330.0
22  interval_24_minus_17_days    1505.0
23  interval_25_minus_17_days    1519.0
24  interval_26_minus_17_days    1708.0
25  interval_27_minus_17_days    2072.0
26  interval_28_minus_17_days    2086.0
27  interval_29_minus_17_days    2254.0
28  interval_30_minus_17_days    2268.0
29  interval_31_minus_17_days    2524.0
30  interval_32_minus_17_days    2538.0
31  interval_33_minus_17_days    2707.0
32  interval_34_minus_17_days    2723.0

In [259]:
import numpy as np
import pandas as pd

def min_interval_table(df, max_dose=34):
    x = df.copy()

    # Parse dose dates
    for n in range(1, max_dose + 1):
        col = f"rtx_{n}_dose_date"
        if col in x.columns:
            x[col] = pd.to_datetime(x[col], errors="coerce", dayfirst=True)

    # Use earliest dose dates per patient (avoids repeated visit rows)
    per_patient = (
        x.groupby("RKD.ID")[[c for c in x.columns if c.startswith("rtx_") and c.endswith("_dose_date")]]
         .min()
         .reset_index()
    )

    # Build min interval per dose (global min across dataset)
    rows = []
    d1 = "rtx_18_dose_date"

    for n in range(2, max_dose + 1):
        dn = f"rtx_{n}_dose_date"
        if dn not in per_patient.columns:
            continue

        interval_series = (per_patient[dn] - per_patient[d1]).dt.days

        rows.append({
            "interval_name": f"interval_{n}_minus_18_days",
            "min_days": interval_series.min(skipna=True)
        })

    return pd.DataFrame(rows)


min_intervals_table = min_interval_table(rtx_merged_data, max_dose=34)
min_intervals_table

                interval_name  min_days
0    interval_2_minus_18_days       NaN
1    interval_3_minus_18_days   -3123.0
2    interval_4_minus_18_days       NaN
3    interval_5_minus_18_days   -2471.0
4    interval_6_minus_18_days       NaN
5    interval_7_minus_18_days   -1823.0
6    interval_8_minus_18_days   -1711.0
7    interval_9_minus_18_days   -1521.0
8   interval_10_minus_18_days   -1256.0
9   interval_11_minus_18_days   -1077.0
10  interval_12_minus_18_days    -805.0
11  interval_13_minus_18_days    -359.0
12  interval_14_minus_18_days       NaN
13  interval_15_minus_18_days    -532.0
14  interval_16_minus_18_days       NaN
15  interval_17_minus_18_days    -189.0
16  interval_18_minus_18_days       0.0
17  interval_19_minus_18_days     123.0
18  interval_20_minus_18_days     250.0
19  interval_21_minus_18_days     497.0
20  interval_22_minus_18_days    1127.0
21  interval_23_minus_18_days    1141.0
22  interval_24_minus_18_days    1316.0
23  interval_25_minus_18_days    1330.0
24  interval_26_minus_18_days    1519.0
25  interval_27_minus_18_days    1883.0
26  interval_28_minus_18_days    1897.0
27  interval_29_minus_18_days    2065.0
28  interval_30_minus_18_days    2079.0
29  interval_31_minus_18_days    2335.0
30  interval_32_minus_18_days    2349.0
31  interval_33_minus_18_days    2518.0
32  interval_34_minus_18_days    2534.0

In [260]:
import numpy as np
import pandas as pd

def min_interval_table(df, max_dose=34):
    x = df.copy()

    # Parse dose dates
    for n in range(1, max_dose + 1):
        col = f"rtx_{n}_dose_date"
        if col in x.columns:
            x[col] = pd.to_datetime(x[col], errors="coerce", dayfirst=True)

    # Use earliest dose dates per patient (avoids repeated visit rows)
    per_patient = (
        x.groupby("RKD.ID")[[c for c in x.columns if c.startswith("rtx_") and c.endswith("_dose_date")]]
         .min()
         .reset_index()
    )

    # Build min interval per dose (global min across dataset)
    rows = []
    d1 = "rtx_19_dose_date"

    for n in range(2, max_dose + 1):
        dn = f"rtx_{n}_dose_date"
        if dn not in per_patient.columns:
            continue

        interval_series = (per_patient[dn] - per_patient[d1]).dt.days

        rows.append({
            "interval_name": f"interval_{n}_minus_19_days",
            "min_days": interval_series.min(skipna=True)
        })

    return pd.DataFrame(rows)


min_intervals_table = min_interval_table(rtx_merged_data, max_dose=34)
min_intervals_table

                interval_name  min_days
0    interval_2_minus_19_days       NaN
1    interval_3_minus_19_days   -3290.0
2    interval_4_minus_19_days       NaN
3    interval_5_minus_19_days   -2638.0
4    interval_6_minus_19_days       NaN
5    interval_7_minus_19_days   -1990.0
6    interval_8_minus_19_days   -1878.0
7    interval_9_minus_19_days   -1688.0
8   interval_10_minus_19_days   -1423.0
9   interval_11_minus_19_days   -1244.0
10  interval_12_minus_19_days    -972.0
11  interval_13_minus_19_days    -526.0
12  interval_14_minus_19_days       NaN
13  interval_15_minus_19_days    -655.0
14  interval_16_minus_19_days       NaN
15  interval_17_minus_19_days    -343.0
16  interval_18_minus_19_days    -167.0
17  interval_19_minus_19_days       0.0
18  interval_20_minus_19_days     127.0
19  interval_21_minus_19_days     374.0
20  interval_22_minus_19_days    1004.0
21  interval_23_minus_19_days    1018.0
22  interval_24_minus_19_days    1193.0
23  interval_25_minus_19_days    1207.0
24  interval_26_minus_19_days    1396.0
25  interval_27_minus_19_days    1760.0
26  interval_28_minus_19_days    1774.0
27  interval_29_minus_19_days    1942.0
28  interval_30_minus_19_days    1956.0
29  interval_31_minus_19_days    2212.0
30  interval_32_minus_19_days    2226.0
31  interval_33_minus_19_days    2395.0
32  interval_34_minus_19_days    2411.0

In [261]:
import numpy as np
import pandas as pd

def min_interval_table(df, max_dose=34):
    x = df.copy()

    # Parse dose dates
    for n in range(1, max_dose + 1):
        col = f"rtx_{n}_dose_date"
        if col in x.columns:
            x[col] = pd.to_datetime(x[col], errors="coerce", dayfirst=True)

    # Use earliest dose dates per patient (avoids repeated visit rows)
    per_patient = (
        x.groupby("RKD.ID")[[c for c in x.columns if c.startswith("rtx_") and c.endswith("_dose_date")]]
         .min()
         .reset_index()
    )

    # Build min interval per dose (global min across dataset)
    rows = []
    d1 = "rtx_20_dose_date"

    for n in range(2, max_dose + 1):
        dn = f"rtx_{n}_dose_date"
        if dn not in per_patient.columns:
            continue

        interval_series = (per_patient[dn] - per_patient[d1]).dt.days

        rows.append({
            "interval_name": f"interval_{n}_minus_20_days",
            "min_days": interval_series.min(skipna=True)
        })

    return pd.DataFrame(rows)


min_intervals_table = min_interval_table(rtx_merged_data, max_dose=34)
min_intervals_table

                interval_name  min_days
0    interval_2_minus_20_days       NaN
1    interval_3_minus_20_days   -3633.0
2    interval_4_minus_20_days       NaN
3    interval_5_minus_20_days   -2981.0
4    interval_6_minus_20_days       NaN
5    interval_7_minus_20_days   -2333.0
6    interval_8_minus_20_days   -2221.0
7    interval_9_minus_20_days   -2031.0
8   interval_10_minus_20_days   -1766.0
9   interval_11_minus_20_days   -1587.0
10  interval_12_minus_20_days   -1315.0
11  interval_13_minus_20_days    -869.0
12  interval_14_minus_20_days       NaN
13  interval_15_minus_20_days    -782.0
14  interval_16_minus_20_days       NaN
15  interval_17_minus_20_days    -686.0
16  interval_18_minus_20_days    -510.0
17  interval_19_minus_20_days    -343.0
18  interval_20_minus_20_days       0.0
19  interval_21_minus_20_days     247.0
20  interval_22_minus_20_days     877.0
21  interval_23_minus_20_days     891.0
22  interval_24_minus_20_days    1066.0
23  interval_25_minus_20_days    1080.0
24  interval_26_minus_20_days    1269.0
25  interval_27_minus_20_days    1633.0
26  interval_28_minus_20_days    1647.0
27  interval_29_minus_20_days    1815.0
28  interval_30_minus_20_days    1829.0
29  interval_31_minus_20_days    2085.0
30  interval_32_minus_20_days    2099.0
31  interval_33_minus_20_days    2268.0
32  interval_34_minus_20_days    2284.0

In [262]:
import numpy as np
import pandas as pd

def min_interval_table(df, max_dose=34):
    x = df.copy()

    # Parse dose dates
    for n in range(1, max_dose + 1):
        col = f"rtx_{n}_dose_date"
        if col in x.columns:
            x[col] = pd.to_datetime(x[col], errors="coerce", dayfirst=True)

    # Use earliest dose dates per patient (avoids repeated visit rows)
    per_patient = (
        x.groupby("RKD.ID")[[c for c in x.columns if c.startswith("rtx_") and c.endswith("_dose_date")]]
         .min()
         .reset_index()
    )

    # Build min interval per dose (global min across dataset)
    rows = []
    d1 = "rtx_21_dose_date"

    for n in range(2, max_dose + 1):
        dn = f"rtx_{n}_dose_date"
        if dn not in per_patient.columns:
            continue

        interval_series = (per_patient[dn] - per_patient[d1]).dt.days

        rows.append({
            "interval_name": f"interval_{n}_minus_21_days",
            "min_days": interval_series.min(skipna=True)
        })

    return pd.DataFrame(rows)


min_intervals_table = min_interval_table(rtx_merged_data, max_dose=34)
min_intervals_table

                interval_name  min_days
0    interval_2_minus_21_days       NaN
1    interval_3_minus_21_days   -3961.0
2    interval_4_minus_21_days       NaN
3    interval_5_minus_21_days   -3309.0
4    interval_6_minus_21_days       NaN
5    interval_7_minus_21_days   -2661.0
6    interval_8_minus_21_days   -2549.0
7    interval_9_minus_21_days   -2359.0
8   interval_10_minus_21_days   -2094.0
9   interval_11_minus_21_days   -1915.0
10  interval_12_minus_21_days   -1643.0
11  interval_13_minus_21_days   -1197.0
12  interval_14_minus_21_days       NaN
13  interval_15_minus_21_days   -1029.0
14  interval_16_minus_21_days       NaN
15  interval_17_minus_21_days   -1014.0
16  interval_18_minus_21_days    -838.0
17  interval_19_minus_21_days    -671.0
18  interval_20_minus_21_days    -328.0
19  interval_21_minus_21_days       0.0
20  interval_22_minus_21_days     630.0
21  interval_23_minus_21_days     644.0
22  interval_24_minus_21_days     819.0
23  interval_25_minus_21_days     833.0
24  interval_26_minus_21_days    1022.0
25  interval_27_minus_21_days    1386.0
26  interval_28_minus_21_days    1400.0
27  interval_29_minus_21_days    1568.0
28  interval_30_minus_21_days    1582.0
29  interval_31_minus_21_days    1838.0
30  interval_32_minus_21_days    1852.0
31  interval_33_minus_21_days    2021.0
32  interval_34_minus_21_days    2037.0

In [263]:
import numpy as np
import pandas as pd

def min_interval_table(df, max_dose=34):
    x = df.copy()

    # Parse dose dates
    for n in range(1, max_dose + 1):
        col = f"rtx_{n}_dose_date"
        if col in x.columns:
            x[col] = pd.to_datetime(x[col], errors="coerce", dayfirst=True)

    # Use earliest dose dates per patient (avoids repeated visit rows)
    per_patient = (
        x.groupby("RKD.ID")[[c for c in x.columns if c.startswith("rtx_") and c.endswith("_dose_date")]]
         .min()
         .reset_index()
    )

    # Build min interval per dose (global min across dataset)
    rows = []
    d1 = "rtx_22_dose_date"

    for n in range(2, max_dose + 1):
        dn = f"rtx_{n}_dose_date"
        if dn not in per_patient.columns:
            continue

        interval_series = (per_patient[dn] - per_patient[d1]).dt.days

        rows.append({
            "interval_name": f"interval_{n}_minus_22_days",
            "min_days": interval_series.min(skipna=True)
        })

    return pd.DataFrame(rows)


min_intervals_table = min_interval_table(rtx_merged_data, max_dose=34)
min_intervals_table

                interval_name  min_days
0    interval_2_minus_22_days       NaN
1    interval_3_minus_22_days       NaN
2    interval_4_minus_22_days       NaN
3    interval_5_minus_22_days   -2309.0
4    interval_6_minus_22_days       NaN
5    interval_7_minus_22_days   -2134.0
6    interval_8_minus_22_days       NaN
7    interval_9_minus_22_days   -1980.0
8   interval_10_minus_22_days       NaN
9   interval_11_minus_22_days   -1827.0
10  interval_12_minus_22_days       NaN
11  interval_13_minus_22_days       NaN
12  interval_14_minus_22_days       NaN
13  interval_15_minus_22_days   -1659.0
14  interval_16_minus_22_days       NaN
15  interval_17_minus_22_days   -1316.0
16  interval_18_minus_22_days   -1127.0
17  interval_19_minus_22_days   -1004.0
18  interval_20_minus_22_days    -877.0
19  interval_21_minus_22_days    -630.0
20  interval_22_minus_22_days       0.0
21  interval_23_minus_22_days      14.0
22  interval_24_minus_22_days     189.0
23  interval_25_minus_22_days     203.0
24  interval_26_minus_22_days     392.0
25  interval_27_minus_22_days     756.0
26  interval_28_minus_22_days     770.0
27  interval_29_minus_22_days     938.0
28  interval_30_minus_22_days     952.0
29  interval_31_minus_22_days    1208.0
30  interval_32_minus_22_days    1222.0
31  interval_33_minus_22_days    1391.0
32  interval_34_minus_22_days    1407.0

In [264]:
rtx_merged_data = update_rtx_doses(rtx_merged_data, base_dose=22, target_dose=23)

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\656049958.py:55: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  return result.groupby("RKD.ID", group_keys=False).apply(_per_patient)

In [265]:
import numpy as np
import pandas as pd

def min_interval_table(df, max_dose=34):
    x = df.copy()

    # Parse dose dates
    for n in range(1, max_dose + 1):
        col = f"rtx_{n}_dose_date"
        if col in x.columns:
            x[col] = pd.to_datetime(x[col], errors="coerce", dayfirst=True)

    # Use earliest dose dates per patient (avoids repeated visit rows)
    per_patient = (
        x.groupby("RKD.ID")[[c for c in x.columns if c.startswith("rtx_") and c.endswith("_dose_date")]]
         .min()
         .reset_index()
    )

    # Build min interval per dose (global min across dataset)
    rows = []
    d1 = "rtx_24_dose_date"

    for n in range(2, max_dose + 1):
        dn = f"rtx_{n}_dose_date"
        if dn not in per_patient.columns:
            continue

        interval_series = (per_patient[dn] - per_patient[d1]).dt.days

        rows.append({
            "interval_name": f"interval_{n}_minus_24_days",
            "min_days": interval_series.min(skipna=True)
        })

    return pd.DataFrame(rows)


min_intervals_table = min_interval_table(rtx_merged_data, max_dose=34)
min_intervals_table

                interval_name  min_days
0    interval_2_minus_24_days       NaN
1    interval_3_minus_24_days       NaN
2    interval_4_minus_24_days       NaN
3    interval_5_minus_24_days   -2498.0
4    interval_6_minus_24_days       NaN
5    interval_7_minus_24_days   -2323.0
6    interval_8_minus_24_days       NaN
7    interval_9_minus_24_days   -2169.0
8   interval_10_minus_24_days       NaN
9   interval_11_minus_24_days   -2016.0
10  interval_12_minus_24_days       NaN
11  interval_13_minus_24_days       NaN
12  interval_14_minus_24_days       NaN
13  interval_15_minus_24_days   -1848.0
14  interval_16_minus_24_days       NaN
15  interval_17_minus_24_days   -1505.0
16  interval_18_minus_24_days   -1316.0
17  interval_19_minus_24_days   -1193.0
18  interval_20_minus_24_days   -1066.0
19  interval_21_minus_24_days    -819.0
20  interval_22_minus_24_days    -175.0
21  interval_23_minus_24_days       NaN
22  interval_24_minus_24_days       0.0
23  interval_25_minus_24_days      14.0
24  interval_26_minus_24_days     203.0
25  interval_27_minus_24_days     567.0
26  interval_28_minus_24_days     581.0
27  interval_29_minus_24_days     749.0
28  interval_30_minus_24_days     763.0
29  interval_31_minus_24_days    1019.0
30  interval_32_minus_24_days    1033.0
31  interval_33_minus_24_days    1202.0
32  interval_34_minus_24_days    1218.0

In [266]:
rtx_merged_data = update_rtx_doses(rtx_merged_data, base_dose=24, target_dose=25)

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\656049958.py:55: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  return result.groupby("RKD.ID", group_keys=False).apply(_per_patient)

In [267]:
import numpy as np
import pandas as pd

def min_interval_table(df, max_dose=34):
    x = df.copy()

    # Parse dose dates
    for n in range(1, max_dose + 1):
        col = f"rtx_{n}_dose_date"
        if col in x.columns:
            x[col] = pd.to_datetime(x[col], errors="coerce", dayfirst=True)

    # Use earliest dose dates per patient (avoids repeated visit rows)
    per_patient = (
        x.groupby("RKD.ID")[[c for c in x.columns if c.startswith("rtx_") and c.endswith("_dose_date")]]
         .min()
         .reset_index()
    )

    # Build min interval per dose (global min across dataset)
    rows = []
    d1 = "rtx_27_dose_date"

    for n in range(2, max_dose + 1):
        dn = f"rtx_{n}_dose_date"
        if dn not in per_patient.columns:
            continue

        interval_series = (per_patient[dn] - per_patient[d1]).dt.days

        rows.append({
            "interval_name": f"interval_{n}_minus_27_days",
            "min_days": interval_series.min(skipna=True)
        })

    return pd.DataFrame(rows)


min_intervals_table = min_interval_table(rtx_merged_data, max_dose=34)
min_intervals_table

                interval_name  min_days
0    interval_2_minus_27_days       NaN
1    interval_3_minus_27_days       NaN
2    interval_4_minus_27_days       NaN
3    interval_5_minus_27_days   -3065.0
4    interval_6_minus_27_days       NaN
5    interval_7_minus_27_days   -2890.0
6    interval_8_minus_27_days       NaN
7    interval_9_minus_27_days   -2736.0
8   interval_10_minus_27_days       NaN
9   interval_11_minus_27_days   -2583.0
10  interval_12_minus_27_days       NaN
11  interval_13_minus_27_days       NaN
12  interval_14_minus_27_days       NaN
13  interval_15_minus_27_days   -2415.0
14  interval_16_minus_27_days       NaN
15  interval_17_minus_27_days   -2072.0
16  interval_18_minus_27_days   -1883.0
17  interval_19_minus_27_days   -1760.0
18  interval_20_minus_27_days   -1633.0
19  interval_21_minus_27_days   -1386.0
20  interval_22_minus_27_days    -742.0
21  interval_23_minus_27_days       NaN
22  interval_24_minus_27_days    -553.0
23  interval_25_minus_27_days       NaN
24  interval_26_minus_27_days    -364.0
25  interval_27_minus_27_days       0.0
26  interval_28_minus_27_days      14.0
27  interval_29_minus_27_days     182.0
28  interval_30_minus_27_days     196.0
29  interval_31_minus_27_days     452.0
30  interval_32_minus_27_days     466.0
31  interval_33_minus_27_days     635.0
32  interval_34_minus_27_days     651.0

In [268]:
rtx_merged_data = update_rtx_doses(rtx_merged_data, base_dose=27, target_dose=28)

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\656049958.py:55: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  return result.groupby("RKD.ID", group_keys=False).apply(_per_patient)

In [269]:
import numpy as np
import pandas as pd

def min_interval_table(df, max_dose=34):
    x = df.copy()

    # Parse dose dates
    for n in range(1, max_dose + 1):
        col = f"rtx_{n}_dose_date"
        if col in x.columns:
            x[col] = pd.to_datetime(x[col], errors="coerce", dayfirst=True)

    # Use earliest dose dates per patient (avoids repeated visit rows)
    per_patient = (
        x.groupby("RKD.ID")[[c for c in x.columns if c.startswith("rtx_") and c.endswith("_dose_date")]]
         .min()
         .reset_index()
    )

    # Build min interval per dose (global min across dataset)
    rows = []
    d1 = "rtx_29_dose_date"

    for n in range(2, max_dose + 1):
        dn = f"rtx_{n}_dose_date"
        if dn not in per_patient.columns:
            continue

        interval_series = (per_patient[dn] - per_patient[d1]).dt.days

        rows.append({
            "interval_name": f"interval_{n}_minus_29_days",
            "min_days": interval_series.min(skipna=True)
        })

    return pd.DataFrame(rows)


min_intervals_table = min_interval_table(rtx_merged_data, max_dose=34)
min_intervals_table

                interval_name  min_days
0    interval_2_minus_29_days       NaN
1    interval_3_minus_29_days       NaN
2    interval_4_minus_29_days       NaN
3    interval_5_minus_29_days   -3247.0
4    interval_6_minus_29_days       NaN
5    interval_7_minus_29_days   -3072.0
6    interval_8_minus_29_days       NaN
7    interval_9_minus_29_days   -2918.0
8   interval_10_minus_29_days       NaN
9   interval_11_minus_29_days   -2765.0
10  interval_12_minus_29_days       NaN
11  interval_13_minus_29_days       NaN
12  interval_14_minus_29_days       NaN
13  interval_15_minus_29_days   -2597.0
14  interval_16_minus_29_days       NaN
15  interval_17_minus_29_days   -2254.0
16  interval_18_minus_29_days   -2065.0
17  interval_19_minus_29_days   -1942.0
18  interval_20_minus_29_days   -1815.0
19  interval_21_minus_29_days   -1568.0
20  interval_22_minus_29_days    -924.0
21  interval_23_minus_29_days       NaN
22  interval_24_minus_29_days    -735.0
23  interval_25_minus_29_days       NaN
24  interval_26_minus_29_days    -546.0
25  interval_27_minus_29_days    -168.0
26  interval_28_minus_29_days       NaN
27  interval_29_minus_29_days       0.0
28  interval_30_minus_29_days      14.0
29  interval_31_minus_29_days     270.0
30  interval_32_minus_29_days     284.0
31  interval_33_minus_29_days     453.0
32  interval_34_minus_29_days     469.0

In [270]:
rtx_merged_data = update_rtx_doses(rtx_merged_data, base_dose=29, target_dose=30)

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\656049958.py:55: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  return result.groupby("RKD.ID", group_keys=False).apply(_per_patient)

In [271]:
import numpy as np
import pandas as pd

def min_interval_table(df, max_dose=34):
    x = df.copy()

    # Parse dose dates
    for n in range(1, max_dose + 1):
        col = f"rtx_{n}_dose_date"
        if col in x.columns:
            x[col] = pd.to_datetime(x[col], errors="coerce", dayfirst=True)

    # Use earliest dose dates per patient (avoids repeated visit rows)
    per_patient = (
        x.groupby("RKD.ID")[[c for c in x.columns if c.startswith("rtx_") and c.endswith("_dose_date")]]
         .min()
         .reset_index()
    )

    # Build min interval per dose (global min across dataset)
    rows = []
    d1 = "rtx_31_dose_date"

    for n in range(2, max_dose + 1):
        dn = f"rtx_{n}_dose_date"
        if dn not in per_patient.columns:
            continue

        interval_series = (per_patient[dn] - per_patient[d1]).dt.days

        rows.append({
            "interval_name": f"interval_{n}_minus_31_days",
            "min_days": interval_series.min(skipna=True)
        })

    return pd.DataFrame(rows)


min_intervals_table = min_interval_table(rtx_merged_data, max_dose=34)
min_intervals_table

                interval_name  min_days
0    interval_2_minus_31_days       NaN
1    interval_3_minus_31_days       NaN
2    interval_4_minus_31_days       NaN
3    interval_5_minus_31_days   -3517.0
4    interval_6_minus_31_days       NaN
5    interval_7_minus_31_days   -3342.0
6    interval_8_minus_31_days       NaN
7    interval_9_minus_31_days   -3188.0
8   interval_10_minus_31_days       NaN
9   interval_11_minus_31_days   -3035.0
10  interval_12_minus_31_days       NaN
11  interval_13_minus_31_days       NaN
12  interval_14_minus_31_days       NaN
13  interval_15_minus_31_days   -2867.0
14  interval_16_minus_31_days       NaN
15  interval_17_minus_31_days   -2524.0
16  interval_18_minus_31_days   -2335.0
17  interval_19_minus_31_days   -2212.0
18  interval_20_minus_31_days   -2085.0
19  interval_21_minus_31_days   -1838.0
20  interval_22_minus_31_days   -1194.0
21  interval_23_minus_31_days       NaN
22  interval_24_minus_31_days   -1005.0
23  interval_25_minus_31_days       NaN
24  interval_26_minus_31_days    -816.0
25  interval_27_minus_31_days    -438.0
26  interval_28_minus_31_days       NaN
27  interval_29_minus_31_days    -256.0
28  interval_30_minus_31_days       NaN
29  interval_31_minus_31_days       0.0
30  interval_32_minus_31_days      14.0
31  interval_33_minus_31_days     183.0
32  interval_34_minus_31_days     199.0

In [272]:
rtx_merged_data = update_rtx_doses(rtx_merged_data, base_dose=31, target_dose=32)

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\656049958.py:55: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  return result.groupby("RKD.ID", group_keys=False).apply(_per_patient)

In [273]:
import numpy as np
import pandas as pd

def min_interval_table(df, max_dose=34):
    x = df.copy()

    # Parse dose dates
    for n in range(1, max_dose + 1):
        col = f"rtx_{n}_dose_date"
        if col in x.columns:
            x[col] = pd.to_datetime(x[col], errors="coerce", dayfirst=True)

    # Use earliest dose dates per patient (avoids repeated visit rows)
    per_patient = (
        x.groupby("RKD.ID")[[c for c in x.columns if c.startswith("rtx_") and c.endswith("_dose_date")]]
         .min()
         .reset_index()
    )

    # Build min interval per dose (global min across dataset)
    rows = []
    d1 = "rtx_33_dose_date"

    for n in range(2, max_dose + 1):
        dn = f"rtx_{n}_dose_date"
        if dn not in per_patient.columns:
            continue

        interval_series = (per_patient[dn] - per_patient[d1]).dt.days

        rows.append({
            "interval_name": f"interval_{n}_minus_33_days",
            "min_days": interval_series.min(skipna=True)
        })

    return pd.DataFrame(rows)


min_intervals_table = min_interval_table(rtx_merged_data, max_dose=34)
min_intervals_table

                interval_name  min_days
0    interval_2_minus_33_days       NaN
1    interval_3_minus_33_days       NaN
2    interval_4_minus_33_days       NaN
3    interval_5_minus_33_days   -3700.0
4    interval_6_minus_33_days       NaN
5    interval_7_minus_33_days   -3525.0
6    interval_8_minus_33_days       NaN
7    interval_9_minus_33_days   -3371.0
8   interval_10_minus_33_days       NaN
9   interval_11_minus_33_days   -3218.0
10  interval_12_minus_33_days       NaN
11  interval_13_minus_33_days       NaN
12  interval_14_minus_33_days       NaN
13  interval_15_minus_33_days   -3050.0
14  interval_16_minus_33_days       NaN
15  interval_17_minus_33_days   -2707.0
16  interval_18_minus_33_days   -2518.0
17  interval_19_minus_33_days   -2395.0
18  interval_20_minus_33_days   -2268.0
19  interval_21_minus_33_days   -2021.0
20  interval_22_minus_33_days   -1377.0
21  interval_23_minus_33_days       NaN
22  interval_24_minus_33_days   -1188.0
23  interval_25_minus_33_days       NaN
24  interval_26_minus_33_days    -999.0
25  interval_27_minus_33_days    -621.0
26  interval_28_minus_33_days       NaN
27  interval_29_minus_33_days    -439.0
28  interval_30_minus_33_days       NaN
29  interval_31_minus_33_days    -169.0
30  interval_32_minus_33_days       NaN
31  interval_33_minus_33_days       0.0
32  interval_34_minus_33_days      16.0

In [274]:
rtx_merged_data = update_rtx_doses(rtx_merged_data, base_dose=33, target_dose=34)

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\656049958.py:55: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  return result.groupby("RKD.ID", group_keys=False).apply(_per_patient)

In [275]:
import numpy as np
import pandas as pd

def min_interval_table(df, max_dose=34):
    x = df.copy()

    # Parse dose dates
    for n in range(1, max_dose + 1):
        col = f"rtx_{n}_dose_date"
        if col in x.columns:
            x[col] = pd.to_datetime(x[col], errors="coerce", dayfirst=True)

    # Use earliest dose dates per patient (avoids repeated visit rows)
    per_patient = (
        x.groupby("RKD.ID")[[c for c in x.columns if c.startswith("rtx_") and c.endswith("_dose_date")]]
         .min()
         .reset_index()
    )

    # Build min interval per dose (global min across dataset)
    rows = []
    d1 = "rtx_34_dose_date"

    for n in range(2, max_dose + 1):
        dn = f"rtx_{n}_dose_date"
        if dn not in per_patient.columns:
            continue

        interval_series = (per_patient[dn] - per_patient[d1]).dt.days

        rows.append({
            "interval_name": f"interval_{n}_minus_34_days",
            "min_days": interval_series.min(skipna=True)
        })

    return pd.DataFrame(rows)


min_intervals_table = min_interval_table(rtx_merged_data, max_dose=34)
min_intervals_table

                interval_name  min_days
0    interval_2_minus_34_days       NaN
1    interval_3_minus_34_days       NaN
2    interval_4_minus_34_days       NaN
3    interval_5_minus_34_days       NaN
4    interval_6_minus_34_days       NaN
5    interval_7_minus_34_days       NaN
6    interval_8_minus_34_days       NaN
7    interval_9_minus_34_days       NaN
8   interval_10_minus_34_days       NaN
9   interval_11_minus_34_days       NaN
10  interval_12_minus_34_days       NaN
11  interval_13_minus_34_days       NaN
12  interval_14_minus_34_days       NaN
13  interval_15_minus_34_days       NaN
14  interval_16_minus_34_days       NaN
15  interval_17_minus_34_days       NaN
16  interval_18_minus_34_days       NaN
17  interval_19_minus_34_days       NaN
18  interval_20_minus_34_days       NaN
19  interval_21_minus_34_days       NaN
20  interval_22_minus_34_days       NaN
21  interval_23_minus_34_days       NaN
22  interval_24_minus_34_days       NaN
23  interval_25_minus_34_days       NaN
24  interval_26_minus_34_days       NaN
25  interval_27_minus_34_days       NaN
26  interval_28_minus_34_days       NaN
27  interval_29_minus_34_days       NaN
28  interval_30_minus_34_days       NaN
29  interval_31_minus_34_days       NaN
30  interval_32_minus_34_days       NaN
31  interval_33_minus_34_days       NaN
32  interval_34_minus_34_days       NaN

In [276]:
rtx_merged_data.shape

(8027, 637)

In [277]:
rtx_merged_data  = rtx_merged_data.dropna(axis=1, how='all')
rtx_merged_data.shape

(8027, 625)

In [278]:
## Rename column names:

In [279]:
rtx_merged_data.rename(
    columns={
        "rtx_24_dose_date": "rtx_23_dose_date",
        "rtx_24_dose_value": "rtx_23_dose_value"
    },
    inplace=True
)
rtx_merged_data.rename(
    columns={
        "rtx_26_dose_date": "rtx_24_dose_date",
        "rtx_26_dose_value": "rtx_24_dose_value"
    },
    inplace=True
)
rtx_merged_data.rename(
    columns={
        "rtx_27_dose_date": "rtx_25_dose_date",
        "rtx_27_dose_value": "rtx_25_dose_value"
    },
    inplace=True
)
rtx_merged_data.rename(
    columns={
        "rtx_29_dose_date": "rtx_26_dose_date",
        "rtx_29_dose_value": "rtx_26_dose_value"
    },
    inplace=True
)
rtx_merged_data.rename(
    columns={
        "rtx_31_dose_date": "rtx_27_dose_date",
        "rtx_31_dose_value": "rtx_27_dose_value"
    },
    inplace=True
)
rtx_merged_data.rename(
    columns={
        "rtx_33_dose_date": "rtx_28_dose_date",
        "rtx_33_dose_value": "rtx_28_dose_value"
    },
    inplace=True
)

In [280]:
## Reorder columns

In [281]:
def reorder_rtx_columns(df):

    cols = list(df.columns)

    # Identify dose numbers based ONLY on dose_date
    dose_numbers = sorted(
        int(c.split("_")[1])
        for c in cols
        if c.startswith("rtx_") and c.endswith("_dose_date")
    )

    # 1) Core columns (non-rtx)
    core_cols = [c for c in cols if not c.startswith("rtx_")]

    # 2) Dose blocks (ordered)
    dose_blocks = []
    for n in dose_numbers:
        block = [
            f"rtx_{n}_dose_date",
            f"rtx_{n}_dose_value",
            f"rtx_{n}_vanish_days",
            f"rtx_{n}_vanish_date",
        ]
        dose_blocks.extend([c for c in block if c in cols])

    # 3) Everything else starting with rtx_ (course columns, intervals, etc.)
    other_rtx_cols = [
        c for c in cols
        if c.startswith("rtx_") and c not in dose_blocks
    ]

    # Build final ordering
    ordered_cols = core_cols + dose_blocks + other_rtx_cols

    return df[ordered_cols]

rtx_merged_data = reorder_rtx_columns(rtx_merged_data)
rtx_merged_data

,RKD.ID,Date_Of_Visit,ANCA_Levels,anca_status,ancaswitch,Repeat.Instrument,Repeat.Instance.x,Data.Access.Group.x,Patient.ID,COVID.19.related.entry.,...,rtx_24_dose_date,rtx_24_dose_value,rtx_25_dose_date,rtx_25_dose_value,rtx_26_dose_date,rtx_26_dose_value,rtx_27_dose_date,rtx_27_dose_value,rtx_28_dose_date,rtx_28_dose_value
0,1,2012-08-31,134.0,ANCA Positive,Switch Status Unknown,Encounters,1,TUH - Tallaght,1,No,...,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN
1,1,2012-09-07,NaN,ANCA Positive,Pos-Pos Switch,Encounters,36,TUH - Tallaght,1,No,...,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN
2,1,2012-09-17,110.0,ANCA Positive,Pos-Pos Switch,Encounters,37,TUH - Tallaght,1,No,...,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN
3,1,2012-09-21,92.0,ANCA Positive,Pos-Pos Switch,Encounters,2,TUH - Tallaght,1,No,...,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN
4,1,2012-09-28,NaN,ANCA Positive,Pos-Pos Switch,Encounters,28,TUH - Tallaght,1,No,...,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8022,28793,2026-01-21,147.0,ANCA Positive,Switch Status Unknown,Encounters,1,CUH - Cork University Hospital,28793,No,...,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN
8023,28796,2025-07-28,NaN,ANCA Status Unknown,Switch Status Unknown,Encounters,2,NaN,28796,No,...,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN
8024,28796,2026-01-30,NaN,ANCA Negative,Switch Status Unknown,Encounters,1,NaN,28796,No,...,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN
8025,28797,2026-02-02,134.0,ANCA Positive,Switch Status Unknown,Encounters,1,CUH - Cork University Hospital,28797,NaN,...,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN
8026,28797,2026-03-26,134.0,ANCA Positive,Pos-Pos Switch,Encounters,2,CUH - Cork University Hospital,28797,NaN,...,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN

In [282]:
rtx_merged_data.columns

Index(['RKD.ID', 'Date_Of_Visit', 'ANCA_Levels', 'anca_status', 'ancaswitch',
       'Repeat.Instrument', 'Repeat.Instance.x', 'Data.Access.Group.x',
       'Patient.ID', 'COVID.19.related.entry.',
       ...
       'rtx_24_dose_date', 'rtx_24_dose_value', 'rtx_25_dose_date',
       'rtx_25_dose_value', 'rtx_26_dose_date', 'rtx_26_dose_value',
       'rtx_27_dose_date', 'rtx_27_dose_value', 'rtx_28_dose_date',
       'rtx_28_dose_value'],
      dtype='object', length=625)

## Interval between date of IV and date of visit

In [283]:
for n in range(1, 29):
    dose_col = f"rtx_{n}_dose_date"
    new_col  = f"days_visit_minus_rtx{n}"

    if dose_col in rtx_merged_data.columns:
        rtx_merged_data[new_col] = (
            pd.to_datetime(rtx_merged_data["Date_Of_Visit"], errors="coerce", dayfirst=True)
            - pd.to_datetime(rtx_merged_data[dose_col], errors="coerce", dayfirst=True)
        ).dt.days

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\3750963175.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rtx_merged_data[new_col] = (
C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\3750963175.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rtx_merged_data[new_col] = (
C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\3750963175.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rtx_merged_data[new_col] = (
C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\3750963175.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rtx_merged_data[new_col] = (
C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\3750963175.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rtx_merged_data[new_col] = (
C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\3750963175.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rtx_merged_data[new_col] = (
C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\3750963175.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rtx_merged_data[new_col] = (
C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\3750963175.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rtx_merged_data[new_col] = (
C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\3750963175.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rtx_merged_data[new_col] = (
C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\3750963175.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rtx_merged_data[new_col] = (
C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\3750963175.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rtx_merged_data[new_col] = (
C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\3750963175.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rtx_merged_data[new_col] = (
C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\3750963175.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rtx_merged_data[new_col] = (
C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\3750963175.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rtx_merged_data[new_col] = (
C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\3750963175.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rtx_merged_data[new_col] = (
C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\3750963175.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rtx_merged_data[new_col] = (
C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\3750963175.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rtx_merged_data[new_col] = (
C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\3750963175.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rtx_merged_data[new_col] = (
C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\3750963175.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rtx_merged_data[new_col] = (
C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\3750963175.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rtx_merged_data[new_col] = (
C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\3750963175.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rtx_merged_data[new_col] = (
C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\3750963175.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rtx_merged_data[new_col] = (
C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\3750963175.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rtx_merged_data[new_col] = (
C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\3750963175.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rtx_merged_data[new_col] = (
C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\3750963175.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rtx_merged_data[new_col] = (
C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\3750963175.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rtx_merged_data[new_col] = (
C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\3750963175.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rtx_merged_data[new_col] = (
C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\3750963175.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rtx_merged_data[new_col] = (

In [284]:
## replace negative days with0

In [285]:
for n in range(1, 29):
    day_col = f"days_visit_minus_rtx{n}"

    if day_col in rtx_merged_data.columns:
        rtx_merged_data[day_col] = rtx_merged_data[day_col].clip(lower=0)

In [286]:
## Apply ITIS

In [287]:
for n in range(1, 29):
    dose_col = f"rtx_{n}_dose_value"

    if dose_col in rtx_merged_data.columns:
        rtx_merged_data[dose_col] = (
            pd.to_numeric(rtx_merged_data[dose_col], errors="coerce")
            .clip(lower=500, upper=2000)
        )

In [288]:
import numpy as np
import pandas as pd

# ---------------------------------------------
# 1. Sigmoid function (UNCHANGED)
# ---------------------------------------------
def sigmoid_curve(x, A, n, d):
    return A / (1 + np.exp(n * (x - d)))

# ---------------------------------------------
# 2. Interpolation functions for A(dose), d(dose), n(dose) (UNCHANGED)
# ---------------------------------------------
A1 = 0.70
A2 = 0.85
dose1 = 500
dose2 = 2000

m_A = (A2 - A1) / (dose2 - dose1)
b_A = A1 - m_A * dose1
def calculate_A(dose):
    return m_A * dose + b_A

d1 = 160
d2 = 200
m_d = (d2 - d1) / (dose2 - dose1)
b_d = d1 - m_d * dose1
def calculate_d(dose):
    return m_d * dose + b_d

# vanish logic (UNCHANGED)
def calculate_n_from_vanish(A, d, vanish_day):
    return np.log(99) / (vanish_day - d)

vanish1 = 240
vanish2 = 300
n1 = calculate_n_from_vanish(A1, d1, vanish1)
n2 = calculate_n_from_vanish(A2, d2, vanish2)

m_n = (n2 - n1) / (dose2 - dose1)
b_n = n1 - m_n * dose1
def calculate_n(dose):
    return m_n * dose + b_n

# ---------------------------------------------
# 3. ITIS computation for ALL doses 1–11 (equations unchanged)
# ---------------------------------------------
def compute_ITIS_generic(row, dose_num):
    dose_col = f"rtx_{dose_num}_dose_value"
    time_col = f"days_visit_minus_rtx{dose_num}"

    dose = row[dose_col]
    time = row[time_col]

    # Skip invalid values
    if pd.isna(dose) or pd.isna(time):
        return np.nan

    A = calculate_A(dose)
    d = calculate_d(dose)
    n = calculate_n(dose)

    return sigmoid_curve(time, A, n, d)

# Create ITIS columns for doses 1–11
for n in range(1, 29):
    dose_col = f"rtx_{n}_dose_value"
    time_col = f"days_visit_minus_rtx{n}"
    out_col  = f"rtx_dose{n}_ITIS"

    if dose_col in rtx_merged_data.columns and time_col in rtx_merged_data.columns:
        rtx_merged_data[out_col] = rtx_merged_data.apply(
            lambda row: compute_ITIS_generic(row, n),
            axis=1
        )

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\2078623993.py:71: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rtx_merged_data[out_col] = rtx_merged_data.apply(
C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\2078623993.py:71: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rtx_merged_data[out_col] = rtx_merged_data.apply(
C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\2078623993.py:71: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rtx_merged_data[out_col] = rtx_merged_data.apply(
C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\2078623993.py:71: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rtx_merged_data[out_col] = rtx_merged_data.apply(
C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\2078623993.py:71: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rtx_merged_data[out_col] = rtx_merged_data.apply(
C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\2078623993.py:71: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rtx_merged_data[out_col] = rtx_merged_data.apply(
C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\2078623993.py:71: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rtx_merged_data[out_col] = rtx_merged_data.apply(
C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\2078623993.py:71: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rtx_merged_data[out_col] = rtx_merged_data.apply(
C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\2078623993.py:71: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rtx_merged_data[out_col] = rtx_merged_data.apply(
C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\2078623993.py:71: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rtx_merged_data[out_col] = rtx_merged_data.apply(
C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\2078623993.py:71: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rtx_merged_data[out_col] = rtx_merged_data.apply(
C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\2078623993.py:71: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rtx_merged_data[out_col] = rtx_merged_data.apply(
C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\2078623993.py:71: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rtx_merged_data[out_col] = rtx_merged_data.apply(
C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\2078623993.py:71: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rtx_merged_data[out_col] = rtx_merged_data.apply(
C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\2078623993.py:71: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rtx_merged_data[out_col] = rtx_merged_data.apply(
C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\2078623993.py:71: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rtx_merged_data[out_col] = rtx_merged_data.apply(
C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\2078623993.py:71: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rtx_merged_data[out_col] = rtx_merged_data.apply(
C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\2078623993.py:71: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rtx_merged_data[out_col] = rtx_merged_data.apply(
C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\2078623993.py:71: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rtx_merged_data[out_col] = rtx_merged_data.apply(
C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\2078623993.py:71: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rtx_merged_data[out_col] = rtx_merged_data.apply(
C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\2078623993.py:71: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rtx_merged_data[out_col] = rtx_merged_data.apply(
C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\2078623993.py:71: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rtx_merged_data[out_col] = rtx_merged_data.apply(
C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\2078623993.py:71: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rtx_merged_data[out_col] = rtx_merged_data.apply(
C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\2078623993.py:71: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rtx_merged_data[out_col] = rtx_merged_data.apply(
C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\2078623993.py:71: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rtx_merged_data[out_col] = rtx_merged_data.apply(
C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\2078623993.py:71: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rtx_merged_data[out_col] = rtx_merged_data.apply(
C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\2078623993.py:71: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rtx_merged_data[out_col] = rtx_merged_data.apply(
C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\2078623993.py:71: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rtx_merged_data[out_col] = rtx_merged_data.apply(

In [289]:
itis_cols = [
    "rtx_dose1_ITIS",
    "rtx_dose2_ITIS",
    "rtx_dose3_ITIS",
    "rtx_dose4_ITIS",
    "rtx_dose5_ITIS",
    "rtx_dose6_ITIS",
    "rtx_dose7_ITIS",
    "rtx_dose9_ITIS",
    "rtx_dose10_ITIS",
    "rtx_dose11_ITIS",
    "rtx_dose12_ITIS",
    "rtx_dose13_ITIS",
    "rtx_dose14_ITIS",
    "rtx_dose15_ITIS",
    "rtx_dose16_ITIS",
    "rtx_dose17_ITIS",
    "rtx_dose18_ITIS",
    "rtx_dose19_ITIS",
    "rtx_dose20_ITIS",
    "rtx_dose21_ITIS",
    "rtx_dose22_ITIS",
    "rtx_dose23_ITIS",
    "rtx_dose24_ITIS",
    "rtx_dose25_ITIS",
    "rtx_dose26_ITIS",
    "rtx_dose27_ITIS",
    "rtx_dose28_ITIS"
]

for col in itis_cols:
    if col in rtx_merged_data.columns:
        rtx_merged_data[col] = rtx_merged_data[col].round(2)

In [290]:
## Calculate cumulative ITIS

In [291]:
import numpy as np

# List of ITIS component columns
itis_cols = [
    "rtx_dose1_ITIS",
    "rtx_dose2_ITIS",
    "rtx_dose3_ITIS",
    "rtx_dose4_ITIS",
    "rtx_dose5_ITIS",
    "rtx_dose6_ITIS",
    "rtx_dose7_ITIS",
    "rtx_dose9_ITIS",
    "rtx_dose10_ITIS",
    "rtx_dose11_ITIS",
    "rtx_dose12_ITIS",
    "rtx_dose13_ITIS",
    "rtx_dose14_ITIS",
    "rtx_dose15_ITIS",
    "rtx_dose16_ITIS",
    "rtx_dose17_ITIS",
    "rtx_dose18_ITIS",
    "rtx_dose19_ITIS",
    "rtx_dose20_ITIS",
    "rtx_dose21_ITIS",
    "rtx_dose22_ITIS",
    "rtx_dose23_ITIS",
    "rtx_dose24_ITIS",
    "rtx_dose25_ITIS",
    "rtx_dose26_ITIS",
    "rtx_dose27_ITIS",
    "rtx_dose28_ITIS"
]

def compute_cumulative_ITIS(row):
    values = row[itis_cols].dropna().values

    # If all ITIS_i are missing → cumulative result is NaN
    if len(values) == 0:
        return np.nan

    # Apply formula: 1 - Π(1 - ITIS_i)
    product = np.prod(1 - values)
    return 1 - product

# Create new column
rtx_merged_data["RTX_IV_ITIS"] = rtx_merged_data.apply(compute_cumulative_ITIS, axis=1)

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\1819362934.py:46: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rtx_merged_data["RTX_IV_ITIS"] = rtx_merged_data.apply(compute_cumulative_ITIS, axis=1)

In [292]:
rtx_merged_data["RTX_IV_ITIS"].fillna(0, inplace=True)
rtx_merged_data["RTX_IV_ITIS"]

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\73836407.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  rtx_merged_data["RTX_IV_ITIS"].fillna(0, inplace=True)

0       0.00
1       0.00
2       0.00
3       0.00
4       0.00
        ...
8022    0.00
8023    0.00
8024    0.84
8025    0.00
8026    0.85
Name: RTX_IV_ITIS, Length: 8027, dtype: float64

In [293]:
mask = (
    (
        rtx_merged_data['IV.therapy.x'].isin([
            'Rituximab - UATC/L01XC02 -- Mabthera',
            'Rituximab - UATC/L01XC02 -- Ruxience',
            'Rituximab - UATC/L01XC02 -- Truxima'
        ])
        &
        (
            rtx_merged_data['RTX_IV_ITIS'].isna()
            | (rtx_merged_data['RTX_IV_ITIS'] == 0)
        )
    )
    |
    (
        rtx_merged_data['treatment_type'].isin([
            'Rituximab - UATC/L01XC02 -- Mabthera',
            'Rituximab - UATC/L01XC02 -- Ruxience',
            'Rituximab - UATC/L01XC02 -- Truxima'
        ])
        &
        (
            rtx_merged_data['RTX_IV_ITIS'].isna()
            | (rtx_merged_data['RTX_IV_ITIS'] == 0)
        )
    )
)

rtx_merged_data.loc[mask, 'RTX_IV_ITIS'] = 0.80

In [294]:
rtx_merged_data['RTX_IV_ITIS-1'] = rtx_merged_data.groupby(['RKD.ID'])['RTX_IV_ITIS'].shift(1)

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\3853403779.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rtx_merged_data['RTX_IV_ITIS-1'] = rtx_merged_data.groupby(['RKD.ID'])['RTX_IV_ITIS'].shift(1)

## RTX ITIS vs CD19

In [295]:
mask = (
    (rtx_merged_data['absolute_cd19_count'] == 0) &
    (rtx_merged_data['RTX_IV_ITIS'] < rtx_merged_data['RTX_IV_ITIS-1'])
)

rtx_merged_data.loc[mask, 'RTX_IV_ITIS'] = rtx_merged_data.loc[
    mask, 'RTX_IV_ITIS-1'
]

In [296]:
rtx_merged_data.loc[
    rtx_merged_data['absolute_cd19_count'] > 10,
    'RTX_IV_ITIS'
] = 0

In [297]:
#rtx_merged_data.to_csv('C:/Users/georgea1/OneDrive - Trinity College Dublin/Desktop/rtx_final.csv',index=True)

In [298]:
#rtx_merged_data.to_csv('C:/Users/georgea1/OneDrive - Trinity College Dublin/Desktop/rtx_final2.csv',index=True)

## CYC Oral

In [299]:
mtp_with_intervals = rtx_merged_data.copy()
mtp_with_intervals

,RKD.ID,Date_Of_Visit,ANCA_Levels,anca_status,ancaswitch,Repeat.Instrument,Repeat.Instance.x,Data.Access.Group.x,Patient.ID,COVID.19.related.entry.,...,rtx_dose21_ITIS,rtx_dose22_ITIS,rtx_dose23_ITIS,rtx_dose24_ITIS,rtx_dose25_ITIS,rtx_dose26_ITIS,rtx_dose27_ITIS,rtx_dose28_ITIS,RTX_IV_ITIS,RTX_IV_ITIS-1
0,1,2012-08-31,134.0,ANCA Positive,Switch Status Unknown,Encounters,1,TUH - Tallaght,1,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,NaN
1,1,2012-09-07,NaN,ANCA Positive,Pos-Pos Switch,Encounters,36,TUH - Tallaght,1,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.0
2,1,2012-09-17,110.0,ANCA Positive,Pos-Pos Switch,Encounters,37,TUH - Tallaght,1,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.0
3,1,2012-09-21,92.0,ANCA Positive,Pos-Pos Switch,Encounters,2,TUH - Tallaght,1,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.0
4,1,2012-09-28,NaN,ANCA Positive,Pos-Pos Switch,Encounters,28,TUH - Tallaght,1,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8022,28793,2026-01-21,147.0,ANCA Positive,Switch Status Unknown,Encounters,1,CUH - Cork University Hospital,28793,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.0
8023,28796,2025-07-28,NaN,ANCA Status Unknown,Switch Status Unknown,Encounters,2,NaN,28796,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,NaN
8024,28796,2026-01-30,NaN,ANCA Negative,Switch Status Unknown,Encounters,1,NaN,28796,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.84,0.0
8025,28797,2026-02-02,134.0,ANCA Positive,Switch Status Unknown,Encounters,1,CUH - Cork University Hospital,28797,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,NaN
8026,28797,2026-03-26,134.0,ANCA Positive,Pos-Pos Switch,Encounters,2,CUH - Cork University Hospital,28797,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.85,0.0

In [300]:
conmed=pd.read_csv("C:/Users/georgea1/OneDrive - Trinity College Dublin/Angel George/Chap 2. Treatment/Data/ITIS Data/RIV/April 2026/Redcap_countinuous_medication_data_merged_version0.0.3 (11).csv")
conmed

,RKD.ID,Repeat.Instrument,Repeat.Instance,Data.Access.Group,Drug,Drug..ATC,Dose,Unit.of.Doses,Unit.of.Doses...Other,Frequency,Frequency...other,Start.Date,On.going,Stop.Date,Complete..6,Date.of.diagnosis,medstart_interval_from_diagnosis,medstop_interval_from_diagnosis
0,1,Treatment - Continuing medications,1,TUH - Tallaght,Prednisolone - UATC/H02AB06,NaN,60.0,mg,NaN,Daily,NaN,2012-08-31,No,2012-09-07,Complete,31/08/2012,0.0,7.0
1,1,Treatment - Continuing medications,2,TUH - Tallaght,Prednisolone - UATC/H02AB06,NaN,45.0,mg,NaN,Daily,NaN,2012-09-07,No,2012-10-19,Complete,31/08/2012,7.0,49.0
2,1,Treatment - Continuing medications,3,TUH - Tallaght,Prednisolone - UATC/H02AB06,NaN,30.0,mg,NaN,Daily,NaN,2012-10-19,No,2012-11-12,Complete,31/08/2012,49.0,73.0
3,1,Treatment - Continuing medications,4,TUH - Tallaght,Prednisolone - UATC/H02AB06,NaN,25.0,mg,NaN,Daily,NaN,2012-11-12,No,2012-11-26,Complete,31/08/2012,73.0,87.0
4,1,Treatment - Continuing medications,5,TUH - Tallaght,Prednisolone - UATC/H02AB06,NaN,20.0,mg,NaN,Daily,NaN,2012-11-26,No,2012-12-21,Complete,31/08/2012,87.0,112.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6594,28796,Treatment - Continuing medications,3,NaN,Prednisolone - UATC/H02AB06,NaN,30.0,mg,NaN,Daily,NaN,2026-01-05,Yes,2026-01-19,Incomplete,28/07/2025,161.0,175.0
6595,28796,Treatment - Continuing medications,4,NaN,Prednisolone - UATC/H02AB06,NaN,20.0,mg,NaN,Daily,NaN,2026-01-19,Yes,2026-02-02,Incomplete,28/07/2025,175.0,189.0
6596,28796,Treatment - Continuing medications,5,NaN,Prednisolone - UATC/H02AB06,NaN,5.0,mg,NaN,Daily,NaN,2026-02-02,Yes,NaN,Incomplete,28/07/2025,189.0,NaN
6597,28796,Treatment - Continuing medications,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,NaN,Incomplete,28/07/2025,NaN,NaN
6598,28797,Treatment - Continuing medications,1,CUH - Cork University Hospital,Avacopan (C5aR inhibitor),NaN,60.0,mg,NaN,Twice daily,NaN,2026-02-12,Yes,2027-02-12,Complete,10/02/2026,2.0,367.0

In [301]:
duplicateRows = conmed[conmed.duplicated(['RKD.ID','Drug','Start.Date','Dose'])]
duplicateRows

,RKD.ID,Repeat.Instrument,Repeat.Instance,Data.Access.Group,Drug,Drug..ATC,Dose,Unit.of.Doses,Unit.of.Doses...Other,Frequency,Frequency...other,Start.Date,On.going,Stop.Date,Complete..6,Date.of.diagnosis,medstart_interval_from_diagnosis,medstop_interval_from_diagnosis
256,45,Treatment - Continuing medications,6,TUH - Tallaght,Other,NaN,5.0,mg,NaN,Once daily,NaN,2012-09-01,Yes,NaN,Complete,01/09/2012,0.0,NaN
318,56,Treatment - Continuing medications,4,TUH - Tallaght,Azathioprine - UATC/L04AX01,NaN,100.0,mg,NaN,Daily,NaN,2013-10-15,Yes,NaN,Complete,13/09/2013,32.0,NaN
493,92,Treatment - Continuing medications,9,TUH - Tallaght,Other,NaN,20.0,mg,NaN,Daily,NaN,NaN,Yes,NaN,Complete,21/12/2005,NaN,NaN
498,93,Treatment - Continuing medications,5,TUH - Tallaght,Other,NaN,75.0,mg,NaN,Daily,NaN,NaN,Yes,NaN,Complete,01/01/2001,NaN,NaN
499,93,Treatment - Continuing medications,6,TUH - Tallaght,Other,NaN,75.0,mg,NaN,Daily,NaN,NaN,Yes,NaN,Complete,01/01/2001,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6533,28772,Treatment - Continuing medications,9,CUH - Cork University Hospital,NaN,lercanidipine,10.0,mg,NaN,Daily,NaN,NaN,Yes,NaN,Incomplete,11/11/2025,NaN,NaN
6545,28780,Treatment - Continuing medications,5,CUH - Cork University Hospital,NaN,vilanterol and fluticasone furoate,NaN,NaN,NaN,NaN,NaN,NaN,Yes,NaN,Incomplete,02/05/2024,NaN,NaN
6565,28789,Treatment - Continuing medications,8,CUH - Cork University Hospital,NaN,atorvastatin and ezetimibe,NaN,NaN,NaN,Daily,NaN,2025-12-28,Yes,NaN,Incomplete,29/12/2025,-1.0,NaN
6581,28793,Treatment - Continuing medications,4,CUH - Cork University Hospital,NaN,nebivolol,5.0,mg,NaN,Once daily,NaN,2026-01-28,Yes,NaN,Incomplete,31/07/2020,2007.0,NaN
6582,28793,Treatment - Continuing medications,5,CUH - Cork University Hospital,NaN,folic acid,5.0,mg,NaN,Once daily,NaN,2026-01-28,Yes,NaN,Incomplete,31/07/2020,2007.0,NaN

In [302]:
conmed=conmed.drop_duplicates(subset=['RKD.ID','Drug','Start.Date','Dose'], keep='first')

In [303]:
cyc_oral=conmed.loc[(conmed['Drug']=='Cyclophosphamide - UATC/L01AA01')]
cyc_oral

,RKD.ID,Repeat.Instrument,Repeat.Instance,Data.Access.Group,Drug,Drug..ATC,Dose,Unit.of.Doses,Unit.of.Doses...Other,Frequency,Frequency...other,Start.Date,On.going,Stop.Date,Complete..6,Date.of.diagnosis,medstart_interval_from_diagnosis,medstop_interval_from_diagnosis
17,2,Treatment - Continuing medications,1,TUH - Tallaght,Cyclophosphamide - UATC/L01AA01,NaN,100.0,mg,NaN,Once daily,NaN,2012-03-27,No,2012-05-11,Complete,01/04/2012,-5.0,40.0
29,3,Treatment - Continuing medications,1,TUH - Tallaght,Cyclophosphamide - UATC/L01AA01,NaN,125.0,mg,NaN,Daily,NaN,2012-05-11,No,2012-09-21,Complete,18/04/2012,23.0,156.0
48,5,Treatment - Continuing medications,1,TUH - Tallaght,Cyclophosphamide - UATC/L01AA01,NaN,100.0,mg,NaN,Daily,NaN,2012-11-01,No,2012-12-04,Complete,02/10/2012,30.0,63.0
52,6,Treatment - Continuing medications,1,TUH - Tallaght,Cyclophosphamide - UATC/L01AA01,NaN,100.0,mg,NaN,Once daily,NaN,1995-05-07,No,1997-05-08,Complete,01/04/1995,36.0,768.0
98,12,Treatment - Continuing medications,3,TUH - Tallaght,Cyclophosphamide - UATC/L01AA01,NaN,100.0,mg,NaN,Once daily,NaN,2017-02-20,No,2017-03-03,Complete,01/02/2012,1846.0,1857.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6389,28719,Treatment - Continuing medications,1,BEU - Beaumont,Cyclophosphamide - UATC/L01AA01,NaN,100.0,mg,NaN,Daily,NaN,2025-05-14,Yes,NaN,Unverified,14/05/2025,0.0,NaN
6390,28720,Treatment - Continuing medications,1,BEU - Beaumont,Cyclophosphamide - UATC/L01AA01,NaN,100.0,mg,NaN,Daily,NaN,2025-05-11,Yes,NaN,Incomplete,08/05/2025,3.0,NaN
6402,28723,Treatment - Continuing medications,1,TUH - Tallaght,Cyclophosphamide - UATC/L01AA01,NaN,125.0,mg,NaN,Daily,NaN,2008-11-22,Yes,2009-03-19,Complete,11/11/2008,11.0,128.0
6411,28729,Treatment - Continuing medications,1,GAL - UCH Galway,Cyclophosphamide - UATC/L01AA01,NaN,150.0,mg,NaN,Daily,NaN,2025-06-11,Yes,NaN,Incomplete,10/06/2025,1.0,NaN
6472,28751,Treatment - Continuing medications,2,BEU - Beaumont,Cyclophosphamide - UATC/L01AA01,cyclophosphamide,75.0,mg,NaN,Daily,NaN,2025-07-23,Yes,2025-10-08,Complete,22/07/2025,1.0,78.0

In [304]:
cyc_oral.rename(columns={"Unit.of.Doses": "cyc_oral_Unit.of.Doses"}, inplace=True)
cyc_oral.rename(columns={"Frequency": "cyc_oral_Frequency"}, inplace=True)
cyc_oral.rename(columns={"Start.Date": "cyc_oral_Start.Date"}, inplace=True)
cyc_oral.rename(columns={"On.going": "cyc_oral_On.going"}, inplace=True)
cyc_oral.rename(columns={"Stop.Date": "cyc_oral_Stop.Date"}, inplace=True)

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\241132510.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cyc_oral.rename(columns={"Unit.of.Doses": "cyc_oral_Unit.of.Doses"}, inplace=True)
C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\241132510.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cyc_oral.rename(columns={"Frequency": "cyc_oral_Frequency"}, inplace=True)
C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\241132510.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cyc_oral.rename(columns={"Start.Date": "cyc_oral_Start.Date"}, inplace=True)
C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\241132510.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cyc_oral.rename(columns={"On.going": "cyc_oral_On.going"}, inplace=True)
C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\241132510.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cyc_oral.rename(columns={"Stop.Date": "cyc_oral_Stop.Date"}, inplace=True)

In [305]:
# Convert date columns to datetime format
cyc_oral['cyc_oral_Start.Date'] = pd.to_datetime(cyc_oral['cyc_oral_Start.Date'])
cyc_oral['cyc_oral_Stop.Date'] = pd.to_datetime(cyc_oral['cyc_oral_Stop.Date'])
mtp_with_intervals['Date_Of_Visit'] = pd.to_datetime(mtp_with_intervals['Date_Of_Visit'])
mtp_with_intervals

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\539841446.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cyc_oral['cyc_oral_Start.Date'] = pd.to_datetime(cyc_oral['cyc_oral_Start.Date'])
C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\539841446.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cyc_oral['cyc_oral_Stop.Date'] = pd.to_datetime(cyc_oral['cyc_oral_Stop.Date'])

,RKD.ID,Date_Of_Visit,ANCA_Levels,anca_status,ancaswitch,Repeat.Instrument,Repeat.Instance.x,Data.Access.Group.x,Patient.ID,COVID.19.related.entry.,...,rtx_dose21_ITIS,rtx_dose22_ITIS,rtx_dose23_ITIS,rtx_dose24_ITIS,rtx_dose25_ITIS,rtx_dose26_ITIS,rtx_dose27_ITIS,rtx_dose28_ITIS,RTX_IV_ITIS,RTX_IV_ITIS-1
0,1,2012-08-31,134.0,ANCA Positive,Switch Status Unknown,Encounters,1,TUH - Tallaght,1,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,NaN
1,1,2012-09-07,NaN,ANCA Positive,Pos-Pos Switch,Encounters,36,TUH - Tallaght,1,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.0
2,1,2012-09-17,110.0,ANCA Positive,Pos-Pos Switch,Encounters,37,TUH - Tallaght,1,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.0
3,1,2012-09-21,92.0,ANCA Positive,Pos-Pos Switch,Encounters,2,TUH - Tallaght,1,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.0
4,1,2012-09-28,NaN,ANCA Positive,Pos-Pos Switch,Encounters,28,TUH - Tallaght,1,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8022,28793,2026-01-21,147.0,ANCA Positive,Switch Status Unknown,Encounters,1,CUH - Cork University Hospital,28793,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.0
8023,28796,2025-07-28,NaN,ANCA Status Unknown,Switch Status Unknown,Encounters,2,NaN,28796,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,NaN
8024,28796,2026-01-30,NaN,ANCA Negative,Switch Status Unknown,Encounters,1,NaN,28796,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.84,0.0
8025,28797,2026-02-02,134.0,ANCA Positive,Switch Status Unknown,Encounters,1,CUH - Cork University Hospital,28797,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,NaN
8026,28797,2026-03-26,134.0,ANCA Positive,Pos-Pos Switch,Encounters,2,CUH - Cork University Hospital,28797,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.85,0.0

In [306]:
import pandas as pd

# Convert date columns to datetime format
cyc_oral['cyc_oral_Start.Date'] = pd.to_datetime(cyc_oral['cyc_oral_Start.Date'])
cyc_oral['cyc_oral_Stop.Date'] = pd.to_datetime(cyc_oral['cyc_oral_Stop.Date'])
mtp_with_intervals['Date_Of_Visit'] = pd.to_datetime(mtp_with_intervals['Date_Of_Visit'])

# Perform a merge on 'RKD.ID' first
merged = mtp_with_intervals.merge(cyc_oral, on='RKD.ID', how='left')

# Filter rows where Start.Date < Date.Of.Visit <= Stop.Date
filtered = merged[
    (merged['cyc_oral_Start.Date'] < merged['Date_Of_Visit']) & 
    (merged['Date_Of_Visit'] <= merged['cyc_oral_Stop.Date'])
]

# Handle cases where cyc_oral_Stop.Date is missing (NaN)
filtered_na = merged[
    (merged['cyc_oral_Start.Date'] <=merged['Date_Of_Visit']) & 
    (pd.isna(merged['cyc_oral_Stop.Date']))
]

# Combine both filtered DataFrames
merged_filtered = pd.concat([filtered, filtered_na])

# Select relevant columns to merge into dataall
cols_to_merge = ['cyc_oral_Unit.of.Doses',  'cyc_oral_Frequency','cyc_oral_Start.Date','cyc_oral_On.going','cyc_oral_Stop.Date']
mtp_with_intervals = mtp_with_intervals.merge(merged_filtered[['RKD.ID', 'Date_Of_Visit'] + cols_to_merge], 
                        on=['RKD.ID', 'Date_Of_Visit'], how='left')

mtp_with_intervals

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\2239311185.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cyc_oral['cyc_oral_Start.Date'] = pd.to_datetime(cyc_oral['cyc_oral_Start.Date'])
C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\2239311185.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cyc_oral['cyc_oral_Stop.Date'] = pd.to_datetime(cyc_oral['cyc_oral_Stop.Date'])

,RKD.ID,Date_Of_Visit,ANCA_Levels,anca_status,ancaswitch,Repeat.Instrument,Repeat.Instance.x,Data.Access.Group.x,Patient.ID,COVID.19.related.entry.,...,rtx_dose26_ITIS,rtx_dose27_ITIS,rtx_dose28_ITIS,RTX_IV_ITIS,RTX_IV_ITIS-1,cyc_oral_Unit.of.Doses,cyc_oral_Frequency,cyc_oral_Start.Date,cyc_oral_On.going,cyc_oral_Stop.Date
0,1,2012-08-31,134.0,ANCA Positive,Switch Status Unknown,Encounters,1,TUH - Tallaght,1,No,...,NaN,NaN,NaN,0.00,NaN,NaN,NaN,NaT,NaN,NaT
1,1,2012-09-07,NaN,ANCA Positive,Pos-Pos Switch,Encounters,36,TUH - Tallaght,1,No,...,NaN,NaN,NaN,0.00,0.0,NaN,NaN,NaT,NaN,NaT
2,1,2012-09-17,110.0,ANCA Positive,Pos-Pos Switch,Encounters,37,TUH - Tallaght,1,No,...,NaN,NaN,NaN,0.00,0.0,NaN,NaN,NaT,NaN,NaT
3,1,2012-09-21,92.0,ANCA Positive,Pos-Pos Switch,Encounters,2,TUH - Tallaght,1,No,...,NaN,NaN,NaN,0.00,0.0,NaN,NaN,NaT,NaN,NaT
4,1,2012-09-28,NaN,ANCA Positive,Pos-Pos Switch,Encounters,28,TUH - Tallaght,1,No,...,NaN,NaN,NaN,0.00,0.0,NaN,NaN,NaT,NaN,NaT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8029,28793,2026-01-21,147.0,ANCA Positive,Switch Status Unknown,Encounters,1,CUH - Cork University Hospital,28793,No,...,NaN,NaN,NaN,0.00,0.0,NaN,NaN,NaT,NaN,NaT
8030,28796,2025-07-28,NaN,ANCA Status Unknown,Switch Status Unknown,Encounters,2,NaN,28796,No,...,NaN,NaN,NaN,0.00,NaN,NaN,NaN,NaT,NaN,NaT
8031,28796,2026-01-30,NaN,ANCA Negative,Switch Status Unknown,Encounters,1,NaN,28796,No,...,NaN,NaN,NaN,0.84,0.0,NaN,NaN,NaT,NaN,NaT
8032,28797,2026-02-02,134.0,ANCA Positive,Switch Status Unknown,Encounters,1,CUH - Cork University Hospital,28797,NaN,...,NaN,NaN,NaN,0.00,NaN,NaN,NaN,NaT,NaN,NaT
8033,28797,2026-03-26,134.0,ANCA Positive,Pos-Pos Switch,Encounters,2,CUH - Cork University Hospital,28797,NaN,...,NaN,NaN,NaN,0.85,0.0,NaN,NaN,NaT,NaN,NaT

In [307]:
mtp_with_intervals=mtp_with_intervals.drop_duplicates(subset=['RKD.ID','Date_Of_Visit'], keep='first')
mtp_with_intervals

,RKD.ID,Date_Of_Visit,ANCA_Levels,anca_status,ancaswitch,Repeat.Instrument,Repeat.Instance.x,Data.Access.Group.x,Patient.ID,COVID.19.related.entry.,...,rtx_dose26_ITIS,rtx_dose27_ITIS,rtx_dose28_ITIS,RTX_IV_ITIS,RTX_IV_ITIS-1,cyc_oral_Unit.of.Doses,cyc_oral_Frequency,cyc_oral_Start.Date,cyc_oral_On.going,cyc_oral_Stop.Date
0,1,2012-08-31,134.0,ANCA Positive,Switch Status Unknown,Encounters,1,TUH - Tallaght,1,No,...,NaN,NaN,NaN,0.00,NaN,NaN,NaN,NaT,NaN,NaT
1,1,2012-09-07,NaN,ANCA Positive,Pos-Pos Switch,Encounters,36,TUH - Tallaght,1,No,...,NaN,NaN,NaN,0.00,0.0,NaN,NaN,NaT,NaN,NaT
2,1,2012-09-17,110.0,ANCA Positive,Pos-Pos Switch,Encounters,37,TUH - Tallaght,1,No,...,NaN,NaN,NaN,0.00,0.0,NaN,NaN,NaT,NaN,NaT
3,1,2012-09-21,92.0,ANCA Positive,Pos-Pos Switch,Encounters,2,TUH - Tallaght,1,No,...,NaN,NaN,NaN,0.00,0.0,NaN,NaN,NaT,NaN,NaT
4,1,2012-09-28,NaN,ANCA Positive,Pos-Pos Switch,Encounters,28,TUH - Tallaght,1,No,...,NaN,NaN,NaN,0.00,0.0,NaN,NaN,NaT,NaN,NaT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8029,28793,2026-01-21,147.0,ANCA Positive,Switch Status Unknown,Encounters,1,CUH - Cork University Hospital,28793,No,...,NaN,NaN,NaN,0.00,0.0,NaN,NaN,NaT,NaN,NaT
8030,28796,2025-07-28,NaN,ANCA Status Unknown,Switch Status Unknown,Encounters,2,NaN,28796,No,...,NaN,NaN,NaN,0.00,NaN,NaN,NaN,NaT,NaN,NaT
8031,28796,2026-01-30,NaN,ANCA Negative,Switch Status Unknown,Encounters,1,NaN,28796,No,...,NaN,NaN,NaN,0.84,0.0,NaN,NaN,NaT,NaN,NaT
8032,28797,2026-02-02,134.0,ANCA Positive,Switch Status Unknown,Encounters,1,CUH - Cork University Hospital,28797,NaN,...,NaN,NaN,NaN,0.00,NaN,NaN,NaN,NaT,NaN,NaT
8033,28797,2026-03-26,134.0,ANCA Positive,Pos-Pos Switch,Encounters,2,CUH - Cork University Hospital,28797,NaN,...,NaN,NaN,NaN,0.85,0.0,NaN,NaN,NaT,NaN,NaT

In [308]:
import numpy as np

# Set specified columns to NaN where 'cyc_oral_Start.Date' equals 'Date.Of.Visit'
cols_to_nan = cols_to_merge = ['cyc_oral_Unit.of.Doses', 'cyc_oral_Frequency','cyc_oral_Start.Date','cyc_oral_On.going','cyc_oral_Stop.Date']

mtp_with_intervals.loc[mtp_with_intervals['cyc_oral_Start.Date'] == mtp_with_intervals['Date_Of_Visit'], cols_to_nan] = np.nan

mtp_with_intervals

,RKD.ID,Date_Of_Visit,ANCA_Levels,anca_status,ancaswitch,Repeat.Instrument,Repeat.Instance.x,Data.Access.Group.x,Patient.ID,COVID.19.related.entry.,...,rtx_dose26_ITIS,rtx_dose27_ITIS,rtx_dose28_ITIS,RTX_IV_ITIS,RTX_IV_ITIS-1,cyc_oral_Unit.of.Doses,cyc_oral_Frequency,cyc_oral_Start.Date,cyc_oral_On.going,cyc_oral_Stop.Date
0,1,2012-08-31,134.0,ANCA Positive,Switch Status Unknown,Encounters,1,TUH - Tallaght,1,No,...,NaN,NaN,NaN,0.00,NaN,NaN,NaN,NaT,NaN,NaT
1,1,2012-09-07,NaN,ANCA Positive,Pos-Pos Switch,Encounters,36,TUH - Tallaght,1,No,...,NaN,NaN,NaN,0.00,0.0,NaN,NaN,NaT,NaN,NaT
2,1,2012-09-17,110.0,ANCA Positive,Pos-Pos Switch,Encounters,37,TUH - Tallaght,1,No,...,NaN,NaN,NaN,0.00,0.0,NaN,NaN,NaT,NaN,NaT
3,1,2012-09-21,92.0,ANCA Positive,Pos-Pos Switch,Encounters,2,TUH - Tallaght,1,No,...,NaN,NaN,NaN,0.00,0.0,NaN,NaN,NaT,NaN,NaT
4,1,2012-09-28,NaN,ANCA Positive,Pos-Pos Switch,Encounters,28,TUH - Tallaght,1,No,...,NaN,NaN,NaN,0.00,0.0,NaN,NaN,NaT,NaN,NaT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8029,28793,2026-01-21,147.0,ANCA Positive,Switch Status Unknown,Encounters,1,CUH - Cork University Hospital,28793,No,...,NaN,NaN,NaN,0.00,0.0,NaN,NaN,NaT,NaN,NaT
8030,28796,2025-07-28,NaN,ANCA Status Unknown,Switch Status Unknown,Encounters,2,NaN,28796,No,...,NaN,NaN,NaN,0.00,NaN,NaN,NaN,NaT,NaN,NaT
8031,28796,2026-01-30,NaN,ANCA Negative,Switch Status Unknown,Encounters,1,NaN,28796,No,...,NaN,NaN,NaN,0.84,0.0,NaN,NaN,NaT,NaN,NaT
8032,28797,2026-02-02,134.0,ANCA Positive,Switch Status Unknown,Encounters,1,CUH - Cork University Hospital,28797,NaN,...,NaN,NaN,NaN,0.00,NaN,NaN,NaN,NaT,NaN,NaT
8033,28797,2026-03-26,134.0,ANCA Positive,Pos-Pos Switch,Encounters,2,CUH - Cork University Hospital,28797,NaN,...,NaN,NaN,NaN,0.85,0.0,NaN,NaN,NaT,NaN,NaT

In [309]:
mtp_with_intervals["cyc_oral_Start.Date"]

0      NaT
1      NaT
2      NaT
3      NaT
4      NaT
        ..
8029   NaT
8030   NaT
8031   NaT
8032   NaT
8033   NaT
Name: cyc_oral_Start.Date, Length: 8027, dtype: datetime64[ns]

In [310]:
import pandas as pd

# Ensure the columns are in datetime format
mtp_with_intervals["Date_Of_Visit"] = pd.to_datetime(mtp_with_intervals["Date_Of_Visit"])
mtp_with_intervals["cyc_oral_Start.Date"] = pd.to_datetime(mtp_with_intervals["cyc_oral_Start.Date"])
mtp_with_intervals["cyc_oral_Stop.Date"] = pd.to_datetime(mtp_with_intervals["cyc_oral_Stop.Date"])
# Calculate the difference in days
mtp_with_intervals["Stop-start"] = (mtp_with_intervals["cyc_oral_Stop.Date"] - mtp_with_intervals["cyc_oral_Start.Date"]).dt.days
mtp_with_intervals["Days_Difference"] = (mtp_with_intervals["Date_Of_Visit"] - mtp_with_intervals["cyc_oral_Start.Date"]).dt.days

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\1646654317.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mtp_with_intervals["Date_Of_Visit"] = pd.to_datetime(mtp_with_intervals["Date_Of_Visit"])
C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\1646654317.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mtp_with_intervals["cyc_oral_Start.Date"] = pd.to_datetime(mtp_with_intervals["cyc_oral_Start.Date"])
C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\1646654317.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mtp_with_intervals["cyc_oral_Stop.Date"] = pd.to_datetime(mtp_with_intervals["cyc_oral_Stop.Date"])
C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\1646654317.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mtp_with_intervals["Stop-start"] = (mtp_with_intervals["cyc_oral_Stop.Date"] - mtp_with_intervals["cyc_oral_Start.Date"]).dt.days
C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\1646654317.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mtp_with_intervals["Days_Difference"] = (mtp_with_intervals["Date_Of_Visit"] - mtp_with_intervals["cyc_oral_Start.Date"]).dt.days

In [311]:
# Ensure Age and Dose are numeric
mtp_with_intervals["Age_Encounters"] = pd.to_numeric(
    mtp_with_intervals["Age_Encounters"], errors="coerce"
)

dose_col = "Dose_Cyclophosphamide - UATC/L01AA01"
mtp_with_intervals[dose_col] = pd.to_numeric(mtp_with_intervals[dose_col], errors="coerce")

age = mtp_with_intervals["Age_Encounters"]
dose = mtp_with_intervals[dose_col]

# Updated age bands:
# 65–73  -> x1.5
# 74–82  -> x2.0
# >82    -> x2.5  (increase by 150%)
mtp_with_intervals["cyc_oral_relative_dose"] = np.select(
    [
        age.between(65, 73, inclusive="both"),
        age.between(74, 82, inclusive="both"),
        age.gt(82),
    ],
    [
        dose * 1.5,  # 65–73: +50%
        dose * 2.0,  # 74–82: +100%
        dose * 2.5,  # >82:   +150%
    ],
    default=dose    # <=64 (or missing): apply algorithm elsewhere / no change here
)

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\3555218276.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mtp_with_intervals["Age_Encounters"] = pd.to_numeric(
C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\3555218276.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mtp_with_intervals[dose_col] = pd.to_numeric(mtp_with_intervals[dose_col], errors="coerce")
C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\3555218276.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mtp_with_intervals["cyc_oral_relative_dose"] = np.select(

In [312]:
# Ensure lymphocyte count and dose are numeric
mtp_with_intervals["lymphocyte_count"] = pd.to_numeric(
    mtp_with_intervals["lymphocyte_count"], errors="coerce"
)

dose_col = "cyc_oral_relative_dose"
mtp_with_intervals[dose_col] = pd.to_numeric(
    mtp_with_intervals[dose_col], errors="coerce"
)

lymph = mtp_with_intervals["lymphocyte_count"]
dose = mtp_with_intervals[dose_col]

mtp_with_intervals["cyc_oral_relative_dose"] = np.select(
    [
        lymph.gt(0.3) & lymph.le(0.7),  # >0.3 to ≤0.7
        lymph.le(0.3)                   # ≤0.3
    ],
    [
        dose * 1.5,  # +50%
        dose * 2.0   # +100%
    ],
    default=dose     # >0.7 (apply algorithm elsewhere) or missing values
)

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\2000342239.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mtp_with_intervals["lymphocyte_count"] = pd.to_numeric(
C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\2000342239.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mtp_with_intervals[dose_col] = pd.to_numeric(
C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\2000342239.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mtp_with_intervals["cyc_oral_relative_dose"] = np.select(

In [313]:
mtp_with_intervals['cyc_oral_relative_dose'] = pd.to_numeric(mtp_with_intervals['cyc_oral_relative_dose'], errors='coerce')
#mtp_with_intervals['cyc_oral_course'] = mtp_with_intervals['cyc_oral_relative_dose']

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\2473146057.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mtp_with_intervals['cyc_oral_relative_dose'] = pd.to_numeric(mtp_with_intervals['cyc_oral_relative_dose'], errors='coerce')

In [314]:
#mtp_with_intervals['cyc_oral_course'].describe()

In [315]:
mtp_with_intervals['cyc_oral_course'] = mtp_with_intervals['cyc_oral_relative_dose'] * mtp_with_intervals['Days_Difference']

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\1740091271.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mtp_with_intervals['cyc_oral_course'] = mtp_with_intervals['cyc_oral_relative_dose'] * mtp_with_intervals['Days_Difference']

In [316]:
mtp_with_intervals['cyc_oral_course'].describe()

count       542.000000
mean      12332.954336
std       25630.255096
min          75.000000
25%        2000.000000
50%        5250.000000
75%       12150.000000
max      267750.000000
Name: cyc_oral_course, dtype: float64

In [317]:
mtp_with_intervals.loc[mtp_with_intervals['cyc_oral_course'] > 25000, 'cyc_oral_course'] = 25000

In [318]:
mtp_with_intervals['cyc_oral_Stop.Date'] = mtp_with_intervals.groupby('RKD.ID')['cyc_oral_Stop.Date'].transform('ffill')
mtp_with_intervals['cyc_oral_Stop.Date']=mtp_with_intervals.groupby('RKD.ID').ffill()['cyc_oral_Stop.Date']
mtp_with_intervals['cyc_oral_course']=mtp_with_intervals.groupby('RKD.ID').ffill()['cyc_oral_course']

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\2876499570.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mtp_with_intervals['cyc_oral_Stop.Date'] = mtp_with_intervals.groupby('RKD.ID')['cyc_oral_Stop.Date'].transform('ffill')
C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\2876499570.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mtp_with_intervals['cyc_oral_Stop.Date']=mtp_with_intervals.groupby('RKD.ID').ffill()['cyc_oral_Stop.Date']
C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\2876499570.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mtp_with_intervals['cyc_oral_course']=mtp_with_intervals.groupby('RKD.ID').ffill()['cyc_oral_course']

In [319]:

mtp_with_intervals['Date_Of_Visit'] = pd.to_datetime(mtp_with_intervals['Date_Of_Visit'])
mtp_with_intervals['cyc_oral_Stop.Date'] = pd.to_datetime(mtp_with_intervals['cyc_oral_Stop.Date'])

# Calculate the interval in days
mtp_with_intervals['interval_from_oral_cyc'] = (mtp_with_intervals['Date_Of_Visit'] - mtp_with_intervals['cyc_oral_Stop.Date']).dt.days
mtp_with_intervals['interval_from_oral_cyc']

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\2163674361.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mtp_with_intervals['Date_Of_Visit'] = pd.to_datetime(mtp_with_intervals['Date_Of_Visit'])
C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\2163674361.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mtp_with_intervals['cyc_oral_Stop.Date'] = pd.to_datetime(mtp_with_intervals['cyc_oral_Stop.Date'])
C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\2163674361.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mtp_with_intervals['interval_from_oral_cyc'] = (mtp_with_intervals['Date_Of_Visit'] - mtp_with_intervals['cyc_oral_Stop.Date']).dt.days

0      NaN
1      NaN
2      NaN
3      NaN
4      NaN
        ..
8029   NaN
8030   NaN
8031   NaN
8032   NaN
8033   NaN
Name: interval_from_oral_cyc, Length: 8027, dtype: float64

In [320]:
mtp_with_intervals['interval_from_oral_cyc'].min()

-1822.0

In [321]:
# Replace values greater than 365 with 365
mtp_with_intervals.loc[mtp_with_intervals['interval_from_oral_cyc'] <0, 'interval_from_oral_cyc'] = 0

In [322]:
import numpy as np
import pandas as pd

# ---------------------------------------------
# 1. Sigmoid function
# ---------------------------------------------
def sigmoid_curve(x, A, n, d):
    return A / (1 + np.exp(n * (x - d)))

# ---------------------------------------------
# 2. Interpolation functions for A(dose), d(dose), n(dose)
# ---------------------------------------------
A1 = 0.60
A2 = 0.90
dose1 = 75
dose2 = 25000

m_A = (A2 - A1) / (dose2 - dose1)
b_A = A1 - m_A * dose1
def calculate_A(dose):
    return m_A * dose + b_A

d1 = 70
d2 = 90
m_d = (d2 - d1) / (dose2 - dose1)
b_d = d1 - m_d * dose1
def calculate_d(dose):
    return m_d * dose + b_d

# vanish logic
def calculate_n_from_vanish(A, d, vanish_day):
    return np.log(99) / (vanish_day - d)

vanish1 = 90
vanish2 = 115
n1 = calculate_n_from_vanish(A1, d1, vanish1)
n2 = calculate_n_from_vanish(A2, d2, vanish2)

m_n = (n2 - n1) / (dose2 - dose1)
b_n = n1 - m_n * dose1
def calculate_n(dose):
    return m_n * dose + b_n

# ---------------------------------------------
# 3. Apply model to each row of mtp_with_intervals
# ---------------------------------------------
def compute_ITIS(row):
    dose = row["cyc_oral_course"]
    time = row["interval_from_oral_cyc"]

    # Skip invalid values
    if pd.isna(dose) or pd.isna(time):
        return np.nan

    A = calculate_A(dose)
    d = calculate_d(dose)
    n = calculate_n(dose)

    return sigmoid_curve(time, A, n, d)

# Create new column
mtp_with_intervals["CYC_Oral_ITIS"] = mtp_with_intervals.apply(compute_ITIS, axis=1)

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\11290406.py:8: RuntimeWarning: overflow encountered in exp
  return A / (1 + np.exp(n * (x - d)))
C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\11290406.py:62: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mtp_with_intervals["CYC_Oral_ITIS"] = mtp_with_intervals.apply(compute_ITIS, axis=1)

In [323]:
mtp_with_intervals["CYC_Oral_ITIS"] = mtp_with_intervals["CYC_Oral_ITIS"].round(2)

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\2105862434.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mtp_with_intervals["CYC_Oral_ITIS"] = mtp_with_intervals["CYC_Oral_ITIS"].round(2)

In [324]:
mtp_with_intervals["CYC_Oral_ITIS"] = mtp_with_intervals["CYC_Oral_ITIS"].fillna(0)

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\1583411981.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mtp_with_intervals["CYC_Oral_ITIS"] = mtp_with_intervals["CYC_Oral_ITIS"].fillna(0)

In [325]:
mask = (
    (
        (mtp_with_intervals['Drug_Cyclophosphamide - UATC/L01AA01'] == 'Cyclophosphamide - UATC/L01AA01') &
        (
            mtp_with_intervals['CYC_Oral_ITIS'].isna() |
            (mtp_with_intervals['CYC_Oral_ITIS'] == 0)
        )
    )
    |
    (
        mtp_with_intervals['treatment_type'].str.contains('Daily oral cyclophosphamide - UATC/LC01AA01', na=False) &
        (mtp_with_intervals['CYC_Oral_ITIS'] == 0)
    )
)

mtp_with_intervals.loc[mask, 'CYC_Oral_ITIS'] = 0.75

In [326]:
#mtp_with_intervals.to_csv('C:/Users/georgea1/OneDrive - Trinity College Dublin/Desktop/cyc_oral_final.csv',index=True)

## Prednisolone ITIS

In [327]:
dose_bins = [-float('inf'), 4.9999, 10, 20, float('inf')]
dose_labels = [
    '< 5 mg/day',
    '5 - 10 mg/day',
    '11 - 20 mg/day',
    '> 20 mg/day'
]

mtp_with_intervals['prd_Dose_cat'] = pd.cut(
    mtp_with_intervals['Dose_Prednisolone - UATC/H02AB06'],
    bins=dose_bins,
    labels=dose_labels,
    right=True,
    include_lowest=True
)

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\4145836722.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mtp_with_intervals['prd_Dose_cat'] = pd.cut(

In [328]:
mtp_with_intervals['prd_Dose_cat'].value_counts()

prd_Dose_cat
5 - 10 mg/day     1091
> 20 mg/day        780
11 - 20 mg/day     252
< 5 mg/day         180
Name: count, dtype: int64

In [329]:
mtp_with_intervals['prd_Dose_cat'] = (
    mtp_with_intervals['prd_Dose_cat']
    .astype('object')
    .fillna(mtp_with_intervals['corticosteroid_dose'])
)

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\3536542573.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mtp_with_intervals['prd_Dose_cat'] = (

In [330]:
mtp_with_intervals['prd_Dose_cat'].value_counts()

prd_Dose_cat
5 - 10 mg/day     1854
> 20 mg/day        908
< 5 mg/day         342
11 - 20 mg/day     308
Name: count, dtype: int64

In [331]:
#mtp_with_intervals.to_csv('C:/Users/georgea1/OneDrive - Trinity College Dublin/Desktop/prd2.csv',index=True)

## Calculate Prednisolone ITIS

In [332]:
# Correct ITIS mapping (negative values)
itis_map = {
    '< 5 mg/day': 0.10,
    '5 - 10 mg/day': 0.25,
    '11 - 20 mg/day': 0.45,
    '> 20 mg/day': 0.75
}

# Initialize as numeric
mtp_with_intervals['Prednisolone_ITIS'] = 0.0

# 
mask = mtp_with_intervals['prd_Dose_cat'].notna()

mtp_with_intervals.loc[mask, 'Prednisolone_ITIS'] = (
    mtp_with_intervals.loc[mask, 'prd_Dose_cat']
    .map(itis_map)
    .astype(float)
)

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\3669567237.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mtp_with_intervals['Prednisolone_ITIS'] = 0.0

In [333]:
mtp_with_intervals['Prednisolone_ITIS'].dtype
# float64

mtp_with_intervals['Prednisolone_ITIS'].value_counts(dropna=False)

Prednisolone_ITIS
0.00    4615
0.25    1854
0.75     908
0.10     342
0.45     308
Name: count, dtype: int64

## Add date of prednisolone stop date to the dataframe

In [334]:
#conmed=pd.read_csv("C:/Users/georgea1/OneDrive - Trinity College Dublin/Angel George/Chap 2. Treatment/Data/ITIS Data/RIV/December 2025/Redcap_countinuous_medication_data_merged_version0.0.3 (6).csv")
#conmed

In [335]:
prd=conmed.loc[(conmed['Drug']=='Prednisolone - UATC/H02AB06')]
prd

,RKD.ID,Repeat.Instrument,Repeat.Instance,Data.Access.Group,Drug,Drug..ATC,Dose,Unit.of.Doses,Unit.of.Doses...Other,Frequency,Frequency...other,Start.Date,On.going,Stop.Date,Complete..6,Date.of.diagnosis,medstart_interval_from_diagnosis,medstop_interval_from_diagnosis
0,1,Treatment - Continuing medications,1,TUH - Tallaght,Prednisolone - UATC/H02AB06,NaN,60.0,mg,NaN,Daily,NaN,2012-08-31,No,2012-09-07,Complete,31/08/2012,0.0,7.0
1,1,Treatment - Continuing medications,2,TUH - Tallaght,Prednisolone - UATC/H02AB06,NaN,45.0,mg,NaN,Daily,NaN,2012-09-07,No,2012-10-19,Complete,31/08/2012,7.0,49.0
2,1,Treatment - Continuing medications,3,TUH - Tallaght,Prednisolone - UATC/H02AB06,NaN,30.0,mg,NaN,Daily,NaN,2012-10-19,No,2012-11-12,Complete,31/08/2012,49.0,73.0
3,1,Treatment - Continuing medications,4,TUH - Tallaght,Prednisolone - UATC/H02AB06,NaN,25.0,mg,NaN,Daily,NaN,2012-11-12,No,2012-11-26,Complete,31/08/2012,73.0,87.0
4,1,Treatment - Continuing medications,5,TUH - Tallaght,Prednisolone - UATC/H02AB06,NaN,20.0,mg,NaN,Daily,NaN,2012-11-26,No,2012-12-21,Complete,31/08/2012,87.0,112.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6592,28796,Treatment - Continuing medications,1,NaN,Prednisolone - UATC/H02AB06,NaN,40.0,mg,NaN,Daily,NaN,2025-07-28,Yes,2025-08-28,Incomplete,28/07/2025,0.0,31.0
6593,28796,Treatment - Continuing medications,2,NaN,Prednisolone - UATC/H02AB06,NaN,15.0,mg,NaN,Daily,NaN,2025-08-25,Yes,2025-11-01,Complete,28/07/2025,28.0,96.0
6594,28796,Treatment - Continuing medications,3,NaN,Prednisolone - UATC/H02AB06,NaN,30.0,mg,NaN,Daily,NaN,2026-01-05,Yes,2026-01-19,Incomplete,28/07/2025,161.0,175.0
6595,28796,Treatment - Continuing medications,4,NaN,Prednisolone - UATC/H02AB06,NaN,20.0,mg,NaN,Daily,NaN,2026-01-19,Yes,2026-02-02,Incomplete,28/07/2025,175.0,189.0
6596,28796,Treatment - Continuing medications,5,NaN,Prednisolone - UATC/H02AB06,NaN,5.0,mg,NaN,Daily,NaN,2026-02-02,Yes,NaN,Incomplete,28/07/2025,189.0,NaN

In [336]:
prd.rename(columns={"Dose": "Prd_Dose"}, inplace=True)
prd.rename(columns={"Unit.of.Doses": "Prd_Unit.of.Doses"}, inplace=True)
prd.rename(columns={"Frequency": "Prd_Frequency"}, inplace=True)
prd.rename(columns={"Start.Date": "Prd_Start.Date"}, inplace=True)
prd.rename(columns={"On.going": "Prd_On.going"}, inplace=True)
prd.rename(columns={"Stop.Date": "Prd_Stop.Date"}, inplace=True)

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\2576858195.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  prd.rename(columns={"Dose": "Prd_Dose"}, inplace=True)
C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\2576858195.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  prd.rename(columns={"Unit.of.Doses": "Prd_Unit.of.Doses"}, inplace=True)
C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\2576858195.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  prd.rename(columns={"Frequency": "Prd_Frequency"}, inplace=True)
C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\2576858195.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  prd.rename(columns={"Start.Date": "Prd_Start.Date"}, inplace=True)
C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\2576858195.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  prd.rename(columns={"On.going": "Prd_On.going"}, inplace=True)
C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\2576858195.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  prd.rename(columns={"Stop.Date": "Prd_Stop.Date"}, inplace=True)

In [337]:
mtp_with_intervals['Date_Of_Visit']

0      2012-08-31
1      2012-09-07
2      2012-09-17
3      2012-09-21
4      2012-09-28
          ...
8029   2026-01-21
8030   2025-07-28
8031   2026-01-30
8032   2026-02-02
8033   2026-03-26
Name: Date_Of_Visit, Length: 8027, dtype: datetime64[ns]

## Fill missing stop date if on going=yes with date of export

In [338]:
import pandas as pd

# Convert date columns to datetime format
prd['Prd_Start.Date'] = pd.to_datetime(prd['Prd_Start.Date'])
prd['Prd_Stop.Date'] = pd.to_datetime(prd['Prd_Stop.Date'])
mtp_with_intervals['Date_Of_Visit'] = pd.to_datetime(mtp_with_intervals['Date_Of_Visit'])

mask = prd['Prd_Stop.Date'].isna() & (prd['Prd_On.going'] == 'Yes')
prd.loc[mask, 'Prd_Stop.Date'] = pd.to_datetime('2025-12-01')

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\1157692556.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  prd['Prd_Start.Date'] = pd.to_datetime(prd['Prd_Start.Date'])
C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\1157692556.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  prd['Prd_Stop.Date'] = pd.to_datetime(prd['Prd_Stop.Date'])
C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\1157692556.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mtp_with_intervals['Date_Of_Visit'] = pd.to_datetime(mtp_with_intervals['Date_Of_Visit'])

In [339]:
import pandas as pd

# Convert date columns to datetime format
prd['Prd_Start.Date'] = pd.to_datetime(prd['Prd_Start.Date'])
prd['Prd_Stop.Date'] = pd.to_datetime(prd['Prd_Stop.Date'])
mtp_with_intervals['Date_Of_Visit'] = pd.to_datetime(mtp_with_intervals['Date_Of_Visit'])

# Perform a merge on 'RKD.ID' first
merged = mtp_with_intervals.merge(prd, on='RKD.ID', how='left')

# Filter rows where Start.Date < Date.Of.Visit <= Stop.Date
filtered = merged[
    (merged['Prd_Start.Date'] < merged['Date_Of_Visit']) & 
    (merged['Date_Of_Visit'] <= merged['Prd_Stop.Date'])
]

# Handle cases where Prd_Stop.Date is missing (NaN)
filtered_na = merged[
    (merged['Prd_Start.Date'] <=merged['Date_Of_Visit']) & 
    (pd.isna(merged['Prd_Stop.Date']))
]

# Combine both filtered DataFrames
merged_filtered = pd.concat([filtered, filtered_na])

# Select relevant columns to merge into dataall
cols_to_merge = ['Prd_Dose','Prd_Unit.of.Doses',  'Prd_Frequency','Prd_Start.Date','Prd_On.going','Prd_Stop.Date']
mtp_with_intervals = mtp_with_intervals.merge(merged_filtered[['RKD.ID', 'Date_Of_Visit'] + cols_to_merge], 
                        on=['RKD.ID', 'Date_Of_Visit'], how='left')

mtp_with_intervals

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\2189922885.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  prd['Prd_Start.Date'] = pd.to_datetime(prd['Prd_Start.Date'])
C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\2189922885.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  prd['Prd_Stop.Date'] = pd.to_datetime(prd['Prd_Stop.Date'])
C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\2189922885.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mtp_with_intervals['Date_Of_Visit'] = pd.to_datetime(mtp_with_intervals['Date_Of_Visit'])

,RKD.ID,Date_Of_Visit,ANCA_Levels,anca_status,ancaswitch,Repeat.Instrument,Repeat.Instance.x,Data.Access.Group.x,Patient.ID,COVID.19.related.entry.,...,interval_from_oral_cyc,CYC_Oral_ITIS,prd_Dose_cat,Prednisolone_ITIS,Prd_Dose,Prd_Unit.of.Doses,Prd_Frequency,Prd_Start.Date,Prd_On.going,Prd_Stop.Date
0,1,2012-08-31,134.0,ANCA Positive,Switch Status Unknown,Encounters,1,TUH - Tallaght,1,No,...,NaN,0.0,NaN,0.00,NaN,NaN,NaN,NaT,NaN,NaT
1,1,2012-09-07,NaN,ANCA Positive,Pos-Pos Switch,Encounters,36,TUH - Tallaght,1,No,...,NaN,0.0,> 20 mg/day,0.75,60.0,mg,Daily,2012-08-31,No,2012-09-07
2,1,2012-09-17,110.0,ANCA Positive,Pos-Pos Switch,Encounters,37,TUH - Tallaght,1,No,...,NaN,0.0,> 20 mg/day,0.75,45.0,mg,Daily,2012-09-07,No,2012-10-19
3,1,2012-09-21,92.0,ANCA Positive,Pos-Pos Switch,Encounters,2,TUH - Tallaght,1,No,...,NaN,0.0,> 20 mg/day,0.75,45.0,mg,Daily,2012-09-07,No,2012-10-19
4,1,2012-09-28,NaN,ANCA Positive,Pos-Pos Switch,Encounters,28,TUH - Tallaght,1,No,...,NaN,0.0,> 20 mg/day,0.75,45.0,mg,Daily,2012-09-07,No,2012-10-19
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8298,28793,2026-01-21,147.0,ANCA Positive,Switch Status Unknown,Encounters,1,CUH - Cork University Hospital,28793,No,...,NaN,0.0,NaN,0.00,NaN,NaN,NaN,NaT,NaN,NaT
8299,28796,2025-07-28,NaN,ANCA Status Unknown,Switch Status Unknown,Encounters,2,NaN,28796,No,...,NaN,0.0,NaN,0.00,NaN,NaN,NaN,NaT,NaN,NaT
8300,28796,2026-01-30,NaN,ANCA Negative,Switch Status Unknown,Encounters,1,NaN,28796,No,...,NaN,0.0,11 - 20 mg/day,0.45,20.0,mg,Daily,2026-01-19,Yes,2026-02-02
8301,28797,2026-02-02,134.0,ANCA Positive,Switch Status Unknown,Encounters,1,CUH - Cork University Hospital,28797,NaN,...,NaN,0.0,NaN,0.00,NaN,NaN,NaN,NaT,NaN,NaT
8302,28797,2026-03-26,134.0,ANCA Positive,Pos-Pos Switch,Encounters,2,CUH - Cork University Hospital,28797,NaN,...,NaN,0.0,NaN,0.00,NaN,NaN,NaN,NaT,NaN,NaT

In [340]:
mtp_with_intervals=mtp_with_intervals.drop_duplicates(subset=['RKD.ID','Date_Of_Visit'], keep='first')
mtp_with_intervals

,RKD.ID,Date_Of_Visit,ANCA_Levels,anca_status,ancaswitch,Repeat.Instrument,Repeat.Instance.x,Data.Access.Group.x,Patient.ID,COVID.19.related.entry.,...,interval_from_oral_cyc,CYC_Oral_ITIS,prd_Dose_cat,Prednisolone_ITIS,Prd_Dose,Prd_Unit.of.Doses,Prd_Frequency,Prd_Start.Date,Prd_On.going,Prd_Stop.Date
0,1,2012-08-31,134.0,ANCA Positive,Switch Status Unknown,Encounters,1,TUH - Tallaght,1,No,...,NaN,0.0,NaN,0.00,NaN,NaN,NaN,NaT,NaN,NaT
1,1,2012-09-07,NaN,ANCA Positive,Pos-Pos Switch,Encounters,36,TUH - Tallaght,1,No,...,NaN,0.0,> 20 mg/day,0.75,60.0,mg,Daily,2012-08-31,No,2012-09-07
2,1,2012-09-17,110.0,ANCA Positive,Pos-Pos Switch,Encounters,37,TUH - Tallaght,1,No,...,NaN,0.0,> 20 mg/day,0.75,45.0,mg,Daily,2012-09-07,No,2012-10-19
3,1,2012-09-21,92.0,ANCA Positive,Pos-Pos Switch,Encounters,2,TUH - Tallaght,1,No,...,NaN,0.0,> 20 mg/day,0.75,45.0,mg,Daily,2012-09-07,No,2012-10-19
4,1,2012-09-28,NaN,ANCA Positive,Pos-Pos Switch,Encounters,28,TUH - Tallaght,1,No,...,NaN,0.0,> 20 mg/day,0.75,45.0,mg,Daily,2012-09-07,No,2012-10-19
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8298,28793,2026-01-21,147.0,ANCA Positive,Switch Status Unknown,Encounters,1,CUH - Cork University Hospital,28793,No,...,NaN,0.0,NaN,0.00,NaN,NaN,NaN,NaT,NaN,NaT
8299,28796,2025-07-28,NaN,ANCA Status Unknown,Switch Status Unknown,Encounters,2,NaN,28796,No,...,NaN,0.0,NaN,0.00,NaN,NaN,NaN,NaT,NaN,NaT
8300,28796,2026-01-30,NaN,ANCA Negative,Switch Status Unknown,Encounters,1,NaN,28796,No,...,NaN,0.0,11 - 20 mg/day,0.45,20.0,mg,Daily,2026-01-19,Yes,2026-02-02
8301,28797,2026-02-02,134.0,ANCA Positive,Switch Status Unknown,Encounters,1,CUH - Cork University Hospital,28797,NaN,...,NaN,0.0,NaN,0.00,NaN,NaN,NaN,NaT,NaN,NaT
8302,28797,2026-03-26,134.0,ANCA Positive,Pos-Pos Switch,Encounters,2,CUH - Cork University Hospital,28797,NaN,...,NaN,0.0,NaN,0.00,NaN,NaN,NaN,NaT,NaN,NaT

In [341]:
import numpy as np

# Set specified columns to NaN where 'aza_Start.Date' equals 'Date.Of.Visit'
cols_to_nan = cols_to_merge = ['Prd_Dose','Prd_Unit.of.Doses', 'Prd_Frequency','Prd_Start.Date','Prd_On.going','Prd_Stop.Date']

mtp_with_intervals.loc[mtp_with_intervals['Prd_Start.Date'] == mtp_with_intervals['Date_Of_Visit'], cols_to_nan] = np.nan

mtp_with_intervals

,RKD.ID,Date_Of_Visit,ANCA_Levels,anca_status,ancaswitch,Repeat.Instrument,Repeat.Instance.x,Data.Access.Group.x,Patient.ID,COVID.19.related.entry.,...,interval_from_oral_cyc,CYC_Oral_ITIS,prd_Dose_cat,Prednisolone_ITIS,Prd_Dose,Prd_Unit.of.Doses,Prd_Frequency,Prd_Start.Date,Prd_On.going,Prd_Stop.Date
0,1,2012-08-31,134.0,ANCA Positive,Switch Status Unknown,Encounters,1,TUH - Tallaght,1,No,...,NaN,0.0,NaN,0.00,NaN,NaN,NaN,NaT,NaN,NaT
1,1,2012-09-07,NaN,ANCA Positive,Pos-Pos Switch,Encounters,36,TUH - Tallaght,1,No,...,NaN,0.0,> 20 mg/day,0.75,60.0,mg,Daily,2012-08-31,No,2012-09-07
2,1,2012-09-17,110.0,ANCA Positive,Pos-Pos Switch,Encounters,37,TUH - Tallaght,1,No,...,NaN,0.0,> 20 mg/day,0.75,45.0,mg,Daily,2012-09-07,No,2012-10-19
3,1,2012-09-21,92.0,ANCA Positive,Pos-Pos Switch,Encounters,2,TUH - Tallaght,1,No,...,NaN,0.0,> 20 mg/day,0.75,45.0,mg,Daily,2012-09-07,No,2012-10-19
4,1,2012-09-28,NaN,ANCA Positive,Pos-Pos Switch,Encounters,28,TUH - Tallaght,1,No,...,NaN,0.0,> 20 mg/day,0.75,45.0,mg,Daily,2012-09-07,No,2012-10-19
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8298,28793,2026-01-21,147.0,ANCA Positive,Switch Status Unknown,Encounters,1,CUH - Cork University Hospital,28793,No,...,NaN,0.0,NaN,0.00,NaN,NaN,NaN,NaT,NaN,NaT
8299,28796,2025-07-28,NaN,ANCA Status Unknown,Switch Status Unknown,Encounters,2,NaN,28796,No,...,NaN,0.0,NaN,0.00,NaN,NaN,NaN,NaT,NaN,NaT
8300,28796,2026-01-30,NaN,ANCA Negative,Switch Status Unknown,Encounters,1,NaN,28796,No,...,NaN,0.0,11 - 20 mg/day,0.45,20.0,mg,Daily,2026-01-19,Yes,2026-02-02
8301,28797,2026-02-02,134.0,ANCA Positive,Switch Status Unknown,Encounters,1,CUH - Cork University Hospital,28797,NaN,...,NaN,0.0,NaN,0.00,NaN,NaN,NaN,NaT,NaN,NaT
8302,28797,2026-03-26,134.0,ANCA Positive,Pos-Pos Switch,Encounters,2,CUH - Cork University Hospital,28797,NaN,...,NaN,0.0,NaN,0.00,NaN,NaN,NaN,NaT,NaN,NaT

In [342]:
mtp_with_intervals = (
    mtp_with_intervals
    .sort_values(['RKD.ID', 'Date_Of_Visit'])
)

# duplicate the column
mtp_with_intervals['Prd_Stop.Date_ffill'] = (
    mtp_with_intervals['Prd_Stop.Date']
)

# forward fill within each patient
mtp_with_intervals['Prd_Stop.Date_ffill'] = (
    mtp_with_intervals
    .groupby('RKD.ID')['Prd_Stop.Date_ffill']
    .ffill()
)

In [343]:
mtp_with_intervals['interval_from_prd_stop_date'] = (
    mtp_with_intervals['Date_Of_Visit'] -
    mtp_with_intervals['Prd_Stop.Date_ffill']
).dt.days

In [344]:
dose_bins = [-float('inf'), 4.9999, 10, 20, float('inf')]
dose_labels = [
    '< 5 mg/day',
    '5 - 10 mg/day',
    '11 - 20 mg/day',
    '> 20 mg/day'
]

mtp_with_intervals['prd_Dose_cat2'] = pd.cut(
    mtp_with_intervals['Prd_Dose'],
    bins=dose_bins,
    labels=dose_labels,
    right=True,
    include_lowest=True
)

In [345]:
mtp_with_intervals['prd_Dose_cat'] = mtp_with_intervals['prd_Dose_cat'].fillna(
    mtp_with_intervals['prd_Dose_cat2']
)

In [346]:
# Correct ITIS mapping (negative values)
itis_map = {
    '< 5 mg/day': 0.10,
    '5 - 10 mg/day': 0.25,
    '11 - 20 mg/day': 0.45,
    '> 20 mg/day': 0.75
}

# Initialize as numeric
mtp_with_intervals['Prednisolone_ITIS'] = 0.0

# 
mask = mtp_with_intervals['prd_Dose_cat'].notna()

mtp_with_intervals.loc[mask, 'Prednisolone_ITIS'] = (
    mtp_with_intervals.loc[mask, 'prd_Dose_cat']
    .map(itis_map)
    .astype(float)
)

In [347]:
mtp_with_intervals['Prednisolone_ITIS'].value_counts(dropna=False)

Prednisolone_ITIS
0.00    3823
0.25    2411
0.75    1058
0.10     405
0.45     330
Name: count, dtype: int64

In [348]:
# create a duplicate column
mtp_with_intervals['prd_Dose_cat_ffill'] = mtp_with_intervals['prd_Dose_cat']

# forward fill the duplicated column
mtp_with_intervals['prd_Dose_cat_ffill'] = (
    mtp_with_intervals['prd_Dose_cat_ffill'].ffill()
)

In [349]:
# A values by dose category
A_map = {
    '< 5 mg/day': 0.10,
    '5 - 10 mg/day': 0.25,
    '11 - 20 mg/day': 0.45,
    '> 20 mg/day': 0.75
}

# d values by dose category
d_map = {
    '< 5 mg/day': 5,
    '5 - 10 mg/day': 6,
    '11 - 20 mg/day': 7,
    '> 20 mg/day': 7
}

# vanish day values by dose category
vanish_map = {
    '< 5 mg/day': 7,
    '5 - 10 mg/day': 9,
    '11 - 20 mg/day': 12,
    '> 20 mg/day': 15
}
def calculate_n(d, vanish_day):
    return np.log(99) / (vanish_day - d)
def compute_prd_ITIS(row):
    dose_cat = row['prd_Dose_cat_ffill']
    time = row['interval_from_prd_stop_date']

    # Skip invalid rows
    if pd.isna(dose_cat) or pd.isna(time):
        return np.nan

    # If visit is before stop date, ITIS should be 0
    if time < 0:
        return 0.0

    A = A_map.get(dose_cat)
    d = d_map.get(dose_cat)
    vanish = vanish_map.get(dose_cat)

    # Safety check
    if A is None or d is None or vanish is None:
        return np.nan

    n = calculate_n(d, vanish)

    return sigmoid_curve(time, A, n, d)
mtp_with_intervals['prd_ITIS_decay'] = (
    mtp_with_intervals
    .apply(compute_prd_ITIS, axis=1)
)
# Check distribution
mtp_with_intervals['prd_ITIS_decay'].describe()

# Inspect a single patient timeline
mtp_with_intervals.loc[
    mtp_with_intervals['prd_Dose_cat_ffill'].notna(),
    ['prd_Dose_cat_ffill', 'interval_from_prd_stop_date', 'prd_ITIS_decay']
].head(10)

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\11290406.py:8: RuntimeWarning: overflow encountered in exp
  return A / (1 + np.exp(n * (x - d)))

   prd_Dose_cat_ffill  interval_from_prd_stop_date  prd_ITIS_decay
1         > 20 mg/day                          0.0        0.736782
2         > 20 mg/day                        -32.0        0.000000
3         > 20 mg/day                        -28.0        0.000000
4         > 20 mg/day                        -21.0        0.000000
5         > 20 mg/day                        -18.0        0.000000
6         > 20 mg/day                          0.0        0.736782
7         > 20 mg/day                          0.0        0.736782
8         > 20 mg/day                        -10.0        0.000000
9      11 - 20 mg/day                          0.0        0.449278
10     11 - 20 mg/day                          0.0        0.449278

In [350]:
# round to 2 decimal places
mtp_with_intervals['prd_ITIS_decay'] = (
    mtp_with_intervals['prd_ITIS_decay'].round(2)
)

In [351]:
mtp_with_intervals['prd_ITIS_decay']

0        NaN
1       0.74
2       0.00
3       0.00
4       0.00
        ...
8298     NaN
8299     NaN
8300    0.00
8301     NaN
8302     NaN
Name: prd_ITIS_decay, Length: 8027, dtype: float64

In [352]:
mask = (
    (mtp_with_intervals['Prednisolone_ITIS'] == 0) &
    (mtp_with_intervals['prd_ITIS_decay'] != 0) &
    (mtp_with_intervals['prd_ITIS_decay'].notna())
)

mtp_with_intervals.loc[mask, 'Prednisolone_ITIS'] = (
    mtp_with_intervals.loc[mask, 'prd_ITIS_decay']
)

In [353]:
mask = (
    (mtp_with_intervals['imputed_corticosteroids'] == 'On') &
    (mtp_with_intervals['Prednisolone_ITIS'].isna())
)

mtp_with_intervals.loc[mask, 'Prednisolone_ITIS'] = 0.25

## Remove unwanted columns

In [354]:
cols_to_drop = [
    'Prd_Stop.Date_ffill',
    'interval_from_prd_stop_date',
    'prd_ITIS_decay',
    'prd_Dose_cat_ffill'
]

mtp_with_intervals.drop(columns=cols_to_drop, inplace=True)

In [355]:
mtp_with_intervals

,RKD.ID,Date_Of_Visit,ANCA_Levels,anca_status,ancaswitch,Repeat.Instrument,Repeat.Instance.x,Data.Access.Group.x,Patient.ID,COVID.19.related.entry.,...,CYC_Oral_ITIS,prd_Dose_cat,Prednisolone_ITIS,Prd_Dose,Prd_Unit.of.Doses,Prd_Frequency,Prd_Start.Date,Prd_On.going,Prd_Stop.Date,prd_Dose_cat2
0,1,2012-08-31,134.0,ANCA Positive,Switch Status Unknown,Encounters,1,TUH - Tallaght,1,No,...,0.0,NaN,0.00,NaN,NaN,NaN,NaT,NaN,NaT,NaN
1,1,2012-09-07,NaN,ANCA Positive,Pos-Pos Switch,Encounters,36,TUH - Tallaght,1,No,...,0.0,> 20 mg/day,0.75,60.0,mg,Daily,2012-08-31,No,2012-09-07,> 20 mg/day
2,1,2012-09-17,110.0,ANCA Positive,Pos-Pos Switch,Encounters,37,TUH - Tallaght,1,No,...,0.0,> 20 mg/day,0.75,45.0,mg,Daily,2012-09-07,No,2012-10-19,> 20 mg/day
3,1,2012-09-21,92.0,ANCA Positive,Pos-Pos Switch,Encounters,2,TUH - Tallaght,1,No,...,0.0,> 20 mg/day,0.75,45.0,mg,Daily,2012-09-07,No,2012-10-19,> 20 mg/day
4,1,2012-09-28,NaN,ANCA Positive,Pos-Pos Switch,Encounters,28,TUH - Tallaght,1,No,...,0.0,> 20 mg/day,0.75,45.0,mg,Daily,2012-09-07,No,2012-10-19,> 20 mg/day
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8298,28793,2026-01-21,147.0,ANCA Positive,Switch Status Unknown,Encounters,1,CUH - Cork University Hospital,28793,No,...,0.0,NaN,0.00,NaN,NaN,NaN,NaT,NaN,NaT,NaN
8299,28796,2025-07-28,NaN,ANCA Status Unknown,Switch Status Unknown,Encounters,2,NaN,28796,No,...,0.0,NaN,0.00,NaN,NaN,NaN,NaT,NaN,NaT,NaN
8300,28796,2026-01-30,NaN,ANCA Negative,Switch Status Unknown,Encounters,1,NaN,28796,No,...,0.0,11 - 20 mg/day,0.45,20.0,mg,Daily,2026-01-19,Yes,2026-02-02,11 - 20 mg/day
8301,28797,2026-02-02,134.0,ANCA Positive,Switch Status Unknown,Encounters,1,CUH - Cork University Hospital,28797,NaN,...,0.0,NaN,0.00,NaN,NaN,NaN,NaT,NaN,NaT,NaN
8302,28797,2026-03-26,134.0,ANCA Positive,Pos-Pos Switch,Encounters,2,CUH - Cork University Hospital,28797,NaN,...,0.0,NaN,0.00,NaN,NaN,NaN,NaT,NaN,NaT,NaN

In [356]:
#mtp_with_intervals.to_csv('C:/Users/georgea1/OneDrive - Trinity College Dublin/Desktop/prd_f.csv',index=True)

In [357]:
mtp_with_intervals["Prednisolone_ITIS"].fillna(0, inplace=True)
mtp_with_intervals["Prednisolone_ITIS"]

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\985499076.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  mtp_with_intervals["Prednisolone_ITIS"].fillna(0, inplace=True)

0       0.00
1       0.75
2       0.75
3       0.75
4       0.75
        ...
8298    0.00
8299    0.00
8300    0.45
8301    0.00
8302    0.00
Name: Prednisolone_ITIS, Length: 8027, dtype: float64

In [358]:
mask = (
    (mtp_with_intervals['imputed_corticosteroids'] == 'On') &
    (mtp_with_intervals['Prednisolone_ITIS']==0) &(mtp_with_intervals['MTP_IV_ITIS']==0)
)

mtp_with_intervals.loc[mask, 'Prednisolone_ITIS'] = 0.25

## Azathioprine

## add start and stop date to encounter dataframe

In [359]:
aza=conmed.loc[(conmed['Drug']=='Azathioprine - UATC/L04AX01')]
aza

,RKD.ID,Repeat.Instrument,Repeat.Instance,Data.Access.Group,Drug,Drug..ATC,Dose,Unit.of.Doses,Unit.of.Doses...Other,Frequency,Frequency...other,Start.Date,On.going,Stop.Date,Complete..6,Date.of.diagnosis,medstart_interval_from_diagnosis,medstop_interval_from_diagnosis
6,1,Treatment - Continuing medications,7,TUH - Tallaght,Azathioprine - UATC/L04AX01,NaN,150.0,mg,NaN,Daily,NaN,2013-01-23,No,2015-08-14,Complete,31/08/2012,145.0,1078.0
12,1,Treatment - Continuing medications,14,TUH - Tallaght,Azathioprine - UATC/L04AX01,NaN,100.0,mg,NaN,Daily,NaN,2015-08-14,No,2015-12-11,Complete,31/08/2012,1078.0,1197.0
13,1,Treatment - Continuing medications,15,TUH - Tallaght,Azathioprine - UATC/L04AX01,NaN,75.0,mg,NaN,Daily,NaN,2015-12-11,No,2016-02-11,Complete,31/08/2012,1197.0,1259.0
14,1,Treatment - Continuing medications,16,TUH - Tallaght,Azathioprine - UATC/L04AX01,NaN,50.0,mg,NaN,Daily,NaN,2016-02-11,No,2016-05-27,Complete,31/08/2012,1259.0,1365.0
15,1,Treatment - Continuing medications,17,TUH - Tallaght,Azathioprine - UATC/L04AX01,NaN,25.0,mg,NaN,Daily,NaN,2016-05-27,No,2016-10-28,Complete,31/08/2012,1365.0,1519.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6404,28723,Treatment - Continuing medications,3,TUH - Tallaght,Azathioprine - UATC/L04AX01,NaN,200.0,mg,NaN,Daily,NaN,2021-05-06,Yes,2025-05-30,Complete,11/11/2008,4559.0,6044.0
6405,28723,Treatment - Continuing medications,4,TUH - Tallaght,Azathioprine - UATC/L04AX01,NaN,100.0,mg,NaN,Daily,NaN,2025-05-30,Yes,2025-08-29,Complete,11/11/2008,6044.0,6135.0
6406,28723,Treatment - Continuing medications,5,TUH - Tallaght,Azathioprine - UATC/L04AX01,NaN,150.0,mg,NaN,Daily,NaN,2009-03-19,Yes,2010-12-02,Complete,11/11/2008,128.0,751.0
6407,28723,Treatment - Continuing medications,6,TUH - Tallaght,Azathioprine - UATC/L04AX01,NaN,75.0,mg,NaN,Daily,NaN,2010-12-02,Yes,NaN,Incomplete,11/11/2008,751.0,NaN
6418,28737,Treatment - Continuing medications,4,CUH - Cork University Hospital,Azathioprine - UATC/L04AX01,NaN,180.0,mg,NaN,Daily,NaN,2026-01-05,Yes,2026-02-12,Complete,03/06/2025,216.0,254.0

In [360]:
aza.rename(columns={"Unit.of.Doses": "aza_Unit.of.Doses"}, inplace=True)
aza.rename(columns={"Frequency": "aza_Frequency"}, inplace=True)
aza.rename(columns={"Start.Date": "aza_Start.Date"}, inplace=True)
aza.rename(columns={"On.going": "aza_On.going"}, inplace=True)
aza.rename(columns={"Stop.Date": "aza_Stop.Date"}, inplace=True)

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\805851823.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  aza.rename(columns={"Unit.of.Doses": "aza_Unit.of.Doses"}, inplace=True)
C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\805851823.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  aza.rename(columns={"Frequency": "aza_Frequency"}, inplace=True)
C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\805851823.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  aza.rename(columns={"Start.Date": "aza_Start.Date"}, inplace=True)
C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\805851823.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  aza.rename(columns={"On.going": "aza_On.going"}, inplace=True)
C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\805851823.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  aza.rename(columns={"Stop.Date": "aza_Stop.Date"}, inplace=True)

In [361]:
# Convert date columns to datetime format
aza['aza_Start.Date'] = pd.to_datetime(aza['aza_Start.Date'])
aza['aza_Stop.Date'] = pd.to_datetime(aza['aza_Stop.Date'])
mtp_with_intervals['Date_Of_Visit'] = pd.to_datetime(mtp_with_intervals['Date_Of_Visit'])

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\1174924826.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  aza['aza_Start.Date'] = pd.to_datetime(aza['aza_Start.Date'])
C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\1174924826.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  aza['aza_Stop.Date'] = pd.to_datetime(aza['aza_Stop.Date'])

In [363]:
data1.shape

(8027, 517)

In [364]:
import pandas as pd

# Convert date columns to datetime format
aza['aza_Start.Date'] = pd.to_datetime(aza['aza_Start.Date'])
aza['aza_Stop.Date'] = pd.to_datetime(aza['aza_Stop.Date'])
mtp_with_intervals['Date_Of_Visit'] = pd.to_datetime(mtp_with_intervals['Date_Of_Visit'])

# Perform a merge on 'RKD.ID' first
merged = mtp_with_intervals.merge(aza, on='RKD.ID', how='left')

# Filter rows where Start.Date < Date.Of.Visit <= Stop.Date
filtered = merged[
    (merged['aza_Start.Date'] < merged['Date_Of_Visit']) & 
    (merged['Date_Of_Visit'] <= merged['aza_Stop.Date'])
]

# Handle cases where aza_Stop.Date is missing (NaN)
filtered_na = merged[
    (merged['aza_Start.Date'] <=merged['Date_Of_Visit']) & 
    (pd.isna(merged['aza_Stop.Date']))
]

# Combine both filtered DataFrames
merged_filtered = pd.concat([filtered, filtered_na])

# Select relevant columns to merge into dataall
cols_to_merge = ['aza_Unit.of.Doses',  'aza_Frequency','aza_Start.Date','aza_On.going','aza_Stop.Date']
mtp_with_intervals = mtp_with_intervals.merge(merged_filtered[['RKD.ID', 'Date_Of_Visit'] + cols_to_merge], 
                        on=['RKD.ID', 'Date_Of_Visit'], how='left')

mtp_with_intervals

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\3199979220.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  aza['aza_Start.Date'] = pd.to_datetime(aza['aza_Start.Date'])
C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\3199979220.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  aza['aza_Stop.Date'] = pd.to_datetime(aza['aza_Stop.Date'])

,RKD.ID,Date_Of_Visit,ANCA_Levels,anca_status,ancaswitch,Repeat.Instrument,Repeat.Instance.x,Data.Access.Group.x,Patient.ID,COVID.19.related.entry.,...,Prd_Frequency,Prd_Start.Date,Prd_On.going,Prd_Stop.Date,prd_Dose_cat2,aza_Unit.of.Doses,aza_Frequency,aza_Start.Date,aza_On.going,aza_Stop.Date
0,1,2012-08-31,134.0,ANCA Positive,Switch Status Unknown,Encounters,1,TUH - Tallaght,1,No,...,NaN,NaT,NaN,NaT,NaN,NaN,NaN,NaT,NaN,NaT
1,1,2012-09-07,NaN,ANCA Positive,Pos-Pos Switch,Encounters,36,TUH - Tallaght,1,No,...,Daily,2012-08-31,No,2012-09-07,> 20 mg/day,NaN,NaN,NaT,NaN,NaT
2,1,2012-09-17,110.0,ANCA Positive,Pos-Pos Switch,Encounters,37,TUH - Tallaght,1,No,...,Daily,2012-09-07,No,2012-10-19,> 20 mg/day,NaN,NaN,NaT,NaN,NaT
3,1,2012-09-21,92.0,ANCA Positive,Pos-Pos Switch,Encounters,2,TUH - Tallaght,1,No,...,Daily,2012-09-07,No,2012-10-19,> 20 mg/day,NaN,NaN,NaT,NaN,NaT
4,1,2012-09-28,NaN,ANCA Positive,Pos-Pos Switch,Encounters,28,TUH - Tallaght,1,No,...,Daily,2012-09-07,No,2012-10-19,> 20 mg/day,NaN,NaN,NaT,NaN,NaT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8146,28793,2026-01-21,147.0,ANCA Positive,Switch Status Unknown,Encounters,1,CUH - Cork University Hospital,28793,No,...,NaN,NaT,NaN,NaT,NaN,NaN,NaN,NaT,NaN,NaT
8147,28796,2025-07-28,NaN,ANCA Status Unknown,Switch Status Unknown,Encounters,2,NaN,28796,No,...,NaN,NaT,NaN,NaT,NaN,NaN,NaN,NaT,NaN,NaT
8148,28796,2026-01-30,NaN,ANCA Negative,Switch Status Unknown,Encounters,1,NaN,28796,No,...,Daily,2026-01-19,Yes,2026-02-02,11 - 20 mg/day,NaN,NaN,NaT,NaN,NaT
8149,28797,2026-02-02,134.0,ANCA Positive,Switch Status Unknown,Encounters,1,CUH - Cork University Hospital,28797,NaN,...,NaN,NaT,NaN,NaT,NaN,NaN,NaN,NaT,NaN,NaT
8150,28797,2026-03-26,134.0,ANCA Positive,Pos-Pos Switch,Encounters,2,CUH - Cork University Hospital,28797,NaN,...,NaN,NaT,NaN,NaT,NaN,NaN,NaN,NaT,NaN,NaT

In [365]:
mtp_with_intervals=mtp_with_intervals.drop_duplicates(subset=['RKD.ID','Date_Of_Visit'], keep='first')
mtp_with_intervals

,RKD.ID,Date_Of_Visit,ANCA_Levels,anca_status,ancaswitch,Repeat.Instrument,Repeat.Instance.x,Data.Access.Group.x,Patient.ID,COVID.19.related.entry.,...,Prd_Frequency,Prd_Start.Date,Prd_On.going,Prd_Stop.Date,prd_Dose_cat2,aza_Unit.of.Doses,aza_Frequency,aza_Start.Date,aza_On.going,aza_Stop.Date
0,1,2012-08-31,134.0,ANCA Positive,Switch Status Unknown,Encounters,1,TUH - Tallaght,1,No,...,NaN,NaT,NaN,NaT,NaN,NaN,NaN,NaT,NaN,NaT
1,1,2012-09-07,NaN,ANCA Positive,Pos-Pos Switch,Encounters,36,TUH - Tallaght,1,No,...,Daily,2012-08-31,No,2012-09-07,> 20 mg/day,NaN,NaN,NaT,NaN,NaT
2,1,2012-09-17,110.0,ANCA Positive,Pos-Pos Switch,Encounters,37,TUH - Tallaght,1,No,...,Daily,2012-09-07,No,2012-10-19,> 20 mg/day,NaN,NaN,NaT,NaN,NaT
3,1,2012-09-21,92.0,ANCA Positive,Pos-Pos Switch,Encounters,2,TUH - Tallaght,1,No,...,Daily,2012-09-07,No,2012-10-19,> 20 mg/day,NaN,NaN,NaT,NaN,NaT
4,1,2012-09-28,NaN,ANCA Positive,Pos-Pos Switch,Encounters,28,TUH - Tallaght,1,No,...,Daily,2012-09-07,No,2012-10-19,> 20 mg/day,NaN,NaN,NaT,NaN,NaT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8146,28793,2026-01-21,147.0,ANCA Positive,Switch Status Unknown,Encounters,1,CUH - Cork University Hospital,28793,No,...,NaN,NaT,NaN,NaT,NaN,NaN,NaN,NaT,NaN,NaT
8147,28796,2025-07-28,NaN,ANCA Status Unknown,Switch Status Unknown,Encounters,2,NaN,28796,No,...,NaN,NaT,NaN,NaT,NaN,NaN,NaN,NaT,NaN,NaT
8148,28796,2026-01-30,NaN,ANCA Negative,Switch Status Unknown,Encounters,1,NaN,28796,No,...,Daily,2026-01-19,Yes,2026-02-02,11 - 20 mg/day,NaN,NaN,NaT,NaN,NaT
8149,28797,2026-02-02,134.0,ANCA Positive,Switch Status Unknown,Encounters,1,CUH - Cork University Hospital,28797,NaN,...,NaN,NaT,NaN,NaT,NaN,NaN,NaN,NaT,NaN,NaT
8150,28797,2026-03-26,134.0,ANCA Positive,Pos-Pos Switch,Encounters,2,CUH - Cork University Hospital,28797,NaN,...,NaN,NaT,NaN,NaT,NaN,NaN,NaN,NaT,NaN,NaT

In [366]:
import numpy as np

# Set specified columns to NaN where 'aza_Start.Date' equals 'Date.Of.Visit'
cols_to_nan = cols_to_merge = ['aza_Unit.of.Doses', 'aza_Frequency','aza_Start.Date','aza_On.going','aza_Stop.Date']

mtp_with_intervals.loc[mtp_with_intervals['aza_Start.Date'] == mtp_with_intervals['Date_Of_Visit'], cols_to_nan] = np.nan

mtp_with_intervals

,RKD.ID,Date_Of_Visit,ANCA_Levels,anca_status,ancaswitch,Repeat.Instrument,Repeat.Instance.x,Data.Access.Group.x,Patient.ID,COVID.19.related.entry.,...,Prd_Frequency,Prd_Start.Date,Prd_On.going,Prd_Stop.Date,prd_Dose_cat2,aza_Unit.of.Doses,aza_Frequency,aza_Start.Date,aza_On.going,aza_Stop.Date
0,1,2012-08-31,134.0,ANCA Positive,Switch Status Unknown,Encounters,1,TUH - Tallaght,1,No,...,NaN,NaT,NaN,NaT,NaN,NaN,NaN,NaT,NaN,NaT
1,1,2012-09-07,NaN,ANCA Positive,Pos-Pos Switch,Encounters,36,TUH - Tallaght,1,No,...,Daily,2012-08-31,No,2012-09-07,> 20 mg/day,NaN,NaN,NaT,NaN,NaT
2,1,2012-09-17,110.0,ANCA Positive,Pos-Pos Switch,Encounters,37,TUH - Tallaght,1,No,...,Daily,2012-09-07,No,2012-10-19,> 20 mg/day,NaN,NaN,NaT,NaN,NaT
3,1,2012-09-21,92.0,ANCA Positive,Pos-Pos Switch,Encounters,2,TUH - Tallaght,1,No,...,Daily,2012-09-07,No,2012-10-19,> 20 mg/day,NaN,NaN,NaT,NaN,NaT
4,1,2012-09-28,NaN,ANCA Positive,Pos-Pos Switch,Encounters,28,TUH - Tallaght,1,No,...,Daily,2012-09-07,No,2012-10-19,> 20 mg/day,NaN,NaN,NaT,NaN,NaT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8146,28793,2026-01-21,147.0,ANCA Positive,Switch Status Unknown,Encounters,1,CUH - Cork University Hospital,28793,No,...,NaN,NaT,NaN,NaT,NaN,NaN,NaN,NaT,NaN,NaT
8147,28796,2025-07-28,NaN,ANCA Status Unknown,Switch Status Unknown,Encounters,2,NaN,28796,No,...,NaN,NaT,NaN,NaT,NaN,NaN,NaN,NaT,NaN,NaT
8148,28796,2026-01-30,NaN,ANCA Negative,Switch Status Unknown,Encounters,1,NaN,28796,No,...,Daily,2026-01-19,Yes,2026-02-02,11 - 20 mg/day,NaN,NaN,NaT,NaN,NaT
8149,28797,2026-02-02,134.0,ANCA Positive,Switch Status Unknown,Encounters,1,CUH - Cork University Hospital,28797,NaN,...,NaN,NaT,NaN,NaT,NaN,NaN,NaN,NaT,NaN,NaT
8150,28797,2026-03-26,134.0,ANCA Positive,Pos-Pos Switch,Encounters,2,CUH - Cork University Hospital,28797,NaN,...,NaN,NaT,NaN,NaT,NaN,NaN,NaN,NaT,NaN,NaT

In [367]:
mtp_with_intervals = (
    mtp_with_intervals
    .sort_values(['RKD.ID', 'Date_Of_Visit'])
)

# duplicate the column
mtp_with_intervals['aza_Stop.Date_ffill'] = (
    mtp_with_intervals['aza_Stop.Date']
)

# forward fill within each patient
mtp_with_intervals['aza_Stop.Date_ffill'] = (
    mtp_with_intervals
    .groupby('RKD.ID')['aza_Stop.Date_ffill']
    .ffill()
)

In [368]:
mtp_with_intervals['interval_from_aza_stop_date'] = (
    mtp_with_intervals['Date_Of_Visit'] -
    mtp_with_intervals['aza_Stop.Date_ffill']
).dt.days

In [369]:
# Ensure Age and Dose are numeric
mtp_with_intervals["Age_Encounters"] = pd.to_numeric(
    mtp_with_intervals["Age_Encounters"], errors="coerce"
)

dose_col = "Dose_Azathioprine - UATC/L04AX01"
mtp_with_intervals[dose_col] = pd.to_numeric(
    mtp_with_intervals[dose_col], errors="coerce"
)

age = mtp_with_intervals["Age_Encounters"]
dose = mtp_with_intervals[dose_col]

mtp_with_intervals["aza_absolute_dose"] = np.select(
    [
        age.between(65, 73, inclusive="both"),
        age.between(74, 82, inclusive="both"),
        age.gt(82),
    ],
    [
        dose + 50,   # 65–73: +50 mg
        dose + 100,  # 74–82: +100 mg
        dose + 150,  # >82: +150 mg
    ],
    default=dose    # <=64 or missing: no change
)

## Calculate aza absolute dose

In [370]:
# Ensure lymphocyte count and dose are numeric
mtp_with_intervals["lymphocyte_count"] = pd.to_numeric(
    mtp_with_intervals["lymphocyte_count"], errors="coerce"
)

dose_col = "aza_absolute_dose"
mtp_with_intervals[dose_col] = pd.to_numeric(
    mtp_with_intervals[dose_col], errors="coerce"
)

lymph = mtp_with_intervals["lymphocyte_count"]
dose = mtp_with_intervals[dose_col]

mtp_with_intervals["aza_absolute_dose"] = np.select(
    [
        lymph.gt(0.3) & lymph.le(0.7),  # >0.3 to ≤0.7
        lymph.le(0.3)                   # ≤0.3
    ],
    [
        dose + 50,   # +50 mg
        dose + 100   # +100 mg
    ],
    default=dose     # >0.7 (no change) or missing values
)

In [371]:
mtp_with_intervals["aza_absolute_dose"].value_counts(dropna=False)

aza_absolute_dose
NaN      6797
150.0     292
100.0     247
200.0     172
50.0       86
75.0       82
175.0      77
125.0      72
250.0      67
225.0      52
25.0       21
275.0      19
300.0      17
137.5       6
325.0       5
350.0       4
187.5       4
212.5       2
37.5        2
12.5        1
262.5       1
280.0       1
Name: count, dtype: int64

In [372]:
# enforce minimum dose of 25 mg
mtp_with_intervals.loc[
    mtp_with_intervals['aza_absolute_dose'] < 25,
    'aza_absolute_dose'
] = 25

In [373]:
# enforce minimum dose of 25 mg
mtp_with_intervals.loc[
    mtp_with_intervals['aza_absolute_dose'] >250,
    'aza_absolute_dose'
] = 250

In [374]:
# create a duplicate column
mtp_with_intervals['aza_Dose_ffill'] = mtp_with_intervals['aza_absolute_dose']

# forward fill the duplicated column
mtp_with_intervals['aza_Dose_ffill'] = (
    mtp_with_intervals['aza_Dose_ffill'].ffill()
)

In [375]:
mtp_with_intervals['aza_absolute_dose'].describe()

count    1230.000000
mean      145.243902
std        58.805504
min        25.000000
25%       100.000000
50%       150.000000
75%       200.000000
max       250.000000
Name: aza_absolute_dose, dtype: float64

## calculate aza ITIS

In [376]:
import pandas as pd
import numpy as np
from datetime import datetime, timedelta

# Define dose-effect parameters
min_dose = 25.0
max_dose = 250.0
min_score = 0.15
max_score = 0.60


# Function to calculate scores
def calculate_score(dose, min_dose, max_dose, min_score, max_score):
    if dose <= min_dose:
        return min_score
    elif dose >= max_dose:
        return max_score
    else:
        return min_score + ((dose - min_dose) / (max_dose - min_dose)) * (max_score - min_score)

# Convert the dose column to numeric, ignoring 'NA'
mtp_with_intervals["aza_absolute_dose"] = pd.to_numeric(mtp_with_intervals["aza_absolute_dose"], errors='coerce')

# Calculate scores, ignoring 'NA'
mtp_with_intervals["Aza_ITIS"] =mtp_with_intervals["aza_absolute_dose"].apply(
    lambda dose: calculate_score(dose, min_dose, max_dose, min_score, max_score) if not np.isnan(dose) else None
)

In [377]:
import numpy as np
import pandas as pd

# ---------------------------------------------
# 1. Sigmoid function
# ---------------------------------------------
def sigmoid_curve(x, A, n, d):
    return A / (1 + np.exp(n * (x - d)))

# ---------------------------------------------
# 2. Interpolation functions for A(dose), d(dose), n(dose)
# ---------------------------------------------
A1 = 0.15
A2 = 0.60
dose1 = 25
dose2 = 250

m_A = (A2 - A1) / (dose2 - dose1)
b_A = A1 - m_A * dose1
def calculate_A(dose):
    return m_A * dose + b_A

d1 = 8
d2 = 10
m_d = (d2 - d1) / (dose2 - dose1)
b_d = d1 - m_d * dose1
def calculate_d(dose):
    return m_d * dose + b_d

# vanish logic
def calculate_n_from_vanish(A, d, vanish_day):
    return np.log(99) / (vanish_day - d)

vanish1 = 10
vanish2 = 14
n1 = calculate_n_from_vanish(A1, d1, vanish1)
n2 = calculate_n_from_vanish(A2, d2, vanish2)

m_n = (n2 - n1) / (dose2 - dose1)
b_n = n1 - m_n * dose1
def calculate_n(dose):
    return m_n * dose + b_n

# ---------------------------------------------
# 3. Apply model to each row of mtp_with_intervals
# ---------------------------------------------
def compute_ITIS(row):
    dose = row["aza_Dose_ffill"]
    time = row["interval_from_aza_stop_date"]

    # Skip invalid values
    if pd.isna(dose) or pd.isna(time):
        return np.nan

    A = calculate_A(dose)
    d = calculate_d(dose)
    n = calculate_n(dose)

    return sigmoid_curve(time, A, n, d)

# Create new column
mtp_with_intervals["Aza_ITIS2"] = mtp_with_intervals.apply(compute_ITIS, axis=1)

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\31742642.py:8: RuntimeWarning: overflow encountered in exp
  return A / (1 + np.exp(n * (x - d)))

In [378]:
# round to 2 decimal places
mtp_with_intervals['Aza_ITIS2'] = (
    mtp_with_intervals['Aza_ITIS2'].round(2)
)

In [379]:
mtp_with_intervals['Aza_ITIS'] = (
    mtp_with_intervals['Aza_ITIS']
    .fillna(mtp_with_intervals['Aza_ITIS2'])
)

In [380]:
cols_to_drop = [
    'aza_Stop.Date_ffill',
    'interval_from_aza_stop_date',
    'aza_Dose_ffill',
    'Aza_ITIS2'
]

mtp_with_intervals.drop(columns=cols_to_drop, inplace=True)

In [381]:
mtp_with_intervals['Aza_ITIS'].fillna(0, inplace=True)
mtp_with_intervals['Aza_ITIS']

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\206142245.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  mtp_with_intervals['Aza_ITIS'].fillna(0, inplace=True)

0       0.0
1       0.0
2       0.0
3       0.0
4       0.0
       ...
8146    0.0
8147    0.0
8148    0.0
8149    0.0
8150    0.0
Name: Aza_ITIS, Length: 8027, dtype: float64

In [382]:
mask = (
    (
        (mtp_with_intervals['Drug_Azathioprine - UATC/L04AX01']
         == 'Azathioprine - UATC/L04AX01')
        &
        (
            mtp_with_intervals['Aza_ITIS'].isna()
            | (mtp_with_intervals['Aza_ITIS'] == 0)
        )
    )
    |
    (
        mtp_with_intervals['treatment_type'].str.contains('Azathioprine - UATC/L04AX01', na=False)
        &
        (mtp_with_intervals['Aza_ITIS'] == 0)
    )
)

mtp_with_intervals.loc[mask, 'Aza_ITIS'] = 0.37

## MMF

In [383]:
mmf=conmed.loc[(conmed['Drug']=='Mycophenolate mofetil - UATC/L04AA06')]
mmf

,RKD.ID,Repeat.Instrument,Repeat.Instance,Data.Access.Group,Drug,Drug..ATC,Dose,Unit.of.Doses,Unit.of.Doses...Other,Frequency,Frequency...other,Start.Date,On.going,Stop.Date,Complete..6,Date.of.diagnosis,medstart_interval_from_diagnosis,medstop_interval_from_diagnosis
85,11,Treatment - Continuing medications,4,TUH - Tallaght,Mycophenolate mofetil - UATC/L04AA06,NaN,1000.0,mg,NaN,Twice daily,NaN,2013-09-06,No,2013-11-01,Complete,28/01/2013,221.0,277.0
87,11,Treatment - Continuing medications,6,TUH - Tallaght,Mycophenolate mofetil - UATC/L04AA06,NaN,2000.0,mg,NaN,Twice daily,NaN,2013-11-01,No,2014-09-19,Complete,28/01/2013,277.0,599.0
88,11,Treatment - Continuing medications,7,TUH - Tallaght,Mycophenolate mofetil - UATC/L04AA06,NaN,1500.0,mg,NaN,Twice daily,NaN,2014-09-19,No,2015-07-24,Complete,28/01/2013,599.0,907.0
90,11,Treatment - Continuing medications,9,TUH - Tallaght,Mycophenolate mofetil - UATC/L04AA06,NaN,750.0,mg,NaN,Daily,NaN,2015-07-24,No,2015-09-24,Complete,28/01/2013,907.0,969.0
91,11,Treatment - Continuing medications,10,TUH - Tallaght,Mycophenolate mofetil - UATC/L04AA06,NaN,500.0,mg,NaN,Daily,NaN,2015-09-24,No,2015-10-30,Complete,28/01/2013,969.0,1005.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6371,28709,Treatment - Continuing medications,1,TUH - Tallaght,Mycophenolate mofetil - UATC/L04AA06,NaN,1000.0,mg,NaN,Twice daily,NaN,2025-03-19,Yes,NaN,Incomplete,NaN,NaN,NaN
6375,28711,Treatment - Continuing medications,2,CUH - Cork University Hospital,Mycophenolate mofetil - UATC/L04AA06,NaN,1000.0,mg,NaN,Twice daily,NaN,2025-05-01,Yes,NaN,Complete,19/11/2021,1259.0,NaN
6385,28716,Treatment - Continuing medications,1,SJH - St. James Hospital,Mycophenolate mofetil - UATC/L04AA06,NaN,2.0,g,NaN,Twice daily,NaN,NaN,Yes,NaN,Complete,NaN,NaN,NaN
6437,28741,Treatment - Continuing medications,1,SJH - St. James Hospital,Mycophenolate mofetil - UATC/L04AA06,NaN,1000.0,mg,NaN,Twice daily,NaN,NaN,Yes,NaN,Complete,NaN,NaN,NaN
6557,28788,Treatment - Continuing medications,2,TUH - Tallaght,Mycophenolate mofetil - UATC/L04AA06,NaN,1000.0,mg,NaN,Twice daily,NaN,2025-12-17,Yes,NaN,Incomplete,NaN,NaN,NaN

In [384]:
mmf.rename(columns={"Unit.of.Doses": "mmf_Unit.of.Doses"}, inplace=True)
mmf.rename(columns={"Frequency": "mmf_Frequency"}, inplace=True)
mmf.rename(columns={"Start.Date": "mmf_Start.Date"}, inplace=True)
mmf.rename(columns={"On.going": "mmf_On.going"}, inplace=True)
mmf.rename(columns={"Stop.Date": "mmf_Stop.Date"}, inplace=True)

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\4048657092.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mmf.rename(columns={"Unit.of.Doses": "mmf_Unit.of.Doses"}, inplace=True)
C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\4048657092.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mmf.rename(columns={"Frequency": "mmf_Frequency"}, inplace=True)
C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\4048657092.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mmf.rename(columns={"Start.Date": "mmf_Start.Date"}, inplace=True)
C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\4048657092.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mmf.rename(columns={"On.going": "mmf_On.going"}, inplace=True)
C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\4048657092.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mmf.rename(columns={"Stop.Date": "mmf_Stop.Date"}, inplace=True)

In [385]:
# Convert date columns to datetime format
mmf['mmf_Start.Date'] = pd.to_datetime(mmf['mmf_Start.Date'])
mmf['mmf_Stop.Date'] = pd.to_datetime(mmf['mmf_Stop.Date'])
mtp_with_intervals['Date_Of_Visit'] = pd.to_datetime(mtp_with_intervals['Date_Of_Visit'])

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\2540323406.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mmf['mmf_Start.Date'] = pd.to_datetime(mmf['mmf_Start.Date'])
C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\2540323406.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mmf['mmf_Stop.Date'] = pd.to_datetime(mmf['mmf_Stop.Date'])

In [386]:
import pandas as pd

# Convert date columns to datetime format
mmf['mmf_Start.Date'] = pd.to_datetime(mmf['mmf_Start.Date'])
mmf['mmf_Stop.Date'] = pd.to_datetime(mmf['mmf_Stop.Date'])
mtp_with_intervals['Date_Of_Visit'] = pd.to_datetime(mtp_with_intervals['Date_Of_Visit'])

# Perform a merge on 'RKD.ID' first
merged = mtp_with_intervals.merge(mmf, on='RKD.ID', how='left')

# Filter rows where Start.Date < Date.Of.Visit <= Stop.Date
filtered = merged[
    (merged['mmf_Start.Date'] < merged['Date_Of_Visit']) & 
    (merged['Date_Of_Visit'] <= merged['mmf_Stop.Date'])
]

# Handle cases where mmf_Stop.Date is missing (NaN)
filtered_na = merged[
    (merged['mmf_Start.Date'] <=merged['Date_Of_Visit']) & 
    (pd.isna(merged['mmf_Stop.Date']))
]

# Combine both filtered DataFrames
merged_filtered = pd.concat([filtered, filtered_na])

# Select relevant columns to merge into dataall
cols_to_merge = ['mmf_Unit.of.Doses',  'mmf_Frequency','mmf_Start.Date','mmf_On.going','mmf_Stop.Date']
mtp_with_intervals = mtp_with_intervals.merge(merged_filtered[['RKD.ID', 'Date_Of_Visit'] + cols_to_merge], 
                        on=['RKD.ID', 'Date_Of_Visit'], how='left')

mtp_with_intervals

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\352741608.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mmf['mmf_Start.Date'] = pd.to_datetime(mmf['mmf_Start.Date'])
C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\352741608.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mmf['mmf_Stop.Date'] = pd.to_datetime(mmf['mmf_Stop.Date'])

,RKD.ID,Date_Of_Visit,ANCA_Levels,anca_status,ancaswitch,Repeat.Instrument,Repeat.Instance.x,Data.Access.Group.x,Patient.ID,COVID.19.related.entry.,...,aza_Start.Date,aza_On.going,aza_Stop.Date,aza_absolute_dose,Aza_ITIS,mmf_Unit.of.Doses,mmf_Frequency,mmf_Start.Date,mmf_On.going,mmf_Stop.Date
0,1,2012-08-31,134.0,ANCA Positive,Switch Status Unknown,Encounters,1,TUH - Tallaght,1,No,...,NaT,NaN,NaT,NaN,0.0,NaN,NaN,NaT,NaN,NaT
1,1,2012-09-07,NaN,ANCA Positive,Pos-Pos Switch,Encounters,36,TUH - Tallaght,1,No,...,NaT,NaN,NaT,NaN,0.0,NaN,NaN,NaT,NaN,NaT
2,1,2012-09-17,110.0,ANCA Positive,Pos-Pos Switch,Encounters,37,TUH - Tallaght,1,No,...,NaT,NaN,NaT,NaN,0.0,NaN,NaN,NaT,NaN,NaT
3,1,2012-09-21,92.0,ANCA Positive,Pos-Pos Switch,Encounters,2,TUH - Tallaght,1,No,...,NaT,NaN,NaT,NaN,0.0,NaN,NaN,NaT,NaN,NaT
4,1,2012-09-28,NaN,ANCA Positive,Pos-Pos Switch,Encounters,28,TUH - Tallaght,1,No,...,NaT,NaN,NaT,NaN,0.0,NaN,NaN,NaT,NaN,NaT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8041,28793,2026-01-21,147.0,ANCA Positive,Switch Status Unknown,Encounters,1,CUH - Cork University Hospital,28793,No,...,NaT,NaN,NaT,NaN,0.0,NaN,NaN,NaT,NaN,NaT
8042,28796,2025-07-28,NaN,ANCA Status Unknown,Switch Status Unknown,Encounters,2,NaN,28796,No,...,NaT,NaN,NaT,NaN,0.0,NaN,NaN,NaT,NaN,NaT
8043,28796,2026-01-30,NaN,ANCA Negative,Switch Status Unknown,Encounters,1,NaN,28796,No,...,NaT,NaN,NaT,NaN,0.0,NaN,NaN,NaT,NaN,NaT
8044,28797,2026-02-02,134.0,ANCA Positive,Switch Status Unknown,Encounters,1,CUH - Cork University Hospital,28797,NaN,...,NaT,NaN,NaT,NaN,0.0,NaN,NaN,NaT,NaN,NaT
8045,28797,2026-03-26,134.0,ANCA Positive,Pos-Pos Switch,Encounters,2,CUH - Cork University Hospital,28797,NaN,...,NaT,NaN,NaT,NaN,0.0,NaN,NaN,NaT,NaN,NaT

In [387]:
mtp_with_intervals=mtp_with_intervals.drop_duplicates(subset=['RKD.ID','Date_Of_Visit'], keep='first')
mtp_with_intervals

,RKD.ID,Date_Of_Visit,ANCA_Levels,anca_status,ancaswitch,Repeat.Instrument,Repeat.Instance.x,Data.Access.Group.x,Patient.ID,COVID.19.related.entry.,...,aza_Start.Date,aza_On.going,aza_Stop.Date,aza_absolute_dose,Aza_ITIS,mmf_Unit.of.Doses,mmf_Frequency,mmf_Start.Date,mmf_On.going,mmf_Stop.Date
0,1,2012-08-31,134.0,ANCA Positive,Switch Status Unknown,Encounters,1,TUH - Tallaght,1,No,...,NaT,NaN,NaT,NaN,0.0,NaN,NaN,NaT,NaN,NaT
1,1,2012-09-07,NaN,ANCA Positive,Pos-Pos Switch,Encounters,36,TUH - Tallaght,1,No,...,NaT,NaN,NaT,NaN,0.0,NaN,NaN,NaT,NaN,NaT
2,1,2012-09-17,110.0,ANCA Positive,Pos-Pos Switch,Encounters,37,TUH - Tallaght,1,No,...,NaT,NaN,NaT,NaN,0.0,NaN,NaN,NaT,NaN,NaT
3,1,2012-09-21,92.0,ANCA Positive,Pos-Pos Switch,Encounters,2,TUH - Tallaght,1,No,...,NaT,NaN,NaT,NaN,0.0,NaN,NaN,NaT,NaN,NaT
4,1,2012-09-28,NaN,ANCA Positive,Pos-Pos Switch,Encounters,28,TUH - Tallaght,1,No,...,NaT,NaN,NaT,NaN,0.0,NaN,NaN,NaT,NaN,NaT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8041,28793,2026-01-21,147.0,ANCA Positive,Switch Status Unknown,Encounters,1,CUH - Cork University Hospital,28793,No,...,NaT,NaN,NaT,NaN,0.0,NaN,NaN,NaT,NaN,NaT
8042,28796,2025-07-28,NaN,ANCA Status Unknown,Switch Status Unknown,Encounters,2,NaN,28796,No,...,NaT,NaN,NaT,NaN,0.0,NaN,NaN,NaT,NaN,NaT
8043,28796,2026-01-30,NaN,ANCA Negative,Switch Status Unknown,Encounters,1,NaN,28796,No,...,NaT,NaN,NaT,NaN,0.0,NaN,NaN,NaT,NaN,NaT
8044,28797,2026-02-02,134.0,ANCA Positive,Switch Status Unknown,Encounters,1,CUH - Cork University Hospital,28797,NaN,...,NaT,NaN,NaT,NaN,0.0,NaN,NaN,NaT,NaN,NaT
8045,28797,2026-03-26,134.0,ANCA Positive,Pos-Pos Switch,Encounters,2,CUH - Cork University Hospital,28797,NaN,...,NaT,NaN,NaT,NaN,0.0,NaN,NaN,NaT,NaN,NaT

In [388]:
import numpy as np

# Set specified columns to NaN where 'mmf_Start.Date' equals 'Date.Of.Visit'
cols_to_nan = cols_to_merge = ['mmf_Unit.of.Doses', 'mmf_Frequency','mmf_Start.Date','mmf_On.going','mmf_Stop.Date']

mtp_with_intervals.loc[mtp_with_intervals['mmf_Start.Date'] == mtp_with_intervals['Date_Of_Visit'], cols_to_nan] = np.nan

mtp_with_intervals

,RKD.ID,Date_Of_Visit,ANCA_Levels,anca_status,ancaswitch,Repeat.Instrument,Repeat.Instance.x,Data.Access.Group.x,Patient.ID,COVID.19.related.entry.,...,aza_Start.Date,aza_On.going,aza_Stop.Date,aza_absolute_dose,Aza_ITIS,mmf_Unit.of.Doses,mmf_Frequency,mmf_Start.Date,mmf_On.going,mmf_Stop.Date
0,1,2012-08-31,134.0,ANCA Positive,Switch Status Unknown,Encounters,1,TUH - Tallaght,1,No,...,NaT,NaN,NaT,NaN,0.0,NaN,NaN,NaT,NaN,NaT
1,1,2012-09-07,NaN,ANCA Positive,Pos-Pos Switch,Encounters,36,TUH - Tallaght,1,No,...,NaT,NaN,NaT,NaN,0.0,NaN,NaN,NaT,NaN,NaT
2,1,2012-09-17,110.0,ANCA Positive,Pos-Pos Switch,Encounters,37,TUH - Tallaght,1,No,...,NaT,NaN,NaT,NaN,0.0,NaN,NaN,NaT,NaN,NaT
3,1,2012-09-21,92.0,ANCA Positive,Pos-Pos Switch,Encounters,2,TUH - Tallaght,1,No,...,NaT,NaN,NaT,NaN,0.0,NaN,NaN,NaT,NaN,NaT
4,1,2012-09-28,NaN,ANCA Positive,Pos-Pos Switch,Encounters,28,TUH - Tallaght,1,No,...,NaT,NaN,NaT,NaN,0.0,NaN,NaN,NaT,NaN,NaT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8041,28793,2026-01-21,147.0,ANCA Positive,Switch Status Unknown,Encounters,1,CUH - Cork University Hospital,28793,No,...,NaT,NaN,NaT,NaN,0.0,NaN,NaN,NaT,NaN,NaT
8042,28796,2025-07-28,NaN,ANCA Status Unknown,Switch Status Unknown,Encounters,2,NaN,28796,No,...,NaT,NaN,NaT,NaN,0.0,NaN,NaN,NaT,NaN,NaT
8043,28796,2026-01-30,NaN,ANCA Negative,Switch Status Unknown,Encounters,1,NaN,28796,No,...,NaT,NaN,NaT,NaN,0.0,NaN,NaN,NaT,NaN,NaT
8044,28797,2026-02-02,134.0,ANCA Positive,Switch Status Unknown,Encounters,1,CUH - Cork University Hospital,28797,NaN,...,NaT,NaN,NaT,NaN,0.0,NaN,NaN,NaT,NaN,NaT
8045,28797,2026-03-26,134.0,ANCA Positive,Pos-Pos Switch,Encounters,2,CUH - Cork University Hospital,28797,NaN,...,NaT,NaN,NaT,NaN,0.0,NaN,NaN,NaT,NaN,NaT

In [389]:
mtp_with_intervals = (
    mtp_with_intervals
    .sort_values(['RKD.ID', 'Date_Of_Visit'])
)

# duplicate the column
mtp_with_intervals['mmf_Stop.Date_ffill'] = (
    mtp_with_intervals['mmf_Stop.Date']
)

# forward fill within each patient
mtp_with_intervals['mmf_Stop.Date_ffill'] = (
    mtp_with_intervals
    .groupby('RKD.ID')['mmf_Stop.Date_ffill']
    .ffill()
)

In [390]:
mtp_with_intervals['interval_from_mmf_stop_date'] = (
    mtp_with_intervals['Date_Of_Visit'] -
    mtp_with_intervals['mmf_Stop.Date_ffill']
).dt.days

In [391]:
# Ensure Age and Dose are numeric
mtp_with_intervals["Age_Encounters"] = pd.to_numeric(
    mtp_with_intervals["Age_Encounters"], errors="coerce"
)

dose_col = "Dose_Mycophenolate mofetil - UATC/L04AA06"
mtp_with_intervals[dose_col] = pd.to_numeric(
    mtp_with_intervals[dose_col], errors="coerce"
)

age = mtp_with_intervals["Age_Encounters"]
dose = mtp_with_intervals[dose_col]

mtp_with_intervals["mmf_relative_dose"] = np.select(
    [
        age.between(65, 73, inclusive="both"),
        age.between(74, 82, inclusive="both"),
        age.gt(82),
    ],
    [
        dose * 1.5,  # 65–73: +50%
        dose * 2.0,  # 74–82: +100%
        dose * 2.5,  # >82: +150%
    ],
    default=dose    # <=64 or missing: no change
)

In [392]:
# Ensure lymphocyte count and dose are numeric
mtp_with_intervals["lymphocyte_count"] = pd.to_numeric(
    mtp_with_intervals["lymphocyte_count"], errors="coerce"
)

dose_col = "mmf_relative_dose"
mtp_with_intervals[dose_col] = pd.to_numeric(
    mtp_with_intervals[dose_col], errors="coerce"
)

lymph = mtp_with_intervals["lymphocyte_count"]
dose = mtp_with_intervals[dose_col]

mtp_with_intervals["mmf_relative_dose2"] = np.select(
    [
        lymph.gt(0.3) & lymph.le(0.7),  # >0.3 to ≤0.7
        lymph.le(0.3)                   # ≤0.3
    ],
    [
        dose * 1.5,  # +50%
        dose * 2.0   # +100%
    ],
    default=mtp_with_intervals["mmf_relative_dose"]  # >0.7 or missing → keep prior algorithm result
)

In [393]:
# enforce minimum dose of 25 mg
mtp_with_intervals.loc[
    mtp_with_intervals['mmf_relative_dose2'] < 125,
    'mmf_relative_dose2'
] = 125

In [396]:
# enforce minimum dose of 25 mg
mtp_with_intervals.loc[
    mtp_with_intervals['mmf_relative_dose2'] > 4000,
    'mmf_relative_dose2'
] = 4000

In [397]:

# create a duplicate column
mtp_with_intervals['mmf_Dose_ffill'] = mtp_with_intervals['mmf_relative_dose2']

# forward fill the duplicated column
mtp_with_intervals['mmf_Dose_ffill'] = (
    mtp_with_intervals['mmf_Dose_ffill'].ffill()
)

In [398]:
mtp_with_intervals['mmf_relative_dose2'].describe()

count     332.000000
mean     1546.837349
std       855.520401
min       125.000000
25%      1000.000000
50%      1500.000000
75%      2000.000000
max      4000.000000
Name: mmf_relative_dose2, dtype: float64

In [399]:
import pandas as pd
import numpy as np
from datetime import datetime, timedelta

# Define dose-effect parameters
min_dose = 125.0
max_dose = 4000
min_score = 0.25
max_score = 0.75


# Function to calculate scores
def calculate_score(dose, min_dose, max_dose, min_score, max_score):
    if dose <= min_dose:
        return min_score
    elif dose >= max_dose:
        return max_score
    else:
        return min_score + ((dose - min_dose) / (max_dose - min_dose)) * (max_score - min_score)

# Convert the dose column to numeric, ignoring 'NA'
mtp_with_intervals["mmf_relative_dose2"] = pd.to_numeric(mtp_with_intervals["mmf_relative_dose2"], errors='coerce')

# Calculate scores, ignoring 'NA'
mtp_with_intervals["MMF_ITIS"] =mtp_with_intervals["mmf_relative_dose2"].apply(
    lambda dose: calculate_score(dose, min_dose, max_dose, min_score, max_score) if not np.isnan(dose) else None
)

In [400]:
import numpy as np
import pandas as pd

# ---------------------------------------------
# 1. Sigmoid function
# ---------------------------------------------
def sigmoid_curve(x, A, n, d):
    return A / (1 + np.exp(n * (x - d)))

# ---------------------------------------------
# 2. Interpolation functions for A(dose), d(dose), n(dose)
# ---------------------------------------------
A1 = 0.25
A2 = 0.75
dose1 = 125
dose2 = 4000

m_A = (A2 - A1) / (dose2 - dose1)
b_A = A1 - m_A * dose1
def calculate_A(dose):
    return m_A * dose + b_A

d1 = 5
d2 = 7
m_d = (d2 - d1) / (dose2 - dose1)
b_d = d1 - m_d * dose1
def calculate_d(dose):
    return m_d * dose + b_d

# vanish logic
def calculate_n_from_vanish(A, d, vanish_day):
    return np.log(99) / (vanish_day - d)

vanish1 = 7
vanish2 = 9
n1 = calculate_n_from_vanish(A1, d1, vanish1)
n2 = calculate_n_from_vanish(A2, d2, vanish2)

m_n = (n2 - n1) / (dose2 - dose1)
b_n = n1 - m_n * dose1
def calculate_n(dose):
    return m_n * dose + b_n

# ---------------------------------------------
# 3. Apply model to each row of mtp_with_intervals
# ---------------------------------------------
def compute_ITIS(row):
    dose = row["mmf_Dose_ffill"]
    time = row["interval_from_mmf_stop_date"]

    # Skip invalid values
    if pd.isna(dose) or pd.isna(time):
        return np.nan

    A = calculate_A(dose)
    d = calculate_d(dose)
    n = calculate_n(dose)

    return sigmoid_curve(time, A, n, d)

# Create new column
mtp_with_intervals["mmf_ITIS2"] = mtp_with_intervals.apply(compute_ITIS, axis=1)

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\2449369129.py:8: RuntimeWarning: overflow encountered in exp
  return A / (1 + np.exp(n * (x - d)))

In [401]:
# round to 2 decimal places
mtp_with_intervals['mmf_ITIS2'] = (
    mtp_with_intervals['mmf_ITIS2'].round(2)
)

In [402]:
mtp_with_intervals['MMF_ITIS'] = (
    mtp_with_intervals['MMF_ITIS']
    .fillna(mtp_with_intervals['mmf_ITIS2'])
)

In [403]:
cols_to_drop = [
    'mmf_Stop.Date_ffill',
    'interval_from_mmf_stop_date',
    'mmf_Dose_ffill',
    'mmf_ITIS2'
]

mtp_with_intervals.drop(columns=cols_to_drop, inplace=True)

In [404]:
mtp_with_intervals['MMF_ITIS'].fillna(0, inplace=True)
mtp_with_intervals['MMF_ITIS']

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\478583443.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  mtp_with_intervals['MMF_ITIS'].fillna(0, inplace=True)

0       0.0
1       0.0
2       0.0
3       0.0
4       0.0
       ...
8041    0.0
8042    0.0
8043    0.0
8044    0.0
8045    0.0
Name: MMF_ITIS, Length: 8027, dtype: float64

In [405]:
##mtp_with_intervals.to_csv('C:/Users/georgea1/OneDrive - Trinity College Dublin/Desktop/MMF_final2.csv',index=True)

In [406]:
mask = (
    (
        (mtp_with_intervals['Dose_Mycophenolate mofetil - UATC/L04AA06']
         == 'Mycophenolate mofetil - UATC/L04AA06')
        &
        (
            mtp_with_intervals['MMF_ITIS'].isna()
            | (mtp_with_intervals['MMF_ITIS'] == 0)
        )
    )
    |
    (
        mtp_with_intervals['treatment_type'].str.contains('Mycophenolate mofetil - UATC/L04AA06', na=False)
        &
        (mtp_with_intervals['MMF_ITIS'] == 0)
    )
)

mtp_with_intervals.loc[mask, 'MMF_ITIS'] = 0.50

In [407]:
#mtp_with_intervals=pd.read_csv("C:/Users/georgea1/OneDrive - Trinity College Dublin/Angel George/Chap 2. Treatment/Data/ITIS Data/RIV/March 2026/itis_final_age_lymphocytes_adjusted_RIV_15_03_2026.csv")
#mtp_with_intervals

## Methotrexate

In [408]:
meth=conmed.loc[(conmed['Drug']=='Methotrexate - UATC/L01BA01')]
meth

,RKD.ID,Repeat.Instrument,Repeat.Instance,Data.Access.Group,Drug,Drug..ATC,Dose,Unit.of.Doses,Unit.of.Doses...Other,Frequency,Frequency...other,Start.Date,On.going,Stop.Date,Complete..6,Date.of.diagnosis,medstart_interval_from_diagnosis,medstop_interval_from_diagnosis
115,16,Treatment - Continuing medications,1,TUH - Tallaght,Methotrexate - UATC/L01BA01,NaN,2.857143,mg,NaN,Once weekly,NaN,2012-10-03,Yes,NaN,Complete,01/07/2012,94.0,NaN
119,17,Treatment - Continuing medications,3,TUH - Tallaght,Methotrexate - UATC/L01BA01,NaN,1.071429,mg,NaN,Once weekly,NaN,2012-12-09,No,2014-03-14,Complete,01/08/2011,496.0,956.0
120,17,Treatment - Continuing medications,4,TUH - Tallaght,Methotrexate - UATC/L01BA01,NaN,1.428571,mg,NaN,Once weekly,NaN,2014-03-14,No,2014-08-08,Complete,01/08/2011,956.0,1103.0
122,17,Treatment - Continuing medications,6,TUH - Tallaght,Methotrexate - UATC/L01BA01,NaN,1.785714,mg,NaN,Once weekly,NaN,2014-08-08,Yes,NaN,Incomplete,01/08/2011,1103.0,NaN
170,29,Treatment - Continuing medications,14,TUH - Tallaght,Methotrexate - UATC/L01BA01,NaN,0.357143,mg,NaN,Once weekly,NaN,2014-02-28,No,2014-04-24,Complete,15/12/2001,4458.0,4513.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6271,28666,Treatment - Continuing medications,4,TUH - Tallaght,Methotrexate - UATC/L01BA01,NaN,2.857143,mg,NaN,Once weekly,NaN,2021-05-04,Yes,2022-10-04,Complete,02/11/2021,-182.0,336.0
6275,28673,Treatment - Continuing medications,1,SJH - St. James Hospital,Methotrexate - UATC/L01BA01,NaN,2.142857,mg,NaN,Once weekly,NaN,NaN,Yes,NaN,Complete,NaN,NaN,NaN
6400,28722,Treatment - Continuing medications,9,CUH - Cork University Hospital,Methotrexate - UATC/L01BA01,NaN,1.785714,mg,NaN,Once weekly,NaN,NaN,Yes,NaN,Incomplete,08/11/2022,NaN,NaN
6469,28750,Treatment - Continuing medications,1,CUH - Cork University Hospital,Methotrexate - UATC/L01BA01,NaN,2.857143,mg,NaN,Once weekly,NaN,2025-07-23,Yes,NaN,Unverified,24/07/2025,-1.0,NaN
6590,28795,Treatment - Continuing medications,2,TUH - Tallaght,Methotrexate - UATC/L01BA01,NaN,2.857143,mg,NaN,Once weekly,NaN,2025-07-30,Yes,NaN,Incomplete,30/07/2025,0.0,NaN

In [409]:
meth.rename(columns={"Unit.of.Doses": "meth_Unit.of.Doses"}, inplace=True)
meth.rename(columns={"Frequency": "meth_Frequency"}, inplace=True)
meth.rename(columns={"Start.Date": "meth_Start.Date"}, inplace=True)
meth.rename(columns={"On.going": "meth_On.going"}, inplace=True)
meth.rename(columns={"Stop.Date": "meth_Stop.Date"}, inplace=True)

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\420895135.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  meth.rename(columns={"Unit.of.Doses": "meth_Unit.of.Doses"}, inplace=True)
C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\420895135.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  meth.rename(columns={"Frequency": "meth_Frequency"}, inplace=True)
C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\420895135.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  meth.rename(columns={"Start.Date": "meth_Start.Date"}, inplace=True)
C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\420895135.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  meth.rename(columns={"On.going": "meth_On.going"}, inplace=True)
C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\420895135.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  meth.rename(columns={"Stop.Date": "meth_Stop.Date"}, inplace=True)

In [410]:
# Convert date columns to datetime format
meth['meth_Start.Date'] = pd.to_datetime(meth['meth_Start.Date'])
meth['meth_Stop.Date'] = pd.to_datetime(meth['meth_Stop.Date'])
mtp_with_intervals['Date_Of_Visit'] = pd.to_datetime(mtp_with_intervals['Date_Of_Visit'])

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\2677764742.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  meth['meth_Start.Date'] = pd.to_datetime(meth['meth_Start.Date'])
C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\2677764742.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  meth['meth_Stop.Date'] = pd.to_datetime(meth['meth_Stop.Date'])

In [411]:
import pandas as pd

# Convert date columns to datetime format
meth['meth_Start.Date'] = pd.to_datetime(meth['meth_Start.Date'])
meth['meth_Stop.Date'] = pd.to_datetime(meth['meth_Stop.Date'])
mtp_with_intervals['Date_Of_Visit'] = pd.to_datetime(mtp_with_intervals['Date_Of_Visit'])

# Perform a merge on 'RKD.ID' first
merged = mtp_with_intervals.merge(meth, on='RKD.ID', how='left')

# Filter rows where Start.Date < Date.Of.Visit <= Stop.Date
filtered = merged[
    (merged['meth_Start.Date'] < merged['Date_Of_Visit']) & 
    (merged['Date_Of_Visit'] <= merged['meth_Stop.Date'])
]

# Handle cases where meth_Stop.Date is missing (NaN)
filtered_na = merged[
    (merged['meth_Start.Date'] <=merged['Date_Of_Visit']) & 
    (pd.isna(merged['meth_Stop.Date']))
]

# Combine both filtered DataFrames
merged_filtered = pd.concat([filtered, filtered_na])

# Select relevant columns to merge into dataall
cols_to_merge = ['meth_Unit.of.Doses',  'meth_Frequency','meth_Start.Date','meth_On.going','meth_Stop.Date']
mtp_with_intervals = mtp_with_intervals.merge(merged_filtered[['RKD.ID', 'Date_Of_Visit'] + cols_to_merge], 
                        on=['RKD.ID', 'Date_Of_Visit'], how='left')

mtp_with_intervals

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\1176381568.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  meth['meth_Start.Date'] = pd.to_datetime(meth['meth_Start.Date'])
C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\1176381568.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  meth['meth_Stop.Date'] = pd.to_datetime(meth['meth_Stop.Date'])

,RKD.ID,Date_Of_Visit,ANCA_Levels,anca_status,ancaswitch,Repeat.Instrument,Repeat.Instance.x,Data.Access.Group.x,Patient.ID,COVID.19.related.entry.,...,mmf_On.going,mmf_Stop.Date,mmf_relative_dose,mmf_relative_dose2,MMF_ITIS,meth_Unit.of.Doses,meth_Frequency,meth_Start.Date,meth_On.going,meth_Stop.Date
0,1,2012-08-31,134.0,ANCA Positive,Switch Status Unknown,Encounters,1,TUH - Tallaght,1,No,...,NaN,NaT,NaN,NaN,0.0,NaN,NaN,NaT,NaN,NaT
1,1,2012-09-07,NaN,ANCA Positive,Pos-Pos Switch,Encounters,36,TUH - Tallaght,1,No,...,NaN,NaT,NaN,NaN,0.0,NaN,NaN,NaT,NaN,NaT
2,1,2012-09-17,110.0,ANCA Positive,Pos-Pos Switch,Encounters,37,TUH - Tallaght,1,No,...,NaN,NaT,NaN,NaN,0.0,NaN,NaN,NaT,NaN,NaT
3,1,2012-09-21,92.0,ANCA Positive,Pos-Pos Switch,Encounters,2,TUH - Tallaght,1,No,...,NaN,NaT,NaN,NaN,0.0,NaN,NaN,NaT,NaN,NaT
4,1,2012-09-28,NaN,ANCA Positive,Pos-Pos Switch,Encounters,28,TUH - Tallaght,1,No,...,NaN,NaT,NaN,NaN,0.0,NaN,NaN,NaT,NaN,NaT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8047,28793,2026-01-21,147.0,ANCA Positive,Switch Status Unknown,Encounters,1,CUH - Cork University Hospital,28793,No,...,NaN,NaT,NaN,NaN,0.0,NaN,NaN,NaT,NaN,NaT
8048,28796,2025-07-28,NaN,ANCA Status Unknown,Switch Status Unknown,Encounters,2,NaN,28796,No,...,NaN,NaT,NaN,NaN,0.0,NaN,NaN,NaT,NaN,NaT
8049,28796,2026-01-30,NaN,ANCA Negative,Switch Status Unknown,Encounters,1,NaN,28796,No,...,NaN,NaT,NaN,NaN,0.0,NaN,NaN,NaT,NaN,NaT
8050,28797,2026-02-02,134.0,ANCA Positive,Switch Status Unknown,Encounters,1,CUH - Cork University Hospital,28797,NaN,...,NaN,NaT,NaN,NaN,0.0,NaN,NaN,NaT,NaN,NaT
8051,28797,2026-03-26,134.0,ANCA Positive,Pos-Pos Switch,Encounters,2,CUH - Cork University Hospital,28797,NaN,...,NaN,NaT,NaN,NaN,0.0,NaN,NaN,NaT,NaN,NaT

In [412]:
mtp_with_intervals=mtp_with_intervals.drop_duplicates(subset=['RKD.ID','Date_Of_Visit'], keep='first')
mtp_with_intervals

,RKD.ID,Date_Of_Visit,ANCA_Levels,anca_status,ancaswitch,Repeat.Instrument,Repeat.Instance.x,Data.Access.Group.x,Patient.ID,COVID.19.related.entry.,...,mmf_On.going,mmf_Stop.Date,mmf_relative_dose,mmf_relative_dose2,MMF_ITIS,meth_Unit.of.Doses,meth_Frequency,meth_Start.Date,meth_On.going,meth_Stop.Date
0,1,2012-08-31,134.0,ANCA Positive,Switch Status Unknown,Encounters,1,TUH - Tallaght,1,No,...,NaN,NaT,NaN,NaN,0.0,NaN,NaN,NaT,NaN,NaT
1,1,2012-09-07,NaN,ANCA Positive,Pos-Pos Switch,Encounters,36,TUH - Tallaght,1,No,...,NaN,NaT,NaN,NaN,0.0,NaN,NaN,NaT,NaN,NaT
2,1,2012-09-17,110.0,ANCA Positive,Pos-Pos Switch,Encounters,37,TUH - Tallaght,1,No,...,NaN,NaT,NaN,NaN,0.0,NaN,NaN,NaT,NaN,NaT
3,1,2012-09-21,92.0,ANCA Positive,Pos-Pos Switch,Encounters,2,TUH - Tallaght,1,No,...,NaN,NaT,NaN,NaN,0.0,NaN,NaN,NaT,NaN,NaT
4,1,2012-09-28,NaN,ANCA Positive,Pos-Pos Switch,Encounters,28,TUH - Tallaght,1,No,...,NaN,NaT,NaN,NaN,0.0,NaN,NaN,NaT,NaN,NaT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8047,28793,2026-01-21,147.0,ANCA Positive,Switch Status Unknown,Encounters,1,CUH - Cork University Hospital,28793,No,...,NaN,NaT,NaN,NaN,0.0,NaN,NaN,NaT,NaN,NaT
8048,28796,2025-07-28,NaN,ANCA Status Unknown,Switch Status Unknown,Encounters,2,NaN,28796,No,...,NaN,NaT,NaN,NaN,0.0,NaN,NaN,NaT,NaN,NaT
8049,28796,2026-01-30,NaN,ANCA Negative,Switch Status Unknown,Encounters,1,NaN,28796,No,...,NaN,NaT,NaN,NaN,0.0,NaN,NaN,NaT,NaN,NaT
8050,28797,2026-02-02,134.0,ANCA Positive,Switch Status Unknown,Encounters,1,CUH - Cork University Hospital,28797,NaN,...,NaN,NaT,NaN,NaN,0.0,NaN,NaN,NaT,NaN,NaT
8051,28797,2026-03-26,134.0,ANCA Positive,Pos-Pos Switch,Encounters,2,CUH - Cork University Hospital,28797,NaN,...,NaN,NaT,NaN,NaN,0.0,NaN,NaN,NaT,NaN,NaT

In [413]:
import numpy as np

# Set specified columns to NaN where 'meth_Start.Date' equals 'Date.Of.Visit'
cols_to_nan = cols_to_merge = ['meth_Unit.of.Doses', 'meth_Frequency','meth_Start.Date','meth_On.going','meth_Stop.Date']

mtp_with_intervals.loc[mtp_with_intervals['meth_Start.Date'] == mtp_with_intervals['Date_Of_Visit'], cols_to_nan] = np.nan

mtp_with_intervals

,RKD.ID,Date_Of_Visit,ANCA_Levels,anca_status,ancaswitch,Repeat.Instrument,Repeat.Instance.x,Data.Access.Group.x,Patient.ID,COVID.19.related.entry.,...,mmf_On.going,mmf_Stop.Date,mmf_relative_dose,mmf_relative_dose2,MMF_ITIS,meth_Unit.of.Doses,meth_Frequency,meth_Start.Date,meth_On.going,meth_Stop.Date
0,1,2012-08-31,134.0,ANCA Positive,Switch Status Unknown,Encounters,1,TUH - Tallaght,1,No,...,NaN,NaT,NaN,NaN,0.0,NaN,NaN,NaT,NaN,NaT
1,1,2012-09-07,NaN,ANCA Positive,Pos-Pos Switch,Encounters,36,TUH - Tallaght,1,No,...,NaN,NaT,NaN,NaN,0.0,NaN,NaN,NaT,NaN,NaT
2,1,2012-09-17,110.0,ANCA Positive,Pos-Pos Switch,Encounters,37,TUH - Tallaght,1,No,...,NaN,NaT,NaN,NaN,0.0,NaN,NaN,NaT,NaN,NaT
3,1,2012-09-21,92.0,ANCA Positive,Pos-Pos Switch,Encounters,2,TUH - Tallaght,1,No,...,NaN,NaT,NaN,NaN,0.0,NaN,NaN,NaT,NaN,NaT
4,1,2012-09-28,NaN,ANCA Positive,Pos-Pos Switch,Encounters,28,TUH - Tallaght,1,No,...,NaN,NaT,NaN,NaN,0.0,NaN,NaN,NaT,NaN,NaT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8047,28793,2026-01-21,147.0,ANCA Positive,Switch Status Unknown,Encounters,1,CUH - Cork University Hospital,28793,No,...,NaN,NaT,NaN,NaN,0.0,NaN,NaN,NaT,NaN,NaT
8048,28796,2025-07-28,NaN,ANCA Status Unknown,Switch Status Unknown,Encounters,2,NaN,28796,No,...,NaN,NaT,NaN,NaN,0.0,NaN,NaN,NaT,NaN,NaT
8049,28796,2026-01-30,NaN,ANCA Negative,Switch Status Unknown,Encounters,1,NaN,28796,No,...,NaN,NaT,NaN,NaN,0.0,NaN,NaN,NaT,NaN,NaT
8050,28797,2026-02-02,134.0,ANCA Positive,Switch Status Unknown,Encounters,1,CUH - Cork University Hospital,28797,NaN,...,NaN,NaT,NaN,NaN,0.0,NaN,NaN,NaT,NaN,NaT
8051,28797,2026-03-26,134.0,ANCA Positive,Pos-Pos Switch,Encounters,2,CUH - Cork University Hospital,28797,NaN,...,NaN,NaT,NaN,NaN,0.0,NaN,NaN,NaT,NaN,NaT

In [414]:
mtp_with_intervals = (
    mtp_with_intervals
    .sort_values(['RKD.ID', 'Date_Of_Visit'])
)

# duplicate the column
mtp_with_intervals['meth_Stop.Date_ffill'] = (
    mtp_with_intervals['meth_Stop.Date']
)

# forward fill within each patient
mtp_with_intervals['meth_Stop.Date_ffill'] = (
    mtp_with_intervals
    .groupby('RKD.ID')['meth_Stop.Date_ffill']
    .ffill()
)

In [415]:
mtp_with_intervals['interval_from_meth_stop_date'] = (
    mtp_with_intervals['Date_Of_Visit'] -
    mtp_with_intervals['meth_Stop.Date_ffill']
).dt.days

In [416]:
mtp_with_intervals['Dose_Methotrexate - UATC/L01BA01'].describe()

count    244.000000
mean       4.096897
std        5.159076
min        0.357143
25%        2.053571
50%        2.857143
75%        2.857143
max       30.000000
Name: Dose_Methotrexate - UATC/L01BA01, dtype: float64

In [417]:
# Ensure Age and Dose are numeric
mtp_with_intervals["Age_Encounters"] = pd.to_numeric(
    mtp_with_intervals["Age_Encounters"], errors="coerce"
)

dose_col = "Dose_Methotrexate - UATC/L01BA01"
mtp_with_intervals[dose_col] = pd.to_numeric(
    mtp_with_intervals[dose_col], errors="coerce"
)

age = mtp_with_intervals["Age_Encounters"]
dose = mtp_with_intervals[dose_col]

mtp_with_intervals["Meth_absolute_dose"] = np.select(
    [
        age.between(65, 73, inclusive="both"),
        age.between(74, 82, inclusive="both"),
        age.gt(82),
    ],
    [
        dose + 50,   # 65–73: +50 mg
        dose + 100,  # 74–82: +100 mg
        dose + 150,  # >82: +150 mg
    ],
    default=dose    # <=64 or missing: no change
)

In [418]:
# enforce minimum dose of 25 mg
mtp_with_intervals.loc[
    mtp_with_intervals['Meth_absolute_dose'] < 0.35,
    'Meth_absolute_dose'
] = 0.35

In [419]:
# enforce minimum dose of 25 mg
mtp_with_intervals.loc[
    mtp_with_intervals['Meth_absolute_dose'] >5,
    'Meth_absolute_dose'
] = 5

In [420]:
mtp_with_intervals['meth_Dose_ffill'] = mtp_with_intervals['Meth_absolute_dose']

# forward fill the duplicated column
mtp_with_intervals['meth_Dose_ffill'] = (
    mtp_with_intervals['meth_Dose_ffill'].ffill()
)

In [421]:

import pandas as pd
import numpy as np
from datetime import datetime, timedelta

# Define dose-effect parameters
min_dose = 0.35
max_dose = 5
min_score = 0.10
max_score = 0.55


# Function to calculate scores
def calculate_score(dose, min_dose, max_dose, min_score, max_score):
    if dose <= min_dose:
        return min_score
    elif dose >= max_dose:
        return max_score
    else:
        return min_score + ((dose - min_dose) / (max_dose - min_dose)) * (max_score - min_score)

# Convert the dose column to numeric, ignoring 'NA'
mtp_with_intervals["Meth_absolute_dose"] = pd.to_numeric(mtp_with_intervals["Meth_absolute_dose"], errors='coerce')

# Calculate scores, ignoring 'NA'
mtp_with_intervals["Methotrexate_ITIS"] =mtp_with_intervals["Meth_absolute_dose"].apply(
    lambda dose: calculate_score(dose, min_dose, max_dose, min_score, max_score) if not np.isnan(dose) else None
)

In [422]:
mtp_with_intervals["Dose_Methotrexate - UATC/L01BA01"].value_counts(dropna=False)

Dose_Methotrexate - UATC/L01BA01
NaN          7783
2.857143       84
2.142857       53
1.428571       42
20.000000      11
10.000000      10
3.571429        8
1.071429        8
1.785714        6
2.500000        4
17.500000       3
0.357143        3
15.000000       3
0.714286        2
25.000000       2
12.500000       1
7.500000        1
30.000000       1
5.000000        1
3.214286        1
Name: count, dtype: int64

In [423]:
mtp_with_intervals["Meth_absolute_dose"].value_counts(dropna=False)

Meth_absolute_dose
NaN         7783
5.000000     115
2.857143      42
2.142857      36
1.428571      27
3.571429       7
1.785714       6
2.500000       4
0.357143       2
0.714286       2
1.071429       2
3.214286       1
Name: count, dtype: int64

In [424]:
import numpy as np
import pandas as pd

# ---------------------------------------------
# 1. Sigmoid function
# ---------------------------------------------
def sigmoid_curve(x, A, n, d):
    return A / (1 + np.exp(n * (x - d)))

# ---------------------------------------------
# 2. Interpolation functions for A(dose), d(dose), n(dose)
# ---------------------------------------------
A1 = 0.10
A2 = 0.55
dose1 = 0.35
dose2 = 5

m_A = (A2 - A1) / (dose2 - dose1)
b_A = A1 - m_A * dose1
def calculate_A(dose):
    return m_A * dose + b_A

d1 = 8
d2 = 10
m_d = (d2 - d1) / (dose2 - dose1)
b_d = d1 - m_d * dose1
def calculate_d(dose):
    return m_d * dose + b_d

# vanish logic
def calculate_n_from_vanish(A, d, vanish_day):
    return np.log(99) / (vanish_day - d)

vanish1 = 10
vanish2 = 14
n1 = calculate_n_from_vanish(A1, d1, vanish1)
n2 = calculate_n_from_vanish(A2, d2, vanish2)

m_n = (n2 - n1) / (dose2 - dose1)
b_n = n1 - m_n * dose1
def calculate_n(dose):
    return m_n * dose + b_n

# ---------------------------------------------
# 3. Apply model to each row of mtp_with_intervals
# ---------------------------------------------
def compute_ITIS(row):
    dose = row["meth_Dose_ffill"]
    time = row["interval_from_meth_stop_date"]

    # Skip invalid values
    if pd.isna(dose) or pd.isna(time):
        return np.nan

    A = calculate_A(dose)
    d = calculate_d(dose)
    n = calculate_n(dose)

    return sigmoid_curve(time, A, n, d)

# Create new column
mtp_with_intervals["meth_ITIS2"] = mtp_with_intervals.apply(compute_ITIS, axis=1)

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\3321641312.py:8: RuntimeWarning: overflow encountered in exp
  return A / (1 + np.exp(n * (x - d)))

In [425]:
# round to 2 decimal places
mtp_with_intervals['meth_ITIS2'] = (
    mtp_with_intervals['meth_ITIS2'].round(2)
)

In [426]:
mtp_with_intervals['Methotrexate_ITIS'] = (
    mtp_with_intervals['Methotrexate_ITIS']
    .fillna(mtp_with_intervals['meth_ITIS2'])
)

In [427]:
cols_to_drop = [
    'meth_Stop.Date_ffill',
    'interval_from_meth_stop_date',
    'meth_Dose_ffill',
    'meth_ITIS2'
]

mtp_with_intervals.drop(columns=cols_to_drop, inplace=True)

In [428]:
#mtp_with_intervals.to_csv('C:/Users/georgea1/OneDrive - Trinity College Dublin/Desktop/Dose_Methotrexate.csv',index=True)

In [429]:
mtp_with_intervals['Methotrexate_ITIS'].fillna(0, inplace=True)
mtp_with_intervals['Methotrexate_ITIS']

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\2613506092.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  mtp_with_intervals['Methotrexate_ITIS'].fillna(0, inplace=True)

0       0.0
1       0.0
2       0.0
3       0.0
4       0.0
       ...
8047    0.0
8048    0.0
8049    0.0
8050    0.0
8051    0.0
Name: Methotrexate_ITIS, Length: 8027, dtype: float64

In [430]:
mask = (
    (
        (mtp_with_intervals['Drug_Methotrexate - UATC/L01BA01']
         == 'Methotrexate - UATC/L01BA01')
        &
        (
            mtp_with_intervals['Methotrexate_ITIS'].isna()
            | (mtp_with_intervals['Methotrexate_ITIS'] == 0)
        )
    )
    |
    (
        mtp_with_intervals['treatment_type'].str.contains('Methotrexate - UATC/L01BA01', na=False)
        &
        (mtp_with_intervals['Methotrexate_ITIS'] == 0)
    )
)

mtp_with_intervals.loc[mask, 'Methotrexate_ITIS'] = 0.32

## Avacopan

In [431]:


mtp_with_intervals['Avacopan_ITIS'] = np.where(
    mtp_with_intervals['Drug_Avacopan (C5aR inhibitor)'] == 'Avacopan (C5aR inhibitor)',
    0.50,
    0
)

In [432]:
mtp_with_intervals['Avacopan_ITIS'].value_counts(dropna=False)

Avacopan_ITIS
0.0    7993
0.5      34
Name: count, dtype: int64

In [433]:
mtp_with_intervals['Avacopan_ITIS'].fillna(0, inplace=True)
mtp_with_intervals['Avacopan_ITIS']

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\3332984863.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  mtp_with_intervals['Avacopan_ITIS'].fillna(0, inplace=True)

0       0.0
1       0.0
2       0.0
3       0.0
4       0.0
       ...
8047    0.0
8048    0.0
8049    0.0
8050    0.0
8051    0.5
Name: Avacopan_ITIS, Length: 8027, dtype: float64

In [434]:
mask = (
    (
        (mtp_with_intervals['Drug_Avacopan (C5aR inhibitor)']
         == 'Avacopan (C5aR inhibitor)')
        &
        (
            mtp_with_intervals['Avacopan_ITIS'].isna()
            | (mtp_with_intervals['Avacopan_ITIS'] == 0)
        )
    )
    |
    (
        mtp_with_intervals['treatment_type'].str.contains('Avacopan (C5aR inhibitor)', na=False)
        &
        (mtp_with_intervals['Avacopan_ITIS'] == 0)
    )
)

mtp_with_intervals.loc[mask, 'Avacopan_ITIS'] = 0.50

C:\Users\georgea1\AppData\Local\Temp\ipykernel_32460\738503531.py:13: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  mtp_with_intervals['treatment_type'].str.contains('Avacopan (C5aR inhibitor)', na=False)

In [435]:
## Cumulative cyc ITIS

In [436]:
import numpy as np

# List of ITIS component columns
itis_cols = [
    "CYC_Oral_ITIS",
    "CYC_IV_ITIS",
]

def compute_cumulative_ITIS(row):
    values = row[itis_cols].dropna().values

    # If all ITIS_i are missing → cumulative result is NaN
    if len(values) == 0:
        return np.nan

    # Apply formula: 1 - Π(1 - ITIS_i)
    product = np.prod(1 - values)
    return 1 - product

# Create new column
mtp_with_intervals["Cumulative__CYC_ITIS"] = mtp_with_intervals.apply(compute_cumulative_ITIS, axis=1)

In [437]:
	#CYC_IV_ITIS	RTX_IV_ITIS	CYC_Oral_ITIS	Prednisolone_ITIS	Aza_ITIS	MMF_ITIS	Methotrexate_ITIS	Avacopan_ITIS

## Cumulative ITIS

In [438]:
import numpy as np

# List of ITIS component columns
itis_cols = [
    "MTP_IV_ITIS",
    "RTX_IV_ITIS",
    'Cumulative__CYC_ITIS',
    "Prednisolone_ITIS",
    "Aza_ITIS",
    "MMF_ITIS",
    "Methotrexate_ITIS",
    "Avacopan_ITIS"
]

def compute_cumulative_ITIS(row):
    values = row[itis_cols].dropna().values

    # If all ITIS_i are missing → cumulative result is NaN
    if len(values) == 0:
        return np.nan

    # Apply formula: 1 - Π(1 - ITIS_i)
    product = np.prod(1 - values)
    return 1 - product

# Create new column
mtp_with_intervals["Cumulative_ITIS"] = mtp_with_intervals.apply(compute_cumulative_ITIS, axis=1)

In [439]:
mtp_with_intervals['Cumulative_ITIS'] = mtp_with_intervals['Cumulative_ITIS'].round(2)

In [440]:
mtp_with_intervals["Cumulative_ITIS"].describe()

count    8027.000000
mean        0.514769
std         0.350226
min         0.000000
25%         0.250000
50%         0.550000
75%         0.840000
max         1.000000
Name: Cumulative_ITIS, dtype: float64

## Final cross check with Cumulative ITIS & Treatment type

In [441]:
mtp_with_intervals["Cumulative_ITIS"].describe()

count    8027.000000
mean        0.514769
std         0.350226
min         0.000000
25%         0.250000
50%         0.550000
75%         0.840000
max         1.000000
Name: Cumulative_ITIS, dtype: float64

In [442]:
mtp_with_intervals.to_csv('C:/Users/georgea1/OneDrive - Trinity College Dublin/Desktop/itis_final_age_lymphocytes_adjusted_RIV_19_04_2026.csv',index=True)

## Definite relapse vs ITIS

In [ ]:
#import pandas as pd
#mtp_with_intervals=pd.read_csv("C:/Users/georgea1/OneDrive - Trinity College Dublin/Angel George/Chap 2. Treatment/Data/ITIS Data/Idibell/January 2026/IDIBELL_itis_final.csv")
#mtp_with_intervals

In [ ]:
import matplotlib.pyplot as plt

plt.figure()
plt.hist(mtp_with_intervals['Cumulative_ITIS'].dropna(), bins=20)
plt.xlabel('Cumulative ITIS')
plt.ylabel('Number of encounters')
plt.title('Over all Distribution of Cumulative ITIS - IDIBELL')
plt.show()

In [ ]:
import matplotlib.pyplot as plt

plt.figure()
plt.scatter(
    mtp_with_intervals['Age_Encounters'],
    mtp_with_intervals['Cumulative_ITIS']
)

plt.xlabel('Age at Encounter')
plt.ylabel('Cumulative ITIS')
plt.title('Cumulative ITIS vs Age - IDIBELL')

plt.show()

In [ ]:
plt.figure()

for pid, df in mtp_with_intervals.groupby('RKD.ID'):
    plt.scatter(df['Age_Encounters'], df['Cumulative_ITIS'], alpha=0.5)

plt.xlabel('Age at Encounter')
plt.ylabel('Cumulative ITIS')
plt.title('Cumulative ITIS vs Age (points colored by patient)')

plt.show()

In [ ]:
import matplotlib.pyplot as plt

plt.figure()
plt.scatter(
    mtp_with_intervals['X.Total.white.cell.count.x10.9.L.'],
    mtp_with_intervals['Cumulative_ITIS']
)

plt.xlabel('Total WCC')
plt.ylabel('Cumulative ITIS')
plt.title('Cumulative ITIS vs Total WCC - IDIBELL')

plt.show()

In [ ]:
relapse_df =mtp_with_intervals[
    mtp_with_intervals['CPD_relapse'] == 'Definite Relapse'
]
relapse_df

In [ ]:
import matplotlib.pyplot as plt

plt.figure()
plt.hist(relapse_df['Cumulative_ITIS'].dropna(), bins=20)
plt.xlabel('Cumulative ITIS')
plt.ylabel('Number of encounters')
plt.title('Distribution of Cumulative ITIS on Definite Relapse Day')
plt.show()

In [ ]:
relapse_df['Cumulative_ITIS'].describe()

In [ ]:
## Define relapse order per patient

In [ ]:
mtp_with_intervals = mtp_with_intervals.sort_values(
    ['RKD.ID', 'Date_Of_Visit']
)

mtp_with_intervals['relapse_number'] = (
    mtp_with_intervals
    .groupby('RKD.ID')['CPD_relapse']
    .transform(lambda x: (x == 'Definite Relapse').cumsum())
)

In [ ]:
relapse_df = mtp_with_intervals[
    mtp_with_intervals['CPD_relapse'] == 'Definite Relapse'
]

In [ ]:
first_relapse = relapse_df[relapse_df['relapse_number'] == 1]
first_relapse

In [ ]:
relapse_df['relapse_number'].value_counts(dropna=False)

In [ ]:
plt.figure()
plt.hist(first_relapse['Cumulative_ITIS'].dropna(), bins=20)
plt.xlabel('Cumulative ITIS')
plt.ylabel('Number of patients')
plt.title('ITIS at First Relapse')
plt.show()

In [ ]:
import matplotlib.pyplot as plt
import os

base_path = r"C:/Users/georgea1/OneDrive - Trinity College Dublin/Desktop"

for n in [1, 2, 3, 4, 5, 6]:
    subset = relapse_df[relapse_df['relapse_number'] == n]

    if len(subset) > 0:
        plt.figure()
        plt.hist(
            subset['Cumulative_ITIS'].dropna(),
            bins=20,
            range=(0, 1)
        )
        plt.xlim(0, 1)
        plt.xlabel('Cumulative ITIS')
        plt.ylabel('Number of encounters')
        plt.title(f'ITIS at Relapse #{n} (n={len(subset)})')

        file_path = os.path.join(
            base_path, f'cumulative_itis_relapse_{n}.png'
        )

        plt.savefig(file_path, dpi=300, bbox_inches='tight')
        plt.show()
        plt.close()

In [ ]:
relapse_df.groupby('relapse_number')['Cumulative_ITIS'].median()

In [ ]:
relapse_df.groupby('relapse_number')['Cumulative_ITIS'].quantile([0.25, 0.75])

In [ ]:
summary_table = (
    relapse_df
    .groupby('relapse_number')['Cumulative_ITIS']
    .agg(
        median='median',
        q25=lambda x: x.quantile(0.25),
        q75=lambda x: x.quantile(0.75)
    )
)

summary_table['Median (IQR)'] = (
    summary_table['median'].round(2).astype(str) +
    ' (' +
    summary_table['q25'].round(2).astype(str) +
    '–' +
    summary_table['q75'].round(2).astype(str) +
    ')'
)

summary_table[['Median (IQR)']]

In [ ]:
## Skewness

In [ ]:
relapse_df.groupby('relapse_number')['Cumulative_ITIS'].skew()

In [ ]:
(relapse_df['Cumulative_ITIS'] == 0).groupby(relapse_df['relapse_number']).mean()

In [ ]:
thresholds = [0.05, 0.1, 0.2]

for t in thresholds:
    print(
        t,
        (relapse_df['Cumulative_ITIS'] < t)
        .groupby(relapse_df['relapse_number'])
        .mean()
    )

In [ ]:
bins = [0, 0.1, 0.25, 0.5, 0.75, 1]
mtp_with_intervals['ITIS_bin'] = pd.cut(
    mtp_with_intervals['Cumulative_ITIS'],
    bins=bins
)

risk_by_bin = (
    mtp_with_intervals
    .groupby('ITIS_bin')['CPD_relapse']
    .apply(lambda x: (x == 'Definite Relapse').mean())
)

risk_by_bin

## Induction

In [ ]:
mtp_with_intervals['CPD_relapse'].value_counts(dropna=False)

In [ ]:
induction =mtp_with_intervals[
    mtp_with_intervals['CPD_relapse'] == 'Under 6 months'
]
induction

In [ ]:
## Exclude interval from diagnosis=0
induction = induction[induction['encounter_interval_from_diagnosis'] != 0]
induction

In [ ]:
induction['encounter_interval_from_diagnosis'].max()

In [ ]:
induction['RKD.ID'].nunique()

In [ ]:
import matplotlib.pyplot as plt

plt.figure()
plt.hist(induction ['Cumulative_ITIS'].dropna(), bins=20)
plt.xlabel('Cumulative ITIS')
plt.ylabel('Number of encounters')
plt.title('Distribution of Cumulative ITIS During induction (under 6 months)')
plt.show()

In [ ]:
## Recent Relapse

In [ ]:
recent_relapse =mtp_with_intervals[
    mtp_with_intervals['CPD_relapse'] == 'Recent relapse'
]
recent_relapse

In [ ]:
import matplotlib.pyplot as plt

plt.figure()
plt.hist(recent_relapse  ['Cumulative_ITIS'].dropna(), bins=20)
plt.xlabel('Cumulative ITIS')
plt.ylabel('Number of encounters')
plt.title('Distribution of Cumulative ITIS on recent relapse encounter ')
plt.show()

In [ ]:
## Neg- Pos Switch encounters

In [ ]:
negpos =mtp_with_intervals[
    mtp_with_intervals['ancaswitch'] == 'Neg-Pos Switch'
]
negpos

In [ ]:
import matplotlib.pyplot as plt

plt.figure()
plt.hist(negpos ['Cumulative_ITIS'].dropna(), bins=20)
plt.xlabel('Cumulative ITIS')
plt.ylabel('Number of encounters')
plt.title('Distribution of Cumulative ITIS on Neg- Pos Switch encounter ')
plt.show()

In [ ]:
no_relapse = mtp_with_intervals[
    mtp_with_intervals['CPD_relapse'] == 'No Relapse'
]
no_relapse

In [ ]:
import matplotlib.pyplot as plt

plt.figure()
plt.hist(no_relapse ['Cumulative_ITIS'].dropna(), bins=20)
plt.xlabel('Cumulative ITIS')
plt.ylabel('Number of encounters')
plt.title('Distribution of Cumulative ITIS on remission Day')
plt.show()

In [ ]:
import matplotlib.pyplot as plt
import numpy as np

n_bootstraps = 4
bins = 20

for b in range(1, n_bootstraps + 1):

    # sample ONE row per patient (with replacement across bootstraps)
    bootstrap_sample = (
        no_relapse
        .groupby('RKD.ID', group_keys=False)
        .apply(lambda x: x.sample(1))
    )

    plt.figure()
    plt.hist(
        bootstrap_sample['Cumulative_ITIS'].dropna(),
        bins=bins,
        range=(0, 1)
    )
    plt.xlim(0, 1)
    plt.xlabel('Cumulative ITIS')
    plt.ylabel('Number of patients')
    plt.title(f'No-relapse Bootstrap #{b}')
    plt.show()

In [ ]:
import numpy as np

sample_ids = np.random.choice(
    mtp_with_intervals['RKD.ID'].unique(),
    size=30,
    replace=False
)

subset = mtp_with_intervals[
    mtp_with_intervals['RKD.ID'].isin(sample_ids)
]

plt.figure()
for pid, g in subset.groupby('RKD.ID'):
    plt.plot(
        g['Date_Of_Visit'],
        g['Cumulative_ITIS'],
        alpha=0.4
    )

plt.xlabel('Time')
plt.ylabel('Cumulative ITIS')
plt.title('Cumulative ITIS Trajectories (Sample of Patients)')
plt.show()

In [ ]:
tp_with_intervals = mtp_with_intervals.sort_values(
    ['RKD.ID', 'encounter_interval_from_diagnosis']
)

mtp_with_intervals['encounter_number'] = (
    mtp_with_intervals
    .groupby('RKD.ID')
    .cumcount() + 1
)

In [ ]:
heatmap_matrix = mtp_with_intervals.pivot(
    index='RKD.ID',
    columns='encounter_number',
    values='Cumulative_ITIS'
)

In [ ]:
plt.figure(figsize=(14, 8))

cmap = plt.cm.viridis.copy()
cmap.set_bad(color='white')   # NaN → white

im = plt.imshow(
    heatmap_matrix,
    aspect='auto',
    interpolation='nearest',
    cmap=cmap,
    vmin=0,
    vmax=1
)

plt.colorbar(im, label='Cumulative ITIS')
plt.xlabel('Encounter number')
plt.ylabel('Patient ID')
plt.title('Cumulative ITIS Across Sequential Encounters')

plt.show()

In [ ]:
import matplotlib.pyplot as plt
import numpy as np

# Create numeric x positions with jitter
x_no = np.random.normal(0, 0.04, size=(mtp_with_intervals['CPD_relapse'] == 'No Relapse').sum())
x_relapse = np.random.normal(1, 0.04, size=(mtp_with_intervals['CPD_relapse'] == 'Definite Relapse').sum())

plt.figure(figsize=(8, 6))

sc1 = plt.scatter(
    x_no,
    mtp_with_intervals.loc[
        mtp_with_intervals['CPD_relapse'] == 'No Relapse',
        'Cumulative_ITIS'
    ],
    c=mtp_with_intervals.loc[
        mtp_with_intervals['CPD_relapse'] == 'No Relapse',
        'Cumulative_ITIS'
    ],
    cmap='viridis',
    vmin=0,
    vmax=1,
    s=12,
    alpha=0.7
)

sc2 = plt.scatter(
    x_relapse,
    mtp_with_intervals.loc[
        mtp_with_intervals['CPD_relapse'] == 'Definite Relapse',
        'Cumulative_ITIS'
    ],
    c=mtp_with_intervals.loc[
        mtp_with_intervals['CPD_relapse'] == 'Definite Relapse',
        'Cumulative_ITIS'
    ],
    cmap='viridis',
    vmin=0,
    vmax=1,
    s=12,
    alpha=0.7
)
for i, status in enumerate(['No Relapse', 'Definite Relapse']):
    vals = mtp_with_intervals.loc[
        mtp_with_intervals['CPD_relapse'] == status,
        'Cumulative_ITIS'
    ].dropna()

    median = np.median(vals)
    q25, q75 = np.percentile(vals, [25, 75])

    plt.hlines(median, i-0.2, i+0.2, colors='black', linewidth=2)
    plt.hlines([q25, q75], i-0.15, i+0.15, colors='black', linewidth=1)
plt.xticks([0, 1], ['No Relapse', 'Definite Relapse'])
plt.ylabel('Cumulative ITIS')
plt.title('Cumulative ITIS Across All Encounters by Relapse Status')

plt.colorbar(sc1, label='Cumulative ITIS')
plt.show()

In [ ]:
plt.figure(figsize=(8, 6))

data = [
    mtp_with_intervals.loc[
        mtp_with_intervals['CPD_relapse'] == 'No Relapse',
        'Cumulative_ITIS'
    ].dropna(),
    mtp_with_intervals.loc[
        mtp_with_intervals['CPD_relapse'] == 'Definite Relapse',
        'Cumulative_ITIS'
    ].dropna()
]

plt.boxplot(data, widths=0.4, showfliers=False)
plt.scatter(
    np.random.normal(1, 0.04, len(data[0])), data[0],
    s=8, alpha=0.4
)
plt.scatter(
    np.random.normal(2, 0.04, len(data[1])), data[1],
    s=8, alpha=0.4
)

plt.xticks([1, 2], ['No Relapse', 'Definite Relapse'])
plt.ylabel('Cumulative ITIS')
plt.title('Cumulative ITIS Across All Encounters')
plt.show()

In [ ]:
## Mixed effect logistic regreesion:

In [ ]:
df = mtp_with_intervals[mtp_with_intervals['encounter_interval_from_diagnosis']>180 ]
df

In [ ]:
df['CPD_relapse'].value_counts(dropna=False)

In [ ]:
df['relapse_status'] = (df['CPD_relapse'] == 'Definite Relapse').astype(int)
df['relapse_status'].value_counts(dropna=False)

In [ ]:
import statsmodels.api as sm

In [ ]:
df = df.dropna(subset=['RKD.ID', 'Cumulative_ITIS', 'relapse_status'])
df

In [ ]:
# Fixed effects formula (use Cumulative_ITIS_z if you scaled)
formula = "relapse_status ~ Cumulative_ITIS"

# Random intercept for patient
# vc_formulas defines variance components; "0 + C(RKD.ID)" gives random intercept per patient
vc_formulas = {"patient": "0 + C(RKD.ID)"}

model = sm.BinomialBayesMixedGLM.from_formula(formula, vc_formulas, df)
result = model.fit_vb()

print(result.summary())

In [ ]:
import pandas as pd
import numpy as np
import statsmodels.api as sm

# Keep only the two groups you care about
df = mtp_with_intervals.loc[
    mtp_with_intervals['CPD_relapse'].isin(['No Relapse', 'Definite Relapse']),
    ['RKD.ID', 'CPD_relapse', 'Cumulative_ITIS']
].copy()

# Outcome as 0/1
df['relapse_status'] = (df['CPD_relapse'] == 'Definite Relapse').astype(int)

# Drop missing predictor / ids
df = df.dropna(subset=['RKD.ID', 'Cumulative_ITIS', 'y_relapse'])

# (Optional but often helpful) scale predictor for interpretability
# df['Cumulative_ITIS_z'] = (df['Cumulative_ITIS'] - df['Cumulative_ITIS'].mean()) / df['Cumulative_ITIS'].std()

In [ ]:
mtp_with_intervals.to_csv('C:/Users/georgea1/OneDrive - Trinity College Dublin/Desktop/ITIS_Final.csv',index=True)